### ISSUE TITLE
Support for Chinese needs to be strengthened.

### ISSUE THREAD

**Issue by showmind** [TongchengOpenSource/smart-doc#10]
When the design language is set to Chinese, there are still many Chinese characters on the generated page. Is there a plan for translation?
设计语言为中文时, 生成的页面上, 还是有很多中文, 有翻译的计划吗?
![image](https://user-images.githubusercontent.com/17521668/70588726-a2828400-1c08-11ea-99ee-f862acada7a0.png)

**Comment by netdied** [comment]
We are not considering strengthening Chinese support at the moment. If needed, you can download the source code and modify it yourself.
暂不考虑加强中文支持 如有需要可以下载源码自己修改
