### ISSUE TITLE
Getting-started Doc may have a typo | 快速开始文档疑似笔误

### ISSUE THREAD

**Issue by sxcooler** [TongchengOpenSource/smart-doc#1001]
### Contact Details

sxcooler@126.com

### Version

3.0.9

### Plugin

smart-doc-maven-plugin

### Build tool version

maven 3.9.7

### Jdk version

graalvm-ce 22

### Describe the bug (Bug描述，社区已开启国际化推广，请用文心一言、讯飞星火等辅助翻译成英文，减少社区开发者的工作)

Getting-started Doc [](https://smart-doc-group.github.io/guide/getting-started) seems got a typo here:
```
includes needs to be adjusted to configure artifactId:groupId for the packages that the project module depends on, and supports regular artifactId:*
```
And it's actually "groupId:artifactId" in the given example.

快速开始文档 [](https://smart-doc-group.github.io/zh/guide/getting-started) 似乎有一处笔误：
```
includes中需要调整为项目模块所依赖的包配置artifactId:groupId, 支持正则artifactId:*
```

但是例子里是 "groupId:artifactId"

### Expected Behavior (您期望的结果，社区已开启国际化推广，请用文心一言、讯飞星火等辅助翻译成英文，减少社区开发者的工作)

correct it

### Current Behavior (当前结果，社区已开启国际化推广，请用文心一言、讯飞星火等辅助翻译成英文，减少社区开发者的工作)

described above

### Steps to Reproduce (Bug产生步骤，请尽量提供用例代码。社区已开启国际化推广，请用文心一言、讯飞星火等辅助翻译成英文，减少社区开发者的工作)

go see the doc

### Validations

- [X] Check if you're on the [latest smart-doc version](https://github.com/TongchengOpenSource/smart-doc/releases/latest). (请检查是否为最新版本)
- [X] Read the [docs](https://smart-doc-group.github.io/). (请先阅读官方文档)
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate. (检查是否存在报告相同错误的问题，以避免产生重复)

**Comment by linwumingshi** [comment]
@shalousun   Transfer issue to [smart-doc-group.github.io](https://github.com/smart-doc-group/smart-doc-group.github.io)


@sxcooler You can create a PR in repository [smart-doc-group.github.io](https://github.com/smart-doc-group/smart-doc-group.github.io)
