### ISSUE TITLE
In a Gradle multi-module scenario, when the model and controller are in separate modules, the request body does not display any parameters.

### ISSUE THREAD

**Issue by marchosius** [TongchengOpenSource/smart-doc#102]
## Your Environment(您的使用环境)

* smart-doc version:
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin): 2.1.2
* build tool version(maven or gradle): gradle 6.8.3

## Expected Behavior(您期望的结果)

![image](https://user-images.githubusercontent.com/48839423/114222156-cb538e80-99a0-11eb-8f38-798ccd0f7122.png)

## Current Behavior(当前结果)

![image](https://user-images.githubusercontent.com/48839423/114221946-8a5b7a00-99a0-11eb-8a82-aa63fb65b085.png)

## Steps to Reproduce (Bug产生步骤，请尽量提供用例代码)

1.
2.
3.
4.

**Comment by shalousun** [comment]
@dev-heqian https://gitee.com/devin-alan/smart-doc-gradle-plugin-demo

**Comment by hwck** [comment]
@dev-heqian In a multi-module setup, check if the dependency of your model in the controller is using 'implementation'. If so, please change it to 'compile'. For more details, refer to the Gradle documentation on the scope of 'implementation' dependencies.

**Comment by shalousun** [comment]
@dev-heqian @hwck The latest official Gradle plugin has already fixed this issue.
