### ISSUE TITLE
During compilation, if it encounters unsupported parameters, it simply does not compile.

### ISSUE THREAD

**Issue by victory-wu** [TongchengOpenSource/smart-doc#109]
```
    /**
     * Retrieve configurations
     * @param keys
     * @return
     */
    @GetMapping
    public JsonEntity keys(@RequestParam("key") List<MerchantConfigKeyEnum> keys) {
        return ReturnUtil.success(merchantConfigService.findByKeyInAndCurrentMerchantId(keys));
    }
```

The system does not support the 'keys' parameter, it directly throws an error, and then the entire document is not compiled.

**Comment by shalousun** [comment]
Spring MVC does not support non-JSON request collection parameter binding to complex objects, but in your case it is an enumeration. Let's identify the enumeration.
