### ISSUE TITLE
Is it possible to support customizing the display content?

### ISSUE THREAD

**Issue by zuonidelaowang** [TongchengOpenSource/smart-doc#11]
The current documentation shows the following content.
URL: http://XXX
Type: GET
Content-Type: application/x-www-form-urlencoded;charset=utf-8
Description: XXXXX
.......

We want to display the interface developer's name, "author", in the documentation. Can we customize the display content to meet the different needs of each company?

Thank you.

**Comment by gujiniCY** [comment]
This feature has been submitted to the dev branch.
该功能已提交至dev分支
