### ISSUE TITLE
The null.min.css under highlight is 404.

### ISSUE THREAD

**Issue by YLongo** [TongchengOpenSource/smart-doc#114]
## Your Environment(您的使用环境)

* smart-doc version: smart-doc-maven-plugin
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin): 2.0.1
* build tool version(maven or gradle): maven

## Current Behavior(当前结果)

https://cdn.bootcdn.net/ajax/libs/highlight.js/10.3.2/styles/null.min.css

![image](https://user-images.githubusercontent.com/9137053/117461796-8cedc700-af80-11eb-946f-36d8542348fd.png)

## Steps to Reproduce (Bug产生步骤，请尽量提供用例代码)

1.
2.
3.
4.

**Comment by shalousun** [comment]
This is intentionally left blank by the official.
