### ISSUE TITLE
Can a condition be added to @ignore so that the parameters are displayed differently depending on the method?

### ISSUE THREAD

**Issue by jacky-neo** [TongchengOpenSource/smart-doc#120]
For example, consider an object:
```java
@Data
public class SysRole implements java.io.Serializable {

    /**
     * id
     * @required
     */
    @TableId(type = IdType.AUTO)
    private Integer id;

    /**
     * Role name
     */
    @NotBlank(message = "{validation.system.roleName}")
    private String roleName;

    /**
     * Description
     */
    private String description;
}

/**
 * Add a system role
 * @param sysRole com.paratera.console.biz.model.system.doc.SysRoleOfAdd
 * @return
 */
@PostMapping("/addSysRole")
public ResultInfo addSysRole(@Valid @RequestBody SysRole sysRole) { }

/**
 * Update a system role
 * @param sysRole
 * @required id
 * @return
 */
@PutMapping ("/updateSysRole")
public ResultInfo updateSysRole(@RequestBody SysRole sysRole) {}
```
When adding, `roleName` and `description` can be passed, but when updating, `id`, `roleName`, and `description` are required. If `@ignore` is added to the `id` attribute, it will affect both the add and update documentation. As a solution, a new class `SysRoleOfAdd` was defined, where `id` was marked with `@ignore`. If `@ignore` could have an attribute, such as `condition`, and accept a SpEL expression like `#{method.name={"addSysRole"}}`, indicating that it takes effect on the `addSysRole` method, then there would be no need to define a new class. The `{}` represents an array, which can contain multiple conditions.

**Comment by shalousun** [comment]
We won't engage in these peculiar practices. The effect of @ignore on fields may be removed by us later on. You can add group validations to handle this.

**Comment by jacky-neo** [comment]
Thank you for the suggestion. I found that group validation has resolved the issue, ensuring both code validation and documentation requirements are met. Please disregard my immature idea.
