### ISSUE TITLE
Error: fastjson not found.

### ISSUE THREAD

**Issue by over35to70icanmakemore** [TongchengOpenSource/smart-doc#121]
Even though the parent POM has been explicitly inherited to include fastjson, there is still an error stating that it cannot be found. This includes errors indicating that inherited dependencies from Sleuth cannot be found...

**Comment by shalousun** [comment]
>Even though the parent POM has been explicitly inherited to include fastjson, there is still an error stating that it cannot be found, including errors indicating that inherited dependencies from Sleuth cannot be found.
This is usually not a problem with smart-doc; smart-doc simply invokes Maven commands and APIs for operation. Moreover, please carefully read the plugin configuration, as the plugin can filter out some libraries that do not need to be loaded. Finally, a reminder to fill out the issue template carefully, providing detailed information. With just a single sentence, it is difficult for open-source authors or developers to identify the problem.

**Comment by over35to70icanmakemore** [comment]
Sorry, due to environmental issues, I am unable to provide screenshots or copy text. I will look into it further.
