### ISSUE TITLE
The `allInOneDocFileName` configuration is invalid; the generated file name is still `AllInOne.md`.

### ISSUE THREAD

**Issue by anaer** [TongchengOpenSource/smart-doc#131]
I've configured `allInOneDocFileName`, but the generated file name is still `AllInOne.md`. Is there something wrong with the configuration?

```
{
    "allInOne": true, 
    "allInOneDocFileName": "Interface Documentation",
    "isStrict": false,
    "outPath": "src/main/resources/doc",
    "coverOld": true,
    "language": "CHINESE"
}
```

**Comment by shalousun** [comment]
Please fill out the issue template as requested; otherwise, the official team will not address it. The issue template also provides reminders. If you do not follow the template, your usage situation is completely unclear.

**Comment by anaer** [comment]
Please fill out the issue template as requested; otherwise, the official team will not process it. The issue template also provides reminders. If you do not follow the template, your usage situation is completely unclear.

It seems there is no issue template provided.
![image](https://user-images.githubusercontent.com/4637100/125886663-bca86dfd-3627-4e94-93c0-41cb9545a4b0.png)
