### ISSUE TITLE
Add common parameters to the interface.

### ISSUE THREAD

**Issue by ZhongCW** [TongchengOpenSource/smart-doc#132]
How should I configure common request parameters in smart-doc.json (I handle these parameters through an interceptor, and they are not passed into the controller)? Similar to the requestHeaders configuration item (expecting requestParams), but it is not found.

**Comment by ZhongCW** [comment]
The customRequest/ResponseFields configuration seems unable to meet this requirement.

**Comment by netdied** [comment]
requestBodyAdvice
Reference:
https://gitee.com/smart-doc-team/smart-doc/wikis/smart-doc%20maven%E6%8F%92%E4%BB%B6?sort_id=1791450
Supports only parameters marked with @RequestBody.

**Comment by ZhongCW** [comment]
> requestBodyAdvice
> Reference:
> [https](https://gitee.com/smart-doc-team/smart-doc/wikis/smart-doc%20maven%E6%8F%92%E4%BB%B6?sort_id=1791450) : //gitee.com/smart-doc-team/smart-doc/wikis/smart-doc%20maven%E6%8F%92%E4%BB%B6?sort_id [= ](https://gitee.com/smart-doc-team/smart-doc/wikis/smart-doc%20maven%E6%8F%92%E4%BB%B6?sort_id=1791450)1791450 Only
> supports parameters marked with @RequestBody

Currently, it is only possible to configure common `headers` through `requestHeaders`, and I am unable to add common `query` parameters in the documentation.
Is there any plan to implement a feature for specifying parameter locations through global configuration?

For example:

```
"globalParameters": [
     "name": "Authorization",
     "type": "string",
     "parameterType": "query",  // Where to place the parameter: header, query, path, body.form
     "desc": "User token",
     "required": true,
     "value": "1"
]
```

**Comment by shalousun** [comment]
> requestBodyAdvice
> Reference:
> [https](https://gitee.com/smart-doc-team/smart-doc/wikis/smart-doc%20maven%E6%8F%92%E4%BB%B6?sort_id=1791450) : //gitee.com/smart-doc-team/smart-doc/wikis/smart-doc%20maven%E6%8F%92%E4%BB%B6?sort_id [= ](https://gitee.com/smart-doc-team/smart-doc/wikis/smart-doc%20maven%E6%8F%92%E4%BB%B6?sort_id=1791450)1791450 Only
> supports parameters marked with @RequestBody

Currently, it is only possible to configure common `headers` through `requestHeaders`, and I am unable to add common `query` parameters in the documentation.
Is there a plan to implement a feature for specifying parameter locations through global configuration?

For example:

```
"globalParameters": [
     "name": "Authorization",
     "type": "string",
     "parameterType": "query",  // Where to place the parameter: header, query, path, body.form
     "desc": "User token",
     "required": true,
     "value": "1"
]
```

Headers are already configured, so there's no need to set them again as header type.

**Comment by ZhongCW** [comment]
> requestBodyAdvice
> Reference:
> [https](https://gitee.com/smart-doc-team/smart-doc/wikis/smart-doc%20maven%E6%8F%92%E4%BB%B6?sort_id=1791450) : //gitee.com/smart-doc-team/smart-doc/wikis/smart-doc%20maven%E6%8F%92%E4%BB%B6?sort_id [= ](https://gitee.com/smart-doc-team/smart-doc/wikis/smart-doc%20maven%E6%8F%92%E4%BB%B6?sort_id=1791450)1791450 Only
> supports parameters marked with @RequestBody

Currently, it is only possible to configure common `headers` through `requestHeaders`, and I am unable to add common `query` parameters in the documentation.
Is there a plan to implement a feature for specifying parameter locations through global configuration?

For example:

```
"globalParameters": [
     "name": "Authorization",
     "type": "string",
     "parameterType": "query",  // Where to place the parameter: header, query, path, body.form
     "desc": "User token",
     "required": true,
     "value": "1"
]
```

My situation is as follows: http://localhost/users?page=1&pageSize=10 Here, the parameters page and pageSize are handled by an interceptor and can be used when calling any interface; these two parameters do not appear on the controller.
I hope to be able to configure the page and pageSize parameters to be added to the query-parameters section of all APIs through configuration.

**Comment by chenqi146** [comment]
#133
