### ISSUE TITLE
Exporting to Postman shows no response.

### ISSUE THREAD

**Issue by sidelines** [TongchengOpenSource/smart-doc#135]
Version 2.2.3, using the Maven plugin to generate Postman format data, the generated data does not include responses.
![image](https://user-images.githubusercontent.com/10252053/128344955-15a5a343-1dab-444d-9a0a-a455df0ffc14.png)

**Comment by shalousun** [comment]
@sidelines Please fill in the complete issue template according to the guidelines.

**Comment by netdied** [comment]
Postman does not have field descriptions for the response, so the generated Postman JSON does not include response content.
