### ISSUE TITLE
The constants in the request link are matched fuzzily, which may cause matching errors.

### ISSUE THREAD

**Issue by jasonkung22** [TongchengOpenSource/smart-doc#138]
## Your Environment (Your usage environment)
version:2.2.3

## Expected Behavior (Expected outcome)
The constants in the request link should be matched correctly.

## Current Behavior (Current outcome)
The constants in the request link are matched incorrectly.

## Possible Solution (Bug resolution suggestion)
Upon reviewing the source code, it was found that this issue is caused by using 'contains'. Other solutions such as 'equals' could be adopted.
![image](https://user-images.githubusercontent.com/26033689/128679376-1499a430-33b2-423a-8ac0-385aef5878eb.png)

## Steps to Reproduce (Steps to reproduce the bug, please provide example code if possible)
1. The links for two different interfaces are as follows:
![image](https://user-images.githubusercontent.com/26033689/128679215-f62a3362-d913-4995-b99b-54822700a528.png)
![image](https://user-images.githubusercontent.com/26033689/128679254-f50d76db-7c0e-42ac-9a82-fb5c65fba351.png)
2. They are parsed as follows:
![image](https://user-images.githubusercontent.com/26033689/128679281-02c0bf57-f62e-4f85-b393-42dd8354d50b.png)

**Comment by shalousun** [comment]
please provide test  case code.

**Comment by jasonkung22** [comment]
1. Within the same constant interface `UriConstant`, the following are defined:
   String ALL = "all";
   String ALL_NEARBY = "all-nearby";
2. In the interface, the following definitions exist:
   @GetMapping(UriConstant.ALL)
   @GetMapping(UriConstant.ALL_NEARBY)
3. The resulting parsed links will be:
   /all
   /all_NEARBY
