### ISSUE TITLE
Generated HTML file is too big in size

### ISSUE THREAD

**Issue by santoshbmath** [TongchengOpenSource/smart-doc#140]
Hi,

First of all thanks for such a nice tool. I was searching for such tool from long.

I generated the HTML document for one of our project which has around 36 services. The generated **HTML file (index.html) is about 21MB** which takes a lot of time to load in browser.

Please look into it if there's a way to reduce the size. One solution would be to provide an option to hide the request or response table similar to "**responseExample**" or "**requestExample**". Users can then select either to display example or just table. The table code in the HTML source is too much.

So options would be,
"requestExample": true | false
"responseExample": true | false
"requestTable": true | false
"responseTable": true | false

Thanks,
Santosh

**Comment by shalousun** [comment]
@santoshbmath In version 2.2.5, we will support controlling whether to display parameter tables in html document.
 options ,
"requestExample": true | false
"responseExample": true | false
"requestParamsTable": true | false // default  true
"responseParamsTable": true | false // default  true
