### ISSUE TITLE
Does it support generating markdown from CDP-style protocols?

### ISSUE THREAD

**Issue by Rimin** [TongchengOpenSource/smart-doc#142]
## Summary (Description of this PR)
Does it support generating markdown documents from CDP, i.e., https://chromedevtools.github.io/devtools-protocol/tot/?

### Basic example (Use case for the PR)
The repository for the specific CDP protocol is at https://github.com/ChromeDevTools/devtools-protocol; the files under the json directory there contain the protocol content. Then, based on this JSON, markdown files are generated.

### Motivation (Purpose of this PR)

We are using this form of protocol and would like to generate md documents, not in the form of web pages like https://chromedevtools.github.io/devtools-protocol/tot/ (which also has automatic generation tools), but in a more readable, convenient, and quick format.

**Comment by shalousun** [comment]
The core of smart-doc is to scan code to generate documentation. It is recommended to develop a separate tool by yourself.
