### ISSUE TITLE
Request headers were set, but they are not displayed in the generated interface documentation.

### ISSUE THREAD

**Issue by mostcool** [TongchengOpenSource/smart-doc#153]
## Your Environment (Your usage environment)
* smart-doc version: 2.2.7
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin): smart-doc-maven-plugin
* build tool version (maven or gradle): maven

## Expected Behavior (Expected outcome)
When using the smart-doc-maven-plugin to generate interface documentation, it should automatically add header request parameters.

## Current Behavior (Current outcome)
Headers were configured in smart-doc.json, but they do not appear in the generated documentation, and when sending a request, the headers are not included.

## Possible Solution (Bug resolution suggestion)
Suggestions for fixing the issue or reasons for the bug are not obligatory but can include ideas on how to implement the change or fix.

## Steps to Reproduce (Steps to reproduce the bug, please provide example code if possible)
Provide a link to a live example or an unambiguous set of steps to reproduce this bug. Include code to reproduce if relevant.
1.
2.
3.
4.

## Context (Description of how the bug affects you)
How has this issue affected you? What are you trying to accomplish? Providing context helps us come up with a solution that is most useful in the real world.

**Comment by mostcool** [comment]
```json
{
  "serverUrl": "http://localhost:8818",
  "pathPrefix": "",
  "isStrict": false,
  "allInOne": true,
  "outPath": "D://docs",
  "coverOld": true,
  "style": "xt256",
  "createDebugPage": true,
  "packageFilters": "",
  "md5EncryptedHtmlName": false,
  "projectName": "myweb",
  "requestFieldToUnderline": false,
  "responseFieldToUnderline": false,
  "sortByTitle": false,
  "showAuthor": true,
  "inlineEnum": true,
  "recursionLimit": 7,
  "allInOneDocFileName": "index.html",
  "requestExample": true,
  "responseExample": true,
  "requestParamsTable": true,
  "responseParamsTable": true,
  "displayActualType": false,
  "ignoreRequestParams": [
    "org.springframework.ui.ModelMap"
  ],
  "responseBodyAdvice": {
    "className": "com.test.common.RestResult"
  },
  "requestHeaders": [
    {
      "name": "gt",
      "type": "string",
      "desc": "token",
      "value": "xxxxxx",
      "required": true,
      "pathPatterns": "*",
      "excludePathPatterns": "/admin/security/login",
      "since": "-"
    }
  ]
}
```

**Comment by oleilei** [comment]
Remove the configuration: "pathPatterns": "*"
