### ISSUE TITLE
The configuration file cannot obtain the Maven configuration

### ISSUE THREAD

**Issue by moil-xm** [TongchengOpenSource/smart-doc#156]
## Summary(关于这个pr的描述)

The configuration file cannot obtain the Maven configuration

### Basic example(pr的用例)

such as "projectName": "${project.artifactId}",

**Comment by shalousun** [comment]
The `ProjectName` can be set in the configuration of the Maven plug-in.

**Comment by moil-xm** [comment]
This will not solve all problems.
Unless the configuration items of smart.json can be configured in maven.
such as pathPrefix,outPath,allInOneDocFileName

**Comment by moil-xm** [comment]
I will think that the configuration file can be written in maven more appropriate.
