### ISSUE TITLE
It is suggested to enrich custom tags. For example, if you want to achieve a grouping effect with @ignore, how should it be handled?

### ISSUE THREAD

**Issue by VirtiL** [TongchengOpenSource/smart-doc#159]
## Summary (Description of this PR)

There is a scenario where I haven't found a solution in the documentation. The situation is as follows:
We use the same form object to provide input parameters for multiple interfaces. We want to accurately display the corresponding parameters for each interface in Torna, and ignore the extraneous ones. An example of how to achieve this using validation annotations is shown below. If we want to achieve the same effect using @ignore or @ignoreParams, how should we handle it?
The desired final effect is as follows:

In the page interface documentation, the parameters should only include pageSize and pageNo.
In the list interface documentation, the parameter should only be id.
In the select interface documentation, the parameters should only include id and name.

### Basic Example (Use Case for the PR)

```java
/**
 * Interface 1
 *
 * @param search Parameter
 * @return WebResult
 */
@GetMapping("/page")
public WebResult<Page<TestVO>> page(@Validated({PageGroup.class}) TestSearch search) {}

/**
 * Interface 2
 *
 * @param search Parameter
 * @return WebResult
 */
@GetMapping("/list")
public WebResult<List<Test>> list(@Validated({ListGroup.class}) TestSearch search) {}

/**
 * Interface 3
 *
 * @param search Parameter
 * @return WebResult
 */
@GetMapping("/select")
public WebResult<TestVO> select(@Validated({OtherGroup.class}) TestSearch search) {}

// Same form
@Data
public class TestSearch implements Serializable {

    /**
     * Page size
     */
    @NotNull(message = "Page size cannot be empty", groups = {PageGroup.class})
    private Integer pageSize = 20;

    /**
     * Page number
     */
    @NotNull(message = "Page number cannot be empty", groups = {PageGroup.class})
    private Integer pageNo = 1;

    /**
     * id
     */
    @NotNull(message = "Id cannot be empty", groups = {ListGroup.class, OtherGroup.class})
    private Integer id;

    /**
     * Name
     */
    @NotBlank(message = "Name cannot be empty", groups = {OtherGroup.class})
    private String name;
}
```

**Comment by shalousun** [comment]
It is recommended that you read the official documents carefully. We are very cautious about using custom document tags because it deviates from the development specifications. Some custom tags will even be discarded in the future.
