### ISSUE TITLE
In allInOne mode, there is an issue with the sequence numbers on the left side.

### ISSUE THREAD

**Issue by QinHongZhe** [TongchengOpenSource/smart-doc#160]
## Your Environment(您的使用环境)

* smart-doc version:
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin):
* build tool version(maven or gradle):

## Current Behavior(当前结果)

![X8 RLQI UHTLN{R9MQV`J25](https://user-images.githubusercontent.com/25653313/143179408-d5d4675f-82de-4b05-88ff-136c15eb49d7.png)

## Steps to Reproduce (Bug产生步骤，请尽量提供用例代码)

1.
2.
3.
4.

**Comment by chenqi146** [comment]
fix 3f49c3ecd672a25020f22a6ff4459da46a3a99f8
