### ISSUE TITLE
When using the @RequestMapping annotation in a controller and not specifying the request method, only GET methods are generated in the documentation.

### ISSUE THREAD

**Issue by fanyawei** [TongchengOpenSource/smart-doc#162]
## Summary (Description of this PR)
Usage scenario:
There is a request that can accept any type of HTTP request and handles them all in the same way.

### Basic Example (Use Case for the PR)
```java
/**
 * Global error handling
 */
@RestController
@RequestMapping("/error")
public class GlobalErrorController implements ErrorController {

	/**
	 * Error handling example
	 * 
	 * @return
	 */
	@RequestMapping
	public Result<Void> error() {
		// Error handling logic
		return Result.success();
	}
}
```
Only generated for GET request method
![image](https://user-images.githubusercontent.com/8381679/143777526-a9c1ea4e-3a98-4d02-a8a9-018de1d8420f.png)
![image](https://user-images.githubusercontent.com/8381679/143777472-6517956b-8a09-42bc-9f12-dd57e4e6f8dc.png)

### Motivation (Purpose of this PR)
It is suggested to generate for all eight types of request methods in Spring MVC.

**Comment by shalousun** [comment]
In practice, this method is usually rarely used. Smart-doc does not need to increase complexity for a rarely used scenario. Our philosophy is only to cover most best practice scenarios, not to satisfy all users.
