### ISSUE TITLE
The plugin does not support maven multi-module projects

### ISSUE THREAD

**Issue by ciweigg2** [TongchengOpenSource/smart-doc#17]

**Comment by netdied** [comment]
For multi-module projects, you need to configure the SourceCodePath and include the paths of projects that are not part of this module.
对于多模块项目 需要配置SourceCodePath 将不是该模块的项目路径加进来

**Comment by ciweigg2** [comment]
"sourceCodePaths": [ //设置代码路径，smart-doc默认会自动加载src/main/java, 没有需求可以不设置
    {
      "path": "alibaba-gift",
      "desc": "测试"
    },
    {
      "path": "alibaba-live",
      "desc": "测试"
    },
    {
      "path": "alibaba-user",
      "desc": "测试"
    }
  ]
The documentation has been generated, but the request and response parameters were not parsed. Is there something else that needs to be configured?
文档生成了 但是请求参数返回参数都没解析出来 需要配置别的么？

![image](https://user-images.githubusercontent.com/41536971/70986631-3cf73180-20f9-11ea-81dc-66469e264c2f.png)

**Comment by netdied** [comment]
![image](https://user-images.githubusercontent.com/20217389/70986869-bdb62d80-20f9-11ea-81d2-9133f18a36da.png)


外部项目配置全路径

**Comment by ciweigg2** [comment]
I placed the plugin in the parent POM, and other modules have been configured according to your method, but it still doesn't work.
我把插件放在了父pom中 其他模块配置路径按照你的方法配置了 还是不行

**Comment by netdied** [comment]
You can start by using smart-doc's unit tests. The plugin has some issues with multi-module projects, and we are currently investigating them.
可以先使用smart-doc的单元测试 插件在针对多module项目时存在一些问题 我们正在排查

**Comment by shalousun** [comment]
@ciweigg2 The maven standard multi-module project has been supported in smart-doc-maven-plugin 1.0.2.
