### ISSUE TITLE
When there are a large number of interfaces, the HTML page is very laggy.

### ISSUE THREAD

**Issue by SugarPPig** [TongchengOpenSource/smart-doc#189]
## Summary(关于这个pr的描述)

Brief explanation of the feature.

### Basic example(pr的用例)

If the proposal involves a new or changed API, include a basic code example. Omit this section if it's not applicable.

### Motivation(提出这个pr目的)

Why are we doing this? What use cases does it support? What is the expected outcome?

**Comment by shalousun** [comment]
@SugarPPig When the html document is large, browser rendering will have performance problems. This can't be solved, it is recommended to put the document into Torna for management
