### ISSUE TITLE
Postman GET request parameter generation.

### ISSUE THREAD

**Issue by ciweigg2** [TongchengOpenSource/smart-doc#19]
I noticed you fixed the bug I previously reported about generating GET parameters in Postman. After downloading the dev branch, I tested it. The interface cannot support file upload types.
看你们修复了我之前提的postman生成get参数的bug
我下载了dev分支后 测试了
接口中存在文件上传类型无法支持

    @GetMapping(value = "/test")
    public void test(@RequestParam MultipartFile file ,@RequestParam String aaa)

    @PostMapping(value = "/test")
    public void test(@RequestParam MultipartFile file ,@RequestParam String aaa)

**Comment by shalousun** [comment]
Smart-doc will not support FormData generation examples in the short term.
smart-doc短期内不会对FormData生成示例做支持。
