### ISSUE TITLE
When the return value of the interface method is String or enum, the document cannot generate the specified value

### ISSUE THREAD

**Issue by jxw1989** [TongchengOpenSource/smart-doc#199]
## Summary(关于这个pr的描述)

When the return value of the interface method is String or enum, the document cannot generate the specified value

### Basic example(pr的用例)
/**
* @return @mock SUCCESS
**/
@PostMapping("/test")
@ResponseBody
String test(){
 return "success"
}
OR 
/**
* @return {@link ResultEnum } @mock SUCCESS
**/
class enum ResultEnum{
  SUCCESS.FAIL;
}
@PostMapping("/test")
@ResponseBody
ResultEnum test(){
 return ResultEnum.valueOf("SUCCESS")
}
### Motivation(提出这个pr目的)

Why are we doing this? What use cases does it support? What is the expected outcome?

**Comment by netdied** [comment]
use @ response

**Comment by jxw1989** [comment]
> use @ response
set default value
