### ISSUE TITLE
Can the document title be modified?

### ISSUE THREAD

**Issue by zhangleijie** [TongchengOpenSource/smart-doc#2]
![image](https://user-images.githubusercontent.com/10412168/68539646-8a2d0880-03c1-11ea-898c-6c669851b97b.png)
![image](https://user-images.githubusercontent.com/10412168/68539649-931dda00-03c1-11ea-8032-9951d5a2d9e9.png)

Hello, I'd like to know how to set a title alias for this tool. Sometimes I want to set the title in Chinese and add a new column display. For example:

Parameter Type Description Required Since
Field Type Description Since

Parameter Name Type Description Required Field Length Version Parent Node
Field Name Type Description ........

**Comment by shalousun** [comment]
There are two ways: one is to modify the source code yourself, and the other is to customize the interface data of smart-doc, then use a custom template for rendering.
有两种方式：一种是自己改源码内部使用，另一种是自己使用开放的数据，然后自定义模板渲染
