### ISSUE TITLE
 I've used ModelAndView globally in my project. Is it possible to skip this without encountering an error during generation?

### ISSUE THREAD

**Issue by yuxicun** [TongchengOpenSource/smart-doc#20]
Hello, I've used ModelAndView globally in my project. Is it possible to skip this during generation without causing an error? Because this class is needed, but every time an interface is generated, this method has to be deregistered, which is a bit troublesome.
您好,我在项目中全局使用了ModelAndView,能否在生成的时候遇到这个就跳过,不报错呢,因为这个类是需要使用的,但是每次生成接口的时候,都要把这个方法注销,有点麻烦

**Comment by yuxicun** [comment]
@RequestMapping({ "/{url}.html", "/{module}/{url}.html" })
	public ModelAndView page(@PathVariable(name = "module", required = false) String module,
			@PathVariable("url") String url, @RequestParam Map<String, Object> params) {
		if (module != null)
			return new ModelAndView(module + "/" + url, params);
		return new ModelAndView(url, params);
	}

**Comment by yuxicun** [comment]
The above is the method that causes the error.
上面是我报错的方法

**Comment by shalousun** [comment]
@yuxicun  This is used for returning pages, right? I'll handle it later. What I considered previously was that front-ends are now mostly developed separately, so at that time I wasn't really keen on providing this support. For new projects, I don't recommend using this kind of return globally; the generated documentation isn't very meaningful.
你这是用于返回页面的吧，后期处理下，我之前考虑的是现在前端基本都是单独开发了，所以当时并不是很想提供这个支持，新项目不建议全局使用这种返回，生成的文档没有什么意义

**Comment by yuxicun** [comment]
Alright, and also, is it possible to add a feature to exclude fields? For example, for soft deletes, the field definitely doesn't need to be returned to the front end.
好的,还有就是是否可增加排除字段功能,比如说假删除,返回给前端肯定不需要假删除字段

**Comment by shalousun** [comment]
@yuxicun You can refer to the official Chinese documentation, which covers both request and response field ignoring.
