### ISSUE TITLE
When importing other packages in the project, smart-doc cannot see the descriptions of the fields.

### ISSUE THREAD

**Issue by skyBuleXiaoXiong** [TongchengOpenSource/smart-doc#204]
## Your Environment(您的使用环境)

* smart-doc version:
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin):
* build tool version(maven or gradle):

## Steps to Reproduce (Bug产生步骤，请尽量提供用例代码)

1.
2.
3.
4.

**Comment by netdied** [comment]
Analyzing other toolkits requires generating a resource package during the build process. Refer to the documentation at https://smart-doc-group.github.io/#/zh-cn/QA for more information.

**Comment by netdied** [comment]
If it's helpful, please close the issue.
