### ISSUE TITLE
Does not support cases where RequestMapping includes multiple paths with parameters.

### ISSUE THREAD

**Issue by Duncan-tree-zhou** [TongchengOpenSource/smart-doc#206]
## Your Environment
- smart-doc version: Tested versions 2.2.2, 2.2.3, 2.3.3, and 2.4.0 all exhibit this issue.
- plugin version (e.g., smart-doc-maven-plugin or smart-doc-gradle-plugin): N/A
- build tool version (maven or gradle): N/A

## Expected Behavior
- If you're describing a bug, tell us what should happen.
- If you're suggesting a change/improvement, tell us how it should work.

## Current Behavior
- When using the Spring MVC `@RequestMapping` annotation, if the path contains two or more identically named parameters, an error occurs:
```java
java.lang.IllegalStateException
	at java.util.LinkedHashMap$LinkedHashIterator.remove(LinkedHashMap.java:730)
	at com.power.doc.utils.DocUtil.formatAndRemove(DocUtil.java:289)
	at com.power.doc.template.SpringBootDocBuildTemplate.buildReqJson(SpringBootDocBuildTemplate.java:606)
	at com.power.doc.template.SpringBootDocBuildTemplate.buildControllerMethod(SpringBootDocBuildTemplate.java:339)
	at com.power.doc.template.SpringBootDocBuildTemplate.getApiData(SpringBootDocBuildTemplate.java:89)
	at com.power.doc.builder.OpenApiBuilder.openApiCreate(OpenApiBuilder.java:82)
	at com.power.doc.builder.OpenApiBuilder.buildOpenApi(OpenApiBuilder.java:70)
	at com.smartdoc.gradle.task.OpenApiTask.executeAction(OpenApiTask.java:39)
	at com.smartdoc.gradle.task.DocBaseTask.action(DocBaseTask.java:99)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
        ...
```
The cause of the issue is that the logic in the following link executes the inner while loop twice, but the iterator only has one item because the parameters are named the same:
https://github.com/smart-doc-group/smart-doc/blob/fc8a6e0c14752ce386e59345079c3d0752f00dfe/src/main/java/com/power/doc/utils/DocUtil.java#L304-L322

## Possible Solution
- Not obligatory, but suggest a fix/reason for the bug, or ideas on how to implement the addition or change.

## Steps to Reproduce
- Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant:
1.
2.
3.
4.

## Context
- How has this issue affected you? What are you trying to accomplish? Providing context helps us come up with a solution that is most useful in the real world.

**Comment by shalousun** [comment]
@Duncan-tree-zhou Please provide a complete example that triggers the error.

**Comment by Duncan-tree-zhou** [comment]
> @Duncan-tree-zhou Please provide a complete example that triggers the error.

Error occurs when using configurations like the following:

```java
@RequestMapping(value={"prefix1/{param1}/suffix","prefix2/{param1}/suffix"})
```

**Comment by netdied** [comment]
Upon testing, no issues were found.
![image](https://user-images.githubusercontent.com/20217389/159425694-53f7820d-9e77-4cfd-a0be-bc58159fbc90.png)
![image](https://user-images.githubusercontent.com/20217389/159425826-46338a64-cb79-4bb0-a9f5-57d0e6ad88a0.png)
For the demo that encountered an error, you can refer to https://github.com/smart-doc-group/smart-doc-example-cn to examine the specific issue.

**Comment by Duncan-tree-zhou** [comment]
>Upon testing, no issues were found.
![image](https://user-images.githubusercontent.com/20217389/159425694-53f7820d-9e77-4cfd-a0be-bc58159fbc90.png)
![image](https://user-images.githubusercontent.com/20217389/159425826-46338a64-cb79-4bb0-a9f5-57d0e6ad88a0.png)
The demo with errors can be referenced at https://github.com/smart-doc-group/smart-doc-example-cn to examine the specific issue.

When RequestMapping includes multiple paths, there are no problems with method-level annotations; the issue arises with class-level annotations.

**Comment by Duncan-tree-zhou** [comment]
@RestController
@RequestMapping(value={"prefix1/{param1}/suffix","prefix2/{param1}/suffix"})
public class MyController {
...
}

**Comment by shalousun** [comment]
@Duncan-tree-zhou How is this path bound at the class level? If it cannot be normally bound, handling this situation is meaningless.

**Comment by Duncan-tree-zhou** [comment]
> @Duncan-tree-zhou How is this path bound at the class level? If it cannot be normally bound, handling this situation is meaningless.

This approach is supported by Spring MVC, allowing it to match two types of prefixes.
