### ISSUE TITLE
The `@apiNote` annotation is not taking effect.

### ISSUE THREAD

**Issue by 89333367** [TongchengOpenSource/smart-doc#207]
## Your Environment
- smart-doc-maven-plugin: 2.4.0
- build tool version(maven or gradle): maven 3.8.2

## Expected Behavior
Documentation generation is expected.

## Current Behavior
![image](https://user-images.githubusercontent.com/20157752/158300711-8a7029b3-8f8c-4b38-989f-693a50cdd1ef.png)

## Context
![image](https://user-images.githubusercontent.com/20157752/158300750-3a931ba4-e5f9-43cb-8964-db75c60263e1.png)

**Comment by netdied** [comment]
apiNode is only applicable for class introductions. The documentation has errors, apologies for the inconvenience, fix in progress.
