### ISSUE TITLE
Does it support overriding response field names?

### ISSUE THREAD

**Issue by Gahon1995** [TongchengOpenSource/smart-doc#208]
## Summary (Description of this PR)

The current `customResponseFields` supports replacing comments and values, but in some scenarios, the response data undergoes unified response code conversion on the gateway side, such as replacing 'code' with 'ret', and 'message' with 'msg'. So, I would like to ask if it is possible to support replacing the generated response field names?

### Basic Example (Use Case for the PR)

Add a configuration `replaceName` to the `customResponseFields` settings. When this field has a value, replace the corresponding field name with the value corresponding to `replaceName`.

**Comment by Gahon1995** [comment]
After using `replaceName` to replace the response name, it has been replaced in the 'fields', but not in the 'example'. Thank you for providing this feature.

**Comment by netdied** [comment]
忘了这里了。

**Comment by netdied** [comment]
Alright, sorry for forgetting to modify the example.
