### ISSUE TITLE
 No plugin found for prefix 'smart-doc' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories

### ISSUE THREAD

**Issue by 283288675** [TongchengOpenSource/smart-doc#210]
## Your Environment(您的使用环境)

* smart-doc version:2.3.4
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin):
* build tool version(maven or gradle):

## Current Behavior(当前结果)

[ERROR] No plugin found for prefix 'smart-doc' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories
## Steps to Reproduce (Bug产生步骤，请尽量提供用例代码)

1.
2.
3.
4.

**Comment by netdied** [comment]
多module项目看一下你的插件放在了哪个pom里 通过命令行执行 https://smart-doc-group.github.io/#/zh-cn/plugins/maven_plugin?id=maven%e5%a4%9a%e6%a8%a1%e5%9d%97%e4%b8%ad%e4%bd%bf%e7%94%a8%e6%8f%92%e4%bb%b6

**Comment by shalousun** [comment]
@283288675 https://smart-doc-group.github.io/#/zh-cn/QA?id=%e9%a1%b9%e7%9b%ae%e6%97%a0%e6%b3%95%e5%8a%a0%e8%bd%bdsmart-doc%e7%9a%84%e6%8f%92%e4%bb%b6
