### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by 283288675** [TongchengOpenSource/smart-doc#212]
## Your Environment(您的使用环境)

* smart-doc version: 2.4.0
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin): 2.4.0
* build tool version(maven or gradle): maven

## Current Behavior(当前结果)

![90bc70ad446d053f9164c32a4a41e7e](https://user-images.githubusercontent.com/15771966/158728152-919096d0-fc95-42b6-bf58-b2107065e082.png)

## Steps to Reproduce (Bug产生步骤，请尽量提供用例代码)

execute ：mvn smart-doc:torna-rest -D file.encoding=UTF-8
OR
![image](https://user-images.githubusercontent.com/15771966/158728382-98340e22-a274-4fdd-a646-06ee31211920.png)

**Comment by netdied** [comment]
项目比较大需要设置参数  -Xms1042m -Xmx2048m

**Comment by shalousun** [comment]
@283288675 https://smart-doc-group.github.io/#/zh-cn/QA?id=%e5%86%85%e5%ad%98%e6%ba%a2%e5%87%ba%e4%ba%86%e6%80%8e%e4%b9%88%e8%a7%a3%e5%86%b3%ef%bc%9f
