### ISSUE TITLE
During page debugging mode, the data in the request header is forced to be encoded using encodeURI.

### ISSUE THREAD

**Issue by tangboming** [TongchengOpenSource/smart-doc#213]
## Your Environment (Your Use Environment)

* smart-doc version: 2.3.2
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin): smart-doc-maven-plugin
* build tool version (maven or gradle): maven

## Expected Behavior (Expected Result)
```javascript
function getInputData(element, returnFormDate) {
    const formData = new FormData();
    $(element).find("tr").each(function (i) {
        const checked = $(this).find('td:eq(0)').children(".checkbox").children("input").is(':checked');
        if (checked) {
            const input = $(this).find('td:eq(2) input');
            console.log("input type:" + $(input).attr("type"))
            const name = $(input).attr("name");
            if ($(input).attr("type") == "file") {
                formData.append(name, $(input)[0].files[0]);
            } else {
                const val = $(input).val();
                if (isValidUrl(val)) {
                    formData.append(name, encodeURI(val));
                } else {
                    // support chinese
                    formData.append(name, encodeURIComponent(val));
                }
            }
        }
    });
    if (returnFormDate) {
        return formData;
    }
    const headersData = {};
//    formData.forEach((value, key) => headersData[key] = value); // This line forces URL encoding on the value, causing the server to not receive the original request header data when submitted
    formData.forEach((value, key) => headersData[key] = decodeURIComponent(value)); // This line is the modified one, it needs to URL decode the value
    return headersData;
}
```

## Current Behavior (Current Result)
For example, if we need to submit an HTTP header like this:
TOKEN: 32q4r1234##!#$#
But after `encodeURIComponent("32q4r1234##!#$#")`, we get:
TOKEN: 32q4r1234%23%23!%23%24%23
The server will not be able to obtain the correct value (unless processed by `decodeURI`), requiring modifications to the underlying framework.
However, the HTTP specification does not require request headers to be encoded, and current HTTP servers do not perform decoding on request header information either.

## Possible Solution (Bug Fix Suggestion)
There is no need to process HTTP request headers with `encodeURI`.

## Steps to Reproduce (Steps to Reproduce the Bug)

1.
2.
3.
4.

**Comment by shalousun** [comment]
@tangboming This is an example of incorrectly raising an issue, where a new version is not tried first and instead, old issues are re-raised. It is recommended to always try upgrading and testing with smart-doc or other open-source software before raising ineffective issues.

**Comment by tangboming** [comment]
After upgrading the plugin to versions 2.3.9 and 2.4.0, the following issues have been encountered:

The issue manifests as follows: a controller method is defined as
```java
@RequestMapping(value = "/activity/info", method = { RequestMethod.GET })
public Object method() {
    // Method content omitted
}
```
During debugging, the generated CURL command is as follows:
```
curl -X **[RequestMethod.GET]** -H 'Content-Type: application/x-www-form-urlencoded;charset=utf-8' -H 'X-Auth-Token:ateccdasdfae' -H 'testUid:16001234133511' -i http://127.0.0.1:15461/activity/info
```
Clicking the "Send Request" button results in "Connection refused, please check the server."
![image](https://user-images.githubusercontent.com/2820011/159200768-c3cf954b-b582-4233-b9ed-0fd0d51c3f8f.png)

**Comment by shalousun** [comment]
@tangboming It is recommended to change it to `method = RequestMethod.GET` or directly use `GetMapping`. The approach of using `method = { RequestMethod.GET }` is currently not supported, and there are no plans to support it in the future. Nowadays, most people use `GetMapping` or `method = RequestMethod.GET`. As for the issue with the service not connecting, it is unrelated to the above; if you do not start the backend service, it will definitely not connect. Such issues can be resolved by checking the browser console.
