### ISSUE TITLE
Unable to recognize constants within the value of `@RequestMapping`.

### ISSUE THREAD

**Issue by SugarFatFree** [TongchengOpenSource/smart-doc#216]
## Your Environment(您的使用环境)
* smart-doc version:2.4.1
* plugin version (e.g. smart-doc-maven-plugin ):2.4.1

## Current Behavior(当前结果)
![B2F043F9-854B-4BFD-9EE7-EF9FDE979C9F](https://user-images.githubusercontent.com/30424828/160736765-3071e2ba-5c89-42c8-b4ce-379a9f44ca93.png)

![49F5D973-09B1-4630-92C9-988F1FAE495A](https://user-images.githubusercontent.com/30424828/160736773-756c2138-842a-4dca-a8bf-aa1a89a5c18a.png)

**Comment by shalousun** [comment]
@hu1240050829 Revert to 2.4.0 for configuration; the automatic handling currently has a bug.

**Comment by SugarFatFree** [comment]
> @hu1240050829 Revert to 2.4.0 for configuration; the automatic handling currently has a bug.

I don't seem to find this configuration annotation in the documentation. How should I proceed?

**Comment by shalousun** [comment]
@hu1240050829 The apiConstants configuration item.
