### ISSUE TITLE
Error in parsing List<Map<String, T>>.

### ISSUE THREAD

**Issue by flywalker** [TongchengOpenSource/smart-doc#223]
## Your Environment

* smart-doc version: 2.4.0
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin): smart-doc-maven-plugin 2.4.0
* build tool version(maven or gradle): 3.6.3

## Expected Behavior

List<Map<String, T>> should be able to parse correctly into
[
    { 
       "map1Key1":{ "key1":"value1", "key2":"value2" }
    },
    { 
      "map2key1":{ "key1":"value1", "key2":"value2" },
      "map2key2":{ "key1":"value1", "key2":"value2" }
    }
]

## Current Behavior

The official example List<Map<String, T>> parsing is incorrect, missing the Map's Key
![ZMYXU@JA$ W_C$C8IF7LK7](https://user-images.githubusercontent.com/9003873/161366288-54257aa7-7d72-4990-b1b2-724c0faa8563.png)

## Steps to Reproduce (Bug产生步骤，请尽量提供用例代码)

1.
2.
3.
4.

**Comment by shalousun** [comment]
@flywalker The data generated by smart-doc is correct, but there are discrepancies when pushing and integrating with torna.
