### ISSUE TITLE
Configuration bug in groups.

### ISSUE THREAD

**Issue by SecureDong** [TongchengOpenSource/smart-doc#226]
## Your Environment

* smart-doc version:
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin): 2.4.1
* build tool version(maven or gradle):
*
## Context (Bug Impact Description)
The "groups" configuration is incorrect when pushed to torna, affecting the group structure. This issue occurs during the first push and with repeated pushes.

```json
"groups": [
    {
      "name": "",
      "apis": ""
    }
]
```

**Comment by shalousun** [comment]
@SecureDong, please add a project description because your group configuration is incorrect and it also differs from what you expect.

**Comment by SecureDong** [comment]
"packageFilters": "com.test.iot.system.domain.commonManager.RoleController",
  "groups": [
    {
      "name": "open",
      "apis": "com.test.iot.system.domain.commonManager.RoleController"
    }
  ],
With this configuration, it is expected that all interfaces in RoleController will be under the 'open' group. However, after pushing, the following result is obtained:

![image](https://user-images.githubusercontent.com/68154292/161434001-96ad16ee-fe65-4e41-9dd7-c10f3649ffcb.png)

**Comment by shalousun** [comment]
@SecureDong When multiple groups exist, there may be issues with the precise filtering limitation of packageFilters.
