### ISSUE TITLE
When the response is a Map<String, Object>, annotate the key.

### ISSUE THREAD

**Issue by Lidozh** [TongchengOpenSource/smart-doc#228]
## Summary
Sometimes, when returning a List<Object>, in order to facilitate front-end value retrieval based on keys, the List<Object> is converted into a map<String, Object> using the Collectors.toMap method. Currently, the examples returned by the map are "mapKey1", "mapKey2", etc., but it is necessary to add corresponding comments to the key; additionally, constructing some simple objects into a map is more convenient for use, and the key values are taken from certain field names, so it is also necessary to add related comment functions for the map's keys.
Brief explanation of the feature.

### Basic example

If the proposal involves a new or changed API, include a basic code example. Omit this section if it's not applicable.

### Motivation

Why are we doing this? What use cases does it support? What is the expected outcome?

**Comment by shalousun** [comment]
@Lidozh does not support this, and there is no elegant way to accommodate such settings. You can refer to https://smart-doc-group.github.io/#/zh-cn/start/javadoc?id=_26-response%e4%bd%bf%e7%94%a8%e4%b8%8d%e6%8e%a8%e8%8d%90 for more information.
