### ISSUE TITLE
The Controller inherits from the Feign interface, but fails to scan the interface documentation.

### ISSUE THREAD

**Issue by siriusdream37** [TongchengOpenSource/smart-doc#229]
# Your Environment
smart-doc version: 2.4.0
plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin): smart-doc-maven-plugin 2.4.0
build tool version (maven or gradle): 3.6.3
# Expected Behavior
The interface documentation should be able to scan normally.
# Current Behavior
The interface documentation cannot be scanned normally.
Example code:
controller:
```
@RestController
@EnableBodyResponseWrap
public class MsisdnController implements MsisdnClient
```

feign interface:
```
@FeignClient(name = "${mos.province.integration}", contextId = "MsisdnClient",qualifier ="MsisdnClient")
public interface MsisdnClient {
    /**
     * Single number activation time query
     * @param param
     * @return
     */
    @PostMapping("/triopi/member/actitime/single/query")
    MemberActitimeSingleQueryVo msisdnActiveInfo(@RequestBody MemberActitimeSingleQueryReq param);
}
```

**Comment by chenqi146** [comment]
May I ask if the MsisdnController has implemented any interfaces?

**Comment by chenqi146** [comment]
Currently, Feign scans the Feign interface to generate documentation. You can try scanning the package path of the Feign.

**Comment by siriusdream37** [comment]
MsisdnController has implemented the interface. Does scanning the Feign package path require separate configuration? If so, how can it be set up?

**Comment by chenqi146** [comment]
You need to add the @restApi tag to the comments in the Feign interface.
![image](https://user-images.githubusercontent.com/36069431/162599489-770f7696-9397-41b8-976e-7e206eb17607.png)
