### ISSUE TITLE
When generating markdown, each time the record field is identified as an exception, syntax error, resulting in generation failure.

### ISSUE THREAD

**Issue by owendawn** [TongchengOpenSource/smart-doc#231]
## Current Behavior
When generating Markdown, an exception is thrown each time the record parameter is included.

Syntax error @[71,52] in file:/D:/workstation/intellij/uv-tcp/hh-media-control-plus/src/main/java/com/hh/media/controller/PlayBack3Controller.java

![image](https://user-images.githubusercontent.com/13972781/163361011-9319a1a4-3f50-4a3e-a9f3-4b9c80d6bad0.png)

## Possible Solution
Hope to fix this bug

**Comment by netdied** [comment]
Java 17 has adopted "record" as a keyword. It is recommended not to use "record" as a variable name, as upgrading the JDK will also be affected.

**Comment by shalousun** [comment]
https://smart-doc-group.github.io/#/zh-cn/QA?id=syntax-error%ef%bc%9f

**Comment by owendawn** [comment]
Understood, OK.
