### ISSUE TITLE
When 'requestExample' is set to false, the sample data cannot be removed.

### ISSUE THREAD

**Issue by inernoro** [TongchengOpenSource/smart-doc#233]
* smart-doc version: 2.4.2
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin): small:openapi
* build tool version (maven or gradle): mvn 3.5.2 and Java 1.8.0_41
* Spring version 2.6.3 on Windows 11 system
* IntelliJ IDEA version 2021.3.3

## Expected Behavior (What you expect to happen)
> When the configuration option 'requestExample' is set to false, example data should not be generated.

## Current Behavior (What is actually happening)
> The generated sample reference data cannot be removed.

## Steps to Reproduce (Bug reproduction steps, please provide test code if possible)
This issue occurs with any interface.

## It causes OpenAPI to generate code using data from the examples to modify class names
> Even when set to false, it still exists.
![image](https://user-images.githubusercontent.com/9151851/163564645-0a91069a-9f51-4b72-94a8-98e5290602fc.png)
> This results in
![image](https://user-images.githubusercontent.com/9151851/163564767-878a2627-c58b-434e-af69-f6f414498866.png)

### smart-doc.json (local, privacy not affected)
```json
{
  "requestExample": false,
  "responseExample": false,
  "outPath": "api",
  "serverUrl": "http://192.168.5.36:7878",
  "isStrict": false,
  "projectName": "sirius",
  "appToken": "1d577ec5d60648afb65daadb8718eea9",
  "openUrl": "http://192.168.5.166:7700/api",
  "debugEnvName": "测试环境",
  "replace": true,
  "debugEnvUrl": "http://192.168.5.36:7878",
  "responseBodyAdvice": {
    "className": "com.miduonet.sirius.classlibrary.basiccomponents.ResultData"
  }
}
```
### pom.xml configuration
```xml
<plugin>
    <groupId>com.github.shalousun</groupId>
    <artifactId>smart-doc-maven-plugin</artifactId>
    <version>2.4.2</version>
    <configuration>
        <!--Specify the configuration file used for generating the documentation, placed in your own project-->
        <configFile>./src/main/resources/smart-doc.json</configFile>
        <!--Specify the project name-->
        <projectName>测试</projectName>
        <includes>
            <include>com.alibaba:fastjson</include>
        </includes>
    </configuration>
    <executions>
        <execution>
            <!--If you do not need to start smart-doc when compiling, comment out the phase-->
            <phase>compile</phase>
            <goals>
                <!--smart-doc provides goals like html, openapi, markdown, etc., which can be configured as needed-->
            </goals>
        </execution>
    </executions>
</plugin>
```

**Comment by shalousun** [comment]
@inernoro This configuration option only affects HTML and Markdown, which can be directly displayed.
