### ISSUE TITLE
The name of operationId is not very reasonable; it might be optimized or allowed to be configured by the user.

### ISSUE THREAD

**Issue by inernoro** [TongchengOpenSource/smart-doc#235]
The name of operationId is not very reasonable; it might be optimized or allowed to be configured by the user.

> The smart-generated OpenAPI includes
![image](https://user-images.githubusercontent.com/9151851/163745227-f10d7174-21c3-44d0-9794-a37466746d56.png)
> This automatically generated operationId ID

> The code is located here:
![image](https://user-images.githubusercontent.com/9151851/163745274-47e9aebf-253a-4132-b807-7663edfd7b95.png)
It is not user-friendly in the OpenAPI generator.

> When I did not delete operationId
![image](https://user-images.githubusercontent.com/9151851/163745430-bce72b86-8c53-48ac-a4ad-6d7080e385f4.png)

> When I deleted operationId, it returned to normal
![image](https://user-images.githubusercontent.com/9151851/163745392-98f7c2fc-9fb7-43c2-b9eb-7667ba4cbca9.png)

When I discovered that operationId in various languages
> For example: C#
![image](https://user-images.githubusercontent.com/9151851/163745723-4c70130d-105b-4498-bbb8-9929f2efe316.png)

> axios
![image](https://user-images.githubusercontent.com/9151851/163745939-ce92cf0c-fed1-4721-9aee-a58c13ef6166.png)
> All have this issue

# Suggestion: Is there a configuration that can remove operationId or use operationId as an excellent custom configuration method name?
> axios
![image](https://user-images.githubusercontent.com/9151851/163745939-ce92cf0c-fed1-4721-9aee-a58c13ef6166.png)

**Comment by shalousun** [comment]
@inernoro, simply adding a configuration option to control the generation would be preferable, as configuring it manually actually involves a significant amount of work.

**Comment by inernoro** [comment]
> @inernoro, simply adding a configuration option to control the generation would be preferable, as configuring it manually actually involves a significant amount of work.

I tested it and found that without this, the unique names generated for each language can become quite varied and peculiar. The operationId serves as a guiding principle, with customizable combinations of controllers and methods.

**Comment by shalousun** [comment]
Use method name instead of rondom value

**Comment by inernoro** [comment]
![image](https://user-images.githubusercontent.com/9151851/166856090-ee558b71-2596-4e93-9ef8-206009d0ce27.png)
You'd better directly remove the operationid parameter. This version directly reports an error

**Comment by inernoro** [comment]
> Use method name instead of rondom value

![](https://user-images.githubusercontent.com/9151851/166856090-ee558b71-2596-4e93-9ef8-206009d0ce27.png)

You'd better directly remove the operationid parameter. This version directly reports an error
