### ISSUE TITLE
support max-length and mock-value columns in parameters table

### ISSUE THREAD

**Issue by GTaurus** [TongchengOpenSource/smart-doc#236]
## Summary(关于这个pr的描述)

add max-length and mock-value columns in parameters table

### Basic example(pr的用例)
like this:
![1650291249(1)](https://user-images.githubusercontent.com/1628689/163820777-e7fdcc52-dd6e-4d81-99c5-d7f279a850f8.png)

### Motivation(提出这个pr目的)

These two pieces of information are very important.

**Comment by chenqi146** [comment]
in html or markdown?

**Comment by GTaurus** [comment]
> in html or markdown?

Both are required, including openapi.

**Comment by shalousun** [comment]
Some information about jsr 303 verification will not be displayed in a new table field, and it will be directly merged into the Description after it is supported later.

**Comment by shalousun** [comment]
suported from v2.5.0
