### ISSUE TITLE
I hope to add a secondary classification.

### ISSUE THREAD

**Issue by SugarFatFree** [TongchengOpenSource/smart-doc#238]
I hope to add a secondary category within the "Controller" section on the left side of the document.

### Basic example (use case for PR)

When I use the same @tag across multiple Controllers,
![00936296-0F84-4F40-A682-B8B914D907EA](https://user-images.githubusercontent.com/30424828/164143067-5be76a0d-bb7d-4039-b905-8cdda5e5f506.png)

The effect shown above seems inappropriate to me, and I hope to see an addition of a secondary category expansion menu.

**Comment by SugarFatFree** [comment]
If using 'groups' for categorization, it places other Controllers without configurations into a 'default' secondary menu. Is it possible to keep the default ones in the primary menu and move those with configured groupings into the secondary menu?

**Comment by shalousun** [comment]
@hu1240050829, currently no one on our team is available to maintain this page template. Considering the modifications made earlier, everyone's efforts in maintaining the template have been quite poor, often resulting in significant bugs. Therefore, we have no plans to support this ourselves. Of course, you are welcome to make modifications yourself, and if your tests prove successful, feel free to submit a PR and we can consider merging it.
