### ISSUE TITLE
Is it possible to add a configuration option to ignore certain controllers?

### ISSUE THREAD

**Issue by jimolonely** [TongchengOpenSource/smart-doc#24]
Hello, I really like this plugin. In the process of my practice, I need to ignore certain controllers. I hope it will be supported in the future! Thank you.
hello，我非常喜欢这款插件，在我实践的过程中需要忽略某些controller，希望后续可以支持！感谢

**Comment by shalousun** [comment]
Will be supported in 1.8.4

**Comment by jimolonely** [comment]
great!
