### ISSUE TITLE
There seems to be an issue with the Request-body display.

### ISSUE THREAD

**Issue by QinHongZhe** [TongchengOpenSource/smart-doc#242]
## Your Environment (Your Using Environment)

* smart-doc version: 2.4.3
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin):
* build tool version(maven or gradle):

## Expected Behavior (Expected Result)

Request-body should either display both parameters or none at all.

## Current Behavior (Current Result)

Only one is displayed:

![image](https://user-images.githubusercontent.com/25653313/164447978-d0bf46a5-72b0-44fb-985c-03291e7a180e.png)
![image](https://user-images.githubusercontent.com/25653313/164448022-eb387b16-c5b1-4b62-a01a-cc1f98b37803.png)

## Steps to Reproduce (Steps to Produce the Bug)

1.
2.
3.
4.

**Comment by chenqi146** [comment]
https://github.com/smart-doc-group/smart-doc/commit/2dbf0f62e5bbbede98181c2f06efa1e88bbb1028
