### ISSUE TITLE
Control layer group validation: @Validated(Save.class), the model cannot be correctly adapted.

### ISSUE THREAD

**Issue by zhouping-git** [TongchengOpenSource/smart-doc#243]
## Summary(关于这个pr的描述)

Entity classes cannot generate validation rules based on the control layer's grouping strategy.

### Basic example(pr的用例)

![image](https://user-images.githubusercontent.com/72516108/164683974-4af04d2f-9ed4-4749-86a5-9962c89f8280.png)
![image](https://user-images.githubusercontent.com/72516108/164684097-0c0b9368-45a9-44ac-b88b-cab4620db0fe.png)
![image](https://user-images.githubusercontent.com/72516108/164684171-425194b9-856a-46ec-866c-75313de65d4b.png)

### Motivation(提出这个pr目的)
Is there a plan to adapt to this requirement?

**Comment by chenqi146** [comment]
这是是我测试的结果, 目前是没有问题的, 你的smart-doc版本是多少
![image](https://user-images.githubusercontent.com/36069431/164853778-b715080f-d163-4340-b4db-bd0395f5cba7.png)
![image](https://user-images.githubusercontent.com/36069431/164853856-193adde3-782a-4168-bd99-d026a1162525.png)
![image](https://user-images.githubusercontent.com/36069431/164854097-0894af26-544e-4e78-a6b0-39363074acd5.png)

**Comment by zhouping-git** [comment]
@chenqi146
After testing, it was found that the generated HTML does implement grouped validation, but this is not achieved using the OpenAPI approach.
Version used:
![image](https://user-images.githubusercontent.com/72516108/164954296-1de2cd92-3b1f-41ff-b517-5bf4e74f2739.png)
In the generated OpenAPI file:
![image](https://user-images.githubusercontent.com/72516108/164954347-a0eb3d6f-6769-40ad-a2dc-f853735dfc1a.png)
![image](https://user-images.githubusercontent.com/72516108/164954362-4ae2693b-c9e0-4192-bc89-0641c16b5a68.png)
![image](https://user-images.githubusercontent.com/72516108/164954370-2afe453b-5f00-4edf-bbca-0d72e4c74b11.png)
The same schema is used for both create and update operations.

Comparison of HTML and OpenAPI:
![image](https://user-images.githubusercontent.com/72516108/164954440-9a804c0f-3b01-40b4-a503-c2890acae728.png)
![image](https://user-images.githubusercontent.com/72516108/164954477-906593b7-1ab5-4e66-bc43-3ea9d7f79e94.png)
![image](https://user-images.githubusercontent.com/72516108/164954494-4100c8f1-0bd9-4012-ac0b-40472481d1b8.png)
![image](https://user-images.githubusercontent.com/72516108/164954506-8dbd022e-a7af-4980-9f50-f4e10133536d.png)

**Comment by zhouping-git** [comment]
Upon testing, it was discovered that the generated HTML implements grouped validation, but this is not achieved using the OpenAPI approach.
Version used:
The generated OpenAPI file:
Among them, the same schema is used for both adding and updating.
Comparison between HTML and OpenAPI:

***@***.***
 
发件人： Joker
发送时间： 2022-04-23 09:23
收件人： smart-doc-group/smart-doc
抄送： zhoupit; Author
主题： Re: [smart-doc-group/smart-doc] ***@***.***(Save.class)，model中无法正确适配 (Issue #243)
This is the result of my test, there are currently no issues. What version of smart-doc are you using?

**Comment by kezhiyang** [comment]
2.6.8 still has the same issue
