### ISSUE TITLE
The generated documentation output contains multiple br tags.

### ISSUE THREAD

**Issue by QinHongZhe** [TongchengOpenSource/smart-doc#248]
## Your Environment (Your Using Environment)

* smart-doc version: 2.4.2
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin): 2.4.2
* build tool version(maven or gradle): mavan

## Expected Behavior (Expected Result)

Correct line breaks

## Current Behavior (Current Result)

![image](https://user-images.githubusercontent.com/25653313/164957357-36a915da-6cca-42c3-93b5-930eee3a6b77.png)

## Steps to Reproduce (Steps to Produce the Bug)

1.
2.
3.
4.

**Comment by chenqi146** [comment]
能否提供一下示例代码吗?
Can you provide sample code?

**Comment by QinHongZhe** [comment]
Hello, there are two pieces of code, one in the entity class and one in smart-doc.json, as shown in the figure below:
![image](https://user-images.githubusercontent.com/25653313/165087549-b9e09179-342b-447b-aea9-72386330d987.png)
![image](https://user-images.githubusercontent.com/25653313/165087569-3333a637-79d1-47ad-8a4a-19c293a26a47.png)

In the configuration file, since line breaks are not allowed, I manually added br tags. However, here it works fine in version 2.3.9.
