### ISSUE TITLE
In smart-doc.json, @RequestHeader is ignored, but the generated document still exists.

### ISSUE THREAD

**Issue by youngledo** [TongchengOpenSource/smart-doc#250]
## Your Environment (Your Using Environment)
* smart-doc version: 2.4.3
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin): smart-doc-maven-plugin
* build tool version(maven or gradle): maven

## Expected Behavior (Expected Result)
I used @RequestHeader on the method parameter and I don't want this request header to appear in the document because I have a global configuration.
```java
@GetMapping("start")
    public void start(@RequestHeader("X-Code") String xCode) {
        //
    }
```

## Current Behavior (Current Result)
The request header is displayed in the document.

## Possible Solution (Bug Fixing Suggestion)
Although now it can be ignored using @ignore, adding them one by one is too much. It is suggested to add a unified ignore configuration in smart-doc.json.

## Steps to Reproduce (Steps to Produce the Bug)
```java
@GetMapping("start")
    public void start(@RequestHeader("X-Code") String xCode) {
        //
    }
```

**Comment by shalousun** [comment]
In the later version 2.4.4, you can use excludePathPatterns to filter out, the configuration reference is as follows:
```
"requestHeaders": [ //Set the request header, you can not set it if there is no requirement
     { //Set the request header, no need to set it
       "name": "X-Code",//Request header name
       "type": "string",//Request header type
       "desc": "desc",//Request header description information
       "value":"X-Code request header value",//Do not set default null
       "required": false,//Whether it is required
       "since": "-",//What version added the change request header
       "excludePathPatterns":"/**"
     }
   ]
```
