### ISSUE TITLE
I hope to generate the document according to the field order.

### ISSUE THREAD

**Issue by maojx0630** [TongchengOpenSource/smart-doc#252]
## Your Environment(您的使用环境)

* smart-doc version:
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin): 2.4.3
* build tool version(maven or gradle):3.6.3

## Expected Behavior(您期望的结果)
<img width="266" alt="image" src="https://user-images.githubusercontent.com/37826107/165697608-ba6bd959-bba9-4ec9-80a6-f4485fa3d18b.png">

## Current Behavior(当前结果)
<img width="527" alt="image" src="https://user-images.githubusercontent.com/37826107/165697557-b2663fb7-c871-4681-b7d7-6152bc75cee3.png">

## Possible Solution(bug解决建议)
I hope to generate the document in the order of fields.

**Comment by chenqi146** [comment]
Can you provide the inheritance and interface structure of this response class?
能否提供此响应类的继承和接口结构吗

**Comment by maojx0630** [comment]
Now I understand, it should be generated in the order of the parent class first.
Is there a way to adjust it to prioritize the subclass?

**Comment by maojx0630** [comment]
<img width="624" alt="image" src="https://user-images.githubusercontent.com/37826107/165875541-fd7cb209-f949-4b72-a997-abffc7c2f4bd.png">
<img width="399" alt="image" src="https://user-images.githubusercontent.com/37826107/165875594-0b136ac8-faf6-40e8-9b75-d55341b899c5.png">

**Comment by chenqi146** [comment]
>I understand now, it should be generated in the order of the parent class first. Is there a way to adjust it to give priority to the subclass?

Fixed https://github.com/smart-doc-group/smart-doc/commit/37d13747114b7d2d3ce2e68498ec638b56cf0904
