### ISSUE TITLE
Enumerated error codes can be generated in the order they are defined.

### ISSUE THREAD

**Issue by maojx0630** [TongchengOpenSource/smart-doc#257]
## Your Environment(您的使用环境)
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin): 2.4.4
* build tool version(maven or gradle): 3.6.3

## Expected Behavior(您期望的结果)
Enumerated error codes can be generated in the order they are defined.
<img width="604" alt="image" src="https://user-images.githubusercontent.com/37826107/166610186-3d8fbde6-dfef-414c-9c4d-67caa386f570.png">

## Current Behavior(当前结果)
<img width="509" alt="image" src="https://user-images.githubusercontent.com/37826107/166610209-87e32cf9-b29a-484a-a192-00175eac36dd.png">

**Comment by chenqi146** [comment]
I have tested it on my side, and the documentation and push notifications generated by smart-doc are in the order of the fields. This issue should be something that torna needs to address.
