### ISSUE TITLE
In the generated OpenAPI document, some names are correct while others are concatenated randomly.

### ISSUE THREAD

**Issue by inernoro** [TongchengOpenSource/smart-doc#259]
## Summary
![image](https://user-images.githubusercontent.com/9151851/166859397-36eb22ef-670e-4af6-8c28-8cdc45dba82d.png)
In the generated OpenAPI document, some names are correct while others are concatenated randomly.
### Motivation
The purpose of this PR is to fix the naming issues in the generated OpenAPI document.

**Comment by shalousun** [comment]
@inernoro Please provide the original Java method name for comparison and testing.

**Comment by inernoro** [comment]
> @inernoro Please provide the original Java method name for comparison and testing.

![image](https://user-images.githubusercontent.com/9151851/166875783-55022a77-48b6-4171-985f-51a8dd2eb657.png)

**Comment by inernoro** [comment]
config
```
{
  "requestExample": false,
  "responseExample": false,
  "outPath": "genesis",
  "serverUrl": "http://10.0.4.4:7878",
  "isStrict": false,
  "projectName": "sirius",
  "appToken": "2a35889b6a8f438bb45f9e0e8218e0ee",
  "openUrl": "http://10.0.4.4:7700/api",
  "debugEnvName": "测试环境",
  "replace": true,
  "debugEnvUrl": "http://10.0.4.4:7878",

  "responseBodyAdvice": {
    "className": "com.miduonet.sirius.classlibrary.basiccomponents.ResultData"
  }
}

```

**Comment by netdied** [comment]
Use the new version (2.4.8) to test the OpenAPI functionality.
