### ISSUE TITLE
Can you write the configuration of json file using Java?

### ISSUE THREAD

**Issue by CrazyLionCat** [TongchengOpenSource/smart-doc#260]
## Summary(关于这个pr的描述)

Brief explanation of the feature.

### Basic example(pr的用例)

If the proposal involves a new or changed API, include a basic code example. Omit this section if it's not applicable.

### Motivation(提出这个pr目的)

Why are we doing this? What use cases does it support? What is the expected outcome?

**Comment by shalousun** [comment]
@JavaLionLi If you are using plugins, it's clear that this is not supported. I have never seen a plugin configuration written in Java, especially for Maven plugins. If you prefer not to use plugins and instead want to start smart-doc to generate documentation by using a main method or unit tests, you can write the configuration in Java, but there are many drawbacks. It is recommended that you review the official documentation yourself.
