### ISSUE TITLE
The enumerations used in the generated OpenAPI can cause the generator or dependent tools to fail to parse the fields, and the types of fields are randomly unparseable.

### ISSUE THREAD

**Issue by inernoro** [TongchengOpenSource/smart-doc#261]
## Your Environment (Your Use Environment)
* smart-doc version: 2.4.4
* springboot-apidoc-parser version: 2.6.3
* Java version: 1.8

## Expected Behavior (Expected Outcome)
> In Swagger,
![image](https://user-images.githubusercontent.com/9151851/166888886-1313998b-9d35-43e7-a9ee-571d1350eb69.png)

## Current Behavior (Current Outcome)
> With Smart Tools,
![image](https://user-images.githubusercontent.com/9151851/166887633-2f1ace96-de73-4c8b-8ccb-6caa5203c3c3.png)

## Possible Solution (Bug Resolution Suggestion)
> Use ref and add missing types to other fields.

## Context (Bug Impact Description)
Normal objects can be viewed,
![image](https://user-images.githubusercontent.com/9151851/166887756-0686d27a-fc4d-4f7f-b71b-94a1b5b1273d.png)
List objects,
![image](https://user-images.githubusercontent.com/9151851/166887810-76a03faf-dd9f-4e86-832a-f0c6589d387a.png)

Objects generated through Smart,
> C# are all Object,
![image](https://user-images.githubusercontent.com/915188395-267ce8c9-800d-45a1-a7d9-db3e84cfc15c.png)
> Axios are all Object,
![image](https://user-images.githubusercontent.com/915188559-114b3992-379c-404f-b9f7-95c3a5f95e1a.png)

Moreover, some types are randomly missing in the fields,
![image](https://user-images.githubusercontent.com/9151851/166889211-e5f6000a-4b34-40a3-99cc-023cfc0bfd41.png)
This does not occur with Swagger,
![image](https://user-images.githubusercontent.com/9151851/166889317-c1716bdb-9fd5-421b-8199-9dd6224bf38d.png)

**Comment by shalousun** [comment]
@inernoro Besides the field types, the issue with 'refer' is the same as #254. Smart-doc was not originally designed for OpenAPI compatibility; it was later added to merely meet the requirements for UI document rendering. Fully supporting this would require significant changes, and the team maintaining it doesn't have time in the short term to make these compatibility adjustments and conduct testing. Of course, if you are able to make these changes yourself and there is an urgent need for them, we welcome your pull request.

**Comment by netdied** [comment]
You can try the new version again.
