### ISSUE TITLE
If the instance pipe symbol "|" is added to the interface parameter but no instance is specified (such as the parameter procDate | in the example), an error will occur during build.

### ISSUE THREAD

**Issue by kangtsang** [TongchengOpenSource/smart-doc#262]
## Summary
Adding a pipe symbol to the interface parameter without filling in an instance (such as the parameter procDate | in the example) will cause a build error.

### Basic Example
    /**
     * Manually execute batch tasks
     * @apiNote Manually execute batch tasks
     * @author wangmeiyuan
     * @date 2022/5/12 18:06
     * @param batchId Execution batch id | 10
     * @param action Batch type: D-Based on job detail id, E-Based on execution info id | D
     * @param procDate |
     * @param oid Institution id, note: Mandatory for manual submission, optional for rerun | 2001
     * @param inputParam The input parameters for this execution, passing will replace the default parameters, not passing will use the detail default parameters | {"date":"20220301"}
     */

### Motivation
To handle this scenario and enhance the robustness of the plugin.

Plugin version: 2.4.5
				<groupId>com.github.shalousun</groupId>
				<artifactId>smart-doc-maven-plugin</artifactId>
				<version>2.4.5</version>

Error location: com.power.doc.template.SpringBootDocBuildTemplate#getRewriteClassName, line 1018

Error stack:
[ERROR] 
java.lang.ArrayIndexOutOfBoundsException: -1
    at com.power.doc.template.SpringBootDocBuildTemplate.getRewriteClassName (SpringBootDocBuildTemplate.java:1018)
    at com.power.doc.template.SpringBootDocBuildTemplate.requestParams (SpringBootDocBuildTemplate.java:749)
    at com.power.doc.template.SpringBootDocBuildTemplate.buildControllerMethod (SpringBootDocBuildTemplate.java:300)
    at com.power.doc.template.SpringBootDocBuildTemplate.getApiData (SpringBootDocBuildTemplate.java:91)
    at com.power.doc.builder.HtmlApiDocBuilder.buildApiDoc (HtmlApiDocBuilder.java:89)
    at com.smartdoc.mojo.HtmlMojo.executeMojo (HtmlMojo.java:48)

Image Information:
![Snipaste_2022-05-13_15-37-21](https://user-images.githubusercontent.com/72589730/168235295-1940d9cd-f3db-4aaf-bcb5-a352c436a1a8.png)

**Comment by shalousun** [comment]
@kangtsang Smart-doc will directly issue an error prompt upon detecting such invalid comments. We enforce strict compliance with the standards and alert users to the problematic comments at that location.
