### ISSUE TITLE
Can the data dictionary be extended to automatically scan for corresponding implementation classes based on an enumeration base class interface?

### ISSUE THREAD

**Issue by wangj-un** [TongchengOpenSource/smart-doc#264]
## Summary
For instance, there is a base interface for data dictionaries: Messageable, with three interface methods: title(), code(), and message(). To generate documentation for an enumeration, it only needs to implement this interface, and the corresponding documentation will be automatically generated. This can be achieved by adding a configuration like the following:
"dataDictionaries": {
  "packageFilters": "com.example.*",    Specifies the package path to scan
  "baseInterfaceName": "com.example.base.Messageable",
  "titleMethodName": "title",
  "codeMethodName": "code",
  "messageMethodName": "message",
}
Then, the corresponding document data can be generated through reflection.

### Basic Example

If the proposal involves a new or changed API, include a basic code example. Omit this section if it's not applicable.

### Motivation

Because there are many enumeration classes in actual projects, and most of them implement a unified interface, and the structure of the enumeration is relatively fixed, configuring each one individually would be cumbersome. Therefore, it is hoped that enumeration data can be automatically scanned.

**Comment by chenqi146** [comment]
Does each enumeration type in your title have a different title?

**Comment by chenqi146** [comment]
Can you provide an example of enum implementation code?

**Comment by wangj-un** [comment]
Sorry, the "title" and the current "dataDictionaries.title" are the same concept; they do not represent each enumeration value within. The title can be directly obtained from the comments of the enum class, and there is no need to declare it in the configuration JSON.
The Messageable interface is defined as follows:
![image](https://user-images.githubusercontent.com/50893903/169184514-75c9123a-7437-429e-9bf5-95bacf26e832.png)
The enum implementation class is as follows:
![image](https://user-images.githubusercontent.com/50893903/169184972-125a0517-a3a9-47a3-b5c1-66f3bee0343c.png)
Configure smart-doc.json as follows (considering that the base enumeration interface may vary due to third-party packages, it is hoped to implement multiple configuration schemes):
![image](https://user-images.githubusercontent.com/50893903/169185904-fa95ad75-0d1b-41e1-be82-5ac5e30b3000.png)
Enumeration processing example:
![image](https://user-images.githubusercontent.com/50893903/169187583-0df9e839-11e3-4953-914f-661542b27a2c.png)
![image](https://user-images.githubusercontent.com/50893903/169187086-de5fea05-1ed1-4447-8e75-a41a8aa33091.png).

The above expresses my requirements.

**Comment by chenqi146** [comment]
ok, thx.
