### ISSUE TITLE
Is the document page not opening? Is this project dead now?

### ISSUE THREAD

**Issue by leesonwei** [TongchengOpenSource/smart-doc#265]
## Your Environment (Your Use Environment)
- Include as many relevant details about the environment you experienced the bug in.
* smart-doc version:
* plugin version (e.g., smart-doc-maven-plugin or smart-doc-gradle-plugin):
* build tool version (maven or gradle):
Google Chrome browser

## Expected Behavior (Expected Outcome)
- If you're describing a bug, tell us what should happen
- If you're suggesting a change/improvement, tell us how it should work
Display official documentation
## Current Behavior (Current Outcome)
- If describing a bug, tell us what happens instead of the expected behavior
- If suggesting a change/improvement, explain the difference from current behavior
Page displays blank
![image](https://user-images.githubusercontent.com/29350722/169200581-19e0bda5-944b-4e0f-b2ea-87d8a4b6099f.png)

## Possible Solution (Suggested Fix for the Bug)
- Not obligatory, but suggest a fix/reason for the bug,
- or ideas how to implement the addition or change

## Steps to Reproduce (Steps to Reproduce the Bug, please try to provide code examples if possible)
- Provide a link to a live example, or an unambiguous set of steps to
- reproduce this bug. Include code to reproduce, if relevant
1.
2.
3.
4.

## Context (Impact of the Bug)
- How has this issue affected you? What are you trying to accomplish?
- Providing context helps us come up with a solution that is most useful in the real world

**Comment by chenqi146** [comment]
I can access it from my end; please check your network connection.
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/36069431/169201862-fde93a79-c121-458e-ba1e-8c588db915fa.png">

**Comment by shalousun** [comment]
@leesonwei If you are unable to access certain external resources internally, please resolve this on your own. The official documentation for smart-doc is hosted on github.io. There's no issue of it being unavailable unless GitHub stops allowing access from China, only then would the official documentation be inaccessible.
