### ISSUE TITLE
Will future versions support the parsing of validation rules for interface request parameters?

### ISSUE THREAD

**Issue by dearsource** [TongchengOpenSource/smart-doc#267]
## Summary
Parsing validation rules for Spring-style interface parameters.
Brief explanation of the feature.

### Basic Example
Example usage:
```java
@Pattern(regexp = "^[\\u4e00-\\u9fa5\\w\\d][\\u4e00-\\u9fa5\\w\\d_]{0,62}[\\u4e00-\\u9fa5\\w\\d]$",
        message = "The name of the customized background image is invalid.")
@Range(min = 0, max = 1, message = "resolution must be in [0,1]")
private int resolution;
```
If the proposal involves a new or changed API, include a basic code example. Omit this section if it's not applicable.

### Motivation
After generating the interface documentation, there is no need to manually add or modify the validation rules for each parameter. If the rules for input parameters are updated, the documentation can be regenerated without manual intervention for the validation rules. In the interface documentation, it is clearly visible which validation rules apply to different interface input parameters.

**Comment by shalousun** [comment]
@dearsource In the future, we could consider extracting the JSR rules and appending them to the comments.
