### ISSUE TITLE
The Spring Boot application written in Kotlin is unable to use translation.

### ISSUE THREAD

**Issue by mdddj** [TongchengOpenSource/smart-doc#270]
After packaging, there is a prompt indicating that the static resource file app.css has no mapping, springboot No mapping for GET /app.css
Then it needs to be handled like this
<img width="358" alt="image" src="https://user-images.githubusercontent.com/29020213/169965377-e5079014-9401-4b59-9ca3-c462cb35a12c.png">
This is my res file
<img width="263" alt="image" src="https://user-images.githubusercontent.com/29020213/169965450-16ff04bf-0295-4ff1-a077-985b3f2674e0.png">
Configuration
<img width="432" alt="image" src="https://user-images.githubusercontent.com/29020213/169965508-5322296b-19f4-4fc7-911b-8bb3cf6b9bc7.png">

Generated document
<img width="1455" alt="image" src="https://user-images.githubusercontent.com/29020213/169965551-523ed23e-9531-42ca-bb1d-a43eef9a7954.png">

**Comment by shalousun** [comment]
Only supports java, cannot support kotlin, and will not support it in the future

**Comment by mdddj** [comment]
OK
