### ISSUE TITLE
Unable to access https://fonts.googleapis.cnpmjs.org/css, resulting in slow page loading.

### ISSUE THREAD

**Issue by tianmingxing** [TongchengOpenSource/smart-doc#271]
## Your Environment (Your Use Environment)

* smart-doc version: 2.2.3
* plugin version (smart-doc-maven-plugin): 2.2.3
* build tool version (maven): 3.8.1

## Expected Behavior (Expected Outcome)

When opening the locally generated HTML file, the page should load within a "normal" amount of time.

## Current Behavior (Current Outcome)

Upon opening the generated HTML page, there is a long blank period, and upon inspection with F12, it is found that access to https://fonts.googleapis.cnpmjs.org/css is blocked, causing the issue.

## Possible Solution (Suggested Fix for the Bug)

Is it possible to customize this address? Or could it be replaced with an address that can be normally accessed within China?

## Context (Impact of the Bug)

Opening the document leads to a wait of several tens of seconds, and after a blank screen, the document finally appears, which significantly affects the viewing experience.

**Comment by shalousun** [comment]
@tianmingxing When submitting an issue for open source, please follow the official issue template and provide necessary information such as version details. Do not submit issues randomly, as there are differences between direct iterations of different versions of these open-source software. Providing uncertain information causes unnecessary problem tracking costs for open-source maintainers.

**Comment by shalousun** [comment]
@tianmingxing It is also best to upgrade and confirm whether the new version has similar issues for some problems. For open-source projects that do not affect business operations, the official team will not provide stability patches specifically for the current version you are using; they continuously move forward with iterations, and there is no maintenance of stable series versions for older versions.

**Comment by tianmingxing** [comment]
>@tianmingxing It is also best to upgrade and confirm whether the new version has similar issues for some problems. For open-source projects that do not affect business operations, the official team will not provide stability patches specifically for the current version you are using; they continuously move forward with iterations, and there is no maintenance of stable series versions for older versions.

The problem description has been modified.

**Comment by tianmingxing** [comment]
> 
> @tianmingxing I am currently using the latest version: [smart-doc-maven-plugin-v2.2.3](https://github.com/smart-doc-group/smart-doc-maven-plugin/releases/tag/2.2.3) [Latest](https://github.com/smart-doc-group/smart-doc-maven-plugin/releases/latest)
But I see that the smart-doc version has reached [2.2.7](https://github.com/smart-doc-group/smart-doc/releases/tag/2.2.7), does smart-doc-maven-plugin need to be upgraded synchronously?

**Comment by tianmingxing** [comment]
Upon reviewing the branch, I noticed that the latest version is 2.4.4 and this issue no longer exists.
