### ISSUE TITLE
Unable to generate JAX-RS documentation.

### ISSUE THREAD

**Issue by youngledo** [TongchengOpenSource/smart-doc#272]
## Your Environment
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin): 2.4.4
* build tool version(maven or gradle): maven-3.8.1

## Expected Behavior(您期望的结果)

Using the Jersey framework (JAX-RS), my project runs normally. The plugin generates all interface documentation, but only the documentation is generated without the interface content. The configuration is as follows:
```json
{
  "serverUrl": "http://127.0.0.1:5731",
  "outPath": "./src/main/resources/static/doc",
  "allInOne": true,
  "coverOld": true,
  "isStrict": false,
  "style": "xt256",
  "createDebugPage": true,
  "allInOneDocFileName": "index.html",
  "appToken": "26477a39eafb4d699d1944761349c1d2",
  "openUrl": "http://10.20.33.220:7700/api",
  "debugEnvName": "Open API",
  "debugEnvUrl": "http://10.20.33.220:5731",
  "replace": true,
  "inlineEnum": true,
  "framework": "JAX-RS",
  "packageFilters": "com.mingyuanyun.tqncdwjspt.core.web.jersey.resource.*",
  "requestHeaders": [
    {
      "name": "Authorization",
      "type": "string",
      "desc": "授权令牌",
      "value": "Basic YWRtaW46YWRtaW4=",
      "required": true,
      "since": "-",
      "excludePathPatterns": "/user/login,/doc/index.html,/favicon.ico,/static/**"
    },
    {
      "name": "X-dbCode",
      "type": "string",
      "desc": "数据库code",
      "value": null,
      "required": true,
      "since": "-",
      "excludePathPatterns": "/doc/index.html,/favicon.ico,/static/**"
    }
  ]
}
```

## Current Behavior(当前结果)

<img width="578" alt="企业微信截图_04dfd05e-60a3-4727-9fb2-284501987be2" src="https://user-images.githubusercontent.com/68590897/170626349-80dcdba1-8d2c-4ec9-9569-b9c16a698c54.png">

## Steps to Reproduce (Bug产生步骤，请尽量提供用例代码)

1. Directly execute the IDEA plugin run, and there are no errors in the console.

## Context(Bug影响描述)

**Comment by shalousun** [comment]
@youngledo Modify and debug it yourself to submit a PR. Currently, there is no one maintaining the JAX-RS functionality, and there's no energy to write a Jersey demo for validation. Maintenance of Spring and other basic issues is also problematic. We hope you can understand that there are too few people participating in open source in China, and many personal open source maintenances are indeed problematic. The main functions of JAX-RS are already in place, and making modifications should not be too difficult.

**Comment by youngledo** [comment]
Okay.

**Comment by youngledo** [comment]
#274
