### ISSUE TITLE
feat: Support for wrapper classes

### ISSUE THREAD

**Issue by lkqm** [TongchengOpenSource/smart-doc#275]
## Support for Configured Wrapper Classes
The interface return class `ApiResult` is not explicitly declared in the controller layer method return values, but is globally configured in the scaffolding:

Controller layer method declaration:
```
@GetMapping(/your/path)
public User getUser(){
}
```

Equivalent to the following declaration:
```
@GetMapping(/your/path)
public ApiResult<User> getUser(){
}
```

We hope to add a configuration option that can be used to set the wrapper type: `returnWrapType=com.company.project.ApiResult`

**Comment by shalousun** [comment]
@lkqm https://smart-doc-group.github.io/#/zh-cn/diy/config?id=responsebodyadvice

**Comment by lkqm** [comment]
thanks
