### ISSUE TITLE
How can I control the output to not include tornado logs?

### ISSUE THREAD

**Issue by youngledo** [TongchengOpenSource/smart-doc#277]
## Summary(关于这个pr的描述)

There are too many logs pushed to Tornado, which are unnecessary to output (they can be turned off by default).
<img width="843" alt="image" src="https://user-images.githubusercontent.com/68590897/170904079-07d3d090-3741-414b-aba6-4804f2982092.png">

### Motivation(提出这个pr目的)

Reduce unnecessary logs.

**Comment by netdied** [comment]
Add configuration.
tornaDebug : false;
