### ISSUE TITLE
We hope to provide independent configurations for Postman, so there's no need to switch configurations back and forth to export documents in different formats.

### ISSUE THREAD

**Issue by unexpectedxx** [TongchengOpenSource/smart-doc#280]
## Summary(关于这个pr的描述)

Brief explanation of the feature.

### Basic example(pr的用例)

If the proposal involves a new or changed API, include a basic code example. Omit this section if it's not applicable.

### Motivation(提出这个pr目的)

Why are we doing this? What use cases does it support? What is the expected outcome?

**Comment by shalousun** [comment]
@mj19910923 Add serverEnv configuration to support users to set global server address variables in postman export
