### ISSUE TITLE
Generating HTML causes an error.

### ISSUE THREAD

**Issue by QinHongZhe** [TongchengOpenSource/smart-doc#281]
## Your Environment(Your Use Environment)

* smart-doc version: 2.4.6
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin): smart-doc-maven-plugin
* build tool version(maven or gradle): maven

## Expected Behavior(Expected Results)

Can correctly execute and generate HTML.

## Current Behavior(Current Results)

![image](https://user-images.githubusercontent.com/25653313/172158112-69fb965e-0274-4e9b-9c97-342e47e3bbe9.png)

## Possible Solution(Bug Resolution Suggestions)

Testing shows that version 2.4.5 works, but version 2.4.6 reports an error.

## Steps to Reproduce (Steps to Produce the Bug, Please Provide Code Examples if Possible)

1. Under the jdk11 environment
2. Using idea 2022.1.2
3. Maven 3.6.9
4.

## Context(Impact of the Bug)

**Comment by QinHongZhe** [comment]
This error might also be caused by my project. I have used reflection to modify permission characters, and I am uncertain if this is the reason. I hope to investigate this further.

**Comment by QinHongZhe** [comment]
However, there is currently no output in the console regarding specific errors in the project files.

**Comment by QinHongZhe** [comment]
This issue has been resolved. It was due to reflection issues in JDK 9 and above. When editing with Maven, it is necessary to add the following parameters:
--add-opens java.base/java.lang.module=ALL-UNNAMED --add-opens java.base/jdk.internal.module=ALL-UNNAMED
The error in my project involved two modules: java.lang.module and jdk.internal.module. Adding these two explicitly depends on the specifics of the project.
Reference: http://events.jianshu.io/p/2e51e6e7a3ba

Could this issue be addressed within the smart-doc plugin?

**Comment by shalousun** [comment]
@QinHongZhe This cannot be handled in smart-doc, and there are many users of JDK 8. Currently, all releases and compilations are based on JDK 1.8.
