### ISSUE TITLE
Can it support the @JsonUnwrapped annotation in Jackson?

### ISSUE THREAD

**Issue by LeeMeo** [TongchengOpenSource/smart-doc#285]
## Summary(关于这个pr的描述)

In our regular projects, the Jackson library is mostly used for JSON, including the use of the @JsonUnwrapped annotation to output flattened JSON. Could support for this annotation be added in the new version?

### Motivation(提出这个pr目的)

Why are we doing this? What use cases does it support? What is the expected outcome?

**Comment by shalousun** [comment]
@LeeMeo This probably won't be supported as it would cause significant disruptive changes to the entire smart-doc codebase. However, it is not an essential feature for users.
