### ISSUE TITLE
Generate interface documentation IndexOutOfBoundsException

### ISSUE THREAD

**Issue by ACodingJie** [TongchengOpenSource/smart-doc#287]
## Your Environment(您的使用环境)

* smart-doc version: 
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin): 2.3.6
* build tool version(maven or gradle):maven

## Expected Behavior(您期望的结果)
å

## Steps to Reproduce (Bug产生步骤，请尽量提供用例代码)
1. Add the plugin to the pom.
2. Use Maven plugin to generate doc and save it; no documents are found in the file directory.

![image](https://user-images.githubusercontent.com/44465791/172835627-47c5a448-e385-401d-adb9-1ed256c39184.png)

**Comment by shalousun** [comment]
@ACodingJie Please upgrade to the latest version yourself and report any issues after testing. The official team will not track or address any issues with historical versions.
