### ISSUE TITLE
Java 17 does not support the record type.

### ISSUE THREAD

**Issue by yhan219** [TongchengOpenSource/smart-doc#288]
## Your Environment

smart-doc-gradle-plugin:
`id "com.github.shalousun.smart-doc" version "2.4.6"`

## Expected Behavior

Defined a return result record:
```
public record AppUserDetail(
        AppUser user,
        UserWallet wallet
) {
}
```
Pushed to torna and did not generate response parameters. There are no user details or wallet details. It worked normally after changing it to a class.

**Comment by shalousun** [comment]
@yhan219 This should be an issue with the parsing underlying qdox used by smart-doc, which is not supported and difficult to fix. It will be addressed later when there is time.

**Comment by yhan219** [comment]
https://github.com/paul-hammant/qdox/issues/67
It seems to be supported. I'll fork it down and take a look when I have some time.

**Comment by shalousun** [comment]
> [paul-hammant/qdox#67](https://github.com/paul-hammant/qdox/issues/67) It seems to be supported. I'll fork it and take a look when I have some time.

It's not supported; it just doesn't throw an error.
