### ISSUE TITLE
When there is a MultipartFile attribute in the form object, generating the document results in an infinite loop.

### ISSUE THREAD

**Issue by liangcmwn** [TongchengOpenSource/smart-doc#29]
FormDataBuildHelper.getFormData encounters an infinite loop when there is a MultipartFile attribute in the fields of the form object.
FormDataBuildHelper.getFormData 遇到表单对象fields中有MultipartFile属性时死循环。

**Comment by netdied** [comment]
![image](https://user-images.githubusercontent.com/20217389/81474210-69d9eb80-9236-11ea-9784-2ef8c8a0ff12.png)
![image](https://user-images.githubusercontent.com/20217389/81474202-647ca100-9236-11ea-90cc-378954595a57.png)
Like this? Could you provide a specific example?
像这样？可不可以给具体的例子？？

**Comment by liangcmwn** [comment]
Yes, you can check the ApiDocTest in https://github.com/liangcmwn/smart-doc-demo; it goes into an infinite loop directly.
是的，可查看 https://github.com/liangcmwn/smart-doc-demo 里的ApiDocTest，直接死循环了
