### ISSUE TITLE
When the title of a request contains line breaks, clicking on the navigation on the left does not directly locate the corresponding request on the right.

### ISSUE THREAD

**Issue by kevin82008** [TongchengOpenSource/smart-doc#290]
## Your Environment
```xml
<plugin>
  <groupId>com.github.shalousun</groupId>
  <artifactId>smart-doc-maven-plugin</artifactId>
  <version>2.4.6</version>
</plugin>
```

## Expected Behavior
All features in the left navigation should directly click and locate to the detailed information on the right.

## Current Behavior
When there is a line break in the text of the left navigation, it cannot locate to the detailed information on the right.

## Possible Solution
When there is a line break, replace line breaks in the ID used by the navigation with spaces.

This solution aims to address the issue where the presence of line breaks in navigation labels causes misalignment between the clickable elements on the left and their corresponding sections on the right. By replacing line breaks with spaces in the IDs associated with these labels, the system can more reliably map clicks to the intended content, ensuring that users can effectively navigate through the documentation without encountering unexpected behavior due to formatting discrepancies.

**Comment by chenqi146** [comment]
Upgrade to 2.4.7 and try it.
