### ISSUE TITLE
In version 2.4.7, configuring enum dictionary scanning results in an error when running the HTML plugin.

### ISSUE THREAD

**Issue by wangj-un** [TongchengOpenSource/smart-doc#292]
Smart-Doc version: 2.4.7
JDK version: 11
Configuration as follows:
![image](https://user-images.githubusercontent.com/50893903/173722751-b52ed8f2-0389-40a9-8b62-61098457ddb3.png)

Interface definition:
![image](https://user-images.githubusercontent.com/50893903/173723738-eb8e3673-29df-4773-a26c-97154d5722b3.png)
Error encountered when running the HTML plugin:
![image](https://user-images.githubusercontent.com/50893903/173722879-4e1ea292-f975-47e8-97fc-9881b0cf39a9.png)

**Comment by chenqi146** [comment]
1. Could you please post your Maven plugin configuration?
2. Did your enumeration implement this interface?

**Comment by wangj-un** [comment]
Through debugging, it was discovered that the exception is thrown during the parsing of request and response parameters in Spring MVC interfaces. Errors occur when either the request or response parameters contain enumeration class parameters that implement the configured interface.
![image](https://user-images.githubusercontent.com/50893903/175016141-af63eeef-3bea-4464-96bd-2a05bcfd58f5.png)
![image](https://user-images.githubusercontent.com/50893903/175013669-11efda61-8730-43e9-aa74-9dd172c4ffab.png)
![image](https://user-images.githubusercontent.com/50893903/175021198-03e5467a-11f7-477f-bd5e-dd0615b07e5b.png)
![image](https://user-images.githubusercontent.com/50893903/175020687-9a8ded3e-fb98-444b-b992-89d01b589cba.png)
![image](https://user-images.githubusercontent.com/50893903/175020909-868dc476-f6a5-4031-bfce-6cc5e732696a.png)
![image](https://user-images.githubusercontent.com/50893903/175020967-5812c118-090b-4d97-8c42-9ab85d2f6b80.png)

**Comment by chenqi146** [comment]
I don't seem to have found any issues. Could you set a breakpoint to see which source codes are being loaded?

**Comment by wangj-un** [comment]
When submitting an issue, include screenshots of the exception stack trace information.
![image](https://user-images.githubusercontent.com/50893903/175877738-706ac7f4-b75e-4926-a480-3ab48e581869.png)

**Comment by wangj-un** [comment]
![image](https://user-images.githubusercontent.com/50893903/175879931-08f01ef3-8ce3-42df-873c-920be787d1e3.png)

**Comment by wangj-un** [comment]
projectBuilder.getApiConfig().getDataDictionary(#String）方法
![image](https://user-images.githubusercontent.com/50893903/175881531-a6efc03f-cc6e-47f5-87e3-1bae8a9f72e1.png)

**Comment by wangj-un** [comment]
对dictionaryListComment方法的小改动建议。
![image](https://user-images.githubusercontent.com/50893903/175889046-b9dca8a9-d893-4ab2-a023-3aad2d6a27c8.png)
List<EnumDictionary> enumDataDict;
        // 数据字典类型为配置接口类时, 从接口实现的枚举集合里面获取枚举信息
        if (!dictionary.getEnumClass().isEnum()){
            Class<? extends Enum> enumClass = dictionary.getEnumImplementSet().stream()
                    .filter(enumImpl -> enumImpl.getCanonicalName().equals(javaClass.getCanonicalName()))
                    .findFirst()
                    .orElseThrow(() -> new RuntimeException("Enum class can't be found."));
            enumDataDict = EnumUtil.getEnumInformation(enumClass, dictionary.getCodeField(),
                    dictionary.getDescField());
        }
        else {
            enumDataDict = dictionary.getEnumDataDict();
        }
        return enumDataDict.stream().map(apiDataDictionary ->
                apiDataDictionary.getName() + "-(\"" + apiDataDictionary.getValue() + "\",\"" + apiDataDictionary.getDesc() + "\")"
        ).collect(Collectors.joining(","));

**Comment by SERE026** [comment]
Enumerations are used with comments, but the @see annotation is not recognized.
