### ISSUE TITLE
The apiObjectReplacements configuration is invalid.

### ISSUE THREAD

**Issue by hqb72** [TongchengOpenSource/smart-doc#293]
## Your Environment(您的使用环境)

* smart-doc version: 2.2.7
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin): smart-doc-maven-plugin
* build tool version(maven or gradle): maven

## Current Behavior(当前结果)

1.
![image](https://user-images.githubusercontent.com/30142521/173809510-28108d44-8dc5-4913-9b58-10cdc0fb9764.png)
2.
![image](https://user-images.githubusercontent.com/30142521/173809584-28ab701d-d40d-4b07-b1bd-edfbd364819f.png)
3.
![image](https://user-images.githubusercontent.com/30142521/173809629-9234a333-b250-4de1-9c3c-7964f789bd59.png)
4.
![image](https://user-images.githubusercontent.com/30142521/173809706-4ce9f3db-7525-4152-9b6a-190f6eb108db.png)

**Comment by hqb72** [comment]
Is the method I used wrong?
是我使用的方法错了吗

**Comment by shalousun** [comment]
@hqb72 It only supports replacements at the controller layer and does not support field replacements, nor will it in the future. For ambiguous types, no tool will be useful.

**Comment by hqb72** [comment]
Okay, received.
好的收到
