### ISSUE TITLE
If the annotation contains an entity class with a full path, generating documentation will result in a bunch of meaningless line breaks.

### ISSUE THREAD

**Issue by suming-123** [TongchengOpenSource/smart-doc#295]
## Your Environment (Your Use Environment)

* smart-doc version:
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin):
* build tool version(maven or gradle):
smart-doc 2.3.5
## Expected Behavior (Expected Result)

No line breaks
## Current Behavior (Current Result)

Sometimes there are many meaningless line breaks
## Steps to Reproduce (Steps to Reproduce the Bug)

1.
![Q 6A7%4K7@4ZE9}D8TQ8~OG](https://user-images.githubusercontent.com/66777490/174217117-74b29f48-63e3-4a7b-9cd0-a05ff83372f7.png)

2.
3.
4.

**Comment by shalousun** [comment]
@suming-123 Please upgrade to the latest version and then report any issues. We will not process or track anything related to the old versions.
