### ISSUE TITLE
Does not support @PATCH

### ISSUE THREAD

**Issue by slimina** [TongchengOpenSource/smart-doc#297]
In the "framework": "JAX-RS" scenario, the http method @PATCH annotation is not supported.

**Comment by shalousun** [comment]
@slimina I've been quite busy lately, but I can fix it myself. It is recommended to submit a PR. The rules for contributions can be found at https://smart-doc-group.github.io/#/zh-cn/community/contributing.

**Comment by slimina** [comment]
https://github.com/smart-doc-group/smart-doc/pull/303
