### ISSUE TITLE
This format of annotation cannot be generated; can this issue be resolved? 

### ISSUE THREAD

**Issue by yuxicun** [TongchengOpenSource/smart-doc#3]
/**
	 * 楼栋 评论 列表
	 * 
	 * @param params page:当前第几页<br>
	 *               limit:每页多少条记录<br>
	 *               buildId:楼栋id<br>
	 *
	 * @return
	 */

**Comment by yuxicun** [comment]
就是每条后边跟一个换行标签这种,无法解析到

**Comment by netdied** [comment]
你的limit和 buildId没有@param注解

**Comment by netdied** [comment]
/**
     * 楼栋 评论 列表
     *
     * @param params page:当前第几页

     * @param limit limit:每页多少条记录

     * @param buildId buildId:楼栋id

     *
     * @return
     */

**Comment by yuxicun** [comment]
@GetMapping("list")
	public BaseResponseEntityT<List<CollectionBuildComment>> findData(@RequestParam Map<String, Object> params) {
		Pageable pageable = JpaUtil.getPage(params, new Sort(Direction.DESC, "createTime"));
		Specification<CollectionBuildComment> spec = new Specification<CollectionBuildComment>() {

**Comment by yuxicun** [comment]
我的方法是使用Map来接收这个参数,但map里的参数通常是没有办法推演出来,所以我特意在注释里面写明传入的字段

**Comment by yuxicun** [comment]
当然这个并不是bug,只是添加br标记以后,生成出来的文档格式更整齐一点而已

**Comment by netdied** [comment]
升级1.7.5 版本及以上 在注释中添加@apiNote  
 /**
     * 根据任务id删除任务
     * @apiNote limit page 
     */
![image](https://user-images.githubusercontent.com/20217389/69210709-a33e7200-0b96-11ea-97f6-b7ddbdef47d3.png)
他会在description显示

**Comment by netdied** [comment]
@apiNote

**Comment by yuxicun** [comment]
[https://s2.ax1x.com/2019/11/20/MWrvQK.png](url)

**Comment by yuxicun** [comment]
我已经使用了1.7.7版本,加上这个注解后,似乎没有什么变化,需要重启项目吗

**Comment by netdied** [comment]
不需要重启项目 注释写好之后在运行一下就好 @apiNote 
![image](https://user-images.githubusercontent.com/20217389/69211105-e3eabb00-0b97-11ea-866d-5ae0d4519b57.png)
![image](https://user-images.githubusercontent.com/20217389/69211129-f9f87b80-0b97-11ea-990c-36435a982132.png)
因为回复写@会自动转换大小写 你看第一张图 是不是大小写错了

**Comment by yuxicun** [comment]
非常感谢,已经成功了,这个软件非常好,但是我还有一个更大胆的想法

**Comment by yuxicun** [comment]
package com.scy.utils;

import java.io.Serializable;
import java.util.HashMap;

/**
 * 设置返回,用法:R.ok().put("","")...
 * 
 * @author SCY
 *
 */
public class R extends HashMap<String, Object> implements Serializable {
	private static final long serialVersionUID = 1L;

	private R() {
		super.put("code", Const.OK.getCode());
	}

	public R put(String key, Object value) {
		super.put(key, value);
		return this;
	}

	public static R error(String msg) {
		R r = new R();
		r.put("code", Const.ERROR.getCode());
		r.put("msg", msg);
		return r;
	}

	public static R error() {
		return error(Const.ERROR.getMsg());
	}

	public static R ok() {
		return ok(Const.OK.getMsg());
	}

	public static R ok(String msg) {
		R r = new R();
		r.put("msg", msg);
		return r;
	}

	public static R ok(Object obj) {
		R r = new R();
		r.put("data", obj);
		return r;
	}

}

**Comment by yuxicun** [comment]
这个是我用来作为返回到前端的封装类,其可以新增任何数据类型的对象,但是在生成文档的时候,会将map中一些其它的不知道的字段给罗列成返回字段,如果能够屏蔽掉这些字段,只返回指定的字段,这个文档生成器就非常完美了,因为如果都定义了泛型的话,有时候可能返回的东西或者类型不是一个,这种就不好使用泛型返回

**Comment by yuxicun** [comment]
package com.scy.utils;

/**
 * 
 * @author SCY
 *
 * @param <T>
 */
public class RT<T> {
	private int code;
	private String msg;
	private T data;
	private Integer count;

	public int getCode() {
		return code;
	}

	public void setCode(int code) {
		this.code = code;
	}

	public String getMsg() {
		return msg;
	}

	public void setMsg(String msg) {
		this.msg = msg;
	}

	public T getData() {
		return data;
	}

	public void setData(T data) {
		this.data = data;
	}

	public Integer getCount() {
		return count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}

	public static <T> RT<T> ok() {
		RT<T> r = new RT<>();
		r.setCode(Const.OK.getCode());
		r.setMsg(Const.OK.getMsg());
		return r;
	}

	public static <T> RT<T> ok(String msg) {
		RT<T> r = new RT<>();
		r.setCode(Const.OK.getCode());
		r.setMsg(msg);
		return r;
	}

	public static <T> RT<T> ok(T data) {
		RT<T> r = new RT<>();
		r.setCode(Const.OK.getCode());
		r.setMsg(Const.OK.getMsg());
		r.setData(data);
		return r;
	}

	public static <T> RT<T> ok(T data, Integer count) {
		RT<T> r = new RT<>();
		r.setCode(Const.OK.getCode());
		r.setMsg(Const.OK.getMsg());
		r.setData(data);
		r.setCount(count);
		return r;
	}

	public static <T> RT<T> ok(Const constant) {
		RT<T> r = new RT<>();
		r.setCode(constant.getCode());
		r.setMsg(constant.getMsg());
		r.setData(null);
		r.setCount(null);
		return r;
	}

	public static <T> RT<T> ok(Const constant, T data) {
		RT<T> r = new RT<>();
		r.setCode(constant.getCode());
		r.setMsg(constant.getMsg());
		r.setData(data);
		return r;
	}

	public static <T> RT<T> ok(Const constant, T data, Integer count) {
		RT<T> r = new RT<>();
		r.setCode(constant.getCode());
		r.setMsg(constant.getMsg());
		r.setData(data);
		r.setCount(count);
		return r;
	}

	public static <T> RT<T> error() {
		RT<T> r = new RT<>();
		r.setCode(Const.ERROR.getCode());
		r.setMsg(Const.ERROR.getMsg());
		return r;
	}

	public static <T> RT<T> error(String msg) {
		RT<T> r = new RT<>();
		r.setCode(Const.ERROR.getCode());
		r.setMsg(msg);
		return r;
	}

	public static <T> RT<T> error(Const constant) {
		RT<T> r = new RT<>();
		r.setCode(constant.getCode());
		r.setMsg(constant.getMsg());
		return r;
	}

}

**Comment by yuxicun** [comment]
下边这个是为了生成文档而使用的返回实体封装,缺点就是没有办法返回判断类型的返回数据

**Comment by yuxicun** [comment]
谢谢作者,先close insue

**Comment by netdied** [comment]
你的第一个extends hashmap的封装 目前我们并没有比较好的方案处理这个问题 如果你有更好的思路 加群讨论啊！！！！
qq群号：170651381
