### ISSUE TITLE
The API request parameter uses List<String> to receive the request Body, and there is an issue with the generated documentation debug page.

### ISSUE THREAD

**Issue by HarryAlen** [TongchengOpenSource/smart-doc#300]
## Your Environment (Your Use Environment)

* smart-doc version: 2.4.7
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin): 2.4.7
* build tool version(maven or gradle): maven
* springboot: 2.6.7
* jdk: 1.8
* IDEA: 2022.1

## Expected Behavior (Expected Result)
Whether it is a delete request or a post request, when the request Body passes an array and the Java interface uses List<T> to receive it, the generated documentation can be normally debugged, and the field description is correct.

## Current Behavior (Current Result)
When the interface is decorated with the @DeleteMapping annotation, in the generated documentation, there is no input box for the request parameters, and the field description automatically concatenates ",[array of string]@since".
![image](https://user-images.githubusercontent.com/15919903/174967272-ffd313d0-fea3-491c-955e-65dd99ee67b7.png)
Using Postman, the interface can be normally requested.
![image](https://user-images.githubusercontent.com/15919903/174965780-75e5e5e3-96db-46e5-adb3-8bd6089bac44.png)

After changing to the @PostMapping annotation, in the generated documentation, the input box for the request parameters is displayed, but the issue of automatic concatenation of the field description still exists.
![image](https://user-images.githubusercontent.com/15919903/174968213-93b95591-8fb2-412d-8a0a-fa170c34ffb0.png)

## Possible Solution (Bug Resolution Suggestion)
For now, the issue of the request parameter edit area not appearing in the documentation generated by accepting the delete request method can be accepted, but the field description must be correct.

## Steps to Reproduce (Steps to Reproduce the Bug)

1. The Java code is roughly as follows:

```java
    /**
     * Batch delete BOM
     * @param ids Collection of box type BOM ids, separated by commas in English
     */
//    @DeleteMapping("/batchDelete")
    @PostMapping("/batchDelete")
    public CommonResult<Void> batchDelete(@RequestBody List<String> ids) {
        System.out.println("ids = " + ids);

        return CommonResult.success();
    }
```

2. CommonResult is a generic return utility class that extends BaseResult<T>
```java
import lombok.Data;

/**
 * General return class
 */
@Data
public abstract class BaseResult<T> {

    // -------------------------------------------------------------- Predefined status codes start

    /**
     * Request success status code
     */
    public static final Integer DEFAULT_SUCCESS_CODE = 200;

    /**
     * System error status code
     */
    public static final Integer DEFAULT_ERROR_CODE = 508;

    /**
     * Unauthorized status code (login expired or no operation permission)
     */
    public static final Integer HTTP_UNAUTHORIZED_CODE = 401;

    // -------------------------------------------------------------- Predefined status codes end

    /**
     * Whether the request was successful
     */
    private boolean success;
    /**
     * Response status code 200-success 508-error 401-unauthorized
     */
    private Integer code;
    /**
     * Response message
     */
    private String message;
    /**
     * Response object
     */
    private T data;

}

```

```java

import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * Interface return utility class
 */
@Data
@EqualsAndHashCode(callSuper = true)
public class CommonResult<T> extends BaseResult<T> {

    public static <T> CommonResult<T> success() {
        return success("Operation successful", null);
    }

    public static <T> CommonResult<T> success(String message) {
        return success(message, null);
    }

    public static <T> CommonResult<T> success(String message, T data) {
        return baseCreate(DEFAULT_SUCCESS_CODE, true, message, data);
    }

    /**
     * Unauthorized return result encapsulation
     */
    public static <T> CommonResult<T> noAuthError() {
        return error(HTTP_UNAUTHORIZED_CODE, "Please log in again");
    }

    /**
     * Unauthorized return result encapsulation
     * @param message Error message
     */
    public static <T> CommonResult<T> noAuthError(String message) {
        return error(HTTP_UNAUTHORIZED_CODE, message);
    }

    public static <T> CommonResult<T> error() {
        return error("The system is busy, please try again later");
    }

    public static <T> CommonResult<T> error(String message) {
        return error(DEFAULT_ERROR_CODE, message);
    }

    public static <T> CommonResult<T> error(Integer code, String message) {
        return baseCreate(code, false, message, null);
    }

    public static <T> CommonResult<T> baseCreate(Integer code, boolean success, String message, T data) {
        CommonResult<T> result = new CommonResult<T>();
        result.setCode(code);
        result.setSuccess(success);
        result.setMessage(message);
        result.setData(data);
        return result;
    }
}
```
3. No error messages during the execution of the maven plugin

## Context (Bug Impact Description)

Cannot happily test on the smart-doc generated documentation debug page anymore

**Comment by shalousun** [comment]
@893230716 The description is fine; for basic types that do not require expansion, smart-doc automatically adds a segment of descriptive text indicating the type contained within. This is not an error but rather an informative comment.
