### ISSUE TITLE
Is it possible to support basic types such as java.time.Period?

### ISSUE THREAD

**Issue by LeeMeo** [TongchengOpenSource/smart-doc#304]
Currently, `java.time.Period` is recognized as an object, and it parses all internal members nested within, causing confusion in the API documentation.
Could we consider supporting basic types such as `java.time.Period`?

Alternatively, we could consider defining a custom annotation `@final` to indicate that the internal members of this type should not be parsed further.
<img width="352" alt="企业微信截图_16564068056187" src="https://user-images.githubusercontent.com/12180796/176139029-3ba7af57-5114-4d9a-b33a-e2f904cc28ce.png">

**Comment by shalousun** [comment]
@LeeMeo Please fill in the template clearly, especially clarifying what the final expectation is. Some features are rarely used or have not been used by those maintaining smart-doc, so it is unclear what form would meet expectations.
