### ISSUE TITLE
How to set the required parameters for RPC interfaces?

### ISSUE THREAD

**Issue by WJah** [TongchengOpenSource/smart-doc#305]
I tried many `@NotNull` and `@NonNull` annotations, but the required field for the RPC interface parameters always remains false.
![image](https://user-images.githubusercontent.com/6975919/176688612-f5c437f4-aba8-49f5-969b-5cf85bf3a5e3.png)

**Comment by shalousun** [comment]
@WJah Perhaps RPC is not supported.

**Comment by netdied** [comment]
Previously, RPC did not support setting the required attribute for GET request parameters. In the next version, it will be possible to implement the required setting for GET request parameters through annotations such as @NotNull.
