### ISSUE TITLE
Issues with Enum Recognition

### ISSUE THREAD

**Issue by SERE026** [TongchengOpenSource/smart-doc#306]
## Summary (Description of this PR)

Hope to support the recognition of enumerations.

### Basic Example (Use Case of the PR)
```
/**
* @see com.xx.XxEnum
*/
```

### Motivation (Purpose of this PR)
Many parameters need to be displayed to the front end through enumerations.

**Comment by chenqi146** [comment]
Could you please describe your use case in detail?
