### ISSUE TITLE
Supports ignoring part or all of the fields of subclass or parent class.

### ISSUE THREAD

**Issue by myifeng** [TongchengOpenSource/smart-doc#307]
## Your Environment

* smart-doc version: smart-doc-maven-plugin 2.4.7
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin): 2.4.7
* build tool version(maven or gradle): Maven

## Expected Behavior

Given the following Java classes:

```java
public class BaseEntity implements Serializable {
    private Long id;
    private Date createTime;
}
```

```java
public class AEntity extends BaseEntity {
    private Long aid;
}
```

```java
public class BEntity extends BaseEntity {
    private Long bid;
}
```

And the custom configuration:

```json
"customRequestFields": [{
    "name":"id",
    "ownerClassName":"com.xxxx.entity.BaseEntity",
    "ignore":true
}]
```

The expectation is that fields inherited from the `BaseEntity` class, specifically `id` and `createTime`, should not be displayed in the request parameter list since they are system-generated fields and should not be user-inputtable.

## Current Behavior

Despite the configuration, the parameters `id` and `createTime` are still shown in the request parameters list.

## Possible Solution

A potential solution could include enhancing the configuration options to better support ignoring fields at the class level or at a more granular level:

1. Extend the functionality of `customRequestFields` to allow ignoring fields from parent classes.
   ```json
   "customRequestFields": [{
       "name":"id",
       "ownerClassName":"com.xxxx.entity.BaseEntity",
       "ignore":true
   }]
   ```

2. Introduce or refine the `ignoreRequestParams` option to support field-level ignoring.
   - To ignore all fields of `BaseEntity`:
     ```json
     "ignoreRequestParams": [
         "com.xxxx.entity.BaseEntity"
     ]
     ```
   - To ignore specific fields of `BaseEntity`:
     ```json
     "ignoreRequestParams": [
         "com.xxxx.entity.BaseEntity$id"
     ]
     ```

## Steps to Reproduce

1. Define a `BaseEntity` class with system-generated fields.
2. Create subclasses (`AEntity`, `BEntity`) that extend `BaseEntity`.
3. Configure `smart-doc` to ignore certain fields from `BaseEntity`.
4. Run the application and generate the API documentation using `smart-doc`.
5. Observe that the ignored fields from `BaseEntity` are still included in the request parameter list.

## Context

This issue impacts the usability of the generated API documentation, as it includes unnecessary fields that are not meant for direct manipulation by end-users. The goal is to have a clean and accurate representation of the API's input requirements, which currently falls short due to the inclusion of system-generated fields in the request parameters.

**Comment by shalousun** [comment]
@myifeng This approach that does not conform to programming standards is not supported by smart-doc. The design philosophy of smart-doc includes two aspects: zero intrusion for documentation generation, and strict coding standards requirements. The strict standard requirement means that the behavior of your code when it runs should be consistent with the output of the documentation, rather than defining some behaviors that are inconsistent with the operation through chaotic configuration. Whether a field is exported to the document, smart-doc natively supports fastjson, jackson, and jsr specifications. These technologies can be used to regulate behavior and achieve consistency in presentation.
