### ISSUE TITLE
How to integrate using dependency packages without using plugins? Every time the code is updated, it has to be executed with a Maven command, which takes more than one minute each time. The user experience is too poor.

### ISSUE THREAD

**Issue by CrazyLionCat** [TongchengOpenSource/smart-doc#313]
## Summary(关于这个pr的描述)

Brief explanation of the feature.

### Basic example(pr的用例)

If the proposal involves a new or changed API, include a basic code example. Omit this section if it's not applicable.

### Motivation(提出这个pr目的)

Why are we doing this? What use cases does it support? What is the expected outcome?

**Comment by shalousun** [comment]
@JavaLionLi

1. Regarding build speed, there is a comment in the plugin that states: "smart-doc can automatically analyze the dependency tree and load all source code dependencies, which in principle affects the efficiency of document building. Therefore, you can use 'includes' to let the plugin load the components you have configured." Please carefully read the documentation for configuration.

2. Why does smart-doc use Maven instead of being bound to IDEA?
    smart-doc relies on source code, which is not limited to the source code within a single project. The code encapsulation is very high, with many codes being distributed like open-source projects to internal repositories, where other projects independently introduce them. This requires Maven or Gradle to analyze dependencies, load remote source code, and extract comments.
    There are also community-based plugins similar to those for IDEA, but due to some technical issues, currently, the generation of documents for complex projects is severely lacking.
    If there are better tools available, we actually recommend using them. Due to limitations in manpower and resources, smart-doc is currently facing many restrictions.
    IDEA is not the only development tool in the industry, and document building does not necessarily have to be done locally. Our initial reason for using Maven and Gradle was actually to consider team-based DevOps scenarios, where DevOps can completely replace manual interaction through webhooks to build interface documents.

**Comment by CrazyLionCat** [comment]
> @JavaLionLi
> 
> 1. Regarding build speed, there is a comment in the plugin: "smart-doc can automatically analyze the dependency tree and load all source code dependencies, which in principle affects the efficiency of document building. Therefore, you can use 'includes' to let the plugin load the components you have configured." Please carefully read the documentation for configuration.
> 
> 2. Why does smart-doc use Maven instead of being integrated with IDEA?
>    Smart-doc relies on source code, which is not limited to the source code within a single project. The code encapsulation is very high, with many codes being distributed like open-source projects to internal repositories, where other projects independently introduce them. This requires Maven or Gradle to analyze dependencies, load remote source code, and extract comments.
>    There are also community-based plugins similar to those for IDEA, but due to some technical issues, currently, the generation of documents for complex projects is severely lacking.
>    If there are better tools available, we actually recommend using them. Due to limitations in manpower and resources, smart-doc is currently facing many restrictions.
>    IDEA is not the only development tool in the industry, and document building does not necessarily have to be done locally. Our initial reason for using Maven and Gradle was actually to consider team-based DevOps scenarios, where DevOps can completely replace manual interaction through webhooks to build interface documents.

Have you considered integrating therapi-runtime-javadoc? This would eliminate the need to use Maven commands. Currently, springdoc-openapi-javadoc uses this approach, generating documentation during code compilation.

**Comment by shalousun** [comment]
> @JavaLionLi
> 
> 1. Regarding build speed, there is a comment in the plugin: "smart-doc can automatically analyze the dependency tree and load all source code dependencies, which in principle affects the efficiency of document building. Therefore, you can use 'includes' to let the plugin load the components you have configured." Please carefully read the documentation for configuration.
> 
> 2. Why does smart-doc use Maven instead of being integrated with IDEA?
>    Smart-doc relies on source code, which is not limited to the source code within a single project. The code encapsulation is very high, with many codes being distributed like open-source projects to internal repositories, where other projects independently introduce them. This requires Maven or Gradle to analyze dependencies, load remote source code, and extract comments.
>    There are also community-based plugins similar to those for IDEA, but due to some technical issues, currently, the generation of documents for complex projects is severely lacking.
>    If there are better tools available, we actually recommend using them. Due to limitations in manpower and resources, smart-doc is currently facing many restrictions.
>    IDEA is not the only development tool in the industry, and document building does not necessarily have to be done locally. Our initial reason for using Maven and Gradle was actually to consider team-based DevOps scenarios, where DevOps can completely replace manual interaction through webhooks to build interface documents.
> 
> Have you considered integrating therapi-runtime-javadoc? This would eliminate the need to use Maven commands. Currently, springdoc-openapi-javadoc uses this approach, generating documentation during code compilation.
> Therapi-runtime-javadoc, in the short term, I personally do not have the time to research this, and secondly, there are some issues that need to be considered before final integration: whether this method can parse code that is packaged like open source and introduced from outside the project. If it is used in API interfaces, whether it can extract comments is a crucial issue. Smart-doc always considers usability in real project scenarios, which is why smart-doc can be introduced as a team-level tool by many companies and adapted to many projects, where other similar source code extraction tools cannot. If full scenario compatibility cannot be achieved, we will not sacrifice usability for individual ease of use.
