### ISSUE TITLE
Generic support is not fully implemented.

### ISSUE THREAD

**Issue by kezhiyang** [TongchengOpenSource/smart-doc#314]
The following generic types are not supported.
public class AuthorityRuleEntity extends AbstractRuleEntity<AuthorityRule> 

public abstract class AbstractRuleEntity<T extends AbstractRule> implements RuleEntity {
T rule
}

![image](https://user-images.githubusercontent.com/9025742/178202368-49196e20-97f8-4237-989e-cf793eb654d4.png)

**Comment by shalousun** [comment]
@kezhiyang The use case you provided is unsupported. First, it's important to understand the parsing rules of smart-doc. For a class like `class A<T> { T rule; }`, the generic type of the field is inferred from the type parameter `T` on the class. Without this initial declaration, it's impossible to map the field type later on.
Additionally, for such unknown Java classes, it's best to provide complete information. For someone like me who has long been away from business development and rarely writes Java nowadays, I have no idea what these classes are or where they come from.
