### ISSUE TITLE
Java 8 supports years, months, dates, etc.

### ISSUE THREAD

**Issue by yhan219** [TongchengOpenSource/smart-doc#315]
## Summary(Description of this PR)

Support for Java 8 date and time APIs including
- `LocalDate`
- `LocalDateTime`
- `LocalTime`
- `YearMonth`
- `Year`

Brief explanation of the feature.

### Basic Example(Usage Example of the PR)

- For `LocalDate`, the format will be `2022-01-10`
- For `LocalDateTime`, the format will be `2022-01-01 01:01:01`
- For `LocalTime`, the format will be `01:01:01`
- For `YearMonth`, the format will be `2022-01`
- For `Year`, the format will be `2022`

Allows configuring the relative format in the configuration.

If the proposal involves a new or changed API, include a basic code example. Omit this section if it's not applicable.

### Motivation(Purpose of this PR)

Why are we doing this? What use cases does it support? What is the expected outcome?

**Comment by shalousun** [comment]
@yhan219 Isn't the default format for LocalDate and LocalDateTime already correct?

**Comment by yhan219** [comment]
Yes, it is correct; it seems that the others are not available.

**Comment by yhan219** [comment]
Additionally, there's `MonthDay` which should be formatted as `01-01`.
