### ISSUE TITLE
Option to change "source code path"

### ISSUE THREAD

**Issue by santoshbmath** [TongchengOpenSource/smart-doc#316]
## Your Environment(您的使用环境)

* smart-doc version: 2.4.8
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin):2.4.8
* build tool version(maven or gradle): maven

## Expected Behavior(您期望的结果)
While generating the doc, it automatically picks source code path as "src/main/java". Provide an option to specify the source code path.

For example, below is the path it loaded for my project but my project does not have "../src/main/java". It has ".../src"
[INFO] Smart-doc has loaded the source code path: [{"path":"C:/eclipse/ws/proj/src/main/java"}]

## Current Behavior(当前结果)
Automatically picks source code path as ".../src/main/java"

## Steps to Reproduce (Bug产生步骤，请尽量提供用例代码)

1.
2.
3.
4.

**Comment by santoshbmath** [comment]
Change it as "enhancement".

**Comment by shalousun** [comment]
@santoshbmath We used to provide related options in the plugin, but this does not conform to the concept of smart-doc, so this configuration item was later cancelled. Placing code in the /src/main/java directory has become an industry standard. smart-doc is not just a documentation tool either, many features are designed to force users to follow best practices.

**Comment by santoshbmath** [comment]
@shalousun Thanks for clarification. I agree with you that industry standard is to place code in /src/main/java but how about legacy application? i felt providing an **optional** option (default set to /src/main/java) will help more projects use smart-doc.

Note: It's not a bug, it's an enhancement request. I don't have permission to change the label to enhancement.

Feel free to close this issue if you feel the implementation is right.
