### ISSUE TITLE
There are instances where the interface scanning is incomplete.

### ISSUE THREAD

**Issue by JoestarCRUD** [TongchengOpenSource/smart-doc#318]
There are instances where the interface scanning is incomplete.
# Your Environment (Details about your usage environment)
- smart-doc version: 2.4.7 (Tried lower versions like 2.4.0 and higher versions like 2.4.9, the issue persists)
- plugin version (e.g., smart-doc-maven-plugin or smart-doc-gradle-plugin): smart-doc-maven-plugin
- build tool version (maven or gradle): maven

# Expected Behavior (If describing a bug, state what should happen)
- Hope to scan all interfaces and generate documentation.
- If suggesting a change/improvement, describe how it should work.

# Current Behavior (Describe the bug's current behavior)
- Only one interface is actually scanned, but I have written comments for all interfaces according to the specification.
- Attached images show the smart-doc bug.

# Possible Solution (Suggest a fix for the bug or reason for the bug)
- Re-examine the method of interface scanning; it would be best to print the scanned interfaces in the maven console.
- If suggesting a change/improvement, explain the difference from current behavior.

Steps to Reproduce (Provide a link to a live example or clear steps to reproduce the bug, include code if relevant)
1.
2.
3.
4.

# Context (How has this issue affected you? What are you trying to accomplish?)
Currently, the generated interface documentation is incomplete. Since the project is large and may contain over 300 interfaces, verifying each one is very time-consuming. I want to generate reliable, concise, and user-friendly interface documentation using smart-doc, but currently, an entire controller's interfaces are not scanned, and it is unknown whether other interfaces are missing.

**Comment by shalousun** [comment]
@JoestarCRUD Did you find that the unexported interfaces are all written as private by you? This is also very uncommon.

**Comment by JoestarCRUD** [comment]
> @JoestarCRUD Did you find that the unexported interfaces are all written as private by you? This is also very uncommon.

Indeed, that's correct; I was not careful enough, thank you for your guidance. If possible, could we add a supplement to the documentation? I indeed read through the official documentation several times without finding a solution. Although this issue is uncommon, I suspect other users might encounter it too.
