### ISSUE TITLE
It is recommended to add the parameter "packageExcludeFilters" for excluding interface packages.

### ISSUE THREAD

**Issue by ZAKLLL** [TongchengOpenSource/smart-doc#319]
### Motivation (Purpose of this PR)

Currently, there is a configuration parameter named "packageFilters" used to scan the interface documentation within a specific package or controller. However, some packages may contain interfaces that are not suitable for public exposure in the interface documentation, such as URLs intended for dev use only, which are used by the interface developers themselves during testing but are developed within the same package. Therefore, could we add a parameter named "packageExcludeFilters" to exclude these undesirable URLs? The final set of interfaces should be the result of f(packageFilters) - f(packageExcludeFilters), where **f(name)** represents retrieving all interfaces within a package.

**Comment by shalousun** [comment]
@ZAKLLL  It is suggested that interfaces intended for personal development and testing should be handled in separate packages to physically isolate them, as mixing them together is not a good practice. Smart-doc is already quite complex, and it already puts significant pressure on our open-source maintenance. We will not accept any non-essential features.
