### ISSUE TITLE
Optimization suggestion: The return value comments were not scanned during the document scan.

### ISSUE THREAD

**Issue by Butcher-hub** [TongchengOpenSource/smart-doc#321]
During the document scan, the return value comments were not retained. Typically, API documentation needs to explain the return values.

![issue](https://s1.ax1x.com/2022/07/29/vPkxjs.jpg)

**Comment by shalousun** [comment]
@Butcher-hub suggests directly explaining in the detailed method comments to maintain a clean and concise document template without adding other display elements.
