### ISSUE TITLE
Issue with multi-layer generics not being recognized in request parameters.

### ISSUE THREAD

**Issue by n65785828** [TongchengOpenSource/smart-doc#322]
### Your Environment (Your Usage Environment)

* smart-doc version: 2.4.8
* plugin version (e.g., smart-doc-maven-plugin or smart-doc-gradle-plugin): 2.4.8
* build tool version: Maven 3.3.9

The project uses a Spring MVC Controller.

```
/**
 * Combustion interface
 * @param param
 * @return
 */
@PostMapping("/test")
public ResultInfo test(@RequestBody RequestInfo<GuardianRegModel<ChildModel>> param){
    return new ResultInfo(ResponseEnum.INVALID_2040);
}
```

After using `smart-doc:torna-rest` to generate documentation for the API, there is no data for `ChildModel` in the request parameters.

Below are the entity classes for the API parameters:

```java
@Data
public class RequestInfo<T> {
    /**
     * Data
     */
    private T data;
    /**
     * Timestamp
     */
    private Long timestamp;
}
```

```java
@Data
public class GuardianRegModel<T> {
    /**
     * Name
     * @mock Zhang San
     */
    private String name;

    /**
     * Children's information
     */
    private List<T> children;
}
```

```java
@Data
public class ChildModel {
    /**
     * Child's name
     * @mock Zhang Si
     */
    private String childName;
    /**
     * Child's age
     * @mock 12
     */
    private Integer childAge;
}
```

**Comment by netdied** [comment]
Unable to reproduce this issue.
![image](https://user-images.githubusercontent.com/20217389/183001999-ba39a432-33ea-4842-9cd3-f6df55376c3b.png)
![image](https://user-images.githubusercontent.com/20217389/183002026-024afba2-5f2c-4c00-beb9-dd4c305e4f4a.png)
You can try debugging to see where the issue lies.

**Comment by shalousun** [comment]
This issue has been inactive for a long time and will be closed temporarily.
