### ISSUE TITLE
Different enumeration contents are mixed together.

### ISSUE THREAD

**Issue by Caiws** [TongchengOpenSource/smart-doc#323]
Your uploaded images appear to be broken links and cannot be displayed here. However, based on your description, it seems you're experiencing an issue with the `smart-doc` tool when generating documentation for your project. Here's the translation:

### Your Environment
- smart-doc version: unspecified
- plugin version (e.g., smart-doc-maven-plugin or smart-doc-gradle-plugin): 2.4.8
- build tool version (Maven or Gradle): Maven

### Expected Behavior
In the documentation, only referenced enumeration data should be included.

### Current Behavior
All enumeration data is mixed together in the documentation.

### Possible Solution
Not obligatory, but you may suggest a fix or reason for the bug, or ideas on how to implement an addition or change.

### Steps to Reproduce
1. Define enumeration class A and enumeration class B.
2. The sample request entity contains enumeration class A.
3. Use `mvn smart-doc:torna-rest` to generate documentation.
4. In the request examples, both enumeration types A and B are listed, despite only A being used.
![image](https://user-images.githubusercontent.com/9735503/183046076-c214e25b-3dbc-4465-837e-1e3032979fea.png)
![image](https://user-images.githubusercontent.com/9735503/183046130-ee2ab6fd-0246-4769-bc4e-b8cb4029a12c.png)
![image](https://user-images.githubusercontent.com/9735503/183046219-bcd0965f-f6f9-463c-a29e-308c93f84a3e.png)
![image](https://user-images.githubusercontent.com/9735503/183046312-4fc21cf2-a017-43c2-ab27-ee70a6aa035b.png)

**Comment by shalousun** [comment]
@Caiws Please confirm whether this bug is caused by smart-doc, or if it's merely a rendering error by Torna. Currently, Torna and smart-doc are developed independently. If it is an issue with Torna's rendering, I suggest submitting an issue on the Torna repository on Gitee.

**Comment by Caiws** [comment]
Upon reviewing the data sent to Torna, it is indeed separate. My apologies for the confusion.
