### ISSUE TITLE
Is there any plan to support Word output format?

### ISSUE THREAD

**Issue by zhouyao1994** [TongchengOpenSource/smart-doc#324]
## Summary(Description of this PR)
I found in the 2021 issues that there were no plans to support Word format output for the time being. Are there any plans to support it now?

Brief explanation of the feature.

### Basic example(Example use case for the PR)

If the proposal involves a new or changed API, include a basic code example. Omit this section if it's not applicable.

### Motivation(Purpose of this PR)

Why are we doing this? What use cases does it support? What is the expected outcome?

**Comment by shalousun** [comment]
@zhouyao1994 You can use it in conjunction with Torna, which has the capability to export to Word. Smart-doc will not provide this function. Unless it's for sending a document to a client to wrap things up, Word doesn't serve much of a purpose in modern development regarding API documentation. Instead, it can lead to fragmented document management within a team. For internal team use, a unified management and presentation tool like Torna is more appropriate. This way, testers and front-end developers don't need to ask where the documents are stored.

**Comment by zhouyao1994** [comment]
> @zhouyao1994 You can use it in conjunction with Torna, which has the capability to export to Word. Smart-doc will not provide this function. Unless it's for sending a document to a client to wrap things up, Word doesn't serve much of a purpose in modern development regarding API documentation. Instead, it can lead to fragmented document management within a team. For internal team use, a unified management and presentation tool like Torna is more appropriate. This way, testers and front-end developers don't need to ask where the documents are stored.

Okay, I understand now, thank you very much.
