### ISSUE TITLE
Are all the required flags in the generated document set to false? How can I set whether a parameter is required or not?

### ISSUE THREAD

**Issue by iyinghui** [TongchengOpenSource/smart-doc#325]
## Your Environment(您的使用环境)

* smart-doc version:
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin):
* build tool version(maven or gradle):
win10 +idea +jdk8

## Expected Behavior(您期望的结果)
I hope to be able to set whether a parameter is required or not. Additionally, why cannot issues be submitted for this project on Gitee?

**Comment by shalousun** [comment]
@iyinghui Whether a parameter is required or not is determined by the `JSR 303`+ specification and Spring's `@Required` annotation, among others. Smart-doc supports framework-standard technologies; this is a coding issue, not a bug. Regarding `Gitee`, the smart-doc code is not maintained on Gitee itself; it merely serves as a synchronization platform. Opening access on `Gitee` increases our open-source maintenance management costs, requiring us to check multiple places. Additionally, in the initial phase of opening access on Gitee, many developers frequently raised thoughtless questions without even bothering to look at the official documentation.
