### ISSUE TITLE
Hope that methods without comments do not generate documentation.

### ISSUE THREAD

**Issue by squallliu** [TongchengOpenSource/smart-doc#328]
## Summary (Description of this PR)

Methods without comments should not generate documentation.

### Basic Example (Use case for the PR)

[Insert use case here]

### Motivation (Purpose of this PR)

Firstly, not all APIs are intended for external use, yet they appear in the documentation.
Secondly, documentation generated without comments lacks titles and looks unappealing.

**Comment by shalousun** [comment]
> @squallliu Firstly, interfaces that one does not wish to include in the API documentation can be ignored by using a custom `@ignore` tag.
> Secondly, regarding the scenario of lack of comments, this is clearly an issue of coding standards. We should not abandon standards just because it looks unattractive. Moreover, as an open-source project, we need to consider the usage scenarios of the majority. For teams adopting smart-doc, it is easy for the team to maintain a unified style of commenting and coding, which also makes it easier for leaders to inspect.

**Comment by squallliu** [comment]
> @squallliu Firstly, interfaces that one does not wish to include in the API documentation can be ignored by using a custom `@ignore` tag. Secondly, regarding the scenario of lack of comments, this is clearly an issue of coding standards. We should not abandon standards just because it looks unattractive. Moreover, as an open-source project, we need to consider the usage scenarios of the majority. For teams adopting smart-doc, it is easy for the team to maintain a unified style of commenting and coding, which also makes it easier for leaders to inspect.
> 
> Could methods without comments use the method name as the title? In fact, a well-named method does not require comments; writing comments can actually lead to inconsistencies between the documentation and the code. When refactoring and renaming a method, comments will not automatically update, leading to a mismatch between the comment and the code (developers often forget to update comments along with the code changes). I have never encouraged writing meaningless comments, unless they are for particularly complex algorithmic code.

**Comment by shalousun** [comment]
> @squallliu Firstly, interfaces that one does not wish to include in the API documentation can be ignored by using a custom `@ignore` tag. Secondly, regarding the scenario of lack of comments, this is clearly an issue of coding standards. We should not abandon standards just because it looks unattractive. Moreover, as an open-source project, we need to consider the usage scenarios of the majority. For teams adopting smart-doc, it is easy for the team to maintain a unified style of commenting and coding, which also makes it easier for leaders to inspect.
> 
> Could methods without comments use the method name as the title? In fact, a well-named method does not require comments; writing comments can actually lead to inconsistencies between the documentation and the code. When refactoring and renaming a method, comments will not automatically update, leading to a mismatch between the comment and the code (developers often forget to update comments along with the code changes). I have never encouraged writing meaningless comments, unless they are for particularly complex algorithmic code.
> 
> First, you need to understand what problems your team aims to solve by introducing a tool. If the team itself has poor enforcement capabilities for standards, smart-doc might not be a good choice.
> Just like the original design intentions of smart-doc are as follows:
> 1. Reduce development workload, eliminate the need for manual documentation, and avoid invasive annotations.
> 2. Enforce strong standards.
> 3. Assist developers in quickly generating interface documentation for interaction with front-end and testing teams, enhancing overall team efficiency.
> If you find that a tool does not meet your team's needs, there is no necessity to use it. Every tool has its own applicable scenarios.
