### ISSUE TITLE
The postman.json file generated by smart-doc causes an error when imported into yapi.

### ISSUE THREAD

**Issue by dai19470** [TongchengOpenSource/smart-doc#33]
The attachment is the generated postman file.
<img width="457" alt="未命名1591410903" src="https://user-images.githubusercontent.com/21135250/83934198-6ad44d80-a7e1-11ea-8d8d-7252bbee78c9.png">
`{
  "info": {
    "schema": "https://schema.getpostman.com/json/collection/v2.0.0/collection.json",
    "_postman_id": "668e04ad-2b3f-4b94-b0d3-e0d1d471f693",
    "name": "smart-doc    2020-06-06 10:26:18"
  },
  "item": [
    {
      "name": "用户管理控制器",
      "item": [
        {
          "name": "分页查询用户信息",
          "request": {
            "method": "GET",
            "body": {
              "mode": "formdata",
              "formdata": [
                {
                  "key": "pageNum",
                  "type": "text",
                  "desc": "当前页",
                  "value": "1"
                },
                {
                  "key": "pageSize",
                  "type": "text",
                  "desc": "每页大小",
                  "value": "10"
                }
              ]
            },
            "url": "http://10.1.130.107:8888/user/list/tt19nd?pageNum\u003d1\u0026pageSize\u003d10",
            "description": "分页查询用户信息",
            "header": []
          },
          "description": "分页查询用户信息"
        }
      ]
    }
  ]
}`

**Comment by shalousun** [comment]
The import of external systems is currently not within the scope of smart-doc's functionality, and any import errors are unrelated to smart-doc itself.
外部系统的导入目前不在smart-doc功能范围，导入错误本身和smart-doc也无关。
