### ISSUE TITLE
When the @see annotation is incorrect, an error in seeEnum judgment causes a null pointer exception to be triggered here.

### ISSUE THREAD

**Issue by 15200933050** [TongchengOpenSource/smart-doc#331]
Version: 2.4.9

When the @see annotation is incorrect, an error in seeEnum judgment causes a null pointer exception to be triggered here.
https://github.com/smart-doc-group/smart-doc/blob/cbe9e6e210ce6bc40a16866dfbdd2614ea6da529/src/main/java/com/power/doc/utils/JavaClassUtil.java#L275

Example of the annotation that triggers the issue:
`@see DmsDataHelper#fillStandardField(List, String)`

**Comment by shalousun** [comment]
@15200933050 Let's optimize it by changing to a checked exception prompt.

**Comment by shalousun** [comment]
@15200933050 我们优化下，改成受检性异常提示。
