### ISSUE TITLE
The inlineEnum feature is not working, and the formatting also looks poor.

### ISSUE THREAD

**Issue by qfengj** [TongchengOpenSource/smart-doc#332]
The inlineEnum, whether set to true or false, yields the same result, and it's not possible to use custom comments.
inlineEnum不管是true或false都是一样的结果，想使用自己的注释也不行

**Comment by shalousun** [comment]
> The inlineEnum, whether set to true or false, yields the same result, and it's not possible to use custom comments.
inlineEnum不管是true或false都是一样的结果，想使用自己的注释也不行

We hope you can provide complete information following the issue template. The purpose of setting up an issue template for every open source project is to facilitate tracking by open source developers. From the simple text above, we cannot understand what you want. It is necessary to clearly express the current actual situation and your expectations. Without a clear understanding of your demands, we do not know how to make improvements and optimizations.
希望你按照issue的模板补充完整信息，现在每个开源设定issue模板也是为了方便开源开发者可以方便跟踪。从上面这些简单的文字里，我们也无法知道你想要什么，当前实际的情况和你期望的东西需要表达清楚，我们不知道你的清晰的诉求也不知道怎么去改进优化。
