### ISSUE TITLE
Issue with parameter concatenation display in curl-example

### ISSUE THREAD

**Issue by SnowWindDancing** [TongchengOpenSource/smart-doc#333]
## Your Environment(您的使用环境)

* smart-doc version:2.4.8
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin):2.4.8
* build tool version(maven or gradle):

## Expected Behavior(您期望的结果)

curl-example中，http://www.xx.com?openId=65&noticeType=2
## Current Behavior(当前结果)

curl-example中，http://www.xx.com?openId=65¬iceType=2

## Steps to Reproduce (Bug产生步骤，请尽量提供用例代码)
```java
/**
 * User Management
 */
@RestController
@RequestMapping("user")
public class UserController {
    /**
     * Test Interface
     */
    @GetMapping("/getTest")
    public Map<Object, Object> getTest(String openId, String noticeType) {
        return new HashMap<>();
    }
}
```

**Comment by shalousun** [comment]
@SnowWindDancing  @not is html special character , not smart-doc bug
