### ISSUE TITLE
Using `@see` annotation with content other than an enumeration class name results in a runtime error.

### ISSUE THREAD

**Issue by wenyuantc** [TongchengOpenSource/smart-doc#340]
First use, an error occurred while generating the documentation.

## Your Environment(Your Using Environment)
* smart-doc version: 2.5.1
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin): smart-doc-maven-plugin
* build tool version(maven or gradle): maven
* smart-doc.json configuration:
```
{
  "outPath": "src/main/resources/static/apiDoc"
}
```

## Expected Behavior(Expected Outcome)
Generate HTML documents.

## Current Behavior(Current Outcome)
An exception occurs: java.lang.RuntimeException: enum not existed

## Steps to Reproduce (Steps to Generate the Bug, Please Provide Code Examples if Possible)
Describe in detail the steps to reproduce this issue.

**Comment by shalousun** [comment]
@wenyuantc It seems that you have a field marked with @see, but the content is empty.
