### ISSUE TITLE
Spring MVC can't support binding Collection on method importUser,Check it in com.qgs.admin.controller.SysUserController

### ISSUE THREAD

**Issue by songfayuan** [TongchengOpenSource/smart-doc#343]
## Your Environment(您的使用环境)
* smart-doc version: 2.2.3
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin): 2.2.3
* build tool version(maven or gradle): maven

![image](https://user-images.githubusercontent.com/26640824/188369935-e24aeb9f-d247-4877-bccf-03069361c57f.png)

报错信息：
java.lang.RuntimeException: Spring MVC can't support binding Collection on method importUser,Check it in com.qgs.admin.controller.SysUserController

不支持list参数？？？

**Comment by shalousun** [comment]
@songfayuan Spring MVC对非json参数List<T> 如果T不是基础类型，支持是有问题的，阿里这个他是用了自己的注解，所以smart-doc就不支持，其实这种很多第三方自己造的工具肯定没法覆盖，绝大多数我们也不会覆盖，逻辑太多了，A工具一个注解，B工具一个注解，注解的意图smart-doc还得自己处理。我们一般就只对spring官方默认的做处理，比如用输入流来做导入;
可以参考文档忽略掉这个接口参数，让smart-doc跳过，https://smart-doc-group.github.io/#/zh-cn/start/javadoc?id=_25-ignoreparams%e4%bd%bf%e7%94%a8
