### ISSUE TITLE
The response parameters generated by the smart-doc plugin do not support JSR303's `@NotNull` and `@NotBlank` annotations.

### ISSUE THREAD

**Issue by folochina** [TongchengOpenSource/smart-doc#347]
## Your Environment(Your Using Environment)
* smart-doc version:
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin): smart-doc-maven-plugin 2.5.3
* build tool version(maven or gradle): 3.8.1
* torna: 1.16.3

## Expected Behavior(Expected Outcome)
JSR303's @NotNull and @NotBlank annotations are only supported for request parameters, not for response results.

## Current Behavior(Current Outcome)
In the JSON pushed to torna, required=0, torna displays "Required" as "No" (torna configuration does not hide required and length columns with torna.view-config.response-hidden-columns=).
Screenshot:
<img width="908" alt="image" >
![image](https://user-images.githubusercontent.com/11660951/189884964-e53c2bca-7915-4e85-86d8-d64e0c78d11c.png)

## Possible Solution(Bug Fixing Suggestion)
Besides this issue, consider supporting both min and max fields for maxLeng, currently only max is supported.
Alternatively, consider parsing JSR303 configurations that are not supported by torna according to the smart-doc configuration template into the description for display.

## Steps to Reproduce (Steps to Generate the Bug, Please Provide Code Examples if Possible)
1. Use the torna-rest plugin to push documentation; the plugin execution log shows accessToken required=0 in JSON.
2. Refresh torna, it also displays as "No."

## Context(Impact of Bug)

**Comment by shalousun** [comment]
@folochina Isn't it incorrect for JSR 303 to be applied to responses in the first place? The framework does not validate returned data.

**Comment by folochina** [comment]
So, does this mean that JSR 303 annotations can be used for requests, while responses should utilize tag annotations? If it's the same object, then both JSR 303 and tag annotations need to be added.
@shalousun

**Comment by netdied** [comment]
Why does the response need to set the 'required' attribute? It seems a bit illogical...

**Comment by folochina** [comment]
To facilitate front-end integration, it helps to confirm the data response.

**Comment by folochina** [comment]
Actually, it's not about using JSR 303 to set the 'required' attribute; I just want to provide descriptions for response parameters.
For instance, Ant Financial's documentation includes parameter descriptions, but WeChat's API documentation does not. <img width="1492" alt="image" src="https://user-images.githubusercontent.com/11660951/190539287-dabea6d8-065d-4bf0-9550-53377a442ea8.png">

**Comment by shalousun** [comment]
@folochina Smart-doc does not support implementing such peculiar features; we only follow the standards of the framework.
