### ISSUE TITLE
The enumeration parsing pushed by smart-doc to torna is incorrect.

### ISSUE THREAD

**Issue by folochina** [TongchengOpenSource/smart-doc#348]
### Your Environment
* smart-doc version: unspecified
* Plugin version (e.g., smart-doc-maven-plugin or smart-doc-gradle-plugin): smart-doc-maven-plugin 2.5.3
* Build tool version (Maven or Gradle): 3.8.1
* Torna: 1.16.3

### Expected Behavior
The enumeration should be parsed correctly.

### Current Behavior
The enumeration is being parsed incorrectly, resulting in duplicates and incorrect names.

### Possible Solution
The solution should involve parsing only the configured enumeration for the "Captcha" (human-machine verification code).

### Steps to Reproduce
**Problem 1: Duplicate Enumeration Parsing**
API definition:
![image](https://user-images.githubusercontent.com/11660951/189889110-f91f2124-55f5-43a0-bb37-93c7bd565533.png)

Request parameters:
![Image](https://user-images.githubusercontent.com/11660951/189889221-0fb4f3da-44a6-4dc8-b86b-0d2350fca2c7.png)
![Image](https://user-images.githubusercontent.com/11660951/189887711-a614bd57-086d-4d82-b25f-71157040ce58.png)

Enumeration class:
![Image](https://user-images.githubusercontent.com/11660951/189887279-2511769f-c7ca-488b-b60b-4a65b2dd948a.png)

`smart-doc` configuration JSON:
Data dictionaries configuration:
![Image](https://user-images.githubusercontent.com/11660951/189887379-d943ad6a-976b-4767-a9e1-38f20d4a6431.png)

The dictionary is duplicated when pushed to Torna via the Maven plugin `torna-rest`:
[Images showing duplicate dictionaries]

**Problem 2: Incorrect Enumeration Name Parsing**
Parameter annotation in the API:
![Image](https://user-images.githubusercontent.com/11660951/189888404-dce1d85e-2a19-44a1-85f6-1c1fce7c2d3e.png)

Enumeration class:
![Image](https://user-images.githubusercontent.com/11660951/189888454-77206eec-6184-4748-a855-ace8171b9815.png)

`smart-doc` configuration:
![Image](https://user-images.githubusercontent.com/11660951/189888515-cfc2fa8f-6822-4011-8d24-1e7787841f5f.png)

When pushed to Torna, the dictionary shows duplicates and incorrect names:
[Images showing duplicate dictionaries with incorrect names]

### Context
The bug affects the documentation accuracy, leading to confusion and potential misuse of the documented APIs due to incorrect information about enumeration values and their descriptions.

**Comment by folochina** [comment]
The enumeration for the first issue is within the same project.
The enumeration for the second issue is in a different project and has been packaged as source according to the standard usage.

**Comment by shalousun** [comment]
@folochina This should be regarded as an issue with the torna integration. Pull requests are welcome; for contributions via pull requests, please refer to https://smart-doc-group.github.io/#/zh-cn/community/contributing.

**Comment by chenqi146** [comment]
![image](https://user-images.githubusercontent.com/36069431/202328232-978792f2-62dc-4747-9d98-1b43caf77670.png)
@folochina Can the interface comments and class comments for these two images be provided?
