### ISSUE TITLE
Support for Jackson annotation `@JsonNaming`  in converting camel case to underscore.

### ISSUE THREAD

**Issue by kzxuan** [TongchengOpenSource/smart-doc#349]
## Your Environment (Your Usage Environment)
* smart-doc version: 2.5.3
* plugin version: smart-doc-maven-plugin 2.5.3
* build tool version: maven 3.6.3

## Expected Behavior (Expected Outcome)
When using the Jackson annotation @JsonNaming(PropertyNamingStrategy.SnakeCaseStrategy.class) on a request body entity class to automatically convert all variable names from camel case to snake case, smart-doc should effectively change the variable names in the documentation to underscore as well.

## Current Behavior (Current Result)
The current version does not recognize the effect of the @JsonNaming annotation, and the variables in the documentation remain in camel case.
Manually annotating each variable with @JsonProperty is effective, but it is inconvenient when there are a large number of fields.

## Possible Solution (Bug Fix Suggestion)
It is suggested to support @JsonNaming.

## Steps to Reproduce (Steps to Generate the Bug, please provide code examples if possible)
To reproduce the issue, simply add @JsonNaming(PropertyNamingStrategy.SnakeCaseStrategy.class) to any request body that has @RequestBody.
![image]

## Context (Impact of the Bug)
The fields in the documentation are incorrect.

**Comment by shalousun** [comment]
@kzxuan Welcome to submit PRs. For contributions via PR, please refer to https://smart-doc-group.github.io/#/zh-cn/community/contributing.
