### ISSUE TITLE
After version 2.4.8, the generated MD files have incorrect line breaks in the parameter list.

### ISSUE THREAD

**Issue by woooyeee** [TongchengOpenSource/smart-doc#352]
## Your Environment (Your Usage Environment)
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin): 2.4.8 ~ 2.5.3
* build tool version (maven or gradle): maven

## Expected Behavior (Expected Outcome)
Using version 2.4.8
![image]

## Current Behavior (Current Result)
After upgrading, the parameter lists for requests and responses have line break issues.
![image]

## Steps to Reproduce (Steps to Generate the Bug, please provide code examples if possible)
Interface definition
![image]

IDEA line break setting
![image]

smart-doc.json
```
{
  "serverUrl": "",
  "isStrict": false,
  "allInOne": true,
  "showAuthor": true,
  "coverOld": true,
  "pathPrefix": "/api",
  "inlineEnum": true,
  "recursionLimit": 3,
  "packageFilters": "com.xxx.api.*",
  "outPath": "src/main/resources/static/doc",
  "projectName": "Server Name"
}
```

**Comment by shalousun** [comment]
same issue https://github.com/smart-doc-group/smart-doc-maven-plugin/issues/17

**Comment by psuvjd** [comment]
Which version of smart-doc-maven-plugin is the fix available in? (Upgrading to which version can resolve this issue?)

**Comment by shalousun** [comment]
> Which version of smart-doc-maven-plugin is the fix available in? (Upgrading to which version can resolve this issue?)
next version 2.5.4

**Comment by psuvjd** [comment]
ok
