### ISSUE TITLE
Can the Maven plugin consider supporting the ability to pass parameters such as appToken through the command line?

### ISSUE THREAD

**Issue by folochina** [TongchengOpenSource/smart-doc#354]
## Summary (Description of this PR)
Currently, multi-environment is managed through multiple modules, and deployments are made using Jenkins. The goal is to compile for different environments and specify which module to push to.
Could the Maven plugin be considered to support passing several parameters such as appToken via the command line to achieve this?

### Basic example (Use case for the PR)
Running `mvn smart-doc:torna-rest -DtornaToken=xxxxx` could push the documentation to the specified appToken module. Command line arguments would override the appToken in the plugin's configuration JSON file.

### Motivation (Purpose of this PR)
Different code branches need to push to different torna modules.

**Comment by shalousun** [comment]
@folochina You can submit a PR to https://github.com/smart-doc-group/smart-doc-maven-plugin. I've been quite busy lately, so contributions to the community are welcome.

https://smart-doc-group.github.io/#/zh-cn/community/contributing

**Comment by netdied** [comment]
Fix
[Pull the plugin code from here](https://github.com/smart-doc-group/smart-doc-maven-plugin)
Repackage and use it, or wait for the new version to be released.
