### ISSUE TITLE
Quick start: In the smart-doc-maven-plugin, entering html in the goal configuration item results in an error.

### ISSUE THREAD

**Issue by whiteS18** [TongchengOpenSource/smart-doc#368]
## Your Environment
JDK 1.8
Using the Maven plugin:
```
<plugin>
    <!-- https://mvnrepository.com/artifact/com.github.shalousun/smart-doc-maven-plugin -->
    <groupId>com.github.shalousun</groupId>
    <artifactId>smart-doc-maven-plugin</artifactId>
    <version>2.5.3</version>
    <configuration>
        <!-- Specify the configuration file used for generating documentation, place the configuration file in your own project -->
        <configFile>./src/main/resources/smart-doc.json</configFile>
    </configuration>
    <executions>
        <execution>
            <!-- If you don't need to start smart-doc when compiling, comment out the phase -->
            <phase>compile</phase>
            <goals>
                <goal>html</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```
## Expected Behavior

Compilation should proceed normally.

## Current Behavior

![Image](https://user-images.githubusercontent.com/31566522/194683964-c2ebe0cb-c4f8-409d-bd99-706ba39d58dd.png)
![Image](https://user-images.githubusercontent.com/31566522/194683994-d72d475e-3755-4734-859d-58616ff75c15.png)

## Steps to Reproduce (Please provide test code if possible)

Copy the XML code section from the quick start of the document into the pom.xml in IDEA, and IDEA will prompt an error with the html inside
```
                        <goals>
                            <goal>html</goal>
                        </goals>
```
being highlighted in red. Double-clicking on the right side of the IDEA plugin will prompt the errors shown in the two screenshots above.

**Comment by shalousun** [comment]
@whiteS18 When using the plugin, configure the 'include' setting to load your own project code, especially for legacy projects like those with JSP dependencies that may not be manageable.
