### ISSUE TITLE
Generated HTML has an abnormal order.

### ISSUE THREAD

**Issue by mazaiting** [TongchengOpenSource/smart-doc#370]
## Mac 12.6 IDEA 2022.2

* smart-doc version: 2.4.0
* plugin version smart-doc-gradle-plugin: 2.4.0
* build tool version(maven or gradle): 7.4.1

## Expected Behavior
The generated HTML has a normal order of sorting.
生成的 html 中顺序排序正常

## Current Behavior(当前结果)
<img width="34" alt="image" src="https://user-images.githubusercontent.com/25228111/194714387-5dcfb754-56ec-4a77-886a-1e08279c5d1b.png">

## Possible Solution(bug解决建议)
Internal sorting is normal, external sorting is abnormal.
内部排序正常, 外部排序异常

**Comment by shalousun** [comment]
@mazaiting Please upgrade to the new version first.

**Comment by mazaiting** [comment]
> @mazaiting Please upgrade to the new version first.

I have upgraded to the latest version, but the problem still exists.

**Comment by shalousun** [comment]
> > @mazaiting Please upgrade to the new version first.
> 
> I have upgraded to the latest version, but the problem still exists.

Currently, it is unclear under what configurations and usage scenarios the disorder occurs. Of course, using the @order tag can lead to disorder. Due to its complexity, smart-doc will not optimize the @order tag in the future. For other reasons, you may need to debug and investigate on your own.

**Comment by shalousun** [comment]
fixed in 3.0.5
