### ISSUE TITLE
The RequestMapping annotation incorrectly parses the request method.

### ISSUE THREAD

**Issue by duanmourena** [TongchengOpenSource/smart-doc#372]
## Context(Bug影响描述)

When using
@RequestMapping(value = "/{id}", method = {RequestMethod.PUT, RequestMethod.PATCH})
the request method is parsed as a GET request. It should correctly be PUT/PATCH.

**Comment by shalousun** [comment]
> ## Context(Bug影响描述)
> When using
@RequestMapping(value = "/{id}", method = {RequestMethod.PUT, RequestMethod.PATCH})
the request method is parsed as a GET request. It should correctly be PUT/PATCH.

Smart-doc does not plan to support multiple method types. Please use the new annotation. The latest version 2.6.0 will not parse incorrectly, but it will only support one method type.
