### ISSUE TITLE
Error in parsing params within RequestMapping.

### ISSUE THREAD

**Issue by duanmourena** [TongchengOpenSource/smart-doc#374]
## Context(Bug影响描述)

For example, in RequestMapping where params include both key and value, the value is not displayed.
@PutMapping(value = "/ukey/{userId}", params = "$operation=bind")
The interface documentation only includes
![image](https://user-images.githubusercontent.com/57820171/195773358-f381ec0c-a4e1-4739-add7-089b0f823c6d.png)

The value "bind" should also be recorded.

**Comment by shalousun** [comment]
value will append behind in desc

**Comment by duanmourena** [comment]
Look at my screenshot; it is not included in the desc.
你看我的截图，并没有在desc里面
