### ISSUE TITLE
In the RPC Markdown documentation, the 'set' type is displayed as an array.

### ISSUE THREAD

**Issue by psuvjd** [TongchengOpenSource/smart-doc#377]
## Your Environment(您的使用环境)

* smart-doc version: 
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin): 2.6.0
* build tool version(maven or gradle): maven

## Expected Behavior(您期望的结果)

![image](https://user-images.githubusercontent.com/16028643/196082049-bc5f0431-71f3-4bba-b70d-8afe276b08be.png)

## Current Behavior(当前结果)

![image](https://user-images.githubusercontent.com/16028643/196082049-bc5f0431-71f3-4bba-b70d-8afe276b08be.png)

## Steps to Reproduce (Bug产生步骤，请尽量提供用例代码)

1.
2.
3.
4.

## Context(Bug影响描述)

If there is only an "array", those reading the documentation will not be able to clearly determine whether they should pass a set, list, collection, array, or some other type.
Moreover, if the generic within the set is an enumeration, it is advisable to retain the capability to indicate optional values of the enumeration in the description, facilitating understanding for the users of the interface about which enumeration values can be passed.

**Comment by shalousun** [comment]
@psuvjd The display of enumerations is controlled by configuration. You might want to look into 'inlineEnum'.

**Comment by psuvjd** [comment]
👌🏻

**Comment by psuvjd** [comment]
In version 2.6.0, after setting "inlineEnum": true, the Dubbo MD documentation only displays the name of the enumerations.
![image](https://user-images.githubusercontent.com/16028643/196579874-28b2699a-7a01-4692-9c8b-9111be16eb75.png)

Expectation: Display the properties of the enumeration (code/desc, etc.)
<img width="782" alt="image" src="https://user-images.githubusercontent.com/16028643/196580004-f23b032b-671e-4c16-9b70-ebe5accd799f.png">

**Comment by shalousun** [comment]
@netdied The type has been handled; now, please handle the enumeration.

**Comment by psuvjd** [comment]
<img width="1189" alt="image" src="https://user-images.githubusercontent.com/16028643/197484148-5d99e52a-0000-45cb-be88-b3a101be10e9.png">
In version 2.6.1, the displayed enumerations are not on separate lines.
