### ISSUE TITLE
Hope to support the new feature record.

### ISSUE THREAD

**Issue by tianguo82** [TongchengOpenSource/smart-doc#381]
In version 2.6.2, when the controller is defined as a record, the generated HTML cannot discover the interfaces. When an interface parameter is defined as a record, the generated HTML lacks field information corresponding to the record. Spring Boot 3 is about to release its official version, supporting JDK 17, and it is hoped that Smart-Doc will also receive support.
版本2.6.2，controller定义为record时生成的html无法发现接口，接口参数定义为record时，生成的html没有record对应字段信息。springboot3即将发布正式版，支持jdk17，希望smart-doc也能得到支持。

**Comment by shalousun** [comment]
@tianguo82 https://github.com/smart-doc-group/smart-doc/issues/288
