### ISSUE TITLE
It is recommended to expand the request path for Dubbo interfaces, not limiting it to 100 characters.

### ISSUE THREAD

**Issue by LongTengJava** [TongchengOpenSource/smart-doc#383]
## Summary(关于这个pr的描述)
Currently, the request path is limited to 100 characters, and if the method is slightly longer, it can no longer be customized for editing.
目前请求路径限制于100个字符，如果方法稍微长一点，就不能再自定义编辑

### Basic example(pr的用例)
RpcResult<List<GwPayTradeRecord>> queryAllTradeByOrderNo(GwPayContext payContext, GwPayTradeQueryRequest request)

### Motivation(提出这个pr目的)
I wanted to make custom modifications to the method, and after saving, it was not allowed to be overridden. However, because the method name exceeded the 100-character limit, it could not be saved.
想对方法自定义修改，保存后不允许再覆盖，但是因为方法名超出了100个字符限制，导致不能保存

**Comment by thc75** [comment]
Torna will be fixed in 1.18.1.

**Comment by LongTengJava** [comment]
您的邮件我已收到，我会尽快给您回复！
龙腾
