### ISSUE TITLE
How to incorporate JSON-RPC into Smart-Doc management.

### ISSUE THREAD

**Issue by sunstarsss** [TongchengOpenSource/smart-doc#384]
The company's project has added a set of JSON-RPC interfaces, which seem to be unable to be managed by Smart-Doc like the previous RESTful ones. Attempting to add an @Dubbo annotation and then comment it out did not take effect either.
公司的项目添加了一套json-rpc接口，似乎没法像之前的Restful一样用smart-doc管理起来，尝试添加一个@dubbo的注解再注释起来，也没有生效？

**Comment by shalousun** [comment]
@sunstarsss JSON-RPC and Dubbo are somewhat different, right? You could join the technical QQ group to discuss it further.

**Comment by sunstarsss** [comment]
来信已收到 谢谢

**Comment by sunstarsss** [comment]
来信已收到 谢谢
