### ISSUE TITLE
Support parsing special Map with key as enumeration type

### ISSUE THREAD

**Issue by timnick-snow** [TongchengOpenSource/smart-doc#387]
```java
    @GetMapping("/some/path")
    public CommonResult<Map<SomeEnum,SomeObject>> query() {
        return CommonResult.success();
    }
```
As shown above, data is a map, but both the key and value of this map are determined. The key is an enumeration, and its specific values can be obtained. The value is a POJO (Plain Old Java Object). Both their specific information can be obtained. For such a special map, it is possible to support parsing and displaying it in the document.

Some statistical interfaces often may have similar structural data. For example, statistical data under various statuses, where the key is the enumeration of these statuses, and the value is the statistical data entity.

Certainly, you can define the following class...

如上所示，data是个map，但是这个map的key和value都是确定的。key是一个枚举，其具体值可以获取到。value是一个pojo。都可以获取到它们的具体信息。  对于这种特殊的map，能否支持解析并显示在文档中。

一些统计性接口，通常可能有类似的结构数据。比如，各种状态下统计数据，那么key就是这个状态的枚举，value就是统计数据实体。
当然可以定义如下的类
```java
    public static class StatisticObj{
        private SomeObject status1;
        private SomeObject status2;
        private SomeObject status3;
        // ...
    }
```
If this special type of map could be directly parsed, then the aforementioned definition would not be necessary.
如果能直接解析这种特殊的map，那么就无需上述定义了

**Comment by shalousun** [comment]
@timnick-snow Pull requests (PRs) are welcome, as the smart-doc community actively encourages contributions from its members for collaborative development. For guidelines on how to submit a PR, please refer to the requirements here: https://smart-doc-group.github.io/#/zh-cn/community/contributing?id=smart-doc%e5%bc%80%e6%ba%90%e5%8f%82%e4%b8%8e%e8%a6%81%e6%b1%82

可以提pr，目前smart-doc大量鼓励社区提pr一起共建，pr可以参照要求https://smart-doc-group.github.io/#/zh-cn/community/contributing?id=smart-doc%e5%bc%80%e6%ba%90%e5%8f%82%e4%b8%8e%e8%a6%81%e6%b1%82
