### ISSUE TITLE
Multiple generics are not supported.

### ISSUE THREAD

**Issue by qq190329** [TongchengOpenSource/smart-doc#39]
When generating documentation for a structure like TestBean<Bean1, Bean2>, Bean2 is not correctly generated and will use the content of Bean1 instead.
TestBean<Bean1, Bean2> 这种的结构生成文档时，Bean2无法正确生成，会用Bean1的内容。

**Comment by netdied** [comment]
![image](https://user-images.githubusercontent.com/20217389/85939500-a1b50380-b948-11ea-9146-3e44a59f5690.png)
![image](https://user-images.githubusercontent.com/20217389/85939507-ada0c580-b948-11ea-98f1-1f82ee879748.png)
![image](https://user-images.githubusercontent.com/20217389/85939514-bc877800-b948-11ea-8d63-53c545fe3199.png)
Is that so? Can you provide a test case?
是这样么？能提供测试样例么？

**Comment by qq190329** [comment]
It's roughly like that. Why can't mine be generated correctly?
大概是这样，为什么我的就无法正确生成。
@Data
public class Result<T, O>  {

	/**
	 * 数据列表
	 */
	private List<T> rows;
	/**
	 * 总条数
	 */
	private int total;

	/**
	 * 其他信息
	 */
	private O other;
}
The structure generated in this way.
The documentation generated.

rows | array | 数据列表 | -
-- | -- | -- | --
└─userId | int64 | 用户id | -
└─userName | string | 账号 | -
└─num | int64 | 数量 | -
total | int32 | 总条数 | -
other | object | 其他信息 | -
└─userId | int64 | 用户id | -
└─userName | string | 账号 | -
└─num | int64 | 数量 | 
In the generated documentation, rows and other become the same.
生成的文档，rows和other变成一样

**Comment by qq190329** [comment]
/**
 * 数据列表
 */
private T rows;
Removing this list and changing it to private T rows;
will generate the correct documentation.

**Comment by netdied** [comment]
Fixed. You can pull the dev branch for testing.
已修复 可以拉取dev分支测试
