### ISSUE TITLE
Can the nesting of parameter beans be supported to set the number of recursive levels?

### ISSUE THREAD

**Issue by codersea** [TongchengOpenSource/smart-doc#390]
If the request parameter bean encounters circular nesting, such as:
In A.java there is a collection property:
List<B> ListB;

And in B.java there is also a collection property:
List<A> ListA;

This situation will generate documentation with many layers of recursion and repeated content. In reality, it is only desired to expand one layer and avoid infinite recursion. Could you consider supporting the setting of the desired number of expansion layers?

**Comment by shalousun** [comment]
@codersea https://smart-doc-group.github.io/#/zh-cn/diy/config?id=recursionlimit
