### ISSUE TITLE
Is smart-doc capable of incrementally pushing headquarters interfaces to torna?

### ISSUE THREAD

**Issue by GHASCZ** [TongchengOpenSource/smart-doc#399]
目前发现同步的时候，不仅仅是同步修改的接口，未修改的接口也会重新进行上传同步，目前有避免这种情况的手段吗？
Currently, during synchronization, not only the modified interfaces are synced, but also the unmodified ones are uploaded and synchronized again. Are there any measures available to prevent this situation?

**Comment by shalousun** [comment]
@GHASCZ The community will later support incremental change pushes based on git.

**Comment by shalousun** [comment]
Smart-doc 3.0.1 now supports incremental pushing of documents to torna.
