### ISSUE TITLE
The issue of excessively deep hierarchy in interface response parameters (ApiParam).

### ISSUE THREAD

**Issue by dai19470** [TongchengOpenSource/smart-doc#40]
When the hierarchy is too deep, there might be some issues with the response data from the API. It is recommended to convert ApiParam into a parent-child structure when generating the return parameters.
![image](https://user-images.githubusercontent.com/21135250/85945730-57487c80-b972-11ea-9dc0-09c1a686d33f.png)
![image](https://user-images.githubusercontent.com/21135250/85945758-76dfa500-b972-11ea-82a9-263fa79b2221.png)

**Comment by netdied** [comment]
The depth of recursion is too deep?

**Comment by netdied** [comment]
```
/**
 * Recursion limit
* @Since 1.8.8
* /
private int recursionLimit = 7;
```
The recursion depth can be set through apiConfig.setRecursionLimit.

**Comment by dai19470** [comment]
I'm using version 1.8.0 and it doesn't have this property. After looking at version 1.8.8, I understand. However, I still hope the official team can provide a parent-child structure. It would be better if the response data didn't use special symbols like "└─". Currently, all response data is placed in List<ApiParam> and uses "└─" to distinguish between parent and child structures, which is not a good experience. If a parent-child structure is used, it would be beneficial for secondary development. For example, when I define YapiJsonBuilder to generate Yapi's json file.

**Comment by shalousun** [comment]
@dai19470  The use of "└─" is because we want to directly display it in formats like HTML and Markdown. The original structure simplifies the front-end rendering, but for integrating with other systems, you'll need to handle the conversion yourself.

**Comment by shalousun** [comment]
@dai19470 An interface for fetching tree-structured API data has been added.

**Comment by dai19470** [comment]
@shalousun  Great, this makes the backend code more versatile. The frontend rendering can then extract from the parent-child structure as needed.
