### ISSUE TITLE
Can the `@ignoreParams` annotation be supported to ignore the display of parameters with `@RequestBody`?

### ISSUE THREAD

**Issue by wugui0823** [TongchengOpenSource/smart-doc#401]
![image](https://user-images.githubusercontent.com/16262592/209493254-127b26bc-8670-4573-b94c-9f8752a4aab0.png)

The input parameter object is shared across multiple methods, but some fields are invalid in individual methods. The `@ignoreParams` annotation is used to ignore these fields, yet the generated documentation still includes them. Therefore, can `@ignoreParams` support ignoring the display of parameters with `@RequestBody`?
入参对象是多个方法共用，但有些字段在个别法是无效的，用了@ignoreParams进行字段忽略，但是生成的文档还是存在，所以`@ignoreParams`能否支持对`@RequestBody`的参数进行忽略展示

**Comment by shalousun** [comment]
@wugui0823 The @ignoreParams tag does not have this function and will not be supported. You could try group validation or creating a new structure separately; group validation might be more complex. It is recommended to create a new structure. These approaches have their pros and cons; you need to weigh them yourself. Sometimes trying to take a shortcut might actually introduce complexity.
ignoreParams这个tag没有这个功能，也不会支持，这种可以尝试分组校验，或者是单独新建个结构体，分组校验可能会复杂一点。建议还是建个新结构体。这些东西都是有利有弊，自己权衡，有时候想偷个懒，但是可能也带来了复杂度

**Comment by wugui0823** [comment]
Received, thank you.
收到，谢谢

**Comment by LeoCao0707** [comment]
@shalousun 你好，我是第一次用，为什么文档上又提供这样的例子呢？
![2023-10-13_20-08](https://github.com/TongchengOpenSource/smart-doc/assets/37643156/78b8cc6f-2233-4c09-8dd2-b6bf7b058388)
