### ISSUE TITLE
Whether it is possible to extract record annotations

### ISSUE THREAD

**Issue by ouyangshuang** [TongchengOpenSource/smart-doc#404]
/**
 * 
 * @param createTime 创建时间
 * @param updateTime 修改时间
 */
public record Test(LocalDateTime createTime, LocalDateTime updateTime) {
}

**Comment by shalousun** [comment]
@ouyangshuang  Sure, you can check out this issue paul-hammant/qdox#107. Of course, if you have time, you can also try to fix and support it. The main issue is with qdox, we reported the issue but didn't have time to research it. Actually, in engineering practice, 'record' is not a good design for Java; when there are many parameters, it becomes confusing even for ourselves. After adding some validation annotations to the input parameters, it no longer looks as clean as POJO (Plain Old Java Object). The biggest problem with POJOs is actually the getter and setter methods. Aside from that, the structure of POJOs is similar to structs in many other languages.

**Comment by bingo084** [comment]
最近qdox似乎支持了record paul-hammant/qdox#191

**Comment by bingo084** [comment]
> @ouyangshuang Sure, you can check out this issue paul-hammant/qdox#107. Of course, if you have time, you can also try to fix and support it. The main issue is with qdox, we reported the issue but didn't have time to research it. Actually, in engineering practice, 'record' is not a good design for Java; when there are many parameters, it becomes confusing even for ourselves. After adding some validation annotations to the input parameters, it no longer looks as clean as POJO (Plain Old Java Object). The biggest problem with POJOs is actually the getter and setter methods. Aside from that, the structure of POJOs is similar to structs in many other languages.

Recently, qdox seems to have added support for records, as indicated by paul-hammant/qdox#191.
