### ISSUE TITLE
import java.util.* results in an inability to resolve the content of collection-type member variables.

### ISSUE THREAD

**Issue by GuoHaoZai** [TongchengOpenSource/smart-doc#405]
## Your Environment(您的使用环境)

* smart-doc version: 2.6.3
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin):  2.6.3
* build tool version(maven or gradle): gradle:6.9

## Expected Behavior(您期望的结果)
It is capable of parsing the correct schema.
能够解析出正确的schema

<img width="636" alt="image" src="https://user-images.githubusercontent.com/44019619/210192252-d7046329-82e2-4656-a615-0d0e9bd0b9ad.png">

## Current Behavior(当前结果)
Due to import java.util.*; it is not possible to resolve collection type fields in DTOs. This results in schema parsing errors.
由于import java.util.*; 导致解析不到DTO中的集合类型字段。schema解析错误

<img width="391" alt="image" src="https://user-images.githubusercontent.com/44019619/210192068-63ae36b3-e7ba-4aa2-93c2-13c66e85722e.png">

## Possible Solution(bug解决建议)
Annotations can be extracted by parsing the compiled source code package. This is because jar packages separate the import xxx.*; statements.
可以通过解析编译后的源代码包来提取注释。因为jar包中会把import xxx.*拆开。

## Steps to Reproduce (Bug产生步骤，请尽量提供用例代码)

```java
@RestController
@RequestMapping("test-controller")
public class TestController {
    @GetMapping("/test")
    public TestDTO test() {
        return new TestDTO();
    }
}
```

```java
import lombok.Data;

import java.util.*; // 重点

@Data
public class TestDTO {
    
    public List<DemoDTO> demos;
    
    @Data
    public static class DemoDTO {
        private Long id;
        private String name;
    }
}
```

## Context(Bug影响描述)
All classes imported via import xxx.*; are unable to resolve their member variables.
所有通过import xxx.*导入的类都无法解析到成员变量

**Comment by shalousun** [comment]
@GuoHaoZai Is this using smart-doc's Swagger or OpenAPI?

**Comment by GuoHaoZai** [comment]
openapi



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年1月3日(周二) 凌晨0:21
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [smart-doc-group/smart-doc] import java.util.*导致解析不到集合类型的成员变量内容 (Issue #405)




 
@GuoHaoZai 这是用smart-doc的swagger还是openapi？

**Comment by GuoHaoZai** [comment]
> 

case中用的openapi，swagger也会有问题

**Comment by GuoHaoZai** [comment]
> @GuoHaoZai Is this using smart-doc's Swagger or OpenAPI?

The case uses OpenAPI, but there would also be issues with Swagger.

**Comment by shalousun** [comment]
@GuoHaoZai I seem to be unable to reproduce it.

**Comment by netdied** [comment]
Following your instructions, I cannot reproduce the issue with import java.util.*; you can join our group or provide a specific demo on GitHub.
按照你说的 import java.util.* 没法儿复现这个问题  可以加群 或者github上提供一下具体的demo

**Comment by GuoHaoZai** [comment]
Normal case.
```java

import lombok.Data;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.List;

/**
 * aaa
 */
@RestController
@RequestMapping("test-controller")
public class TestController3 {
    @GetMapping("/test")
    public TestDTO test() {
        return new TestDTO();
    }

    @Data
    public static class TestDTO {

        public List<DemoDTO> demos;

        @Data
        public static class DemoDTO {
            private Long id;
            private String name;
        }
    }
}

```

Exceptional case.

```java

import lombok.Data;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.*;

/**
 * aaa
 */
@RestController
@RequestMapping("test-controller")
public class TestController3 {
    @GetMapping("/test")
    public TestDTO test() {
        return new TestDTO();
    }

    @Data
    public static class TestDTO {

        public List<DemoDTO> demos;

        @Data
        public static class DemoDTO {
            private Long id;
            private String name;
        }
    }
}

```

**Comment by shalousun** [comment]
@GuoHaoZai We copied your code into the smart-doc project but still could not reproduce the issue. Please provide a demo project that can reproduce the problem.
