### ISSUE TITLE
The errorCodeDictionaries enumeration class does not exist; getter method results in an error.

### ISSUE THREAD

**Issue by Ikki-Dai** [TongchengOpenSource/smart-doc#408]
## Your Environment(您的使用环境)

* smart-doc version: latest
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin): 2.6.3
* build tool version(maven or gradle): maven

## Expected Behavior(您期望的结果)

errorCodeDictionaries: [{
  "title": "http code",
  "enumClassName": "org.springframework.http.HttpStatus",
  "codeField": "value",
  "descField": "reasonPhrase"
}]

## Current Behavior(当前结果)

java.lang.NoSuchMethodException: org.springframework.http.HttpStatus.getValue()

## Possible Solution(bug解决建议)

Enums may not have getter methods corresponding to their fields.
Enum 可能不存在字段对应的 getter 方法

## Steps to Reproduce (Bug产生步骤，请尽量提供用例代码)

1.
2.
3.
4.

## Context(Bug影响描述)

When designing an interface using RESTful,
it is not possible to use Spring HTTP status as the response code for outputting documentation.

**Comment by Ikki-Dai** [comment]
Configuring the internal enumeration `org.eclipse.jetty.http.HttpStatus.Code` also fails to resolve: `ClassNotFoundException` is thrown.
配置 org.eclipse.jetty.http.HttpStatus.Code 内部枚举，也无法解析：`ClassNotFoundException`

**Comment by netdied** [comment]
Business enumerations are generally defined by oneself, aren't they? What scenarios require the use of the HttpStatus enumeration class? Here, enumeration values are obtained through the reflection of getter methods; if a getter method cannot be found, the enumeration class cannot be parsed.
业务枚举一般不是自己定义嘛？是什么场景需要使用HttpStatus枚举类呢？这里是通过反射getter方法获取枚举值，如果找不到getter方法都无法对枚举类进行解析。

**Comment by Ikki-Dai** [comment]
The API is designed according to standard RESTful principles, using HTTP status.
API 按照标准restful 设计的，使用的http status

**Comment by shalousun** [comment]
@Ikki-Dai Upon reviewing the code, it seems that the issue actually stems from the Spring source code; some fields have getters added while others do not, resulting in an inconsistent style.

**Comment by Ikki-Dai** [comment]
Let's see if we can support parsing methods for codeField and descField; if they end with () then execute the corresponding method.
看看能不能把 `codeField` 和 `descField` 支持解析方法，如果是`()` 结尾就执行对应的方法

**Comment by shalousun** [comment]
> Let's see if we can support parsing methods for codeField and descField; if they end with () then execute the corresponding method.
看看能不能把 `codeField` 和 `descField` 支持解析方法，如果是`()` 结尾就执行对应的方法

This can also be the configuration with the least changes.
可以这个也是配置改变最小的了
