### ISSUE TITLE
The configurations for customResponseFields/customRequestFields are not taking effect.

### ISSUE THREAD

**Issue by xpp011** [TongchengOpenSource/smart-doc#409]
## Your Environment(您的使用环境)

* smart-doc version: 2.6.3
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin):2.6.3
* build tool version(maven or gradle):maven 3.8.6

## Expected Behavior(您期望的结果)
![image](https://user-images.githubusercontent.com/72737308/211583070-bb6dc982-92fb-4640-b64b-be9b5918b50d.png)

![image](https://user-images.githubusercontent.com/72737308/211583017-fcdc3b0f-bfcf-4591-ad15-2dbf8d6323ac.png)

## Current Behavior(当前结果)
![image](https://user-images.githubusercontent.com/72737308/211583357-f97f3954-4238-4061-a04d-eed3f94aaab1.png)

## Possible Solution(bug解决建议)
https://github.com/smart-doc-group/smart-doc/blob/03071a01975860388426342cdf380ed534121945/src/main/java/com/power/doc/helper/ParamsBuildHelper.java#L189
https://github.com/smart-doc-group/smart-doc/blob/03071a01975860388426342cdf380ed534121945/src/main/java/com/power/doc/helper/ParamsBuildHelper.java#L194
The key generation strategy for responseFieldMap and getCustomReqFieldMap is `ownerClassName + "." + name`. Here, using the `CustomField.nameEquals()` method with fieldName will not match.
responseFieldMap和getCustomReqFieldMap的key的生成策略是`ownerClassName + "." + name`，这里通过`CustomField.nameEquals()`方法使用fieldName是匹配不到的。

The matching in the JsonBuildHelper class should be fine.
JsonBuildHelper类的匹配应该是没问题的

https://github.com/smart-doc-group/smart-doc/blob/03071a01975860388426342cdf380ed534121945/src/main/java/com/power/doc/helper/JsonBuildHelper.java#L293

**Comment by shalousun** [comment]
@xpp011 It is suggested to refer to the open-source contribution instructions and then directly submit a pull request. https://smart-doc-group.github.io/#/zh-cn/community/contributing

**Comment by xpp011** [comment]
@shalousun Pull request has been submitted.[PR](https://github.com/smart-doc-group/smart-doc/pull/412)
