### ISSUE TITLE
Field duplication: the new version of Page still has this issue.

### ISSUE THREAD

**Issue by liangbaika** [TongchengOpenSource/smart-doc#41]
![image](https://user-images.githubusercontent.com/33059022/86085186-19159f00-bad1-11ea-8c7b-36057bdb35af.png)

**Comment by shalousun** [comment]
We have conducted mybatis-plus page tests on the official test case demo, and the latest version cannot reproduce your problem. You can run the demo's document generation to see the effect;
https://github.com/shalousun/api-doc-test/blob/master/src/main/java/com/power/doc/controller/MybatisPlusPageController.java
If there is a discrepancy between the use case and your usage, please provide your use case code for our testing.
