### ISSUE TITLE
When the method returns a collection, the related contentData object is not marked as the related content in the ApiAllData object is not marked as an array return

### ISSUE THREAD

**Issue by doufather** [TongchengOpenSource/smart-doc#415]
Versions 2.6 and above will not indicate that the method returns an array object, while version 2.5 is normal.
2.5版本正常，2.6以上会报错
![array](https://user-images.githubusercontent.com/14035923/215698148-cb521075-4201-455f-aa99-584e4ce89b74.png)

**Comment by shalousun** [comment]
@doufather Welcome to submit PR. https://github.com/smart-doc-group/smart-doc/issues/416

**Comment by shalousun** [comment]
fix #439
