### ISSUE TITLE
When generating interface documentation for a multi-module project, an error occurs: Symbol not found.

### ISSUE THREAD

**Issue by git-code-for-me** [TongchengOpenSource/smart-doc#420]
## Your Environment(您的使用环境)

* smart-doc version: smart-doc-maven-plugin:2.4.9
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin):
* build tool version(maven or gradle):

## Expected Behavior(您期望的结果)
Generate the documentation normally.

## Current Behavior(当前结果)
Error: The web module cannot recognize references to other modules, such as the declaration of entity in controller. An error occurs during packaging: Symbol not found (package not found).

## Steps to Reproduce (Bug产生步骤，请尽量提供用例代码)

1.
2.
3.
4.

**Comment by shalousun** [comment]
@git-code-for-me https://smart-doc-group.github.io/#/zh-cn/plugins/maven_plugin?id=maven%e5%a4%9a%e6%a8%a1%e5%9d%97%e4%b8%ad%e4%bd%bf%e7%94%a8%e6%8f%92%e4%bb%b6

**Comment by git-code-for-me** [comment]
> @git-code-for-me https://smart-doc-group.github.io/#/zh-cn/plugins/maven_plugin?id=maven%e5%a4%9a%e6%a8%a1%e5%9d%97%e4%b8%ad%e4%bd%bf%e7%94%a8%e6%8f%92%e4%bb%b6

Thanks
