### ISSUE TITLE
I hope to support array type in the return value.

### ISSUE THREAD

**Issue by sunxue299** [TongchengOpenSource/smart-doc#421]
### Motivation(提出这个pr目的)
For example, if I want to return an array of enums, at this point I do not wish to use a List to return the data; instead, I prefer to use an array like State[].
I noticed that the current version 2.4.9 does not support this method. If it returns an array [], its result is type='object' rather than type='array', which leads to the final display being in a non-array format.

It is hoped that support for returning arrays can be included in the new version.
比如我要返回一个枚举的数组，这时我不想使用List返回数据，而是想用State[] 数组这种方式。
我发现目前2.4.9版本不支持该方式，如果返回数组[] 它的结果是type='object'而不是type='array'，导致最后是以非数组的方式显示的。

希望能够在新版中支持数组的返回

**Comment by shalousun** [comment]
@sunxue299 Have you tried the latest version? The one you are using is quite outdated. It would be best to provide a code snippet that completes a test case.
最新的版本有试过吗，你这个版本已经比较落后了 ，最好提供一个完成测试用例代码片段

**Comment by sunxue299** [comment]
@shalousun I tested with the latest version, 2.6.4:
I conducted two tests on the same interface, respectively returning data in array structure for the first test and List structure for the second test.
The JSON results and descriptions returned by smart-doc are shown in the screenshots that follow:
我使用最新版2.6.4测试：
对同一个接口进行2次测试，分别为：第一次返回的数据中为数组结构，第二次返回的数据为List结构。
smart-doc返回的json结果及描述在我后面的截图中：
![1](https://user-images.githubusercontent.com/46645260/218241170-bd81b13a-2939-44d6-be8d-76c4c8a9e6d3.jpg)
![2](https://user-images.githubusercontent.com/46645260/218241185-c5edb632-70af-43ee-91fa-d0ea037f8ecc.jpg)
![3](https://user-images.githubusercontent.com/46645260/218241191-ab0b54b4-e19d-4596-b840-ca21ddae9d0e.jpg)
![5](https://user-images.githubusercontent.com/46645260/218241193-e0acffe4-1334-4eb7-9101-e764c4010fba.jpg)
![4](https://user-images.githubusercontent.com/46645260/218241197-8f984cf6-96b2-4e54-b2bc-6b1e13de7b93.jpg)

**Comment by shalousun** [comment]
[#429](https://github.com/smart-doc-group/smart-doc/issues/429)
