### ISSUE TITLE
SpringBoot Get Content-Type From RequestMapping.

### ISSUE THREAD

**Issue by LoopOuroboros** [TongchengOpenSource/smart-doc#424]
## Your Environment(您的使用环境)

* smart-doc version: 2.6.4
* plugin version (smart-doc-maven-plugin): 2.6.4
* build tool version(maven or gradle): 3.8.5

## Expected Behavior(您期望的结果)
The code part is translated into English.
```java
     /**
     * POST Content String Test
     *
     * @param str Input content
     * @return return input content
     */
    @PostMapping(value = "str", consumes = MediaType.TEXT_PLAIN_VALUE, produces = MediaType.TEXT_PLAIN_VALUE)
    public String postBodyStr(@RequestBody String str) {
        return str;
    }
```
Generate a partial screenshot of Smart-Doc.
![image](https://user-images.githubusercontent.com/36392404/217789851-1cb75a51-286b-4ec9-aa99-652c391d2778.png)

Actual request method Postman screenshot.
![image](https://user-images.githubusercontent.com/36392404/217790395-76e9c8b4-7930-4f4a-95a1-9152e82c816d.png)
It should be a Postman request body with Content-Type = text/plain.
应该是Postman这种请求体，Content-Type = text/plain

## Current Behavior(当前结果)
Writing method 1.
```java
     /**
     * POST Content String Test
     *
     * @param str Input content
     * @return return input content
     */
    @PostMapping("str")
    public String postBodyStr(@RequestBody String str) {
        return str;
    }
```
![image](https://user-images.githubusercontent.com/36392404/217792935-de683852-e5a4-46e9-9151-f59748a55826.png)

Writing method 2.
```java
      /**
     * POST Content String Test
     *
     * @param str Input content
     * @return return input content
     */
    @PostMapping(value = "str", consumes = MediaType.TEXT_PLAIN_VALUE, produces = MediaType.TEXT_PLAIN_VALUE)
    public String postBodyStr(@RequestBody String str) {
        return str;
    }
```
![image](https://user-images.githubusercontent.com/36392404/217794314-6fc9f892-8df5-440e-a3bb-e01786204d61.png)

## Possible Solution(bug解决建议)

SpringMVCRequestMappingHandler
```java
           Object produces = annotation.getNamedParameter(mappingAnnotation.getProducesProp());
            if (Objects.nonNull(produces)) {
                mediaType = produces.toString();
            }
```
The `Content-Type` is obtained through the consumes attribute of the Spring annotation RequestMapping, and produces corresponds to the Accept header in the request.
It is recommended to add parameter parsing for RequestMapping:
params can obtain fixed request parameters
headers obtain default request header settings
consumes obtains Content-Type
produces obtains Accept

## Steps to Reproduce (Bug产生步骤，请尽量提供用例代码)

1.
2.
3.
4.

**Comment by shalousun** [comment]
@MagakiReimu The Content-Type being JSON is correct; the issue might be with the data pushed by smart-doc, or it could be a problem with the example generated by torna.

**Comment by LoopOuroboros** [comment]
This is a JSON file directly generated by smart-doc:openapi.
![image](https://user-images.githubusercontent.com/36392404/217806605-87eb22af-5348-40fc-b0dc-5e8123aac956.png)
The Content-Type here should not be application/json; it should be text/plain.
When the type after @RequestBody is String, the Content-Type should not be fixed to application/json.
It is best to obtain it from the consumes attribute of @RequestMapping.
This would also resolve issue #369.

**Comment by shalousun** [comment]
Using JSON to send does not present an issue; the main error is that in this case, it inherently lacks a field. This was altered in later versions by other pull requests, as earlier versions did not have fields under such circumstances.
这个用json发并不存在问题，主要的错误是这种情况它本省就没有字段，这个后来其他pr改出了问题，以前较早的版本这种情况是没有字段的
