### ISSUE TITLE
The official documentation of smart-doc shows duplicated configurations.

### ISSUE THREAD

**Issue by PolarishT** [TongchengOpenSource/smart-doc#426]
## Your Environment(您的使用环境)
dev

* smart-doc version:
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin):
* build tool version(maven or gradle):

## Steps to Reproduce (Bug产生步骤，请尽量提供用例代码)

1.
2.
3.
4.

## Context(Bug影响描述)

![image](https://user-images.githubusercontent.com/72297937/218238668-fe4b3409-5c0d-44fb-acc3-de934e23107f.png)

**Comment by shalousun** [comment]
@AllianceTing You can refer to the PR requirements to submit a pull request for fixing it.
