### ISSUE TITLE
If the result returned by @ResponseBody contains an array type field, it will not be displayed as an array.

### ISSUE THREAD

**Issue by sunxue299** [TongchengOpenSource/smart-doc#429]
## Your Environment(您的使用环境)

* smart-doc version: 2.6.4
* plugin version ( smart-doc-maven-plugin ):  2.6.4
* build tool version(maven ): 3.5

## Expected Behavior(您期望的结果)
{
  "type":"array"
}

## Current Behavior(当前结果)
{
  "type":"object"
}

## Steps to Reproduce (Bug产生步骤，请尽量提供用例代码)
The same interface was tested twice: the first time, the returned data was in an array structure; the second time, the returned data was in a List structure.
The JSON results and descriptions returned by smart-doc are shown in the screenshots that follow:

对同一个接口进行2次测试，分别为：第一次返回的数据中为数组结构，第二次返回的数据为List结构。
smart-doc返回的json结果及描述在我后面的截图中：
![image](https://user-images.githubusercontent.com/46645260/219604053-b99c89c0-08f2-498b-b012-1be999bedeae.png)
![image](https://user-images.githubusercontent.com/46645260/218241185-c5edb632-70af-43ee-91fa-d0ea037f8ecc.jpg)
![image](https://user-images.githubusercontent.com/46645260/218241191-ab0b54b4-e19d-4596-b840-ca21ddae9d0e.jpg)
![image](https://user-images.githubusercontent.com/46645260/218241193-e0acffe4-1334-4eb7-9101-e764c4010fba.jpg)
![image](https://user-images.githubusercontent.com/46645260/218241197-8f984cf6-96b2-4e54-b2bc-6b1e13de7b93.jpg)

**Comment by shalousun** [comment]
https://github.com/smart-doc-group/smart-doc/issues/429
