### ISSUE TITLE
When there are no comments for the controller and method, can their names be used for display?

### ISSUE THREAD

**Issue by yuanli** [TongchengOpenSource/smart-doc#432]
Under the current circumstances, for controllers and methods without comments, the generated HTML document displays as follows:
当前情况下，对于没有注释的controller和method，最终生成的html文档显示如下：
![image](https://user-images.githubusercontent.com/1327080/220807222-881da009-be9b-487b-ad39-5c77f2c4029f.png)

The corresponding controller and request names on the left side are blank, making it impossible to distinguish the corresponding content when viewing the document.
It is hoped that in the absence of comments, the class name and function name can be used as the default display.
左侧对应的controller和request名称为空，查看文档时无法区分对应的内容。
希望在没有注释的情况下使用类名、函数名做默认的展示。

**Comment by shalousun** [comment]
@yuanli This is something you can supplement yourself with comments. Not providing them isn't that it cannot be done, but rather the philosophy of smart-doc is to require comments from the source to improve the quality of research and development documentation.
