### ISSUE TITLE
In debug mode, can it support customizing the IP and port to access the service on the page?

### ISSUE THREAD

**Issue by Cmy-art** [TongchengOpenSource/smart-doc#435]
## Summary(关于这个pr的描述)

In debug mode, can it support customizing the IP and port to access the service on the page?

### Basic example(pr的用例)

![image](https://user-images.githubusercontent.com/54198439/221070361-3db8a868-7ec9-49cb-a9d4-9e0a1adab285.png)

### Motivation(提出这个pr目的)
This facilitates debugging.

**Comment by shalousun** [comment]
@Cmy-art 
You can use a tool like torna to push the interfaces, which supports multiple environments. Switching server addresses within an HTML file is not as efficient as generating and importing into Postman.
可以去使用torna这种，把接口往torna推送，支持多环境，这种在一个html中换服务器地址还不如生成导入postman

**Comment by Cmy-art** [comment]
Okay, thank you very much.
