### ISSUE TITLE
I hope to enhance the capability of recognizing custom interface annotations.

### ISSUE THREAD

**Issue by lbhfuture** [TongchengOpenSource/smart-doc#446]
## Summary(关于这个pr的描述)
Based on my actual testing, Smart-Doc can only scan Spring's `@Controller` and  `@RequestMapping` (and their derivatives). Would it be possible to add the functionality of custom annotations in the configuration file, such as `@RestfulController` and `@RestfulMethod`, and then generate interface documentation based on these custom annotations?
根据我的实际测试，smart-doc 只能扫描 Spring 的 @Controller、@RequestMapping（以及他们的衍生类），能否在配置文件中增加自定义注解功能，比如 @RestfulController、@RestfulMethod ，然后可以根据这些自定义注解生成接口文档。

### Motivation(提出这个pr目的)
In actual business development, the basic framework generally uses custom annotations instead of Spring's to implement specific functions. I hope that smart-doc can add support for custom annotations.
实际业务开发中，基础框架一般会使用自定义注解，而不是使用 Spring 的，以便实现特定的功能，希望 smart-doc 能够增加对自定义注解的支持。

**Comment by shalousun** [comment]
@lbhfuture Parsing custom annotations is not very realistic; annotations come in various forms, and smart-doc currently supports a few common community frameworks without finding any commonalities. The forms of enterprise custom annotations are even more diverse. From an open-source perspective, your own approach is just one among many, as there are numerous different practices. Therefore, it would be sufficient for you to maintain the open-source project internally for your own company's use.
自定义注解解析这个不太现实，注解形式比较多样，smart-doc目前支持几个常用社区框架上也没找到什么共同点。企业自定义注解的形式更多，站在开源角度讲你们自己也仅仅是其中一种，还有很多不同的做法。因此你们自己基于开源二次维护到公司内部自己用就可以了

**Comment by lbhfuture** [comment]
Okay, thank you.
