### ISSUE TITLE
Unable to retrieve comments for fields in request classes of multi-module interfaces.

### ISSUE THREAD

**Issue by Yoka416** [TongchengOpenSource/smart-doc#448]
## Your Environment(您的使用环境)
maven

Project module structure:

├─parent
├──A
├──---A.1
│        pom.xml
├──---A.2(web接口层)
│        pom.xml
│ pom.xml
├──B
├──C（实体类）
├──D
├──---D.1
├──---D.2
│ pom.xml
└─pom.xml

* smart-doc version:2.2.1
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin):
* build tool version(maven or gradle):maven --3.8.6

## Expected Behavior(您期望的结果)
Entity class parameters can be scanned for comments, and this entity class is located in another module.
实体类入参能够扫描到注释，该实体类在另一个模块中

## Current Behavior(当前结果)
Entity class parameters cannot scan the comments of class fields.
实体类入参无法扫描到类字段的注释

Attempt:
Refer to the multi-module case study -- spring-boot-maven-multiple-module, modify naming and configuration file locations, unsuccessful.
Adding plugins was also unsuccessful.<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-source-plugin</artifactId>
				<version>2.2.1</version>
				<executions>
					<execution>
						<id>attach-sources</id>
						<goals>
							<goal>jar-no-fork</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
However, the generated classes folder includes a smart-doc.json file.
<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-javadoc-plugin</artifactId>
				<version>3.4.0</version>
			</plugin>
Unsuccessful.

**Comment by shalousun** [comment]
@Yoka416 It is recommended to first upgrade, and also to ascertain whether Maven strictly follows a parent-child traceable structure. If there are multiple directories constructed, but the relationships are disconnected, it will not be possible to locate the relationships for loading the source code; Maven plugins strictly utilize Maven's API for searching. Another suggestion is that if referencing `spring-boot-maven-multiple-module` does not resolve the issue, consider submitting a demo project that can reproduce this issue with a complete Maven setup, or fork `spring-boot-maven-multiple-module` and submit a pull request that can reproduce the issue.

**Comment by Yoka416** [comment]
> 
After upgrading, comments were successfully retrieved. Now there are two issues:
1. Some of our request classes depend on external base classes, but we do not want to display the fields of the external base classes in the interface documentation's parameters; we only want to show the fields of the inherited request class. Can this be resolved?
2. A single request class serves as the input parameter for multiple interfaces, but within this request class, some fields are mandatory for the first interface, while others are mandatory for the second interface. What should be done when there is a conflict regarding the mandatory nature of fields within the same request class?
升级之后成功获取注释了。现在有个两个问题就是：
1、我们有些请求类依赖外部的基类，但是在接口文档的入参中不想显示外部依赖的基类字段，只显示继承的请求类的字段，这个可以解决么？
2、一个请求类是多个接口的请求入参，但是这个请求类中有些字段是第一个接口的必填，有些字段是第二个接口的必填。当出现同一个请求类有字段必填与否冲突了怎么办

**Comment by Yoka416** [comment]
> > 
> 
> 升级之后成功获取注释了。现在有个两个问题就是： 1、我们有些请求类依赖外部的基类，但是在接口文档的入参中不想显示外部依赖的基类字段，只显示继承的请求类的字段，这个可以解决么？ 2、一个请求类是多个接口的请求入参，但是这个请求类中有些字段是第一个接口的必填，有些字段是第二个接口的必填。当出现同一个请求类有字段必填与否冲突了怎么办

谢谢大佬解答。

**Comment by netdied** [comment]
1. Use the ignoreRequestParams configuration. Refer to the configuration file: https://smart-doc-group.github.io/#/diy/config?id=ignorerequestparams
2. It is recommended to use different entities for each request, or perform grouped validation through JSR-303.
1. 使用ignoreRequestParams 配置 。参考配置文件:https://smart-doc-group.github.io/#/diy/config?id=ignorerequestparams
2. 建议每个请求用不同的实体，或者通过jsr303 分组校验。

**Comment by Yoka416** [comment]
>
1. Use the ignoreRequestParams configuration. Refer to the configuration file: https://smart-doc-group.github.io/#/diy/config?id=ignorerequestparams
2. It is recommended to use different entities for each request, or perform grouped validation through JSR-303.

 1. 使用ignoreRequestParams 配置 。参考配置文件:https://smart-doc-group.github.io/#/diy/config?id=ignorerequestparams
> 2. 建议每个请求用不同的实体，或者通过jsr303 分组校验。

Hello, is it not possible to ignore a request class that is based on a base? There are quite a few fields in the external base class dependencies that need to be ignored. Moreover, it seems that parameters inherited from external base classes cannot be ignored.
你好，第一个不能忽略一个基于base的请求类么？因为依赖的外部基类中要忽略的字段有点多。而且继承外部基类的参数好像忽略不了

**Comment by shalousun** [comment]
> > 1. Use the ignoreRequestParams configuration. Refer to the configuration file: https://smart-doc-group.github.io/#/diy/config?id=ignorerequestparams

2. It is recommended to use different entities for each request, or perform grouped validation through JSR-303.
1. 使用ignoreRequestParams 配置 。参考配置文件:https://smart-doc-group.github.io/#/diy/config?id=ignorerequestparams
> > 2. 建议每个请求用不同的实体，或者通过jsr303 分组校验。
> 
> Hello, is it not possible to ignore a request class that is based on a base? There are quite a few fields in the external base class dependencies that need to be ignored. Moreover, it seems that parameters inherited from external base classes cannot be ignored.
你好，第一个不能忽略一个基于base的请求类么？因为依赖的外部基类中要忽略的字段有点多。而且继承外部基类的参数好像忽略不了

Version 2.6.7 should be able to ignore the fields of a base class.
2.6.7应该可以忽略基类的字段了
