### ISSUE TITLE
JAX-RS, Content-Type became blank when using @Produces({})

### ISSUE THREAD

**Issue by ciera23** [TongchengOpenSource/smart-doc#450]
## Your Environment(您的使用环境)

* smart-doc version:2.6.5
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin): 2.6.5
* build tool version(maven or gradle):maven
* framework: JAX-RS

## Expected Behavior(您期望的结果)
Show Content-Type succesfully 

## Current Behavior(当前结果)
if use the following setting, the Content-Type will be blank
@Produces({"application/json"})

if use this, Content-Type will show successfully
@Produces("application/json")

## Steps to Reproduce (Bug产生步骤，请尽量提供用例代码)

1.
2.
3.
4.

**Comment by shalousun** [comment]
@ciera23 use Consumes in state of Produces for request contentType

**Comment by shalousun** [comment]
@ciera23 use Consumes in state of Produces for request contentType
