### ISSUE TITLE
Replace the actual return type with a custom type.

### ISSUE THREAD

**Issue by ooknight** [TongchengOpenSource/smart-doc#457]
I have used a unified return class to specially handle the paginated results.
我使用的统一返回类对分页的结果进行了特殊处理

``` java
@Data
@JsonInclude(JsonInclude.Include.NON_NULL)
public class Result<T> {

    private int code;
    private String message;
    private T data;
    private Long total;

    public static <T> Result<List<T>> success(org.springframework.data.domain.Page<T> data) {
        Result<List<T>> result = new Result<>();
        result.setCode(200);
        result.setMessage("success");
        result.setData(data.getContent());
        result.setTotal(data.getTotalElements());
        return result;
    }

}
```

Expectation（期望）
```json
{
  "code": 200,
  "message": "success",
  "data": [
      {
        "id": 251,
        "name": "angelena.corwin"
      }
  ],
  "total": 50
}
```

Actuality（实际）
```json
{
  "code": 200,
  "message": "success",
  "data": {
    "content": [
      {
        "id": 251,
        "name": "angelena.corwin"
      }
    ],
    "totalPages": 10,
    "totalElements": 50,
    "size": 5,
    "number": 1,
    "sort": {},
    "first": true,
    "last": false,
    "numberOfElements": 50,
    "empty": false
  },
  "total": 50
}
```
Although I can ignore the unnecessary fields through customResponseFields, I am unable to change the nested structure of data.content. Are there any good suggestions for generating the desired documentation in such situations? If this feature is not supported, could you consider adding functionality similar to apiObjectReplacements for configuring return objects, or implement a custom return type like @return java.util.List<T> as seen in @param pageable com.power.doc.model.PageRequestDto? Thank you!
虽然可以通过 customResponseFields 忽略掉不需要的字段，但是 data.content 的嵌套结构无法改变。
目前是否有好的建议，使这种情况可以生成期望的文档？
如果无法支持，是否可以增加对返回对象配置类似 apiObjectReplacements 的功能，
或者像 `@param pageable com.power.doc.model.PageRequestDto` 这样实现 `@return java.util.List<T>` 自定义返回类型。
谢谢！

**Comment by shalousun** [comment]
@ooknight 
The similar requirements have been mentioned before, and theThe similar requirements have been mentioned before, and the them is that they are not and the main reason for not implementing them is that they are not developer-friendly. The best approach is to avoid using many strange configurations and simply write a few lines of textual annotations. Therefore, we have little intention of providing non-standardized solutions. If you wish to proceed, you can submit a pull request based on the @return annotation.
之前有人说过类似需求，没做的原因主要就是对开发并不友好，最好的方式就是很多奇怪的配置都不要用，就简单写几行文字性注释就好了，所以不太标准话的我们都没什么意向去提供了，如果你们要搞可以基于@return 提pr

**Comment by shalousun** [comment]
@liusk98

**Comment by liusk98** [comment]
> @liusk98
Alright, I will follow up on this.
好的，由我来跟进

**Comment by luo-zhan** [comment]
你的统一包装不太规范啊，正常的不都是下面这种吗：
```json
{
  "code": 200,
  "message": "success",
  "data": {
     "total": 50,
     "pageNumber": 1,
     "pageSize": 20,
     "records": [...]
  }
}
```

**Comment by linwumingshi** [comment]
`Controller`
```java
    @GetMapping
    public Result<List<Car>> test() {
        Car car = new Car();
        car.setLength(1.0);
        car.setName("car");
        List<Car> cars = List.of(car);
        return Result.success(new PageImpl<>(cars, PageRequest.of(0, 10), 1));
    }
```

`Result`
```java
package com.power.doc.controller.jsr;

import com.fasterxml.jackson.annotation.JsonInclude;
import lombok.Data;

import java.util.List;

@Data
@JsonInclude(JsonInclude.Include.NON_NULL)
public class Result<T> {
    /**
     * code
     */
    private int code;
    /**
     * message
     */
    private String message;
    /**
     * data
     */
    private T data;
    /**
     * total
     */
    private Long total;

    public static <T> Result<List<T>> success(org.springframework.data.domain.Page<T> data) {
        Result<List<T>> result = new Result<>();
        result.setCode(200);
        result.setMessage("success");
        result.setData(data.getContent());
        result.setTotal(data.getTotalElements());
        return result;
    }

}
```


the API documentation:
 
**Response-fields:**

| Field | Type | Description | Since |
|-------|------|-------------|-------|
|code|int32|code|-|
|message|string|message|-|
|data|array|data|-|
|└─name|string|car name|-|
|└─length|double|car  length|-|
|total|int64|total|-|

**Response-example:**
```json
{
  "code": 0,
  "message": "",
  "data": [
    {
      "name": "",
      "length": 0.0
    }
  ],
  "total": 0
}
```
