### ISSUE TITLE
Error in parsing objects annotated with @RequestBody across different interfaces.

### ISSUE THREAD

**Issue by Gahon1995** [TongchengOpenSource/smart-doc#458]
## Your Environment(您的使用环境)
All are the latest versions.

## Expected Behavior(您期望的结果)
The field names corresponding to openapi generated from different interfaces should be distinct.
不同接口生成的openapi对应的字段名应该不一样

## Current Behavior(当前结果)
In multiple different interfaces, objects with the `In multiple different interfaces, objects with the `annotation that have only one type objects with the `@RequestBody` annotation that have only one type in common but differ in name are all parsed as the same type. For example, the field names generated for all interfaces become "userId".
多个不同接口下的RequestBody注解的不同对象里都只有一个类型相同但是名称不同的，都会被解析成同一个类型
， 比如所有接口生成的字段名都为userId

## Possible Solution(bug解决建议)
Upon reviewing the OpenAPI interface documentation, the requests for different interfaces all point to a component named `string` in their refs.
查看openapi接口文档，不同接口的请求指向的refs都是同一个名为`string`的component

## Steps to Reproduce (Bug产生步骤，请尽量提供用例代码)
For example, if the following three are used as parameters with the `@ResponseBody` annotation in different interfaces within various controllers, the generated OpenAPI might display the input parameters for all three interfaces as "userId".

```java
public class UserDeleteRequest  {

    /**
     * 用户id
     */
    private Long userId;
}

public class RoleDeleteRequest  {

    /**
     * 角色id
     */
    private Long roleId;
}

public class MenuDeleteRequest  {

    /**
     * 菜单id
     */
    private Long menuId;
}
```

## Context(Bug影响描述)

This results in errors in the generated OpenAPI interface, rendering it unusable.
导致生成的openapi接口错误，无法正常使用

**Comment by shalousun** [comment]
@Gahon1995 Please submit an issue following the issue template to facilitate problem tracking.

**Comment by Gahon1995** [comment]
> @Gahon1995 Please submit an issue following the issue template to facilitate problem tracking.

The modifications are complete; please take a look when you have time.
修改好了，有时间看看
