### ISSUE TITLE
The nested object collection in the return result has not been parsed.

### ISSUE THREAD

**Issue by lw5946** [TongchengOpenSource/smart-doc#46]
## Expected Behavior(您期望的结果)

Display the properties of objects in nested collections in the documentation.

## Current Behavior(当前结果)

Nested objects are displayed, but the generics of collection objects (List<>) are not shown.

## Steps to Reproduce (Bug产生步骤，请尽量提供用例代码)

The object structure is as follows:
`R` is a unified return object, with `ProductOrderVo` placed inside the `data` attribute of `R`. However, the `productList` attribute within `ProductOrderVo` cannot be parsed.

```java
public class R<T> implements Serializable {
  private String code = ResultCode.SUCCESS.getCode();
  private String msg = "success";
  private T data;
}
```
```java
public class ProductOrderVo implements Serializable {
  private List<ProductAppOrderRelVo> productList;
}
```

```java
public class ProductAppOrderRelVo implements Serializable {
  private String productName;
  private List<AppOrderAddedVo> addedList;
  private String userName;
}
```

## Your Environment(您的使用环境)

* smart-doc version: 1.8.8
Using the method of generating documentation with a test class. The code is as follows:
```java
@SpringBootTest
public class SmartDocTests {
  @Test
  public void testBuilderControllersApi() {
    ApiConfig config = new ApiConfig();
    config.setDataDictionaries(null);
    // 以前的版本为setSourcePaths，SourceCodePath为SourcePath
    config.setSourceCodePaths(
        SourceCodePath.path().setDesc("本项目代码").setPath(DocGlobalConstants.PROJECT_CODE_PATH)
        ,
        SourceCodePath.path()
            .setDesc("加载外部项目源码")
            .setPath(
                "D:\\xxx\\xxx\\xxx\\"
                    + DocGlobalConstants.PROJECT_CODE_PATH));
    config.setServerUrl("http://ip:port/context");

    config.setAllInOne(true);

    config.setOutPath("d:\\test\\md");
    ApiDocBuilder.buildApiDoc(config);
  }
}
```

**Comment by shalousun** [comment]
reference https://gitee.com/sunyurepository/smart-doc/wikis/使用smart-doc的代码最佳实践?sort_id=1812571

**Comment by lw5946** [comment]
I'm following the correct example, but the generic class of the general return result contains an embedded object collection, and the generic objects in this embedded collection cannot be parsed.
我这是按照正确示范来做的，只不过通用返回结果的泛型类中内嵌了一个对象集合，而此内嵌集合的泛型对象解析不出来

**Comment by netdied** [comment]
Try using version 1.9.0, will you?
尝试使用一下1.9.0版本呢？
