### ISSUE TITLE
Missing parameter.

### ISSUE THREAD

**Issue by dengbin21** [TongchengOpenSource/smart-doc#465]
![image](https://user-images.githubusercontent.com/30514263/228400828-6b2cfd35-31a8-4679-adec-773997aedd06.png)

![image](https://user-images.githubusercontent.com/30514263/228400917-65f60c2d-7b39-4d14-ae0d-c1771278744b.png)
In the generated openapi.json, the parameter is missing.

**Comment by shalousun** [comment]
@dengbin21 Please submit according to the issue template. If not submitted as per the template, we are completely unaware of the version information, which is why many open-source projects have written an issue template.
