### ISSUE TITLE
Using an internal enumeration of the class as a parameter cannot be resolved.

### ISSUE THREAD

**Issue by dengbin21** [TongchengOpenSource/smart-doc#469]
## Your Environment(您的使用环境)

* smart-doc version: 2.6.5
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin):smart-doc-maven-plugin
* build tool version(maven or gradle):maven 

## Expected Behavior(您期望的结果)

参数完整

## Current Behavior(当前结果)

参数丢失

## Steps to Reproduce (Bug产生步骤，请尽量提供用例代码)

1.
![image](https://user-images.githubusercontent.com/30514263/228707874-79e72a27-d894-4ea7-8994-d3aef1165133.png)
2.
![image](https://user-images.githubusercontent.com/30514263/228707914-f3034ad3-e844-419b-8511-177b3d070b1c.png)
3.
4.

## Context(Bug影响描述)

导致生成的openapi.json，没有该参数

**Comment by shalousun** [comment]
@dengbin21 这个目前排查是https://github.com/paul-hammant/qdox 层的bug，qdox现在维护比较慢，建议把暂时不用用内部类的方式定义枚举。单独定义应该没问题。等后面有空我们再看怎么去fix qdox这个bug，当然如果你有兴趣也可以和我交流参与这个的fix

**Comment by dengbin21** [comment]
1.SwaggerBuilder.buildPathUrlsRequest 155行那一块，也有个bug，是不是取apiDoc.getTags()；算是笔误
2.如果是枚举，生成openapi.json时，枚举值会缺失，需要把枚举值列举出来
3.另外后面有计划支持swagger相关的注解吗？

**Comment by shalousun** [comment]
> 1.SwaggerBuilder.buildPathUrlsRequest 155行那一块，也有个bug，是不是取apiDoc.getTags()；算是笔误 2.如果是枚举，生成openapi.json时，枚举值会缺失，需要把枚举值列举出来 3.另外后面有计划支持swagger相关的注解吗？

swagger这个注解不会在smart-doc上支持，如果有老项目可去使用torna上的swagger插件。其余两个问题有兴趣可以提pr参与共建，枚举在openapi上缺失一个可能是对openAPI协议没研究清楚，细节比较多全对接上还是挺复杂的。

**Comment by MSamor** [comment]
遇到了相同的问题，内部类枚举识别不了。现在还是没有解决方案？
