### ISSUE TITLE
Since version 2.7.7, Dubbo has changed the `@Service` annotation to `@DubboService`.

### ISSUE THREAD

**Issue by zrlw** [TongchengOpenSource/smart-doc#47]
## Summary
1. Suggestion
Change the definition of Dubbo annotations from `SERVICE` to an array to accommodate both `@service` and `@DubboService` tags.

2. Discussion
For Dubbo services exposed only through configuration files, such as the following:
```
  <bean id="demoService" class="com.demo.provider.DemoServiceImpl" /> 
  <dubbo:service interface="com.demo.provider.Provider" ref="demoService" />
```
Could scanning the configuration file also resolve this?
  
### Basic example
If the proposal involves a new or changed API, include a basic code example. Omit this section if it's not applicable.
### Motivation
Why are we doing this? What use cases does it support? What is the expected outcome?

**Comment by shalousun** [comment]
@zrlw It will support the new annotations provided by Dubbo. Secondly, smart-doc has already provided the `@dubbo` tag for users to mark their interfaces; currently, we do not wish to add complexity to parsing XML.
