### ISSUE TITLE
In a Quarkus project, generating openapi.json results in a null pointer exception.

### ISSUE THREAD

**Issue by SurelySomeday** [TongchengOpenSource/smart-doc#471]
## Your Environment(您的使用环境)

* Using Quarkus to build a web project (JAX-RS standard).
* quarkus version:  2.16.5.Final
* quarkus-resteasy-reactive:  2.16.5.Final
* smart-doc version:  2.6.7
* plugin version (smart-doc-maven-plugin):2.6.3
* build tool version(maven): 3.8.6

* smart-doc.json
```json
{
  "serverUrl": "http://localhost:8090/",
  "outPath": "src/main/resources/META-INF/resources",
  "isStrict": false,
  "allInOne": true,
  "coverOld": true,
  "createDebugPage": true,
  "style":"xt256",
  "packageFilters": "",
  "projectName": "quarkus-demo",
  "framework": "JAX-RS"
}
```

## Expected Behavior(您期望的结果)

```cmd
# Expects the command to correctly generate openapi.json.
mvn smart-doc:openapi
```

## Current Behavior(当前结果)

```cmd
java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because the return value of "com.power.doc.model.ApiMethodDoc.getContentType()" is null
```

## Possible Solution(bug解决建议)
The error code location indicated in the prompt is as follows (AbstractOpenApiBuilder), where getContentType() returns null.
提示的报错代码位置如下(AbstractOpenApiBuilder)，getContentType()返回null。

![image](https://user-images.githubusercontent.com/32257480/230294538-19cab54f-e375-4a13-86e7-634670ef84b1.png)

## Steps to Reproduce (Bug产生步骤，请尽量提供用例代码)

1. Using the mvn command
```
# Using the mvn command
mvn smart-doc:openapi
```
2. Sample Java code
```java
@Path("/permission")
@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
public class PermissionResource {


    @GET
    @Path("")
    @RolesAllowed("anno")
    public Uni<List<User>> all() {
        return User.findAll().list();
    }

    @GET
    @Path("/error")
    @PermitAll
    public Uni<Void> ex() throws Exception {
        throw new Exception("test");
    }


}
```

## Context(Bug影响描述)
It is possible to generate debug-all.html for use, but unable to generate openapi.json.

**Comment by shalousun** [comment]
@SurelySomeday If you're interested, feel free to submit a PR for the fix. We also warmly welcome everyone to participate in community co-building.

**Comment by shalousun** [comment]
@SurelySomeday upgrade to 3.0.1
