### ISSUE TITLE
Regarding the issue where the ignore annotation tag does not take effect for response parameters.

### ISSUE THREAD

**Issue by my-nunu** [TongchengOpenSource/smart-doc#477]
## Summary(关于这个pr的描述)
I'd like to ask the author if this was intentionally designed to handle things differently, specifically conducting an isResp check on some markers before proceeding with the subsequent logic.
想问一下作者大大，这块是故意设计成不一样的处理方式吗？针对一些标记专门进行了isResp判断之后再执行以后的逻辑；

**Comment by shalousun** [comment]
@my-nunu 
The response parameters are filtered using FastJson or Jackson annotations, which smart-doc supports. This ensures that the actual returned data and the documentation are completely consistent. The use of custom tag ignore is not recommended.
相应参数用FastJson或者是Jackson的注解去过滤了，smart-doc支持他们的注解的，这样实际返回的数据和文档也是完全一致，自定义的tag ignore不提倡使用
