### ISSUE TITLE
Add a Constraint column to describe parameter constraints in the output document table.

### ISSUE THREAD

**Issue by durian530** [TongchengOpenSource/smart-doc#479]
## Summary(关于这个pr的描述)

![企业微信截图_16816987824270](https://user-images.githubusercontent.com/91531396/232364161-0d58f815-c8be-4b4e-8f4c-75931152ba95.png)
![企业微信截图_16816988678131](https://user-images.githubusercontent.com/91531396/232364302-3913c4d5-b7de-438b-9a4e-59a7df78344d.png)

The current output document is relatively crude in describing parameter constraints, as shown in the figure above. The parameters page and size have their own size constraints, but this information is missing in the output document. Can we add a Constraint column to the output table to describe the constraint information associated with the parameters?
当前输出文档对参数约束的描述较为粗糙，如上图，page和size本身是有大小约束的，但是输出文档中丢失了这一块的信息，能否在输出表格中添加一列Constraint，用于描述参数附带的约束信息

### Motivation(提出这个pr目的)
The constraint description of the interface parameters is an important part of accurately understanding the details of the API. Adding a new Constraint column can help developers use the documentation more accurately.
If this proposal is feasible, I will submit PRs to improve this requirement in succession.
接口参数的约束描述是准确理解api细节的重要一环，添加新的Constraint列能帮助开发者更准确地使用文档。
若该提议可行的话，后续我会陆续提交pr完善该需求。

**Comment by shalousun** [comment]
@durian530 
It's not necessary to add another column; adding more columns could affect the aesthetic layout of the document. It would be sufficient to incorporate the validation information into the comments, similar to the approach taken with the following fields. Moreover, some companies may not need to display this validation information, while others do. Those submitting PRs should also consider controlling the display.
没必要在加一列了，列加多了文档的排版会很丑，可以像下面的几个字段吧验证补充添加到注释里就可以了。而且这个验证信息有的公司是不需要展示，有的公司需要，提pr的也可以考虑下控制展示
