### ISSUE TITLE
Throw an exception when the return type of the generic T is a byte array.

### ISSUE THREAD

**Issue by zrlw** [TongchengOpenSource/smart-doc#48]
When generating Dubbo interface documentation with `mvn smart-doc:rpc-html`, encountering such a method will throw an exception.
mvn smart-doc:rpc-html生成dubbo接口文档时，遇到这样的方法会抛出异常：
SomeResponse<byte[]> someMethod(String somParam);

## Expected Behavior(您期望的结果)
It can be parsed normally.
能正常解析。

## Current Behavior(当前结果)
RpcDocBuildTemplate.methodDefinition throw exception：
java.util.regex.PatternSyntaxException: Unclosed character class near index 5
byte[]

## Your Environment(您的使用环境)
smart-doc 1.9.0
jdk 1.8

**Comment by zrlw** [comment]
Capturing this exception and ignoring it directly is fine.
捕获这个异常直接忽略即可。

**Comment by netdied** [comment]
You can pull the latest dev branch and repackage it, or wait for the next version to be released.
可以拉去最新的dev分支 重新打包或等下一个版本发布
