### ISSUE TITLE
Cannot obtain the parent interface of multiple inheritance.

### ISSUE THREAD

**Issue by younker99** [TongchengOpenSource/smart-doc#480]
## Your Environment(您的使用环境)

* smart-doc version: 2.6.7
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin): 未使用
* build tool version(maven or gradle): maven 3.6.3

## Expected Behavior(您期望的结果)
class A;
class B extends A;
class C extends B;

When generating documentation for C, it is expected to generate interface information from A and B.
对C生成文档时，期望生成A与B中的接口信息。 

## Current Behavior(当前结果)

Only methods from B will be retrieved; those from A will not be loaded.
只会获取B中的method，不会加载A中的。

## Possible Solution(bug解决建议)

In the IRestDocTemplate, on line 1049, in the getParenClassMethods method, it is expected to use recursion to obtain the parent class information of the class, rather than just loading the immediate parent of the current class.

IRestDocTemplate中，1049行，getParenClassMethods方法，期望采用递归获取class的父类信息，而不是只加载当前class的父。

## Context(Bug影响描述)

Document generation is abnormal when there is multiple inheritance.

多层继承时文档生成异常

**Comment by shalousun** [comment]
good
