### ISSUE TITLE
For interfaces without comments, could the class and method names be displayed?

### ISSUE THREAD

**Issue by ldgithub2199** [TongchengOpenSource/smart-doc#483]
For classes and methods without comments, the documentation directory displays blank entries. Could it be made to show the class name, method name, or interface path, similar to Swagger?
![image](https://user-images.githubusercontent.com/65696427/232447450-9b378d27-829a-4602-9d79-0147cd7a22b9.png)

**Comment by shalousun** [comment]
@ldgithub2199 It might be better to add the comments yourself. Smart-doc doesn't display them to enforce the requirement of writing comments. Once you open a loophole, some people will take shortcuts, which is very detrimental to team management. This isn't a technical issue or a bug; such requests have been declined multiple times.
还不如自己去加注释，smart-doc不展示就是为了强制要求写注释，当你打开一个缺口总有人会偷懒，对团队管理着非常不利，这个并不是技术问题，也不是bug，这样的需求已经被拒绝很多次了。

**Comment by ldgithub2199** [comment]
There are two scenarios to consider: for some interfaceThere are two scenarios to consider: for some interface naming, like 'delete some methods lack comments and it's not feasible to require others to add them. Wouldn't it be more convenient to display the interface or method names by default, similar to Swagger?
有这么两种场景哈：对于有些接口或者方法命名比较清晰地，比如delete，add等，可能会不加注释；引入了其他团队的包，部分方法没有注释，又没办法要求别人全部加注释。默认展示接口名或方法名是不是更方便点。像swagger那样
![image](https://user-images.githubusercontent.com/65696427/232645051-4dd53653-7180-4449-ab3c-0504477f8b77.png)
