### ISSUE TITLE
When inheriting a constant class, it cannot be resolved.

### ISSUE THREAD

**Issue by beautymerry** [TongchengOpenSource/smart-doc#486]
## Your Environment(您的使用环境)

smart-doc-maven-plugin 2.4.2
## Expected Behavior(您期望的结果)

url地址 /DemoConstant/Demo2Constant

The URL address " /DemoConstant/Demo2Constant"

## Current Behavior(当前结果)
 url 地址 /Demo2Constant.DemoConstant/Demo2Constant
The URL address "/Demo2Constant.DemoConstant/Demo2Constant"

## Steps to Reproduce (Bug产生步骤，请尽量提供用例代码)
Parent class constant
public class DemoConstant {
    public static final String DemoConstant ="/DemoConstant";
}

Child class constant
public class Demo2Constant extends DemoConstant{

    public static final String Demo2Constant ="/Demo2Constant";
}

@GetMapping( Demo2Constant.DemoConstant+ Demo2Constant.Demo2Constant)
    public String demoRest4(){
        logger.info("测试日志打印");
        return "Success";
    }

## Context(Bug影响描述)
Constants after inheritance cannot be resolved
继承后的常量无法解析

**Comment by shalousun** [comment]
@beautymerry Please upgrade to check if there are any issues with the latest version. If so, you can prioritize submitting a PR (Pull Request) to resolve them yourself.

**Comment by my-nunu** [comment]
工程中外部依赖中的常量也无法解析出来；

**Comment by delei** [comment]
@beautymerry 请升级到最新版本，并确保常量类源码可以被`smart-doc`扫描到

##  Environment(您的使用环境)

- smart-doc-maven-plugin 2.7.7

**Comment by delei** [comment]
> 工程中外部依赖中的常量也无法解析出来；

@my-nunu 外部依赖需要考虑是否被`smart-doc-maven-plugins`中内置的`FilterChain`忽略，请知悉：
- 官网文档中暂未详细描述哪一些会被`FilterChain`忽略处理
- 未被内置`FilterChain`忽略的是可以解析出来的
- 由于`FilterChain`的逻辑优先级比插件配置中的`<include>`高，使用`<include>`包含依赖也不会起作用


以下提供一个样例：

## Environment(您的使用环境)

- smart-doc-maven-plugin 2.7.7

## Example(用例)

引入一个未被内置`FilterChain`过滤的三方库

```xml
<dependency>
    <groupId>net.dreamlu</groupId>
    <artifactId>mica-core</artifactId>
    <version>2.7.15</version>
</dependency>
```

插件配置

```xml
<plugin>
      <groupId>com.github.shalousun</groupId>
      <artifactId>smart-doc-maven-plugin</artifactId>
      <version>2.7.7</version>
      <configuration>
          <configFile>src/main/resources/smart-doc.json</configFile>
          <projectName>${project.description}</projectName>
          <includes>
              <!-- 包含 mica -->
              <include>net.dreamlu:.*</include>
          </includes>
      </configuration>
      <executions>
          <execution>
              <!--    <phase>compile</phase>-->
              <goals>
                  <goal>html</goal>
              </goals>
          </execution>
      </executions>
  </plugin>
```

`controller`用例

```java
@RestController
@RequestMapping(value = "/constant")
public class ConstantController {

    /**
     * 常量用例02
     *
     * @param userId
     */
    @PostMapping(BaseConstant.BASE_PATH + "/tt-" + MicaConstant.MDC_ACCOUNT_ID_KEY)
    public void constant02(String userId) {
    }


    /**
     * 常量用例03
     *
     * @param userId
     */
    @PostMapping(BaseConstant.BASE_PATH + "/tt-" + ResourceUtils.URL_PROTOCOL_WAR)
    public void constant03(String userId) {
    }
}

```
生成结果
<img width="1053" alt="image" src="https://github.com/TongchengOpenSource/smart-doc/assets/17263766/f282eb7e-eea5-42d2-b4bd-d4baa5476aea">


上述用例中：
- `MicaConstant.MDC_ACCOUNT_ID_KEY`是三方库`mica`的常量值，文档中可以生成
- `ResourceUtils.URL_PROTOCOL_WAR`是`spring`中的常量值，文档中无法生成

## Source Code（源码）
具体有哪些`FilterChain`，以及哪些会被过滤处理，可`debug`或阅读插件源码[`ArtifactFilterUtil#ignoreArtifact`](https://github.com/TongchengOpenSource/smart-doc-maven-plugin/blob/master/src/main/java/com/ly/doc/plugin/util/ArtifactFilterUtil.java)方法

**Comment by delei** [comment]
@shalousun 已提交一个`issue`
https://github.com/TongchengOpenSource/smart-doc-maven-plugin/issues/55

**Comment by shalousun** [comment]
@delei 这个看后续能不能从Qdox上去改善，插件做filter把不必要的加载过滤掉主要还是为了开箱即用，smart-doc一直以来的理念是尽可能让用户少配置

**Comment by ifrankwang** [comment]
最新版本 `3.0.1` 有类似的问题：

常量参数：
```java
public static final String API_PREFIX = RequestConstants.API_PREFIX + PREFIX;
```

Controller：
```java
@RestController
@RequestMapping(ApiConstants.API_PREFIX + "/client")
public class TestController {

  @GetMapping("/page")
  public Object getPage() {...}
}
```

生成结果：
<img width="435" alt="image" src="https://github.com/TongchengOpenSource/smart-doc/assets/18070730/07b28a3d-fff2-43af-b568-8b3b3da7334b">

**Comment by shalousun** [comment]
@ifrankwang fixed in 3.0.2
