### ISSUE TITLE
Regarding the default value issue for parameter annotations.

### ISSUE THREAD

**Issue by yingzichao** [TongchengOpenSource/smart-doc#487]
## Your Environment(您的使用环境)

* smart-doc version:2.6.5

## Expected Behavior(您期望的结果)

![image](https://user-images.githubusercontent.com/23230214/233291987-158b2ab1-dad4-4f13-8ca3-a5171c3b2893.png)

## Current Behavior(当前结果)
![image](https://user-images.githubusercontent.com/23230214/233291842-36691a68-9704-47f7-894a-9e20bb8abf80.png)

## Possible Solution(bug解决建议)

![image](https://user-images.githubusercontent.com/23230214/233292088-4f2f1f65-a917-406e-92cf-34967b89e208.png)

## Steps to Reproduce (Bug产生步骤，请尽量提供用例代码)

![image](https://user-images.githubusercontent.com/23230214/233292225-09abb6cb-0f30-459f-8d73-a916573be0a9.png)

## Context(Bug影响描述)
Java requires forward slashes (/) to be escaped. After escaping, smart-doc incorrectly displays the default values of parameters.

**Comment by shalousun** [comment]
@yingzichao PRs for fixes are welcome.
