### ISSUE TITLE
Custom extension of DocJavaMethod.

### ISSUE THREAD

**Issue by younker99** [TongchengOpenSource/smart-doc#488]
## Summary(关于这个pr的描述)
Before converting List<DocJavaMethod> to List<ApiMethodDoc>, invoke custom extensions for adjustments.
在`List<DocJavaMethod>`转化为`List<ApiMethodDoc>`前，调用自定义的拓展进行调整。`

### Basic example(pr的用例)
Preliminary design is as follows:
1. Define `ICusJavaMethodExtension` with the content being `List<DocJavaMethod> apply(JavaClass cls, List<DocJavaMethod> methodList)`.
2. Add an `ICusJavaMethodExtension cusJavaMethodExtension` attribute to `ApiConfig`.
3. In `IRestDocTemplate`, before converting `List<DocJavaMethod>` to `List<ApiMethodDoc>` within the `buildEntryPointMethod`, check and invoke `cusJavaMethodExtension` to update the `List<DocJavaMethod>`.

初步设计是
1. 定义`ICusJavaMethodExtension`,内容为`List<DocJavaMethod> apply(JavaClass cls, List<DocJavaMethod> methodList)`
2. ApiConfig中添加ICusJavaMethodExtension cusJavaMethodExtension属性
3. 在IRestDocTemplate中buildEntryPointMethod里，`List<DocJavaMethod>`转化为`List<ApiMethodDoc>`前，判断并调用cusJavaMethodExtension，更新`List<DocJavaMethod>`

### Motivation(提出这个pr目的)

The common controller encapsulated in the project features multiple levels of inheritance, with some methods having dynamic return types and parameters. The type information parsed by smart-doc for these interfaces is inaccurate and cannot be adjusted.

项目中封装的通用controller存在多层继承，部分method的返回值和入参是动态类型，此部分接口smart-doc解析出的类型信息不准确，却又无法调整。

**Comment by shalousun** [comment]
@younker99 You can supplement the examples in the test project at https://github.com/smart-doc-group/smart-doc-example-cn first. Wouldn't it be better to rename ICusJavaMethodExtension to ICustomJavaMethodHandler, as smart-doc does not advocate for using non-generic terms that are too specific? Start by adding examples and then submit a PR.

**Comment by younker99** [comment]
@shalousun 
https://github.com/smart-doc-group/smart-doc-example-cn/pull/20
Controller sample has been supplemented.

**Comment by shalousun** [comment]
> @shalousun [smart-doc-group/smart-doc-example-cn#20](https://github.com/smart-doc-group/smart-doc-example-cn/pull/20) Controller sample has been supplemented.

merged

**Comment by coffee-developer** [comment]
How to inject a custom ICustomJavaMethodHandler into ApiConfig

**Comment by coffee-developer** [comment]
How to inject a custom ICustomJavaMethodHandler into ApiConfig,This is how I configure it, maven throws an exception when packaging,
Failed to execute goal com.ly.smart-doc:smart-doc-maven-plugin:3.0.8:torna-rest (default-cli) on project erp-oms: Execution default-cli of goal com.ly.smart-doc:smart-doc-maven-plugin:3.0.8:torna-rest failed: Interfaces can't be instantiated! Register an InstanceCreator or a TypeAdapter for this type. Interface name: com.ly.doc.handler.ICustomJavaMethodHandler -> [Help 1]

![Image](https://github.com/user-attachments/assets/8afb1338-d853-4a19-9d94-ceadc06c3caf)

![Image](https://github.com/user-attachments/assets/d33c1a4f-72f0-499c-a417-6d99d8bf07ca)

如何注入一个自定义的ICustomJavaMethodHandler到ApiConfig,我是这么配置,maven 在打包时抛出异常,
Failed to execute goal com.ly.smart-doc:smart-doc-maven-plugin:3.0.8:torna-rest (default-cli) on project erp-oms: Execution default-cli of goal com.ly.smart-doc:smart-doc-maven-plugin:3.0.8:torna-rest failed: Interfaces can't be instantiated! Register an InstanceCreator or a TypeAdapter for this type. Interface name: com.ly.doc.handler.ICustomJavaMethodHandler -> [Help 1]
