### ISSUE TITLE
It is suggested to support user-defined RPC interface annotations.

### ISSUE THREAD

**Issue by zrlw** [TongchengOpenSource/smart-doc#49]
## Summary
It is recommended that the RPC interface documentation generation supports user-defined interface annotations to facilitate the creation of users' own RPC interface documentation.
建议生成rpc接口文档支持用户自定义的接口注解，以支持生成用户自己的rpc接口文档。

### Basic example
1. User-defined RPC interface annotations
```
public @interface MyService {
...
}
```
2. Interface class using custom RPC interface annotations:
```
@MyService  
public interface MyInterface {
...
}
```
3. Generate interface documentation for custom RPC interface annotations:
```
mvn smart-doc:rpc-html  -Drpc.annotations="com.xxx.MyService,com.xxx.YourService" // Support for multiple custom annotations separated by commas
```
### Motivation
Extend the adaptability of smart-doc to more scenarios.
扩展smart-doc的适应场景

**Comment by netdied** [comment]
Interface scanning can be achieved by adding the @Dubbo annotation to the class.
可以通过在类上添加@dubbo注释的方式实现接口扫描 
![image](https://user-images.githubusercontent.com/20217389/88450470-c0dc7d80-ce81-11ea-9656-2855ef747f79.png)

**Comment by zrlw** [comment]
对于已入版本库的系统而言，再去改代码加注解是行不通的

**Comment by netdied** [comment]
You can try downloading the code and modifying it to add your own annotations when checking for the @Dubbo annotation.
可以尝试下载代码修改 在判断@dubbo注释时添加自己的注释
![image](https://user-images.githubusercontent.com/20217389/88451580-511ec080-ce8a-11ea-8cff-90037d64d3a5.png)

**Comment by shalousun** [comment]
@zrlw Implementing custom annotation scanning is not that simple; there are many property configurations within an annotation. Just like with Dubbo, we have only just started and are waiting for user feedback to make improvements. We haven't yet extracted much of the information from the annotations.
开自定义注解扫描这个事情不是那么简单，一个注解里有很多属性配置。就像dubbo的我们目前也仅仅是先做出来等待用户的反馈去完善，注解里的很多信息都没去提取。
