### ISSUE TITLE
Interface integration with generics added, unable to resolve (RPC)

### ISSUE THREAD

**Issue by itfigael** [TongchengOpenSource/smart-doc#493]
## Your Environment(您的使用环境)

* smart-doc version: 2.6.8
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin):
* build tool version(maven or gradle):

## Expected Behavior(您期望的结果)
```
interface A<T>{
void common(T param);
}


/**
* @dubbo
*/
interface B extends A<String>{
void BFunction(String name);
}
```
Class B can inherit the common methods from Class A and support generic type resolution.
B能带出A中的common方法，并支持泛型解析

## Current Behavior(当前结果)
Only the documentation for the BFunction of interface B was generated; the common methods from interface A were not included, nor was support for generics provided.
仅生成了 B 接口的BFunction文档，A接口的common无法带出，也无法支持泛型。

## Steps to Reproduce (Bug产生步骤，请尽量提供用例代码)

1.
2.
3.
4.

**Comment by shalousun** [comment]
@itfigael If you are interested and can fix it yourself, I suggest submitting a pull request (PR).
