### ISSUE TITLE
Could you provide a configuration that can disable the automatic generation of random numbers for mock values?

### ISSUE THREAD

**Issue by xiaoyao-jimmy** [TongchengOpenSource/smart-doc#497]
RT

**Comment by shalousun** [comment]
@xiaoyao-jimmy 
What impact do random values have? In fact, you can use the `@mock` tag to specify and override them yourself. The purpose of providing JSON is for those interfacing with the API to immediately understand the structure and type of data to be filled in upon seeing your JSON structure. The example itself is meant to quickly inform about the data formats of inputs and outputs; it's not about starting to use parameters from the documentation right away. Those with some development experience know that most of the values in documentation don't make sense, even if the data is handwritten.
随机值有什么影响吗。其实你可以自己用`@mock` tag指定覆盖掉。给json的目的是对接接口的人一看你的json结构体和填充的类型就只知道怎么写。example本身就是为了快速知道入参和出参的数据格式，并不是拿着文档里参数就开始用，有一定开发经验的都知道，文档中的值大多数都是搞不通的，即便是手写的数据。

**Comment by xiaoyao-jimmy** [comment]
我们做了二次的平台开发，会利用smart-doc做扫描。每次随机数的变更都会导致记录发生变更，大部分时候随机数对我们来说没有参考意义，我们希望没有@mock的时候，example本身就可以是空的结构，这样我们平台可以轻松的认为接口没有发生变更。因为我们的报文直接使用的smart-doc的结构体，如果不支持配置的话，就需要再进行定制化的逻辑判断，或者自己重写这部分随机数逻辑

**Comment by xiaoyao-jimmy** [comment]
> @xiaoyao-jimmy 随机值有什么影响吗。其实你可以自己用@mock tag指定覆盖掉。给json的目的是对接接口的人一看你的json结构体和填充的类型就只知道怎么写。example本身就是为了快速知道入参和出参的数据格式，并不是拿着文档里参数就开始用，有一定开发经验的都知道，文档中的值大多数都是搞不通的，即便是手写的数据。（ps 其实可以强制每个参数都增加@mock，也可以实现没有变更记录，但是会对使用者不太友好）

**Comment by xiaoyao-jimmy** [comment]
We have conducted secondary platform development. Changes in random numbers can lead the platform to think that the interface has been modified, and in most cases, filling in example parameters with random numbers doesn't serve much purpose. We hope to support leaving them unfilled when not using `@mock`. Since we are directly using the structure of smart-doc for communication, if configuration is not supported, we can only rewrite the logic for generating random numbers or add customized logic to the platform. Therefore, we hope to leave an opening for this part in smart-doc (ps: in fact, we could force every parameter to include `@mock`, which could also achieve no change records, but it would not be very user-friendly).
我们进行了二次的平台开发。随机数的变更会导致平台认为接口有变更记录，绝大多数情况下，随机数的example参数填充没有太大的作用，我们希望支持未使用`@mock`可以不填充。由于直接使用的smart-doc的结构体进行的通信，不支持配置的话，我们只能重写随机数生成这部分逻辑，或者在平台增加定制化逻辑，所以希望在smart-doc里面给这部分留个口子（ps 其实可以强制每个参数都增加`@mock`，也可以实现没有变更记录，但是会对使用者不太友好）

**Comment by shalousun** [comment]
You could also submit a pull request (PR). In fact, making basic type judgments would suffice. For instance, after toggling a switch, similar to how integers return 0 and strings return empty, as in the following format, which maintains the integrity of the JSON without affecting the judgment:
你们也可以提pr，其实做好基本类型判断就可以，比如有开关之后，类似整型返回：0，字符串返回空就可以，例如下面这种格式，保留了json的完整性，也不影响判断
```
{
 "id":0,
"name":"",
}
```
