### ISSUE TITLE
The reference to other objects in the object returned by the interface cannot be resolved.

### ISSUE THREAD

**Issue by Thingfxj** [TongchengOpenSource/smart-doc#498]
## Your Environment(您的使用环境)
window11
idea  2021.3.2
jdk17 springboot3.0.6

* smart-doc version:2.6.8
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin): smart-doc-gradle-plugin
* build tool version(maven or gradle):gradle

## Expected Behavior(您期望的结果)

It is expected to normally obtain the attribute information of class A and class B.
期望正常获取到A类和B类的属性信息

## Steps to Reproduce (Bug产生步骤，请尽量提供用例代码)

1. A
public class A{
    private String name;
}

2. B
public class B{
    private String id;
    private Set<A> a;
}
3. The interface returns B.
4. When generating the documentation, Set<A> reports an error and cannot recognize the properties related to B, returning {}.

**Comment by shalousun** [comment]
Do not use 'permits' in field names for now, as this is a Java keyword and qdox currently has a bug with restrictions.
先不要在字段名中用permits，这个Java的关键字，qdox目前限制有bug

**Comment by shalousun** [comment]
fix in 2.6.9
