### ISSUE TITLE
Simple enum types used as parameters will throw NPE (NullPointerException).

### ISSUE THREAD

**Issue by Alphathur** [TongchengOpenSource/smart-doc#5]
![image](https://user-images.githubusercontent.com/53657329/69479466-65f90f00-0e38-11ea-9da5-79cb139c1876.png)
![image](https://user-images.githubusercontent.com/53657329/69479484-9b056180-0e38-11ea-9212-ba148bd818b9.png)

**Comment by shalousun** [comment]
fix on 1.7.8
