### ISSUE TITLE
Unable to properly resolve nested generics

### ISSUE THREAD

**Issue by zrlw** [TongchengOpenSource/smart-doc#50]
## Expected Behavior(您期望的结果)
When parsing the following RPC method:
解析下面的rpc方法时：
```
SomeResp<PageInfo<SomeVO>>  someFunction(SomeReq req);·
```
Where `PageInfo` is the pagination wrapper class of `pageHelper`, and `SomeVO` is a VO object as shown below,
其中PageInfo是pageHelper的分页包装类，SomeVO是如下所示VO对象，
```
public class SomeVO {
    String name;
    Integer age;
    BigDecimal amt;
}
```
`SomeResp` is a generic class as shown below:
SomeResp是如下所示的泛型类：
```
public class SomeResp<T> {
     T result;
}
```
The expected analysis result is to list the members of `SomeVO` in the response list, without listing the members of `PageInfo` (providing a mechanism to specify types that are not expanded).
期望分析结果是在响应列表列出的SomeVO的成员，
不列出PageInfo成员（提供一种指定类型不展开的机制）。

## Current Behavior(当前结果)
1. The interface definition for generating documentation with smart-doc is:
```
Definition:  SomeResp<SomeVO>>  someFunction(SomeReq req);  // It's missing the "PageInfo<"
```

2. The "Response-fields" list has displayed `result` layer by layer, but it only shows the members of the `PageInfo` class, without involving `SomeVO` at all.
Below is the uploaded image, for well-known reasons, it might need to be accessed from outside the country to display properly.

![image](https://user-images.githubusercontent.com/40652892/88673498-44fd6200-d11b-11ea-85bb-ecce519fcbde.png)

## Your Environment(您的使用环境)
smart-doc-maven-plugin 1.1.2

**Comment by shalousun** [comment]
@zrlw Smart-doc is based on source code analysis, and it's important to understand that the analysis results can differ between having the source code and not having it. If you find that third-party libraries cannot be analyzed, first check whether your Maven configuration allows the smart-doc plugin to load the remote `pagehelper-spring-boot-starter-1.3.0-sources.jar`.

Many issues with smart-doc due to the environment can be resolved by reading the documentation in the Gitee repository of smart-doc.

smart-doc是基于源码来完成分析的，有源码和无源码的分析结果是不太一致的，一定要明白这个基础原理。对于第三方库如果发现不能分析那么首先你需要检查maven配置是否能够让smart-doc的插件去加载到远程的pagehelper-spring-boot-starter-1.3.0-sources.jar。
关于smart-doc的很多因为使用环境导致的问题可以去国内码云找到smart-doc的仓库仔细阅读文档。

当然方法定义显示属于bug

**Comment by zrlw** [comment]
1. 能访问远程的pagehlper的，只是解析结果列表里充斥了PageInfo的数十个成员参数，类似把HashMap展开一样，我看JavaClassUtil的getFields是写死过滤掉Date、HashMap等等这类东西的，可否提供一个参数，让类似PageInfo这类基础组件也可以被过滤掉。
2. 对于```A<B<C<D<E>>>>```这种泛型，最重要的是解析最内层的E，并不是B、C、D中间的三层。当然如能解析出来全部最好了，但是现在smart-doc解析泛型用的是一个映射map，并不是树形结构，只解析了最外的A、B两层，并没有继续迭代处理，当然简单改一下代码，碰到泛型嵌套时深度递归一下，把这种嵌套泛型简化为两层泛型如```A<E>```（这是我自己简单改造的方式），继续用这个map输出的分析结果也好过现在把泛型```A<B<C<D<E>>>>```的分析结果搞成```A<B>```。

**Comment by netdied** [comment]
可以拉一下最新dev的代码 再试一下

**Comment by zrlw** [comment]
dev最新的代码可以解析嵌套泛型了，这里提一个建议，泛型类型参数类型与其分析为object，不如设为实际的类型，只需要把ParamsBuildHelper.java 下面的代码（241行起）稍微改改：
```
                        if (typeSimpleName.length() == 1) {
                            processedType = DocClassUtil.processTypeNameForParams(typeSimpleName.toLowerCase());
                        } else {
                            processedType = isShowJavaType ? typeSimpleName : DocClassUtil.processTypeNameForParams(typeSimpleName.toLowerCase());
                        }
```
比如改成下面这样：
```
                        if (subTypeName.length() == 1) { // 判断是否为泛型时判断类名全称更合适一些
                            if (globGicName.length > 0) {
                                processedType = genericMap.get(subTypeName) != null ? genericMap.get(subTypeName) : globGicName[0];
                            }
                            else {
                                processedType = DocClassUtil.processTypeNameForParams(typeSimpleName.toLowerCase());
                            }
                        } else {
                            processedType = isShowJavaType ? typeSimpleName : DocClassUtil.processTypeNameForParams(typeSimpleName.toLowerCase());
                        }
```

**Comment by shalousun** [comment]
@zrlw smart-doc不想给实际类型的原因，smart-doc主要是为restful接口服务，restful接口有用户是直接导出来做对外文档的，不需要去显示实际的类型，目前也不想加参数去区别是rpc还是restful，所以就用通用object。rpc是对内文档，当前的rpc文档也是面向java开发生成，实际上开发人员基本只需要看有完整的接口方法定义。参数就是辅助作用。

**Comment by zrlw** [comment]
改了一下代码实现了参数包名过滤（不在参数列表里展开和应用无关的成员，比如PageInfo这个），供参考：
```
0) 应用工程的smart-doc.json里加一行输出的参数包名清单，类似packageFilters格式，支持逗号分隔多包名
paramPackageFilters: "com.xxx,com.yyy"
1) ApiConfig.java加了参数包名过滤成员paramPackageFilters及set、get方法;
2) 增加ApiConfigContainer类存全局静态对象ApiConfig，smart-doc-mavcen-plugind的BaseDocsGeneratorMojo的execute初始化ApiConfig后设置；
3） DocUtil加了一个参数包名的匹配方法：
    public static boolean isMatch(String className) {
        if (StringUtil.isEmpty(ApiConfigContainer.apiConfig.getParamPackageFilters())) {
            return true; // 没有设置参数包名过滤参数按匹配处理
        }
        String[] patterns = ApiConfigContainer.apiConfig.getParamPackageFilters().split(",");
        for (String str : patterns) {
            str = str.trim(); // 建议controller的isMatch方法也做一下截空，否则逗号前后有空格时就匹配不上了
            String name = str;
            if (str.endsWith("*")) {
                name = str.substring(0, str.length() - 2);
            }
            if (className.startsWith(name)) {  // 建议controller的isMatch方法里的contains也改为更严谨的startsWith
                return true;
            }
        }
        return false;
    }

4) ParamsBuildHelper的buildParams方法107行的else分支前增加过滤处理：
        } else if (cls != null && !DocUtil.isMatch(cls.getCanonicalName())) { // 对于不在生成文档中展示详细成员的参数类型
            if (className.contains("<")) { // 只展开泛型的类型参数
                for (String gicName : globGicName) {
                    JavaClass gicCls = projectBuilder.getClassByName(gicName);
                    StringBuilder preBuilder = new StringBuilder();
                    for (int j = 0; j < level; j++) {
                        preBuilder.append(DocGlobalConstants.FIELD_SPACE);
                    }
                    ApiParam param1 = ApiParam.of().setField(preBuilder.toString() + "?")
                                    .setType(gicCls.getSimpleName()).setDesc(gicCls.getComment())
                                    .setVersion(DocGlobalConstants.DEFAULT_VERSION);
                    paramList.add(param1);
                    paramList.addAll(buildParams(gicName, preBuilder.toString() + "└─", nextLevel, 
                    isRequired, responseFieldMap, isResp, registryClasses, projectBuilder, groupClasses));
                }
            }    
        } else {  // 在这个else前面增加上述代码
            List<DocJavaField> fields = JavaClassUtil.getFields(cls, 0, new HashSet<>());  // 只有else分支用到fields，从前面83行挪来
            boolean isGenerics = JavaFieldUtil.checkGenerics(fields);
            out:

5) JavaClassUtil的getFields方法处理非枚举也加了包名过滤（99行）
            // ignore enum parent class  下面代码增加了包名过滤
            if (!cls1.isEnum()) {
                JavaClass parentClass = cls1.getSuperJavaClass();
                if (null != parentClass && DocUtil.isMatch(parentClass.getCanonicalName())) {
                    fieldList.addAll(getFields(parentClass, counter, addedFields));
                }
                List<JavaType> implClasses = cls1.getImplements();
                for (JavaType type : implClasses) {
                    JavaClass javaClass = (JavaClass) type;
                    if (DocUtil.isMatch(javaClass.getCanonicalName())) {
                        fieldList.addAll(getFields(javaClass, counter, addedFields));
                    }
                }
            }
```

**Comment by netdied** [comment]
谢谢你的分享 不过忽略某个类会导致解析数据格式改变 对于读文档的人不友好 如果你们公司有这个需求可以自己编译一个版本哦

**Comment by zrlw** [comment]
还有一个地方提醒一下，对于泛型```A<T,E>```，如果有方法：
```
A getNoneTypeParameterResult(String blah) {
    return new A();
}
```
没有声明泛型A的类型参数T和E，这种情况smart-doc的ParamsBuildHelper会抛下标越界异常：
```
            for (int i = 0; i < cls.getTypeParameters().size(); i++) {
                genericMap.put(variables.get(i).getName(), globGicName[i]);  // <---- 这里globGicName下标越界
            }
```

**Comment by HappySnoopy** [comment]
Could you please confirm whether the issue with nested generics has not been resolved in version 1.2.2 of the Maven plugin? The results I'm getting with the Maven plugin still can't handle nested generics.
麻烦问一下，1.2.2版本的maven插件是不是没有解决这个问题？我用maven插件跑出来的结果依然处理不了嵌套的泛型
