### ISSUE TITLE
Cannot resolve generic type parameters in the input.

### ISSUE THREAD

**Issue by data-agent-ts** [TongchengOpenSource/smart-doc#501]
## Your Environment(您的使用环境)

* smart-doc version: 2.6.4
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin): 2.6.4
* build tool version(maven or gradle):  Maven

## Expected Behavior(您期望的结果)
    @PostMapping("/page")
    @ApiOperation("分页查询")
    public PageResult<AcceptorEval> page(@RequestBody QueryModel<AcceptorEvalCondition> model) {
        return acceptorEvalService.page(model);
    }
    
QueryModel is an external jar package. AcceptorEvalCondition is code written for the project.
    QueryModel 是外部jar 包  AcceptorEvalCondition 是项目编写的代码
    
public class QueryModel<T> implements ExtensibleObject {
    private T condition;
    private Paging paging;
    private Sorting[] sorts;
    private Map<String, Object> extras;

    public QueryModel() {
    }
    
During parsing, the input parameter only has "condition":{}.
The expectation is to parse the corresponding internal fields of the condition.
    解析时  入参 只有 "condition":{}
期望是解析对应的condition内部字段

## Current Behavior(当前结果)
Condition is not parsed.
condition不解析

## Possible Solution(bug解决建议)
It seems likely that the issue is related to the internal and external code of the project, as other issues appear to be parsed normally.
感觉可能是项目内外部代码 的问题  因为看其他issue 都是正常解析的

## Steps to Reproduce (Bug产生步骤，请尽量提供用例代码)

1.

3.
4.

**Comment by data-agent-ts** [comment]
![Snipaste_2023-05-12_15-41-41](https://github.com/smart-doc-group/smart-doc/assets/45841179/84c6baaa-2aac-4745-a0f2-fcf5c7553c87)

**Comment by data-agent-ts** [comment]
![image](https://github.com/smart-doc-group/smart-doc/assets/45841179/49ea080c-52bb-4dc2-9bfb-63fa150dc990)
The generic type has been correctly obtained.
泛型是正确获取到了的

**Comment by shalousun** [comment]
@tt1998215 
You need to enable smart-doc to read the code outside of the module. For multi-mode projects, it is recommended to refer to the documentation. Without source code, the nature of generics is such that they are erased during compilation; this is not a bug with smart-doc.
你要让smart-doc能读取到模块外的代码，多模式项目建议看文档，没有源码的时候范型本质是属于会被编译擦除的，这个不属于smart-doc bug

**Comment by tt1998215** [comment]
@shalousun  condition是我自己编写的源代码啊  sourcecode path中注册了的  这个没解析到啊

**Comment by data-agent-ts** [comment]
The issue was resolved after obtaining the source code of the third-party class.
获取第三方类源码后解决
