### ISSUE TITLE
Please upload to the Maven repository as soon as possible.

### ISSUE THREAD

**Issue by EXCaster** [TongchengOpenSource/smart-doc#505]
Being a Java tool, like Swagger, which can be easily introduced through Maven, would be much more convenient.
身为java工具像swagger一样可以从maven引入就会方便很多

**Comment by shalousun** [comment]
@EXCaster Isn't it a basic requirement for a Maven repository to be a Java library? Moreover, Smart-doc is inherently non-invasive (the documentation generation tool's code is not included in the distribution package), and it generates documentation by scanning source code, following a different principle. I suggest you take a look at the official documentation.
发maven仓库不是java 库的基本需求。然后smart-doc本来就是无倾入性（发布包里没有文档生成工具的代码）扫源代码生成文档的，使用原理也不一样，建议看看官方文档

**Comment by xiaoyao-jimmy** [comment]
他的意思估计是https://mvnrepository.com/拉不到最新的版本。https://central.sonatype.com/已经有了。

**Comment by xiaoyao-jimmy** [comment]
His point is that the latest version can't be found on https://mvnrepository.com, but it's already available on https://central.sonatype.com.
他的意思估计是[https://mvnrepository.com 拉不到最新的版本。https://central.sonatype.com 已经有了。
