### ISSUE TITLE
After integrating torna, the gateway module generates an error in the Dubbo RPC documentation.

### ISSUE THREAD

**Issue by littleCoolD** [TongchengOpenSource/smart-doc#506]
## Your Environment(您的使用环境)

* smart-doc version: 2.4.9
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin):2.4.9
* build tool version(maven or gradle):项目用的是java17，springboot3.0

## Expected Behavior(您期望的结果)
It is possible to successfully generate RPC documentation.

## Current Behavior(当前结果)
Unable to generate.

## Steps to Reproduce (Bug产生步骤，请尽量提供用例代码)

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  17.622 s
[INFO] Finished at: 2023-05-15T17:28:46+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.shalousun:smart-doc-maven-plugin:2.4.9:html (default-cli) on project spsaas-gateway: Execution default-cli of goal com.github.shalousun:smart-doc-maven-plugin:2.4.9:html failed: A required class was missing while executing com.github.shalousun:smart-doc-maven-plugin:2.4.9:html: io/micrometer/core/instrument/docs/MeterDocumentation
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>com.github.shalousun:smart-doc-maven-plugin:2.4.9
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/home/cd/.m2/repository/com/github/shalousun/smart-doc-maven-plugin/2.4.9/smart-doc-maven-plugin-2.4.9.jar
[ERROR] urls[1] = file:/home/cd/.m2/repository/javax/annotation/javax.annotation-api/1.2/javax.annotation-api-1.2.jar
[ERROR] urls[2] = file:/home/cd/.m2/repository/org/codehaus/plexus/plexus-utils/3.3.0/plexus-utils-3.3.0.jar
[ERROR] urls[3] = file:/home/cd/.m2/repository/org/apache/maven/plugin-tools/maven-plugin-annotations/3.6.4/maven-plugin-annotations-3.6.4.jar
[ERROR] urls[4] = file:/home/cd/.m2/repository/org/codehaus/plexus/plexus-sec-dispatcher/2.0/plexus-sec-dispatcher-2.0.jar
[ERROR] urls[5] = file:/home/cd/.m2/repository/org/codehaus/plexus/plexus-cipher/2.0/plexus-cipher-2.0.jar
[ERROR] urls[6] = file:/home/cd/.m2/repository/org/apache/maven/maven-builder-support/3.8.5/maven-builder-support-3.8.5.jar
[ERROR] urls[7] = file:/home/cd/.m2/repository/org/apache/maven/resolver/maven-resolver-util/1.6.3/maven-resolver-util-1.6.3.jar
[ERROR] urls[8] = file:/home/cd/.m2/repository/org/apache/maven/shared/maven-shared-utils/3.3.4/maven-shared-utils-3.3.4.jar
[ERROR] urls[9] = file:/home/cd/.m2/repository/commons-io/commons-io/2.6/commons-io-2.6.jar
[ERROR] urls[10] = file:/home/cd/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.5/org.eclipse.sisu.inject-0.3.5.jar
[ERROR] urls[11] = file:/home/cd/.m2/repository/com/google/inject/guice/4.2.2/guice-4.2.2-no_aop.jar
[ERROR] urls[12] = file:/home/cd/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar
[ERROR] urls[13] = file:/home/cd/.m2/repository/com/google/guava/guava/25.1-android/guava-25.1-android.jar
[ERROR] urls[14] = file:/home/cd/.m2/repository/org/checkerframework/checker-compat-qual/2.0.0/checker-compat-qual-2.0.0.jar
[ERROR] urls[15] = file:/home/cd/.m2/repository/com/google/errorprone/error_prone_annotations/2.1.3/error_prone_annotations-2.1.3.jar
[ERROR] urls[16] = file:/home/cd/.m2/repository/com/google/j2objc/j2objc-annotations/1.1/j2objc-annotations-1.1.jar
[ERROR] urls[17] = file:/home/cd/.m2/repository/org/codehaus/mojo/animal-sniffer-annotations/1.14/animal-sniffer-annotations-1.14.jar
[ERROR] urls[18] = file:/home/cd/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.26/plexus-interpolation-1.26.jar
[ERROR] urls[19] = file:/home/cd/.m2/repository/org/codehaus/plexus/plexus-component-annotations/2.1.0/plexus-component-annotations-2.1.0.jar
[ERROR] urls[20] = file:/home/cd/.m2/repository/org/apache/commons/commons-lang3/3.8.1/commons-lang3-3.8.1.jar
[ERROR] urls[21] = file:/home/cd/.m2/repository/org/apache/maven/shared/maven-dependency-tree/3.1.0/maven-dependency-tree-3.1.0.jar
[ERROR] urls[22] = file:/home/cd/.m2/repository/org/eclipse/aether/aether-util/1.1.0/aether-util-1.1.0.jar
[ERROR] urls[23] = file:/home/cd/.m2/repository/com/github/shalousun/smart-doc/2.4.9/smart-doc-2.4.9.jar
[ERROR] urls[24] = file:/home/cd/.m2/repository/com/ibeetl/beetl/3.10.0.RELEASE/beetl-3.10.0.RELEASE.jar
[ERROR] urls[25] = file:/home/cd/.m2/repository/org/antlr/antlr4-runtime/4.9.2/antlr4-runtime-4.9.2.jar
[ERROR] urls[26] = file:/home/cd/.m2/repository/com/github/shalousun/qdox/2.0.2/qdox-2.0.2.jar
[ERROR] urls[27] = file:/home/cd/.m2/repository/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar
[ERROR] urls[28] = file:/home/cd/.m2/repository/net/datafaker/datafaker/1.4.0/datafaker-1.4.0.jar
[ERROR] urls[29] = file:/home/cd/.m2/repository/com/github/mifmif/generex/1.0.2/generex-1.0.2.jar
[ERROR] urls[30] = file:/home/cd/.m2/repository/dk/brics/automaton/automaton/1.11-8/automaton-1.11-8.jar
[ERROR] urls[31] = file:/home/cd/.m2/repository/com/github/shalousun/common-util/2.1.4/common-util-2.1.4.jar
[ERROR] urls[32] = file:/home/cd/.m2/repository/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
[ERROR] urls[33] = file:/home/cd/.m2/repository/org/bouncycastle/bcprov-jdk15on/1.70/bcprov-jdk15on-1.70.jar
[ERROR] urls[34] = file:/home/cd/.m2/repository/com/squareup/okhttp3/okhttp/4.10.0/okhttp-4.10.0.jar
[ERROR] urls[35] = file:/home/cd/.m2/repository/com/squareup/okio/okio-jvm/3.0.0/okio-jvm-3.0.0.jar
[ERROR] urls[36] = file:/home/cd/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.5.31/kotlin-stdlib-jdk8-1.5.31.jar
[ERROR] urls[37] = file:/home/cd/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib-jdk7/1.5.31/kotlin-stdlib-jdk7-1.5.31.jar
[ERROR] urls[38] = file:/home/cd/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib-common/1.5.31/kotlin-stdlib-common-1.5.31.jar
[ERROR] urls[39] = file:/home/cd/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib/1.6.20/kotlin-stdlib-1.6.20.jar
[ERROR] urls[40] = file:/home/cd/.m2/repository/org/jetbrains/annotations/13.0/annotations-13.0.jar
[ERROR] urls[41] = file:/home/cd/.m2/repository/com/google/code/gson/gson/2.9.0/gson-2.9.0.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR] 
[ERROR] -----------------------------------------------------
[ERROR] : io.micrometer.core.instrument.docs.MeterDocumentation
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException

Process finished with exit code 1

**Comment by shalousun** [comment]
You could try upgrading to the latest version to see if that resolves the issue.

**Comment by littleCoolD** [comment]
It's resolved. It was a version issue; upgrading to the latest version fixed it.
解决了 版本问题 升级到最新版就好了
