### ISSUE TITLE
Will it be possible to implement reading the return type object from @return in the future?

### ISSUE THREAD

**Issue by littleCoolD** [TongchengOpenSource/smart-doc#508]
## Summary(关于这个pr的描述)

Brief explanation of the feature.

### Basic example(pr的用例)
 /**
    * @return {@link com.test.Result}
    */
If the proposal involves a new or changed API, include a basic code example. Omit this section if it's not applicable.

### Motivation(提出这个pr目的)
The code uses wrapper classes to handle the unified return results, so the return values inside the interface are not what we actually want. Is it possible to directly read the final return type using @return?
代码用包装类处理统一返回结果了 接口里面返回值不是我们真正想要的 是否可以通过@return直接实现读取最后的返回类型

**Comment by shalousun** [comment]
@littleCoolD Why not use ResponseBodyAdvice? This way, you don't need to write it yourself every time. Check out https://smart-doc-group.github.io/#/zh-cn/diy/config?id=responsebodyadvice.

**Comment by littleCoolD** [comment]
@shalousun It's solved.
