### ISSUE TITLE
When using @JsonIgnore in a subclass to ignore a property, it will still output the same-named property from the parent class.

### ISSUE THREAD

**Issue by HKMV** [TongchengOpenSource/smart-doc#509]
## Environment
smart-doc: 2.6.6
spring-boot: 2.7.11

## Expected Result
When using @JsonIgnore in the subclass, it should also ignore the same-named field in the parent class.

## Current Result
The same-named field in the parent class is not ignored.

**Comment by shalousun** [comment]
@HKMV If you're able to handle it, welcome to submit a PR (Pull Request) to contribute to the project.
