### ISSUE TITLE
With smart-doc 2.6.9+torna 1.21.1, there is a description in torna with non-comment validation.

### ISSUE THREAD

**Issue by henyi-c** [TongchengOpenSource/smart-doc#511]
Why does the description include Validate[max:20] and such? I've only used validation annotations, which theoretically should have nothing to do with the comments.
![image](https://github.com/smart-doc-group/smart-doc/assets/84907218/00b75655-ac6c-485b-85a8-eeca2a5cfe6f)

**Comment by shalousun** [comment]
@henyi-c  This is actually a community requirement. Some people want to include the validation rules in the documentation, making it convenient for front-end developers to also perform validation according to these rules. Like you, others might not want to display them. The validation rules are just appended to the comments, and smart-doc has some other things that are also appended after the comments. After all, adding many columns to the parameter table can make the layout quite messy. If you're interested, you can submit a PR (Pull Request) to optimize this by controlling whether or not to display the validation rules appended to the comments—those who need to show the rules can turn it on, and those who don't want to display them can leave it off.
 这个其实也是社区的需求，有的希望把验证规则体现在文档中，方便让前端这些也同样去根据验证规则做一层校验。像你们可能又不想显示。检验规则只是append在注释的后面，smart-doc还有一些其他的东西也是append到注释后面，毕竟参数表格搞很多栏排版就会很乱。如果有兴趣可以提pr优化，控制下入需要显示验证规则的就打开附加到注释，不想显示验证规则的就不加。

**Comment by henyi-c** [comment]
Alright, thank you for the response.
