### ISSUE TITLE
The project is unable to ignore or load the direct dependencies of other packages.

### ISSUE THREAD

**Issue by 347866243** [TongchengOpenSource/smart-doc#514]
## Your Environment(您的使用环境)

* smart-doc version:
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin):
* build tool version(maven or gradle):

## Steps to Reproduce (Bug产生步骤，请尽量提供用例代码)

1.
2.
3.
4.

**Comment by shalousun** [comment]
@lyon-wz 能修改下描述清楚点吗，这个信息太少了，不知道你说的是什么情况

**Comment by zxhprogram** [comment]
> 

我来补充一下，我遇到了相同的问题，忽略配置是无效的
![image](https://github.com/smart-doc-group/smart-doc/assets/20292097/52fc2d52-906d-452e-9b84-9fb2a0a2f269)

**Comment by netdied** [comment]
文档里有提到 ，如果配置了include，Exclude无效。只会加载include里面的内容。

**Comment by abing22333** [comment]
smart-doc的exclude和include都只对指定依赖有效。

比如说，`spring-boot-starter-data-mongodb`中有`spring-data-mongodb`,
当exclude `spring-boot-starter-data-mongodb` 时，不会exclude `spring-data-mongodb`，maven中的exclusion不太一样。

@zxhprogram  @lyon-wz

**Comment by abing22333** [comment]
详细的插件配置文档已更新： https://smart-doc-group.github.io/#/zh-cn/plugins/maven_plugin?id=%e6%8f%92%e4%bb%b6-configuration  @lyon-wz  @zxhprogram 
如果问题已解决请关闭issue  @lyon-wz
