### ISSUE TITLE
RPC documentation supports parsing parameters for generic arrays or generic collections.

### ISSUE THREAD

**Issue by zrlw** [TongchengOpenSource/smart-doc#52]
## Summary
Currently, when parsing generic arrays or generic collections, it directly analyzes the generic type parameters.

### Basic example
```
void method(A<B>[] arrs);
```
Both A and B are non-primitive types, but the current generated RPC documentation only includes members of B in the request parameters, without including members of A.

**Comment by zrlw** [comment]
I reviewed the code and found that the `requestParams` method in `RpcDocBuildTemplate` does not consider generics when handling collections and array branches.
For a simple revision, you could add a condition to check if the `typeName` contains "<" (though this is not rigorous) when processing array types. If it does, skip this branch and proceed with the last branch, which would yield relatively better results, at least listing the members of A.

**Comment by shalousun** [comment]
@zrlw The parsing of code rules by smart-doc is derived from observing the writing of most business codes, and during implementation, some constraints were also made based on the interface coding standards of large companies. The consistent design philosophy is not to become a tool that supports any coding format. Although the above examples can be supported, it is really unnecessary to write business interfaces this way, as it unnecessarily increases the burden on the caller.
