### ISSUE TITLE
Support custom return values in @return.

### ISSUE THREAD

**Issue by InvincibleCaterpillar** [TongchengOpenSource/smart-doc#523]
## Summary(关于这个pr的描述)
We have encapsulated a layer of generic return code in our code, and the content returned by the interface will be packaged. The responseBodyAdvice provided by smart-doc currently only allows the front end to see the structure of Result, and the specific content of data in Result cannot be displayed.
我们在代码中封装了一层通用返回的代码，接口返回的内容会被包装，目前smart-doc提供的responseBodyAdvice，只能够让前端看到Result的结构，result中data具体内容无法显示。

### Motivation(提出这个pr目的)
If you encounter such a situation with generic return encapsulation, you cannot obtain the correct return value content.
如果遇到通用返回封装这种情况，无法获取到正确的返回值内容

**Comment by shalousun** [comment]
@InvincibleCaterpillar 
<img width="497" alt="image" src="https://github.com/smart-doc-group/smart-doc/assets/9592228/56c1ba91-2c5e-4c7e-9fad-740015cea79a">
responseBodyAdvice has other configuration options as well, such as specifying the data field name. Of course, here it is necessary to ensure that your generic source code is recognized. There is support after return, but it is not an easy-to-use feature. You need to write the complete class name to parse, which undoubtedly increases the burden on developers. If adding a configuration is not a problem, it is recommended to submit a pull request to improve the documentation. The documentation project address is:
 
https://github.com/smart-doc-group/smart-doc-group.github.io/blob/master/docs/zh-cn/diy/config.md

**Comment by shalousun** [comment]
same issue https://github.com/smart-doc-group/smart-doc/issues/457

**Comment by InvincibleCaterpillar** [comment]
If the responseBodyAdvice configuration specifies fields, what if the returned data objects are inconsistent across different interfaces? Wouldn't specifying them turn them all into one type of object?
responseBodyAdvice配置中指定字段的话，如果是不同的接口，返回的data对象不一致怎么办呢，指定之后不是都变成一个对象的了吗

**Comment by InvincibleCaterpillar** [comment]
Has the `@return` version been released yet?
`@return`版本已经发布了吗

**Comment by shalousun** [comment]
> If the responseBodyAdvice configuration specifies fields, what if the returned data objects are inconsistent across different interfaces? Wouldn't specifying them turn them all into one type of object?
responseBodyAdvice配置中指定字段的话，如果是不同的接口，返回的data对象不一致怎么办呢，指定之后不是都变成一个对象的了吗

It's not what you think. Your program encapsulates the common structure, but you need to specify the generic field name of the common return type and then directly replace it.
这个不是你理解的意思，你程序对通用结构做封装，但是你要指定下通用返回的范型字段名称，然后直接替换的

**Comment by InvincibleCaterpillar** [comment]
![image](https://github.com/smart-doc-group/smart-doc/assets/134379088/d375f3ff-68b2-4521-ac15-78d12bd76409)
![image](https://github.com/smart-doc-group/smart-doc/assets/134379088/5b10fb13-dd03-46c9-8e02-cc1037e3a382)
我配置了我的通用返回对象，但是Result中的data对象是不确定的，我无法指定字段

**Comment by InvincibleCaterpillar** [comment]
![image](https://github.com/smart-doc-group/smart-doc/assets/134379088/f05345ee-6a0c-498f-b37c-9d9b705f1f96)
![image](https://github.com/smart-doc-group/smart-doc/assets/134379088/d357f95d-67f9-47bb-a9fb-7b9e75cf8a7b)
我配置了我的通用返回对象，但是Result中的data对象是不确定的，我无法指定字段

**Comment by shalousun** [comment]
@InvincibleCaterpillar I see that the fields in your Result class are annotated with comments. If you specify them through responseBodyAdvice, you will find that the fields of this class appear in the documentation, but the field comments you wrote do not appear. This indicates that smart-doc has not read your Result, which might be the reason it cannot be parsed. In Java, generics are erased after compilation; 'T data' actually becomes 'Object data'. Then, smart-doc cannot replace the type of the data field in the Result with the actual type of T, making it unparsable. You can refer to this document to let smart-doc recognize your original code.
我看你的Result类是字段是添加了注释，如果你通过reponseBodyAdvice指定后，你发现文档中有这个类的字段，但是没有你自己写的字段注释，说明你没有让smart-doc读取到你这个Result，这可能就是没发解析原因，java的范型后会被擦除，T data实际上变成了Object data；然后smart-doc无法将Result<T>中的T实际类型去替换data字段的类型，这就无法解析了。可以看下这个文档，让smart-doc能知道你的原始代码，https://smart-doc-group.github.io/#/zh-cn/faq?id=%e6%b3%a8%e9%87%8a%e6%80%8e%e4%b9%88%e6%8f%90%e5%8f%96%e4%b8%8d%e5%88%b0%e5%95%8a%ef%bc%9f

**Comment by InvincibleCaterpillar** [comment]
![image](https://github.com/smart-doc-group/smart-doc/assets/134379088/bd860b7e-4ea1-4f44-b2f3-f17396871e5f)
![image](https://github.com/smart-doc-group/smart-doc/assets/134379088/8b8ac8e6-f9f1-44c2-a69a-e76fee084b10)
The handler class in the second image implements ResponseBodyAdvice, which is used to process the Result class. If I directly return an Object in the controller, can smart-doc trace back to the specific content of the generic type?
第二张图片的handler类实现了ResponseBodyAdvice，用于处理result类，我如果在controller中直接返回Object，smart-doc能够溯源到泛型具体内容吗

**Comment by shalousun** [comment]
@InvincibleCaterpillar For example, the actual effect is pub User get(); when you configure ResponseBodyAdvice, smart-doc will eventually recognize the method as pub Result get(); this is consistent with your desired outcome. However, the prerequisite is that smart-doc can find the source code of the Result class; for specific reasons, see the previous reply.
比如实际效果是pub User get(); 当你配置了ResponseBodyAdvice, smart-doc最终将方法识别成pub Result<User> get(); 这样就和你想要的结果是一样的，但是前提条件是smart-doc能找到Result这个类的源代码，具体原因见前一个回复

**Comment by chenqi146** [comment]
> ![image](https://private-user-images.githubusercontent.com/134379088/248607602-bd860b7e-4ea1-4f44-b2f3-f17396871e5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2MDQ0NTgsIm5iZiI6MTcwMjYwNDE1OCwicGF0aCI6Ii8xMzQzNzkwODgvMjQ4NjA3NjAyLWJkODYwYjdlLTRlYTEtNGY0NC1iMmYzLWYxNzM5Njg3MWU1Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNVQwMTM1NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOTgxMzQ0NTk0ZjZmNTdiZjc4ZWM1MjEzNDEyZDQ2ZDYxZDQ0YmNkMTVmN2YyMjA3YWFiMjM3YTI1MGFlMDAwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PA7a7oQV-ghnqd0B0qFcRleDldFyD8ZdwMbZ3u13htM) ![image](https://private-user-images.githubusercontent.com/134379088/248607801-8b8ac8e6-f9f1-44c2-a69a-e76fee084b10.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2MDQ0NTgsIm5iZiI6MTcwMjYwNDE1OCwicGF0aCI6Ii8xMzQzNzkwODgvMjQ4NjA3ODAxLThiOGFjOGU2LWY5ZjEtNDRjMi1hNjlhLWU3NmZlZTA4NGIxMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNVQwMTM1NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NDc0YTU4YzA5NmRmMTI4NjljYjg5NWRmYjk4MjNjOGMzYTFmYTA2ZGJjY2JjM2Y4OGUxMWQ1NjQyOWQ2ODRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.k5TCrDNh1-oTpHiz2_Bz-r1sMeCLGl8q8e55VD-DnQ4) 

The handler class in the second image implements ResponseBodyAdvice, which is used to process the Result class. If I directly return an Object in the controller, can smart-doc trace back to the specific content of the generic type?
第二张图片的handler类实现了ResponseBodyAdvice，用于处理result类，我如果在controller中直接返回Object，smart-doc能够溯源到泛型具体内容吗

This won't work; smart-doc only scans source code and requires a specific type to be defined.
这个不行, smart-doc只扫描源码, 需要定义具体类型
