### ISSUE TITLE
Unable to generate Dubbo interface documentation.

### ISSUE THREAD

**Issue by liruizi-rsc** [TongchengOpenSource/smart-doc#529]
Using plugin version 2.7.1, both the `smart-doc.json` and `consumer-example.conf` files have been generated, yet I'm still unable to generate the Dubbo interface documentation.
<img width="822" alt="image" src="https://github.com/smart-doc-group/smart-doc/assets/134056636/3f2cac4d-aeeb-44c8-a1dc-99f82f4ef015">
<img width="709" alt="image" src="https://github.com/smart-doc-group/smart-doc/assets/134056636/b63f6473-e36f-481d-94ea-736b0b633d31">
<img width="962" alt="image" src="https://github.com/smart-doc-group/smart-doc/assets/134056636/1bbef7e2-a0fd-45df-88f3-944a1b8457ef">

   <plugin>
                <groupId>com.github.shalousun</groupId>
                <artifactId>smart-doc-maven-plugin</artifactId>
                <version>2.7.1</version>
                <configuration>
                    
                    <configFile>./src/main/reources/smart-doc.json</configFile>
                    
                    <projectName>kcb-apps-api</projectName>
                    
                    <excludes>
                         
                        <exclude>com.alibaba:fastjson</exclude>
                    </excludes>
                    
                    
                    <includes>
                        
                        <include>com.alibaba:fastjson</include>
                    </includes>
                </configuration>
                <executions>
                    <execution>
                        
                        <phase>compile</phase>
                        <goals>
                            <goal>html</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

**Comment by rongyanjuren** [comment]
I logged in with the wrong account, please respond in chat 530, thank you!
这个是我登陆错账号了，请在530中回答，谢谢啦
