### ISSUE TITLE
Unable to generate Dubbo API documentation.

### ISSUE THREAD

**Issue by rongyanjuren** [TongchengOpenSource/smart-doc#530]

**Comment by rongyanjuren** [comment]
529也是我发的，登陆错账号了，请在这个里边回答，谢谢啦

**Comment by Fioooooooo** [comment]
@rongyanjuren 
I haven't been able to reproduce it locally. Could you provide a demo that replicates the issue? If there indeed is a problem, I might be able to attempt a fix.
我在本地没有复现，你可以提供能复现的 demo 吗，确实有问题的话，我或许可以尝试修复

**Comment by shalousun** [comment]
Is your `Service` annotation from Dubbo or Spring? If it's Spring's, it won't work. Only those annotated with Dubbo's annotations or classes having `@Dubbo` in their comments will be scanned.
你的Service注解是dubbo的还是spring的，spring的肯定不行，只有上 有dubbo的注解或者类注释上有@dubbo 才会扫描

**Comment by rongyanjuren** [comment]
> @rongyanjuren I haven't been able to reproduce it locally. Could you provide a demo that replicates the issue? If there indeed is a problem, I might be able to attempt a fix.
我在本地没有复现，你可以提供能复现的 demo 吗，确实有问题的话，我或许可以尝试修复

I've already identified the issue, and it turned out to be a mistake on my part. However, I'm unable to delete this issue now.
我已经找到问题了，是我操作的问题，但是我没办法删除这个issue了

**Comment by rongyanjuren** [comment]
> > 529也是我发的，登陆错账号了，请在这个里边回答，谢谢啦
> 
> 你的Service注解是dubbo的还是spring的，spring的肯定不行，只有上 有dubbo的注解或者类注释上有@dubbo 才会扫描

我已经找到问题了，是我操作的问题，但是我没办法删除这个issue了。。。
