### ISSUE TITLE
When integrating smart-doc in a Dubbo Provider, it results in the generation of duplicated interface documents.

### ISSUE THREAD

**Issue by Fioooooooo** [TongchengOpenSource/smart-doc#531]
## Your Environment (Your Usage Environment)

* smart-doc version: 2.7.1

## Problem Description

When generating RPC interface documentation, `smart-doc` includes non-`default` methods from parent `interfaces` directly into the `methodDocList` to ensure inherited methods are scanned. This approach works appropriately in a `Dubbo API` module integrated with `smart-doc`, as it is necessary to retrieve all methods within the `interface`.

However, this leads to an issue when integrating `smart-doc` in a `Dubbo Provider`: both the implementation class's methods and those of its `interface` are entirely scanned, resulting in duplicate generation of interface documentation.

![image](https://github.com/smart-doc-group/smart-doc/assets/48234109/cbda8daa-5787-487b-91f3-9578c3e013be)

## Affected Versions

`smart-doc` versions from [2.6.9 to 2.7.1] are impacted by this issue.

**Comment by shalousun** [comment]
good
