### ISSUE TITLE
I hope it can read annotations from springfox, springdoc, and swagger.

### ISSUE THREAD

**Issue by shblaze** [TongchengOpenSource/smart-doc#537]
## Summary(关于这个pr的描述)

It is hoped that smart-doc could, by default, interpret annotations from springfox and springdoc. This would leverage the existing annotations in legacy projects. Adopting smart-doc in historical projects might otherwise render the invested code assets (annotations from springfox and springdoc) underutilized. If smart-doc could extract existing annotations and resort to Javadoc comments for those not present, the migration of legacy projects would become significantly more straightforward.
希望smartdoc可以默认读取springfox、springdoc的注解。这样历史项目的注解就会被使用上。历史项目使用smartdoc，会导致原来的代码资产（springfox、sprngdoc的注解）被浪费。如果可以提取已有注解，没有的取javadoc上的注释。历史项目迁移就很容易了

Brief explanation of the feature.

### Basic example(pr的用例)

If the proposal involves a new or changed API, include a basic code example. Omit this section if it's not applicable.

### Motivation(提出这个pr目的)

Why are we doing this? What use cases does it support? What is the expected outcome?

**Comment by shalousun** [comment]
@shblaze The community does not have a support plan for this feature at present. You might consider using Torna's Swagger plugin, which is compatible with older systems.

**Comment by Eli-Xia** [comment]
> @shblaze 这不会支持，你们可以去用torna搞的swagger插件，兼容老的
这块具体应该如何实现? 还望指导
