### ISSUE TITLE
Smart-doc is unable to recognize complex generic types.

### ISSUE THREAD

**Issue by etdoudou** [TongchengOpenSource/smart-doc#538]
![image](https://github.com/smart-doc-group/smart-doc/assets/131353676/5d4a14a5-fe8f-4606-9d83-0708e6ab8727)
![image](https://github.com/smart-doc-group/smart-doc/assets/131353676/560cceed-4c4b-4eca-ba19-80d4f4d4e7b4)
![image](https://github.com/smart-doc-group/smart-doc/assets/131353676/446c8080-ce71-4413-adc6-600ad7b4b823)

![image](https://github.com/smart-doc-group/smart-doc/assets/131353676/23457813-ab7d-4c06-990f-588f8c922977)

Even though the Baomidou page has been configured in the Maven plugin, it's not being recognized.
在maven插件里面也配置了baomidou的page,但是为何无法识别

**Comment by etdoudou** [comment]
![image](https://github.com/smart-doc-group/smart-doc/assets/131353676/a5cea351-ac64-40c4-a7c9-5e8c28c55f24)
I noticed that source code was downloaded during compilation. Could you clarify what situation this refers to?
我看编译的时候也下载了源码，问下这个是啥情况

**Comment by netdied** [comment]
It appears that your `AppVo` class has not been scanned. Please confirm whether the directory containing `AppVo` is being included in the scan.
这个像是你的AppVo 类没有被扫描到。确认下AppVo所在的文件夹是否被扫描。

**Comment by netdied** [comment]
![image](https://github.com/smart-doc-group/smart-doc/assets/20217389/9ba5cfa9-7d90-4ae5-9de3-d4fc50d63fe2)
The parameters of the `Page` class are all present, but the generic type `T` within `List<records>` is being recognized as `Object`.
Page类的参数都是有的 就是List <T> records  T被识别问Object

**Comment by etdoudou** [comment]
Yes, it might require specifying the paths. If the request (`req`) related classes are being scanned successfully, then the issue could lie in the paths configuration for scanning the `AppVo` class.
是的，这个需要指定路径吗？我看了下req都扫描到了
![image](https://github.com/smart-doc-group/smart-doc/assets/131353676/272ece24-727e-4121-a54c-bc744a40d491)

**Comment by netdied** [comment]
Try upgrading to version 2.7.1 and see if that helps. Since the request (`req`) is being scanned, the VO should not be overlooked. You can remove the `customResponseFileds` and `responseBodyAdvice` configuration options.
升级到2.7.1试下呢。req能扫到vo应该不会被忽略才对。 customResposneFileds 和 responseBodyAdvice 配置项可以去掉。

**Comment by etdoudou** [comment]
ok

**Comment by etdoudou** [comment]
Upgrading resolved the issue. It appears to have been a bug in version 2.6.1.
升级就好了。看来是2.6.1的bug

**Comment by etdoudou** [comment]
>Try upgrading to version 2.7.1 and see if that helps. Since the request (req) is being scanned, the VO should not be overlooked. You can remove the customResponseFileds and responseBodyAdvice configuration options.

Thank you. I recall it wasn't like this before... It's probably due to an update at some point.
