### ISSUE TITLE
Ignoring the entire entity using @ignore is inconvenient.

### ISSUE THREAD

**Issue by wanlinMa-163** [TongchengOpenSource/smart-doc#54]
## Summary (Description of this PR)
For the request parameters, I want to ignore the `WebSecurityContextService` class. This class contains many attributes of other objects, and using `@ignore` is very inconvenient as there are too many classes to modify. Is there any method to resolve this?
### Basic Example (Use Case for the PR)
```java
@PostMapping("delete")
public ResultObject deleteConfigMap(
    @RequestParam String configMapName,
    WebSecurityContextService securityContextService
) {}
```

**Comment by netdied** [comment]
Use the latest version to ignore request parameters by configuring `ignoreRequestParams`.
