### ISSUE TITLE
能否支持 RequestBody类中的字段，添加required字段

### ISSUE THREAD

**Issue by lijiawen** [TongchengOpenSource/smart-doc#550]
## Summary(关于这个pr的描述)

Brief explanation of the feature.

### Basic example(pr的用例)
可以增加 @required tag标记，在类属性里增加该tag标记后，渲染为必填字段

If the proposal involves a new or changed API, include a basic code example. Omit this section if it's not applicable.

### Motivation(提出这个pr目的)
解决RequestBody类中字段，在openapi格式文件中没有渲染为required（必填）字段的需求

Why are we doing this? What use cases does it support? What is the expected outcome?

**Comment by shalousun** [comment]
@lijiawen @required tag已经被在新版本中删除了，请使用jsr 30x规范，@required 不属于开源框架规范支持的。

**Comment by lijiawen** [comment]
@shalousun 是 JSR 175 规范么，没有搜到jsr 30或jsr 30x规范。
@required tag 不建议删除，我理解用户没写这个tag，就不启用对应功能就可以了，框架不需要以只覆盖全jsr 规范为标准，而应该是尽可能满足更多的合理需求吧，删除tag这个真的没办法理解。

**Comment by lijiawen** [comment]
@shalousun smart-doc本身也定义了11个tag，为何不允许required 这个tag了呢

**Comment by shalousun** [comment]
> @shalousun smart-doc本身也定义了11个tag，为何不允许required 这个tag了呢

smart-doc并不仅仅是一个工具，我们在工具上做的一些限制也是让使用这开发程序的时候代码更规范，所以我们在非必要情况下绝不造概念误导使用者

**Comment by 9-4-6** [comment]
> jsr 30x规范



> JSR 175 规范么



> @shalousun 是 JSR 175 规范么，没有搜到jsr 30或jsr 30x规范。 @required tag 不建议删除，我理解用户没写这个tag，就不启用对应功能就可以了，框架不需要以只覆盖全jsr 规范为标准，而应该是尽可能满足更多的合理需求吧，删除tag这个真的没办法理解。

我也不太理解，既然生成api接口文档上有这个required字段，就应该可以控制

> @shalousun 是 JSR 175 规范么，没有搜到jsr 30或jsr 30x规范。 @required tag 不建议删除，我理解用户没写这个tag，就不启用对应功能就可以了，框架不需要以只覆盖全jsr 规范为标准，而应该是尽可能满足更多的合理需求吧，删除tag这个真的没办法理解。

我也不太理解

**Comment by netdied** [comment]
参考：https://www.jianshu.com/p/48725b7328c9
JavaEE提供了更丰富参数必填校验， @required 注释不是java规范标准。

**Comment by 9-4-6** [comment]
> 参考：https://www.jianshu.com/p/48725b7328c9 JavaEE提供了更丰富参数必填校验， @required 注释不是java规范标准。

我的意思，不是说新增@required 来对字段进行校验。只是生成接口文档时，Required 为true。
![1698886983950](https://github.com/TongchengOpenSource/smart-doc/assets/32507511/8534f11a-0e0a-41a5-a7d0-770e843a66df)

**Comment by abing22333** [comment]
如果文档上面Required 为true，但是实际接口没有校验该字段，这是表现 (required: true )和行为(传不传值随意)不一致, 建议使用JSR-303规范的@NotNull注解来完成你的要求。
另外，官方尽可能的少自定义tag，都是去兼容主流框架和规范（依赖JSR-303来实现required， 依赖Jackson框架来忽略字段）。如果是通过添加tag来完成很多特性，那和swagger有什么区别呢？注解换成tag? 
@CollectBugs

**Comment by 9-4-6** [comment]
最后一点你说的很有道理 ，按照架构理念是不能新增tag了，违背最初设计思想。
但是 生成的接口文档上，既然有Required 字段，又没办法控制改为true，真的很奇怪


是不是把生成的文档中去掉Required字段。比较合理。









在 2023-11-02 09:27:11，"abing" ***@***.***> 写道：

如果文档上面Required 为true，但是实际接口没有校验该字段，这是表现 (required: true )和行为(传不传值随意)不一致。
另外，官方尽可能的少自定义tag，都是去兼容主流规范（依赖JSR-303来实现required， 依赖Jackson框架来忽略字段）。如果是通过添加tag来完成很多特性，那和swagger有什么区别呢？注解换成tag?

**Comment by 9-4-6** [comment]
最后一点你说的很有道理 ，按照架构理念是不能新增tag了，违背最初设计思想。
但是 生成的接口文档上，既然有Required 字段，又没办法控制改为true，真的很奇怪


是不是把生成的文档中去掉Required字段。比较合理。


字段是否必填。直接在代码注释里面说明就可以









在 2023-11-02 09:27:11，"abing" ***@***.***> 写道：

如果文档上面Required 为true，但是实际接口没有校验该字段，这是表现 (required: true )和行为(传不传值随意)不一致。
另外，官方尽可能的少自定义tag，都是去兼容主流规范（依赖JSR-303来实现required， 依赖Jackson框架来忽略字段）。如果是通过添加tag来完成很多特性，那和swagger有什么区别呢？注解换成tag?

**Comment by abing22333** [comment]
> 如果文档上面Required 为true，但是实际接口没有校验该字段，这是表现 (required: true )和行为(传不传值随意)不一致, 建议使用JSR-303规范的@NotNull注解来完成你的要求。 另外，官方尽可能的少自定义tag，都是去兼容主流框架和规范（依赖JSR-303来实现required， 依赖Jackson框架来忽略字段）。如果是通过添加tag来完成很多特性，那和swagger有什么区别呢？注解换成tag? @CollectBugs

@CollectBugs 上面那段话段话我编辑了几次，不知道你有没有看见最新的。

**Comment by 9-4-6** [comment]
ok，谢谢
















在 2023-11-02 09:40:25，"abing" ***@***.***> 写道：

如果文档上面Required 为true，但是实际接口没有校验该字段，这是表现 (required: true )和行为(传不传值随意)不一致, ***@***.***注解来完成你的要求。 另外，官方尽可能的少自定义tag，都是去兼容主流框架和规范（依赖JSR-303来实现required， 依赖Jackson框架来忽略字段）。如果是通过添加tag来完成很多特性，那和swagger有什么区别呢？注解换成tag? @CollectBugs

@CollectBugs 上面那段话段话我编辑了几次，不知道你有没有看见最新的。

**Comment by netdied** [comment]
openapi目前已修复此问题。新pom如下：
<dependency>
            <groupId>com.ly.smart-doc</groupId>
            <artifactId>smart-doc</artifactId>
            <version>3.0.0</version>
        </dependency>
        
   设置      
   componentType : RANDOM，可依据jsr303生成required 字段
   设置
   componentType : NORMAL，可能不生成required（请求体和返回体用同一个类时无法生成） 
   老版本默认 NORMAL模式。

**Comment by 9-4-6** [comment]
谢谢，已验证
















在 2023-11-02 09:46:30，"Forget" ***@***.***> 写道：

openapi目前已修复此问题。新pom如下：

com.ly.smart-doc
smart-doc
3.0.0


设置
componentType : RANDOM，可依据jsr303生成required 字段
设置
componentType : NORMAL，可能不生成required（请求体和返回体用同一个类时无法生成）
老版本默认 NORMAL模式。
