### ISSUE TITLE
When an interface directly returns a generic type, the generic type cannot be resolved.

### ISSUE THREAD

**Issue by zcfire2017** [TongchengOpenSource/smart-doc#551]
## Summary(关于这个pr的描述)

Brief explanation of the feature.

### Basic example(pr的用例)

If the proposal involves a new or changed API, include a basic code example. Omit this section if it's not applicable.

### Motivation(提出这个pr目的)

Why are we doing this? What use cases does it support? What is the expected outcome?

**Comment by zcfire2017** [comment]
![image](https://github.com/smart-doc-group/smart-doc/assets/34852479/bb5df2f3-1b87-4f38-ae54-8d66ed1c2e56)
![image](https://github.com/smart-doc-group/smart-doc/assets/34852479/a3288986-cdea-4267-8f67-8aba9b187cd8)

**Comment by zcfire2017** [comment]
It seems that directly returning a generic type might not be ideal. I've found that wrapping the generic in an object allows the generic type to be properly recognized.
是不是不应该直接返回泛型呢？我试过用对象包装泛型后是可以识别到泛型类型的

**Comment by zcfire2017** [comment]
![image](https://github.com/smart-doc-group/smart-doc/assets/34852479/1feee2c6-ddb6-48e5-be22-7bb834168ae0)
Indeed, wrapping the generic in an additional object layer resolves the issue, although it does introduce extra complexity. This can be cumbersome, especially when operations like create, update, and delete ideally only require returning a simple status.
这样就可以，需要包装一层对象，但是如果这些写就比较麻烦，毕竟增删改的时候只需要返回一个状态就行了

**Comment by shalousun** [comment]
@zcfire2017 Smart-doc infers documentation based on interface definitions, and it does so at a non-runtime stage of your program. Therefore, it necessitates specifying concrete return objects for generics. You should declare exactly what is being returned – this approach actually makes the interface code more intelligible for readers. However, for legacy projects, implementing such refinements could prove somewhat tedious.
smart-doc是基于接口定义推导，而且是在你程序的非运行时，所以需要在范型上指定具体的返回对象，返回什么指定什么，其实这样看接口代码的人也是最容易看懂的，只是老项目需要优化稍微会蛮烦些。

**Comment by zcfire2017** [comment]
@shalousun How can I specify it? Could you provide an example?

**Comment by shalousun** [comment]
> @shalousun How can I specify it? Could you provide an example?
https://smart-doc-group.github.io/#/zh-cn/start/bestPractice
