### ISSUE TITLE
When using a generic Controller, an "arrayIndexOutOfBoundsException: 1" error occurs, preventing the generation of documentation.

### ISSUE THREAD

**Issue by zhonghangliu** [TongchengOpenSource/smart-doc#554]
## Summary(关于这个pr的描述)
After removing the general class that the business Controller inherited from, the documentation was generated normally. However, if we retain the situation shown in the diagram below, an "arrayIndexOutOfBoundsException: 1" error will be prompted.
将业务Controller继承的通用类删除后，文档正常生成。 但是按照下图保留的情况，会提示arrayIndexOutOfBoundsException: 1错误。

### Basic example(pr的用例)

1、Business Controller
![image](https://github.com/smart-doc-group/smart-doc/assets/16207087/f2255c3a-fb40-4ad6-ac16-99f3a2e3b555)

2、Used a generic Controller
![image](https://github.com/smart-doc-group/smart-doc/assets/16207087/0c0d6f7e-7df6-4a22-b9e9-e91a2fbe2aff)

3、Error Message
![image](https://github.com/smart-doc-group/smart-doc/assets/16207087/629de6c8-3a1f-42e2-8d85-2f23b76d698d)

### Motivation(提出这个pr目的)

In this situation, how can the documentation be generated correctly?

**Comment by shalousun** [comment]
@zhonghangliu Need to wait for support in a later version, as we haven't had this code scenario before, so the support isn't very good.
需要等后面的版本支持，这个代码场景之前我们没有，所以支持不太好

**Comment by zhonghangliu** [comment]
Understood
收到

**Comment by shalousun** [comment]
@zhonghangliu Is it that using the historical version doesn't produce the correct results?
