### ISSUE TITLE
When pushing torna-rpc documentation to torna, it is necessary to define outpath in smart-doc.json.

### ISSUE THREAD

**Issue by tianyuxingxuan** [TongchengOpenSource/smart-doc#556]
你好，我有个疑问请教下，我在上报 rest 接口和 dubbo接口到torna平台，也就是使用输出目标为 torna-rest 和torna-rpc。为什么输出 rest 接口时 smart-doc.json 不需要配置outPath值，而输出 dubbo 接口时需要配置 outPath字段值。我理解二者都不需要生成文档，应该都可以不配置 outPath 字段值。
![image](https://github.com/smart-doc-group/smart-doc/assets/20947910/07e63207-6493-4aad-b96f-de57684d652d)

**Comment by shalousun** [comment]
@tianyuxingxuan 如果能修复，欢迎提pr fix . 贡献要求可参考https://github.com/smart-doc-group/smart-doc/issues/416
