### ISSUE TITLE
@ignore doesn't work

### ISSUE THREAD

**Issue by jackmiking** [TongchengOpenSource/smart-doc#562]
## Your Environment(您的使用环境)

* smart-doc version: 2.7.4
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin): 2.7.4
* build tool version(maven or gradle): maven 3.9.1

## Expected Behavior(您期望的结果)

the class's field with an @ignore tag should not show in doc.

## Current Behavior(当前结果)

still show in doc.

## Steps to Reproduce (Bug产生步骤，请尽量提供用例代码)

1. writting code like this.
``` 
/**
     * 游戏id
     *
     * @ignore
     */
    @ApiModelProperty(value = "游戏id", hidden = true)
    protected Long gameId;
```
2. build with maven:
```
 mvn  smart-doc:openapi -pl :xxxmodule -am
```
3. gameId is still showing.

## Context(Bug影响描述)

@ignore tag doesn't work.

**Comment by jackmiking** [comment]
btw: "游戏id" can be parsed correctly.

**Comment by shalousun** [comment]
> btw: "游戏id" can be parsed correctly.
https://smart-doc-group.github.io/#/zh-cn/start/javadoc?id=_21-ignore%e4%bd%bf%e7%94%a8

**Comment by jackmiking** [comment]
自动回复：你的邮件我已经收到，如果需要回复的我会尽快回复的。感谢你的谅解····

**Comment by jackmiking** [comment]
https://smart-doc-group.github.io/#/start/javadoc?id=_21-ignore-use  Please update this document

**Comment by shalousun** [comment]
> https://smart-doc-group.github.io/#/start/javadoc?id=_21-ignore-use Please update this document

If you're interested in contributing to open source, you can make modifications and contribute，https://github.com/smart-doc-group/smart-doc-group.github.io
