### ISSUE TITLE
The smart-doc build failed to correctly recognize the placeholders.

### ISSUE THREAD

**Issue by hunter-git** [TongchengOpenSource/smart-doc#568]
## Your Environment(您的使用环境)
windows系统 JDK1.8  maven 3.6.1

* smart-doc version: 2.7.1
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin): 2.7.1
* build tool version(maven or gradle): maven 3.6.1

## Expected Behavior(您期望的结果)

Successfully generated the interface documentation.
成功生成接口文档

## Current Behavior(当前结果)

C:\Users\YSTen\.jdks\corretto-1.8.0_382\bin\java.exe -Dmaven.multiModuleProjectDirectory=D:\YSTen\code\cos-base-artf\cms-server-lvp\cms-lvp-epg -Djansi.passthrough=true -Dmaven.home=D:\YSTen\env\apache-maven-3.6.1 -Dclassworlds.conf=D:\YSTen\env\apache-maven-3.6.1\bin\m2.conf "-Dmaven.ext.class.path=C:\Program Files\JetBrains\IntelliJ IDEA 2023.2\plugins\maven\lib\maven-event-listener.jar" "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA 2023.2\lib\idea_rt.jar=65409:C:\Program Files\JetBrains\IntelliJ IDEA 2023.2\bin" -Dfile.encoding=UTF-8 -classpath D:\YSTen\env\apache-maven-3.6.1\boot\plexus-classworlds-2.6.0.jar org.codehaus.classworlds.Launcher -Didea.version=2023.2 -s C:\Users\YSTen\.m2\settings.xml -Dmaven.repo.local=D:\maven\repository -DskipTests=true com.github.shalousun:smart-doc-maven-plugin:2.7.1:markdown
[INFO] Scanning for projects...
Downloading from pub-local-nexus: http://192.168.48.13:8081/repository/public/com/ysten/cms/cms-server-lvp/$%7Brevision%7D/cms-server-lvp-$%7Brevision%7D.pom
Downloading from aliyun-nexus: http://maven.aliyun.com/nexus/content/groups/public/com/ysten/cms/cms-server-lvp/$%7Brevision%7D/cms-server-lvp-$%7Brevision%7D.pom
Downloading from central: https://repo.maven.apache.org/maven2/com/ysten/cms/cms-server-lvp/$%7Brevision%7D/cms-server-lvp-$%7Brevision%7D.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: com.ysten.cms:cms-biz-common:jar -> duplicate declaration of version (?) @ line 112, column 21
[FATAL] Non-resolvable parent POM for com.ysten.cms:cms-lvp-epg:${revision}: Could not transfer artifact com.ysten.cms:cms-server-lvp:pom:${revision} from/to pub-local-nexus (http://192.168.48.13:8081/repository/public/): Connect to 192.168.48.13:8081 [/192.168.48.13] failed: Connection timed out: connect and 'parent.relativePath' points at wrong local POM @ line 5, column 13
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project com.ysten.cms:cms-lvp-epg:${revision} (D:\YSTen\code\cos-base-artf\cms-server-lvp\cms-lvp-epg\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.ysten.cms:cms-lvp-epg:${revision}: Could not transfer artifact com.ysten.cms:cms-server-lvp:pom:${revision} from/to pub-local-nexus (http://192.168.48.13:8081/repository/public/): Connect to 192.168.48.13:8081 [/192.168.48.13] failed: Connection timed out: connect and 'parent.relativePath' points at wrong local POM @ line 5, column 13 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

Process finished with exit code 1

## Steps to Reproduce (Bug产生步骤，请尽量提供用例代码)

1.The parent project versions of each submodule are managed uniformly using placeholders, for example:
```
<parent>
    <groupId>com.ysten.cos</groupId>
    <artifactId>ysten-cos</artifactId>
    <version>${revision}</version>
</parent>
```
2. Then the error mentioned above occurred.

**Comment by shalousun** [comment]
@hunter-git You can test other Maven commands yourself. Actually, this recognition issue is unrelated to smart-doc; the plugin only depends on Maven's API and implements a mojo. The actual operations are still performed by Maven's API. For multi-module Maven projects, you need to use commands based in the root directory to build.

**Comment by hunter-git** [comment]
项目正常的install之类的操作是正常的，但是执行smart-doc相关的命令才会有把${rvision}识别为普通字符串



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年08月11日 10:00 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [smart-doc-group/smart-doc] smart-doc构建未能正确识别占位符 (Issue #568) |

@hunter-git 可以自己测试下mvn命令，其实这个识别和smart-doc没关系，插件也只是依赖maven的API，实现了下mojo，真正操作还是maven的api在操作

**Comment by shalousun** [comment]
@hunter-git For multi-module projects, it's recommended to switch to using Maven commands. Executing on development tools differs from using the original Maven commands. The smart-doc plugin first calls Maven's API to perform compilation, and if the compilation is successful, it then calls smart-doc to generate the documentation. Judging from the error, the main issue seems to be an error during the compilation step.

**Comment by delei** [comment]
> 项目正常的install之类的操作是正常的，但是执行smart-doc相关的命令才会有把${rvision}识别为普通字符串
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2023年08月11日 10:00 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [smart-doc-group/smart-doc] smart-doc构建未能正确识别占位符 (Issue #568) | @hunter-git 可以自己测试下mvn命令，其实这个识别和smart-doc没关系，插件也只是依赖maven的API，实现了下mojo，真正操作还是maven的api在操作 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

It's recommended to check the `pom.xml` files and multi-module dependencies within the project, and to follow the official documentation for configuration. Place the `smart-doc-maven-plugin` configuration in the outermost parent module. You can also refer to my sample project, which is a Maven multi-module project using `${revision}` to manage version numbers uniformly, and this problem has not been reproduced:
https://github.com/delei/smart-doc-dev
建议检查工程中的pom.xml和多模块依赖，并按照[官方文档](https://smart-doc-group.github.io/#/zh-cn/plugins/maven_plugin?id=maven%e5%a4%9a%e6%a8%a1%e5%9d%97%e4%b8%ad%e4%bd%bf%e7%94%a8%e6%8f%92%e4%bb%b6)配置，将 `smart-doc-maven-plugin` 配置在最外层的父模块中。也可以看下我的这个样例工程，也是maven多模块，且使用的 `${revision}`统一管理版本号，并未复现此问题
https://github.com/delei/smart-doc-dev
