### ISSUE TITLE
Is it possible to add support for Open Feign?

### ISSUE THREAD

**Issue by WangFeiwu** [TongchengOpenSource/smart-doc#573]
## Summary(关于这个pr的描述)
The project already has support for Netflix Feign, but since version 9.0 it has been renamed to Open Feign, and the package name has changed from `org.springframework.cloud.netflix.feign.FeignClient` to `org.springframework.cloud.openfeign.FeignClient`, so projects using Open Feign are unable to generate documentation.

Additionally, for interfaces using `@FeignClient` (where JavaDoc is written on the interface), if the implementation class uses `@RestController`, the generated interface cannot read the JavaDoc.
项目已经有Netflix Feign的支持，但是自9.0版本起它改名叫Open Feign了，包名也由org.springframework.cloud.netflix.feign.FeignClient变为org.springframework.cloud.openfeign.FeignClient，因此使用Open Feign的项目无法生成文档。
另外，对于使用@FeignClient的接口（JavaDoc写在接口上），其实现类使用@RestController，这样生成的接口无法读取到JavaDoc。

### Basic example(pr的用例)
```

/**
 * 信息管理
 */
@org.springframework.cloud.openfeign.FeignClient(name = "info")
public interface BasCateApi {
    /**
     * 列表
     * @param paramVo
     * @return
     */
    @PostMapping("/cateList")
    DefaultResult<List<BasCateDto>> list(@RequestBody BasCateListVo paramVo);
}

实现类：

@RestController
public class BasCateClient implements BasCateApi {
    /**
     * 列表
     * @param paramVo
     * @return
     */
    @Override
    public DefaultResult<List<BasCateDto>> list(@Valid BasCateListVo paramVo) {
        return new DefaultResult<>(null);
    }
}
```
### Motivation(提出这个pr目的)
I hope that there can be added support for Open Feign and that it utilizes the JavaDoc of the interfaces.
希望能增加对Open Feign的支持，并使用接口的JavaDoc.

**Comment by shalousun** [comment]
@WangFeiwu If you're interested, you can join in and contribute to the development together.
