### ISSUE TITLE
The documentation generation process did not report any errors with version 2.6.6, but it encountered errors when using version 2.7.4.

### ISSUE THREAD

**Issue by MAKENOTES** [TongchengOpenSource/smart-doc#576]
## Your Environment(您的使用环境)

* smart-doc version:2.7.4
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin):smart-doc-maven-plugin:2.7.4
* build tool version(maven or gradle):maven:3.8.7

## Steps to Reproduce (Bug产生步骤，请尽量提供用例代码)
1.mvn -Dfile.encoding=UTF-8 smart-doc:html

## Context(Bug影响描述)
[INFO] Smart-doc Starting Create API Documentation at: 2023-08-21 18:16:52
[INFO] API documentation is output to => /home/xxx/java/xxx/./src/main/resources/static/doc
[**ERROR**] 
java.lang.RuntimeException: Could not obtain annotations for class: org.springframework.data.mongodb.repository.cdi.MongoRepositoryBean
java.lang.NoClassDefFoundError: jakarta/enterprise/inject/spi/Bean
    at com.power.doc.utils.DocClassUtil.getAnnotations (DocClassUtil.java:317)
    at com.power.doc.template.IRestDocTemplate.defaultEntryPoint (IRestDocTemplate.java:1045)
    at com.power.doc.template.IRestDocTemplate.processApiData (IRestDocTemplate.java:56)
    at com.power.doc.template.SpringBootDocBuildTemplate.getApiData (SpringBootDocBuildTemplate.java:54)
    at com.power.doc.builder.HtmlApiDocBuilder.buildApiDoc (HtmlApiDocBuilder.java:89)
    at com.smartdoc.mojo.HtmlMojo.executeMojo (HtmlMojo.java:48)
    at com.smartdoc.mojo.BaseDocsGeneratorMojo.execute (BaseDocsGeneratorMojo.java:165)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:370)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:298)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:283)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:226)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:407)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:348)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.122 s
[INFO] Finished at: 2023-08-21T18:16:54+08:00
[INFO] ------------------------------------------------------------------------

**Comment by abing22333** [comment]
There is too little information available to reproduce the issue，Please provide additional detail, include the maven configuration, smart-doc configuration，and the minimum code snippet that triggers the bug
可用信息太少了，无法复现。请将maven配置，smart-doc配置，最小出bug代码补充一下。

**Comment by shalousun** [comment]
@MAKENOTES Please provide the Spring Boot version and the MongoDB dependency you are using. This issue with `jakarta/enterprise/inject/spi/Bean` seems to stem primarily from the changes introduced with the upgrade to JDK 17.

**Comment by MAKENOTES** [comment]
> 
1、Both the Spring Boot version and the MongoDB dependency are 3.1.0, and the runtime environment is OpenJDK 17.

 
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.1.0</version>
        <relativePath/> 
    </parent>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-mongodb</artifactId>
        </dependency>


2、smart-doc.json

{
  "outPath": "./src/main/resources/static/doc",
  "serverUrl": "http://localhost:8080",
  "createDebugPage": true,
  "style":"xt256",
  "projectName": "SpringBoot2-Open-Api",
  "isStrict": false,
  "allInOne": true
}

3、pom.xml

            <plugin>
                <groupId>com.github.shalousun</groupId>
                <artifactId>smart-doc-maven-plugin</artifactId>
                <version>2.7.4</version>
                <configuration>
                    
                    <configFile>./src/main/resources/smart-doc.json</configFile>
                    
                    <projectName>接口文档</projectName>
                    
                    <excludes>
                        <exclude>com.xxx:framework</exclude>
                    </excludes>
                    <includes>
                    </includes>
                </configuration>
                <executions>
                    <execution>
                        
                        <phase>compile</phase>
                        <goals>
                            
                            <goal>html</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

**Comment by abing22333** [comment]
Could you please provide the Controller that reproduces the bug along with the associated request and response objects?

**Comment by MAKENOTES** [comment]
>Could you please provide the Controller that reproduces the bug along with the associated request and response objects?

Controller
```

@Slf4j
@RestController
public class HelloController {

    @Resource
    private ISysUserService iSysUserService;

    /**
     * 获取用户信息
     *
     * @param id 用户id
     * @return Rs
     * @apiNote 通过用户的id去查询到用户的详细信息
     */
    @GetMapping("/getUser")
    public Rs<SysUserEntity> getUser(@RequestParam("id") Long id) {
        SysUserEntity sysUserEntity = iSysUserService.getById(id);
        return Rs.success(sysUserEntity);
    }
}
```
SysUserEntity
```
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Table(value = "sys_user", onInsert = MybatisFlexInsertListener.class, onUpdate = MybatisFlexUpdateListener.class)
public class SysUserEntity implements Serializable {

    /**
     * 主键ID
     */
    @Id(keyType = KeyType.Auto)
    private BigInteger id;

    private String name;

    /**
     * 年龄
     */
    private Integer age;

    private String email;

    /**
     * 创建时间戳
     */
    private Long createdAt;

    /**
     * 最后更新时间戳
     */
    private Long updatedAt;

    /**
     * 删除时间戳
     */
    @Column(isLogicDelete = true)
    private Long deletedAt;

    /**
     * 版本
     */
    @Column(version = true)
    private Long version;


}

**Comment by MAKENOTES** [comment]
I found the problem. I shielded the project involving MongoDB code and still reported an error. Then I removed the MongoDB dependency and it didn't report an error anymore.
我发现问题了，我把项目涉及mongodb代码屏蔽，依然报错，然后再把mongodb依赖去掉就不报错了。
```
    <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-data-mongodb</artifactId>
    </dependency>
```

**Comment by shalousun** [comment]
> I found the problem. I shielded the project involving MongoDB code and still reported an error. Then I removed the MongoDB dependency and it didn't report an error anymore.
我发现问题了，我把项目涉及mongodb代码屏蔽，依然报错，然后再把mongodb依赖去掉就不报错了。
> 
> ```
>     <dependency>
>         <groupId>org.springframework.boot</groupId>
>         <artifactId>spring-boot-starter-data-mongodb</artifactId>
>     </dependency>
> ```
You could try excluding `spring-boot-starter-data-mongodb` when using smart-doc by configuring the `exclude` setting, or conversely, specify only the modules you need using the `include` option.
你可以先看用smart-doc的exclude把spring-boot-starter-data-mongodb去掉，或者是include加载自己需要的

**Comment by MAKENOTES** [comment]
```              
                    <excludes>
                        <!--格式为：groupId:artifactId;参考如下-->
                        <!--也可以支持正则式如：com.alibaba:.* -->
                        <exclude>org.springframework.boot:spring-boot-starter-data-mongodb</exclude>
                    </excludes>
```
It seems that the adjustment didn't take effect, as I'm still encountering the same error message. I've confirmed that removing the `spring-boot-starter-data-mongodb` dependency resolves the issue and allows normal operation.

The problem appears similar to the one discussed below, but using `include` did work in my test. Nevertheless, when `include` is left empty and `exclude` is configured, it fails to take effect.
加上了貌似没有生效？依然提示同样错误。 我确认 去掉 spring-boot-starter-data-mongodb 这个依赖，可以正常运行。
问题应该和下面这个差不多，但是 include 试了下是ok的。另外include空，exclude配置了也没有生效。
https://github.com/smart-doc-group/smart-doc/issues/514

**Comment by abing22333** [comment]
I'm unable to reproduce the bug on my end for some reason. If it's convenient, please upload the code to GitHub.
不知道什么原因，我这边复现不了bug, 方便的话请把代码上传到github

**Comment by MAKENOTES** [comment]
> I'm unable to reproduce the bug on my end for some reason. If it's convenient, please upload the code to GitHub.
不知道什么原因，我这边复现不了bug, 方便的话请把代码上传到github

[doc.zip](https://github.com/smart-doc-group/smart-doc/files/12434566/doc.zip)

**Comment by abing22333** [comment]
The reported error object, `org.springframework.data.mongodb.repository.cdi.MongoRepositoryBean`, is part of `spring-boot-mongodb`. Please start by excluding this dependency:

```xml
<exclude>org.springframework.boot:spring-boot-mongodb</exclude>
```

I will investigate further why excluding `spring-boot-starter-data-mongodb` did not yield the expected result.

**Comment by abing22333** [comment]
>The reported error object, `org.springframework.data.mongodb.repository.cdi.MongoRepositoryBean`, is part of `spring-boot-mongodb`. Please start by excluding this dependency:
```xml
<exclude>org.springframework.boot:spring-boot-mongodb</exclude>
```
>I will investigate further why excluding `spring-boot-starter-data-mongodb` did not yield the expected result.

Smart-doc first parses all dependencies and then executes the logic for `exclude` and `include`.
smart-doc是先解析出所有的依赖，再去执行exclude和include的逻辑。

**Comment by abing22333** [comment]
The detailed plugin configuration documentation has been updated.： https://smart-doc-group.github.io/#/zh-cn/plugins/maven_plugin?id=%e6%8f%92%e4%bb%b6-configuration 
If the issue is resolved, please close the ticket.  @MAKENOTES

**Comment by zhangchaoyanggit** [comment]
>The reported error object, `org.springframework.data.mongodb.repository.cdi.MongoRepositoryBean`, is part of `spring-boot-mongodb`. Please start by excluding this dependency:
```xml
<exclude>org.springframework.boot:spring-boot-mongodb</exclude>
```
>I will investigate further why excluding `spring-boot-starter-data-mongodb` did not yield the expected result.


Has this issue been resolved? I am encountering the same problem where adding MongoDB results in an error.
这个问题解决了吗?我也是这个问题 加入mongodb就报错

**Comment by MAKENOTES** [comment]
>The reported error object, `org.springframework.data.mongodb.repository.cdi.MongoRepositoryBean`, is part of `spring-boot-mongodb`. Please start by excluding this dependency:
```xml
<exclude>org.springframework.boot:spring-boot-mongodb</exclude>
```
>I will investigate further why excluding `spring-boot-starter-data-mongodb` did not yield the expected result.
> >  Smart-doc first parses all dependencies and then executes the logic for exclude and include.
smart-doc是先解析出所有的依赖，再去执行exclude和include的逻辑。
> 
> Has this issue been resolved? I am encountering the same problem where adding MongoDB results in an error.

Including any package should resolve the issue.
```
                <plugin>
                    <groupId>com.github.shalousun</groupId>
                    <artifactId>smart-doc-maven-plugin</artifactId>
                    <version>2.7.5</version>
                    <configuration>
                        <!--指定生成文档的使用的配置文件,配置文件放在自己的项目中-->
                        <configFile>${basedir}/src/main/resources/${profiles.smart-doc}</configFile>
                        <!--指定项目名称-->
                        <projectName>接口文档</projectName>
                        <excludes>
                        </excludes>
                        <includes>
                            <include>com.xxx:xxx-common</include>
                        </includes>
                    </configuration>
                    <executions>
                        <execution>
                            <!--如果不需要在执行编译时启动smart-doc，则将phase注释掉-->
                            <phase>compile</phase>
                            <goals>
                                <!--smart-doc提供了html、openapi、markdown等goal，可按需配置-->
                                <goal>html</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
```

**Comment by shalousun** [comment]
bump to latest version
