### ISSUE TITLE
The generated `openapi.json` file does not correctly assign the `format` property to path parameters of the interfaces.

### ISSUE THREAD

**Issue by FeiyuEVE** [TongchengOpenSource/smart-doc#578]
## Your Environment(您的使用环境)

* smart-doc version: 2.7.5
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin): smart-doc-maven-plugin
* build tool version(maven or gradle): maven

## Expected Behavior(您期望的结果)
Under springboot 2.7.1 
```
@PostMapping("/{id}/update")
public Result< Void > update(@PathVariable String id) {

}
```
Using smart-doc to generate openapi.json, the description of this interface in
```
"parameters": {
  "shema" {
    "format": "string",
    "type": "string"
  }
}
```
Causes the function parameter id to be of String type in the springboot client request generated through this openapi.json and openapi-generator

## Current Behavior(当前结果)

Under springboot 2.7.1
```
@PostMapping("/{id}/update")
public Result< Void > update(@PathVariable String id) {

}
```
Using smart-doc to generate openapi.json, the description of this interface in
```
"parameters": {
  "shema" {
    "format": "integer",
    "type": "string"
  }
}
```
The issue results in the parameter `id` being generated as an `Integer` type in the Spring Boot client requests when utilizing `openapi.json` alongside the `openapi-generator`.

**Comment by abing22333** [comment]
i can't reproduce the bug
```json
    "schemas": {
      "string": {
        "format": "string",
        "type": "string"
      }
    }
```
code：
```java

@RestController("test")
public class TestController {
    /**
     * 这个是一个更新接口
     *
     * @param id id
     * @return string
     */
    @PostMapping("/{id}/update")
    public String update(@PathVariable String id) {
        return null;
    }
}

```

pom.xml ：
```xml
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <version>2.7.1</version>
        </dependency> 
    </dependencies>
```

```xml
<plugins>
    <plugin>
        <groupId>com.github.shalousun</groupId>
        <artifactId>smart-doc-maven-plugin</artifactId>
        <version>2.7.5</version>
        <configuration>
            <configFile>./src/main/resources/smart-doc.json</configFile>
        </configuration>
    </plugin>
</plugins> 
```
smart-doc.json:
```json
{
  "outPath": "target/doc"
}
```

**Comment by FeiyuEVE** [comment]
I'll try again

**Comment by FeiyuEVE** [comment]
can you debug the plugin？I want to add a breat on the following function 
```
    public Map<String, Object> buildParametersSchema(ApiParam apiParam) {
        Map<String, Object> schema = new HashMap<>(10);
        String openApiType = DocUtil.javaTypeToOpenApiTypeConvert(apiParam.getType());
        schema.put("type", openApiType);
        if ("file".equals(apiParam.getType())) {
            schema.put("format", "binary");
            schema.put("type", "string");
        } else if ("object".equals(openApiType)) {
            if ("enum".equals(apiParam.getType())) {
                schema.put("enum", apiParam.getEnumValues());
            }
        } else if (ARRAY.equals(apiParam.getType())) {
            if (CollectionUtil.isNotEmpty(apiParam.getEnumValues())) {
                schema.put("type", "string");
                schema.put("items", apiParam.getEnumValues());
            } else {
                schema.put("type", ARRAY);
                Map<String, String> map = new HashMap<>(4);
                map.put("type", "string");
                map.put("format", "string");
                schema.put("items", map);
            }
        } else {
            schema.put("type", apiParam.getType());
            schema.put("format", "integer");
        }
        return schema;
    }
```

**Comment by abing22333** [comment]
> You can reference this document  https://smart-doc-group.github.io/#/zh-cn/plugins/maven-plugin-debug

**Comment by FeiyuEVE** [comment]
The breakpoint has been hit at the function I mentioned previously. For the `apiParam`, the `type` attribute is `string`. Since none of the preceding `if` statements check for `type` being specifically `string`, the flow falls through to the final `else` clause, where it incorrectly sets `type` back to `string` and assigns `format` the value `integer`.

**Comment by abing22333** [comment]
> What this `@PostMapper` annotation? I haven't cross it before

generated by me
```java
 "components": {
    "schemas": {
      "string": {
        "format": "string",
        "type": "string"
      }
    }
  }
```
It seems like my reference was to `parameters`, which makes me think my configuration might not be correct.

**Comment by abing22333** [comment]
@PostMapper 这个是什么注解？我没见过，也没百度出来。

 我生成的文档是

 ```java
 "components": {
    "schemas": {
       "string": {
         "format": "string",
         "type": "string"
       }
     }
   }
 ```

 你的是parameters，感觉我配置不对

**Comment by FeiyuEVE** [comment]
my mistake in the issue, I meant the @PostMapping annotation

**Comment by abing22333** [comment]
> my mistake in the issue, I meant the @PostMapping annotation

can you provide the configuration for smart-doc please?

**Comment by FeiyuEVE** [comment]
```
{
"serverUrl",
"outPath",
"isStrict": false,
"allInOne": true,
"coverOld": true,
"allInOneDocFileName": "index.html",
"packageFilters",
"style":"xt256",
"inlineEnum": true,
"responseBodyAdvice": {
"className": "com.test.test.model.vo.Result"
}
}
```

`Result` is a unified wrapper class for return values.

**Comment by FeiyuEVE** [comment]
Indeed, there is a "string" defined in the "components". However, the "parameters" I mentioned are situated within the properties indexed by the interface's name. Namely,
```
“/test/{id}/update”{
"post":{
"parameters":[
{
"schema": {
"format": "integer",
"type":"string"
}
}
]
}
}
```

**Comment by abing22333** [comment]
I'm not overly familiar with generating OpenAPI specifications myself, and my OpenAPI output doesn't even include the details you've mentioned.
我对生成openapi也不太熟，我的openapi甚至都没有你的这个输出

**Comment by FeiyuEVE** [comment]
![029AAA61](https://github.com/smart-doc-group/smart-doc/assets/9366829/c55999c3-774e-4a2d-99a0-d5c656038568)

**Comment by abing22333** [comment]
> ![029AAA61](https://user-images.githubusercontent.com/9366829/262679886-c55999c3-774e-4a2d-99a0-d5c656038568.png)

If it's convenient, you can upload the code to GitHub, and I can pull the code from there.
如果方便的话，你可以把代码上传到github，我拉代码

**Comment by FeiyuEVE** [comment]
Alright, I'll set up a project to test it. Please give me a moment. Thank you for your patience.

**Comment by FeiyuEVE** [comment]
I might not be able to upload the code to GitHub easily due to company policies. Instead, I forked your smart-doc-demo repository. Then, I adjusted the Spring Boot version to 2.7.1, set the Java version to 1.8, and updated the smart-doc version to 2.7.5, keeping all other configurations unchanged. Afterwards, I made adjustments to the code.
我在公司可能不太好往github传代码
我fork了你的smart-doc-demo
然后调整Springboot版本为2.7.1，java版本为1.8，smart-doc版本为2.7.5，其他配置不变
调整代码：
```
import javax.annotation.Resource;
import javax.validation.Valid;

@PostMapping("/api/v1/{id}/users")
public ResponseResult<User> createUser(@PathVariable String id, @Valid @RequestBody User user) {
     userRepository.add(user);
     return ResponseResult.ok();
 }

然后生成的openapi文档里：
    "/api/v1/{id}/users": {
      "post": {
        "summary": "Create user.",
        "deprecated": false,
        "description": "Create user.",
        "tags": [
          "The type User controller."
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/User_request"
              },
              "examples": {
                "json": {
                  "summary": "test data",
                  "value": "{\n  \"id\": 1,\n  \"firstName\": \"\",\n  \"lastName\": \"\",\n  \"email\": \"\"\n}"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/ResponseResultUser_response"
                },
                "examples": {
                  "json": {
                    "summary": "test data",
                    "value": "{\n  \"success\": true,\n  \"status\": \"200\",\n  \"message\": \"\",\n  \"data\": {\n    \"id\": 1,\n    \"firstName\": \"\",\n    \"lastName\": \"\",\n    \"email\": \"\"\n  },\n  \"timestamp\": \"\"\n}"
                  }
                }
              }
            }
          }
        },
        "operationId": "api-v1-{id}-users-POST",
        **"parameters": [
          {
            "schema": {
              "format": "integer",
              "type": "string"
            },**
            "in": "path",
            "description": "No comments found.",
            "required": true,
            "name": "id"
          }
        ]
      }
    }
```

**Comment by FeiyuEVE** [comment]
There is a field like this, inside which lies the `schema` I mentioned.
```
"parameters": [
{
"schema": {
"format": "integer",
"type": "string"
},
```

**Comment by FeiyuEVE** [comment]
https://github.com/FeiyuEVE/smart-doc-demo/tree/codespace-effective-giggle-r9wrxx5w4525469
The modifications are in this branch now.

**Comment by abing22333** [comment]
> https://github.com/FeiyuEVE/smart-doc-demo/tree/codespace-effective-giggle-r9wrxx5w4525469 The modifications are in this branch now.

reproduce it，however ,I'm not quit familiar with OpenAPI yet; I'll go and learn more about it first

**Comment by FeiyuEVE** [comment]
https://spec.openapis.org/oas/v3.1.0#schema-object
