### ISSUE TITLE
When generating the `openapi.json`, I assigned the same interface description to both the `summary` and `description` fields of the Path Item Object.

### ISSUE THREAD

**Issue by FeiyuEVE** [TongchengOpenSource/smart-doc#580]
## Your Environment(您的使用环境)

* smart-doc version: 2.7.5
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin): smart-doc-maven-plugin
* build tool version(maven or gradle): maven
* springboot: 2.7.1

## Expected Behavior(您期望的结果)
For example, in the smart-doc-demo project, the generated OpenAPI documentation.

    "/api/v1/users": {
      "get": {
        "summary": "Get all users list.",
        "deprecated": false,
        "tags": [
          "The type User controller."
        ],

## Current Behavior(当前结果)

    "/api/v1/users": {
      "get": {
        "summary": "Get all users list.",
        "deprecated": false,
        "description": "Get all users list.",
        "tags": [
          "The type User controller."
        ],

## Possible Solution(bug解决建议)
Summary and description are usually different contents, or you can choose one of them.

OpenAPI official description: https://spec.openapis.org/oas/v3.1.0#path-item-object

## Steps to Reproduce (Bug产生步骤，请尽量提供用例代码)
1. Generate the `openapi.json` using Smart-doc.
2. Utilize the generated `openapi.json` and OpenAPI Generator to produce a Java Spring Boot RESTTemplate-based client.

## Context(Bug影响描述)

When using OpenAPI Generator to generate a client, comments for functions are derived from the `summary` and `description` fields. If the content of these two fields is identical, the generated code will include two lines of duplicate comments.

**Comment by shalousun** [comment]
@FeiyuEVE You're welcome to submit a Pull Request to address this issue. Indeed, improvements to the OpenAPI code generation process greatly benefit from the input of real-world users like yourself who can help refine and enhance its functionality based on practical application scenarios.
