### ISSUE TITLE
The generated openapi.json does not represent the Map type.

### ISSUE THREAD

**Issue by FeiyuEVE** [TongchengOpenSource/smart-doc#581]
## Your Environment(您的使用环境)

* smart-doc version: 2.7.5
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin): smart-doc-maven-plugin
* build tool version(maven or gradle):maven
* springboot: 2.7.1

## Expected Behavior(您期望的结果)
For the Map type, generate the following structure.
{
  "type": "object",
  "additionalProperties": {
    "type": "string"
  }
}
or
{
  "type": "object",
  "additionalProperties": {
    "$ref": "#/components/schemas/ComplexModel"
  }
}

## Current Behavior(当前结果)

{
  "type": "object"
}

## Possible Solution(bug解决建议)

https://spec.openapis.org/oas/v3.1.0#model-with-map-dictionary-properties

## Steps to Reproduce (Bug产生步骤，请尽量提供用例代码)

1. Generate the `openapi.json` using Smart-doc.
2. Utilize OpenAPI Generator and the `openapi.json` to generate a Java Spring Boot RestTemplate client.

## Context(Bug影响描述)

For interfaces with parameters involving maps or return types containing maps, the generated OpenAPI documentation does not exhibit this information, leading to clients produced by OpenAPI Generator having parameters or return values as `Object` type instead of the specific `Map` type.

**Comment by abing22333** [comment]
Smart-doc does not recommend using maps in interfaces by default. Is there a particular reason you must use maps in your scenario?

**Comment by FeiyuEVE** [comment]
It's not a necessity; I have removed the maps from the interfaces.
They were merely for convenience in some scenarios.
不是一定要，我把接口中的map都去掉了
有些场景下省事而已
