### ISSUE TITLE
Doesn't the annotation support text blocks?

### ISSUE THREAD

**Issue by oooopl** [TongchengOpenSource/smart-doc#589]
Similar to this.
`
@PreAuthorize("""
            		xxxx
            """)
`

**Comment by shalousun** [comment]
@kaizen84 
This high-version JDK feature is not supported by Smart-Doc using QDox at the moment, and it may take some time for the community to fix it.
这个高版本的jdk特性，smart-doc使用qdox目前因该是不支持，可能要等段时间社区才能修复。

**Comment by oooopl** [comment]
> @kaizen84 
This high-version JDK feature is not supported by Smart-Doc using QDox at the moment, and it may take some time for the community to fix it.
这个高版本的jdk特性，smart-doc使用qdox目前因该是不支持，可能要等段时间社区才能修复。

那完了，把所有的文本块去掉不现实,qdox 很久没更新了

**Comment by oooopl** [comment]
尴尬了
