### ISSUE TITLE
The documentation shows that both the request body and the response body are {}.

### ISSUE THREAD

**Issue by FeiyuEVE** [TongchengOpenSource/smart-doc#595]
## Your Environment(您的使用环境)

* smart-doc version: 2.7.6
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin): smart-doc-maven-plugin
* build tool version(maven or gradle): maven
* springboot: 2.7.1

## Expected Behavior(您期望的结果)
The documentation includes request body and response body types.

## Current Behavior(当前结果)
The documentation shows that both the request body and the response body are {}.
文档中显示请求体和返回体都是{}

## Steps to Reproduce (Bug产生步骤，请尽量提供用例代码)
1. Use smart-doc-demo to directly generate HTML or OpenAPI documentation.
2. The documentation shows that the request body and response body type definitions are set to {}.

**Comment by shalousun** [comment]
@FeiyuEVE 可以撤回2.7.5看下

**Comment by FeiyuEVE** [comment]
> @FeiyuEVE 可以撤回2.7.5看下

(⊙o⊙)…也没有

**Comment by FeiyuEVE** [comment]
> @FeiyuEVE 可以撤回2.7.5看下

有了

**Comment by shalousun** [comment]
fixed in 2.7.7
