### ISSUE TITLE
When using ResponseBodyAdvice and the interface returns a List structure, generate a response example as an array.

### ISSUE THREAD

**Issue by amazinglzj** [TongchengOpenSource/smart-doc#599]
## Your Environment(您的使用环境)

* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin): 2.7.5
 
## Expected Behavior(您期望的结果)
Pushing Trona-generated response examples is normal.

## Current Behavior(当前结果)
The outermost layer of the Trona-generated response examples is an array structure.

## Steps to Reproduce (Bug产生步骤，请尽量提供用例代码)

1. smart-doc.json
 ```
 "responseBodyAdvice":{
    "className":"com.xxx.vo.Result"
  }
```
2. Controller
```
  public List<xxx> test() {
        return new ArrayList<xxx>();
    }
```
3. Push to torna
   "isResponseArray":1

## Context(Bug影响描述)
The outermost layer of the response examples generated on Torna is an array structure.
```
[
    {
        "code": 0,
        "message": "string",
        "errors": "string",
        "results": [
            {
                "Id": 0
            }
        ]
    }
]
```

**Comment by abing22333** [comment]
I've tested versions 2.7.5, 2.7.4, and 2.7.3 on my end, but I can't reproduce the issue. If it's convenient for you, please fork from this [repository](https://github.com/smart-doc-group/smart-doc-example-cn), submit your code changes, and then @me.

**Comment by abing22333** [comment]
> I've tested versions 2.7.5, 2.7.4, and 2.7.3 on my end, but I can't reproduce the issue. If it's convenient for you, please fork from this [repository](https://github.com/smart-doc-group/smart-doc-example-cn), submit your code changes, and then @me.

I misunderstood; I thought there was a problem with the locally generated HTML.
