### ISSUE TITLE
Every time I push code, the response body data of the generated interface documentation is empty when executing the CI command.

### ISSUE THREAD

**Issue by 1314520lfd** [TongchengOpenSource/smart-doc#607]
## Your Environment(您的使用环境)

* smart-doc version: 2.7.7
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin):
* build tool version(maven or gradle):

## Expected Behavior(您期望的结果)
每次push代码,执行ci命令生成完好接口文档

## Steps to Reproduce (Bug产生步骤，请尽量提供用例代码)

1.
2.
3.
4.

## Context(Bug影响描述)
Every time I push code and execute the CI command to generate interface documentation, the response body data is empty.
每次push代码,执行ci命令生成接口文档的响应体data为空

**Comment by shalousun** [comment]
@1314520lfd 
Do you encounter any issues when generating documentation locally? Could you provide a use case where the problem occurred? In theory, this issue should not be related to CI, as CI also executes mvn commands. You could try running mvn locally to see if it helps.
你本地开发生成有问题吗，可以提供下用例，生成出问题理论和ci没关系，ci执行的应该也是mvn命令，可以mvn本地执行看下

**Comment by 1314520lfd** [comment]
本地生成没有问题，就是线上执行ci的时候为空，可能是在执行ci时没有拉取到对应注释的源码，这个你们那边有遇到过吗？

**Comment by 1314520lfd** [comment]
/**
     * 获取黑名单列表
     * @param groupId groupId或名称
     * @return 黑名单列表数据
     */
    @GetMapping("/list")
    public R<IPage<JarBlackList>> getBlackList(@RequestParam(value = "groupId",required = false) String groupId,
                                               @RequestParam(value = "name",required = false) String name,
                                               @RequestParam(value = "current",required = false) Long current,
                                               @RequestParam(value = "size",required = false) Long size) {
        return jarBlackListService.getBlackList(groupId,name,current,size);
    }
这是我的一个接口样例
smart-doc-deploy-show-doc:
  image: harbor-sys.v5q.cn/xmht/maven:3.3.9-jdk-8withCos
  tags:
    - top
  stage: smart-doc-deploy-show-doc
  script:
    - mvn -X smart-doc:show-doc-rest -pl :branch-manage -am
  only:
    - /^develop.*$/
  
这是我的ci     stage要执行的命令
            <plugin>
                <groupId>com.github.shalousun</groupId>
                <artifactId>smart-doc-maven-plugin</artifactId>
                <version>${smart-doc.version}</version>
                <configuration>
                    
                    <configFile>./src/main/resources/smart-doc.json</configFile>
                    <projectName>branch-manage</projectName>
                    
                    <excludes>
                        
                        
                        <exclude>com.google.guava:guava</exclude>
                    </excludes>
                    
                    
                    <includes>
                        
                        
                        <include>com.alibaba:fastjson</include>
                        
                        <include>com.baomidou:mybatis-plus-extension</include>
                    </includes>
                </configuration>
                <executions>
                    <execution>
                        
                        
                        <goals>
                            
                            <goal>html</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
这是我的插件配置


{
  "serverUrl": "http://{{address}}",
  "isStrict": false,
  "outPath": "./doc",
  "packageFilters": "",
  "projectName": "xx",
  "appToken": "xx",
  "openUrl": "xx",
  "showDocOpenUrl": "xx",
  "showDocApiKey": "xx",
  "showDocApiToken": "xx",
  "apifoxConfig": {
    "authorization": "xx",
    "projectId": "xx",
    "apiOverwriteMode": "ignore",
    "syncApiFolder": "true",
    "apiFolderId": "1",
    "importBasePath": "false"
  },
  "debugEnvName": "测试环境",
  "replace": true,
  "debugEnvUrl": "http://127.0.0.1:7878",
  "customResponseFields": [
    {
      "name": "map",
      "desc": "数据",
      "ownerClassName": "com.alibaba.fastjson.JSONObject",
      "ignore": true,
      "value": "{}"
    }
  ],
  "customRequestFields": [
    {
      "name": "map",
      "desc": "状态码",
      "ownerClassName": "com.alibaba.fastjson.JSONObject",
      "value": "数据",
      "required": false,
      "ignore": true
    }
  ],
  "dataDictionaries": [
    {
      "title": "数据状态",
      "enumClassName": "so.sao.core.enums.Status",
      "codeField": "code",
      "descField": "name"
    },
    {
      "title": "http请求方式",
      "enumClassName": "so.sao.core.enums.HttpMethod",
      "codeField": "code",
      "descField": "name"
    }
  ],
  "errorCodeDictionaries": [
    {
      "title": "业务code",
      "enumClassName": "so.sao.core.tool.api.ResultCode",
      "codeField": "code",
      "descField": "message"
    }
  ],
  "groups": [
  ]
}这是我的smart-doc配置
麻烦您那边看能不能复现一下

**Comment by shalousun** [comment]
@1314520lfd 你目前的信息肯定复现，然后你们用的版本看起来好像不是官方原版的，这个情况之前也没出现过，如果你们查不了，你可以写个能复现的测试项目放在github或者gitee告诉我们，我们用你的demo来测试

**Comment by 1314520lfd** [comment]
我们这个是二开的，后面实在没有方案我会写一个demo的，到时候通知你们去测吧

**Comment by shalousun** [comment]
This issue has not been updated for more than 90 days and will be temporarily closed.
