### ISSUE TITLE
When using @JsonProperty(value = "code") to generate a Postman file, an extra space is added before the parameter name, resulting in " code".

### ISSUE THREAD

**Issue by yangyf520** [TongchengOpenSource/smart-doc#623]
Version in use:
  2.6.1

Problem:
  The parameter uses @JsonProperty(value = "code") for name conversion and smart-doc to generate the Postman file.
  When executing the generated Postman file's interface, an error occurs due to the parameter name having an extra space.

Expectation:
  Remove the space from the beginning of the " code" parameter name.

**Comment by abing22333** [comment]
The latest version has already reached 2.7.5; you can switch to the newest version to check if the bug still exists.

**Comment by yangyf520** [comment]
> 2.7.5
I've tried it, but the same issue persists.

**Comment by yangyf520** [comment]
> The latest version has already reached 2.7.5; you can switch to the newest version to check if the bug still exists.

It's the same issue.

**Comment by delei** [comment]
> Version in use: 2.6.1
>
> Problem: The parameter uses @JsonProperty(value = "code") for name conversion and smart-doc to generate the Postman file. When executing the generated Postman file's interface, an error occurs due to the parameter name having an extra space.
>
> Expectation: Remove the space from the beginning of the " code" parameter name.

It is recommended to follow the template in `.github/ISSUE_TEMPLATE`, to improve the issue description information, and provide specific examples as much as possible, such as the generated `postman.json` file.

**Comment by shalousun** [comment]
@yangyf520 Please provide the use case and a screenshot of the Postman generation. Currently, it seems that if there is no space in the value of @JsonProperty(value = "code"), the issue cannot be reproduced.

**Comment by yangyf520** [comment]
<img width="648" alt="企业微信截图_af3a3453-08b8-4fd0-a7bc-8a698599a9d6" src="https://github.com/TongchengOpenSource/smart-doc/assets/16890816/2e913735-7f6a-4e7d-863a-adf3e1bd745f">

**Comment by yangyf520** [comment]
@JsonProperty(value = "code")
private String companyCode;

Java的Vo里这样配置的

**Comment by yangyf520** [comment]
@PostMapping(value = "/add", produces = MediaType.APPLICATION_JSON_VALUE)
    public String save(@Valid @RequestBody CompaniesVo vo) {
        return companiesService.save(vo).toString();
    }
    
    上边属性是CompaniesVo里的参数

**Comment by shalousun** [comment]
@yangyf520 Using the latest version (2.7.7), I didn't encounter your issue, but if developers hard-code spaces, it indeed causes this kind of problem. A `pr` has been submitted to handle this situation as well.

**Comment by delei** [comment]
> @PostMapping(value = "/add", produces = MediaType.APPLICATION_JSON_VALUE) public String save(@Valid @requestbody CompaniesVo vo) { return companiesService.save(vo).toString(); }
> 
> ```
> 上边属性是CompaniesVo里的参数
> ```

@yangyf520 根据提供的用例，问题已复现，我试着调试下问题

- smart-doc version: 2.7.7

**Comment by delei** [comment]
@yangyf520 Using the latest version (2.7.7), I didn't encounter your issue, but if developers hard-code spaces, it indeed causes this kind of problem. A `pr` has been submitted to handle this situation as well.
