### ISSUE TITLE
Can `customResponseFields` ignore `org.springframework.data.domain.Pageable` in the response?

### ISSUE THREAD

**Issue by yangyf520** [TongchengOpenSource/smart-doc#625]
## Summary(关于这个pr的描述)
When using `org.springframework.data.domain.Pageable` for query pagination, can the returned results overwrite these parameters?
使用org.springframework.data.domain.Pageable做查询分页，返回结果可以覆盖这部分参数么

**Comment by shalousun** [comment]
@yangyf520 Do you not want certain fields to be displayed in the document（是一些字段不想显示在文档中）?

**Comment by shalousun** [comment]
If it's convenient, could you please help with the registration? https://github.com/TongchengOpenSource/smart-doc/issues/12

**Comment by yangyf520** [comment]
<img width="1077" alt="企业微信截图_b514208e-7e13-42b4-9b99-76ec2924ef61" src="https://github.com/TongchengOpenSource/smart-doc/assets/16890816/c5676772-5282-4aab-9e95-3970e3935cd1">

**Comment by yangyf520** [comment]
> @yangyf520 Do you not want certain fields to be displayed in the document（是一些字段不想显示在文档中）?

内容太多没有用途的不用显示，是否可以配置成不显示，如何实现呢，谢谢

**Comment by shalousun** [comment]
`customResponseFields` does support this feature, but a bug appeared in later versions.
customResponseFields是支持这个功能的，不过后来的版本改动中出现了bug

**Comment by yangyf520** [comment]
>`customResponseFields` does support this feature, but a bug appeared in later versions. 
customResponseFields是支持这个功能的，不过后来的版本改动中出现了bug

Which version can be fixed?
哪个版本可以修复呢

**Comment by abing22333** [comment]
> >customResponseFields does support this feature, but a bug appeared in later versions.
 customResponseFields是支持这个功能的，不过后来的版本改动中出现了bug
> 
>Which version can be fixed?
 哪个版本可以修复呢

It has been fixed; it will be available in the next version.
已经修复了，下个版本就可以了
