### ISSUE TITLE
[feature request] The JavaScript used in the HTML documentation should be implemented natively.

### ISSUE THREAD

**Issue by zoze0** [TongchengOpenSource/smart-doc#63]
## Summary (Description of this PR)
The JavaScript in the HTML documentation is implemented natively.

### Motivation (Purpose of this PR)
Sometimes development must occur on an intranet, where the documentation cannot be accessed from the external network, preventing the download of jQuery and web fonts.
The main impact is that the collapsible function of the left-side interface menu is lost.

**Comment by shalousun** [comment]
@jetmit We are not very familiar with the front-end part, and the template was also modified by users. If your company has a front-end team, we suggest that you make the changes yourself and then submit a PR.

**Comment by zoze0** [comment]
> @jetmit We are not very familiar with the front-end part, and the template was also modified by users. If your company has a front-end team, we suggest that you make the changes yourself and then submit a PR.

Well, considering that if more features are to be added, it might still require support from third-party libraries; writing everything in native JavaScript may not be very practical.
This issue needs further consideration.
