### ISSUE TITLE
方法参数有HttpServletResponse，HttpServletRequest 参数，我想屏蔽这个两个参数应该怎么做

### ISSUE THREAD

**Issue by mu-qiao** [TongchengOpenSource/smart-doc#635]

**Comment by mu-qiao** [comment]
方法参数有HttpServletResponse，HttpServletRequest 参数，我想屏蔽这个两个参数应该怎么做

**Comment by netdied** [comment]
用的哪个版本？这两个参数会自动屏蔽的
![image](https://github.com/TongchengOpenSource/smart-doc/assets/20217389/88a74917-f81f-4676-856e-9870458d4f11)

**Comment by mu-qiao** [comment]
2.4.2
![image](https://github.com/TongchengOpenSource/smart-doc/assets/80091862/2f6a13c4-2930-45b1-983e-30b453eda949)
![image](https://github.com/TongchengOpenSource/smart-doc/assets/80091862/6cbc80e2-a4ab-4740-81c8-7b54cc80fa90)

**Comment by mu-qiao** [comment]
使用2.7.7之后这个问题解决了，感谢
