### ISSUE TITLE
How to display the Content-Type of the document interface as application/json?

### ISSUE THREAD

**Issue by Machaing** [TongchengOpenSource/smart-doc#65]
The HTML documents I generated using the Maven plugin display 'application/x-www-form-urlencoded' as the Content-Type for each interface, whether it is annotated with @GetMapping or @PostMapping.

How can I set the Content-Type to application/json?

**Comment by Fioooooooo** [comment]
Can you provide a method example? Additionally, if post and put requests use RequestBody to receive parameters, they will default to displaying application/json.

**Comment by shalousun** [comment]
@Machaing Please submit issues according to the issue template; issues not following this format will be officially declined for processing.
