### ISSUE TITLE
Cannot obtain the comments of inner classes within a class.

### ISSUE THREAD

**Issue by 9-4-6** [TongchengOpenSource/smart-doc#650]
伪代码如下
class  A{

   class c{
    /**
    *  姓名
    */
    private String name;
 
   }

}
name并没有生成

**Comment by abing22333** [comment]
使用的那个版本？是如何使用的？
![image](https://github.com/TongchengOpenSource/smart-doc/assets/50514081/9971a28a-e97d-469e-84c1-574c477dea45)
我自己试一下，这样是可以生成的。

**Comment by 9-4-6** [comment]
> 使用的那个版本？是如何使用的？ ![image](https://user-images.githubusercontent.com/50514081/279608981-9971a28a-e97d-469e-84c1-574c477dea45.png) 我自己试一下，这样是可以生成的。

我是没有直接
