### ISSUE TITLE
The generated OpenAPI includes an extra "type: object" in the generic return objects.

### ISSUE THREAD

**Issue by lovesea6688** [TongchengOpenSource/smart-doc#651]
## Your Environment(您的使用环境)

* smart-doc version: 
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin):2.7.7
* build tool version(maven or gradle):
* jdk version: 11
![image](https://github.com/TongchengOpenSource/smart-doc/assets/8375961/ed525256-e570-4735-9273-c2708a2a004c)
![image](https://github.com/TongchengOpenSource/smart-doc/assets/8375961/ba344012-cc64-4866-b9b3-21a7781e9880)

The generic return has an extra "type: object".
泛型的返回多了一个 type:object

## Steps to Reproduce (Bug产生步骤，请尽量提供用例代码)

1.
2.
3.
4.

**Comment by chenqi146** [comment]
这个是你的UserVo对象

**Comment by lovesea6688** [comment]
> 这个是你的UserVo对象
That's a bug with Knife4j; adding that causes the display to be abnormal, but it's normal without it.
那就是knife4j的BUG，加了这个就显示不正常了，不加就显示正常
