### ISSUE TITLE
It is suggested to add the function of interface classification.

### ISSUE THREAD

**Issue by miaoweibiao** [TongchengOpenSource/smart-doc#654]
例如我在controller上加注解
/**
   *   AAA / BBB
   */

达到效果是 AAA是一个目录，BBB是AAA的子目录

**Comment by chenqi146** [comment]
你看下`group`是否能够满足你这个需求

**Comment by shalousun** [comment]
建议用group，目前也是满足的，AAA / BBB一个书写并不方便，也增加smart-doc解析难度

**Comment by miaoweibiao** [comment]
> 你看下`group`是否能够满足你这个需求

感谢回复，确实是这个东西，group这个可以写在代码上面吗（例如在Controller注释上面，加个@group这种东西）？还是一定要配置在.json配置文件上？

**Comment by miaoweibiao** [comment]
> 建议用group，目前也是满足的，AAA / BBB一个书写并不方便，也增加smart-doc解析难度

感谢回复，另外请问一下，group这个可以写在代码上面吗（例如在Controller注释上面，加个@group这种东西）？还是一定要配置在.json配置文件上？

**Comment by shalousun** [comment]
> > 建议用group，目前也是满足的，AAA / BBB一个书写并不方便，也增加smart-doc解析难度
> 
> 感谢回复，另外请问一下，group这个可以写在代码上面吗（例如在Controller注释上面，加个@group这种东西）？还是一定要配置在.json配置文件上？
现在应该只能写配置，但是配置里的group相对比较灵活，支持正则的

**Comment by miaoweibiao** [comment]
> > > 建议用group，目前也是满足的，AAA / BBB一个书写并不方便，也增加smart-doc解析难度
> > 
> > 
> > 感谢回复，另外请问一下，group这个可以写在代码上面吗（例如在Controller注释上面，加个@group这种东西）？还是一定要配置在.json配置文件上？
> > 现在应该只能写配置，但是配置里的group相对比较灵活，支持正则的

好的，谢谢~
