### ISSUE TITLE
Is there a comprehensive document available

### ISSUE THREAD

**Issue by miaoweibiao** [TongchengOpenSource/smart-doc#655]
@see @mock这种东西，都是我网上搜了很久才知道的功能，官方有没有一个比较全的文档，告诉我们现在都支持什么功能？

**Comment by chenqi146** [comment]
https://smart-doc-group.github.io/#/zh-cn/start/javadoc

**Comment by miaoweibiao** [comment]
> https://smart-doc-group.github.io/#/zh-cn/start/javadoc

谢谢
