### ISSUE TITLE
Support for custom extended parsing, external plugins can be implemented for Smart-Doc.

### ISSUE THREAD

**Issue by netdied** [TongchengOpenSource/smart-doc#656]
## Summary(关于这个pr的描述)
Support for custom extended parsing, external plugins can be implemented for Smart-Doc.
支持自定义扩展解析，外部可以实现smart-doc的插件

### Motivation(提出这个pr目的)
Support for custom extended parsing, external plugins can be implemented for Smart-Doc.
支持自定义扩展解析，外部可以实现smart-doc的插件

**Comment by jingxiang** [comment]
这个比较匹配我的想法，我会在后面实现你这个需求

**Comment by linwumingshi** [comment]
#839
