### ISSUE TITLE
Chinese character encoding issues.

### ISSUE THREAD

**Issue by kevinkeh** [TongchengOpenSource/smart-doc#659]
## Your Environment(您的使用环境)

* smart-doc version:3.0.0
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin): smart-doc-maven-plugin
* build tool version(maven or gradle): maven 3.6.3
* jdk version: 1.8

## Expected Behavior(您期望的结果)

历史原因，代码文件编码为GBK，生成的文档中文部分是乱码的，用mvn -Dfile.encoding=GBK(UTF-8)都不行

## Current Behavior(当前结果)
![image](https://github.com/TongchengOpenSource/smart-doc/assets/30526647/4b438b68-3980-480d-b465-366fc5b54640)

## Steps to Reproduce (Bug产生步骤，请尽量提供用例代码)

1. mvn -Dfile.encoding=GBK smart-doc:html
2.
3.
4.

**Comment by shalousun** [comment]
@kevinkeh You can try modifying the encoding setting in https://github.com/TongchengOpenSource/smart-doc-maven-plugin/blob/master/src/main/java/com/ly/doc/plugin/mojo/BaseDocsGeneratorMojo.java by setting javaProjectBuilder.setEncoding(Charset.DEFAULT_CHARSET) to see if it can solve this problem. If it works, the encoding setting can be made available in future versions. If it doesn't work, there may be no current solution available.

**Comment by kevinkeh** [comment]
@shalousun 修改为javaProjectBuilder.setEncoding("GBK")后，依然乱码，不过我跟踪了下代码，发现这个设置后面并没有使用，在com.ly.doc.builder.HtmlApiDocBuilder#buildApiDoc(com.ly.doc.model.ApiConfig, com.thoughtworks.qdox.JavaProjectBuilder)方法中，创建这个对象时com.ly.doc.builder.ProjectDocConfigBuilder，以及后面com.ly.doc.builder.ProjectDocConfigBuilder#loadJarJavaSource，都是默认写死了utf-8, 我都改成GBK后，问题得到解决。

可以考虑将这个编码做成maven插件的配置项，类似maven-compiler-plugin中config的encoding
