### ISSUE TITLE
Display the basic parent class attributes at the top when generating documentation.

### ISSUE THREAD

**Issue by yangyf520** [TongchengOpenSource/smart-doc#662]
## Summary(关于这个pr的描述)

Display the basic parent class attributes at the top when generating documentation.
基础的父类属性生成文档时显示到最上边

### Basic example(pr的用例)

public class MyDto extends BaseDto implements Serializable {
    private static final long serialVersionUID = 1L;

    /**
     * 主键ID
     */
    private Integer id;
}

@Data
public class BaseDto implements Serializable {
    private static final long serialVersionUID = 1L;

    /**
     * 创建时间
     */
    private LocalDateTime createdAt;

    /**
     * 更新时间
     */
    private LocalDateTime updateAt;
}

生成的API文档时，createdAt都是放到最前边，如下所示：
"createdAt": "2023-11-19T01:23:40",
"id": 1454399,

### Motivation(提出这个pr目的)

继承的属性放到属性最后边

**Comment by shalousun** [comment]
@yangyf520 这个需求实际无解，private Integer id;实际上你也可以放在BaseDto里，这个时候有用户就想放前面了。
