### ISSUE TITLE
JAX-RS array Request Payload cannot generate documentation properly.

### ISSUE THREAD

**Issue by pky920216344** [TongchengOpenSource/smart-doc#666]
## Your Environment(您的使用环境)

* smart-doc version: 3.0.0
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin): 3.0.0
* build tool version(maven or gradle): maven
* jdk version: 1.8
* javax.ws.rs version: 2.1.0

## Expected Behavior(您期望的结果)

```java
@POST
@Path("/foo")
@Consumes({MediaType.APPLICATION_JSON})
@Produces({MediaType.APPLICATION_JSON})
public void create(List<Foo> list) {

}
```
The above code API can be accessed normally and should generate the correct API documentation.
以上代码API能正常访问，应该生成正确的API文档

## Current Behavior(当前结果)

```log
[ERROR] 
java.lang.RuntimeException: Jaxrs rest can't support binding Collection on method create
```

## Possible Solution(bug解决建议)

1. Support for array Request Payload.

## Steps to Reproduce (Bug产生步骤，请尽量提供用例代码)

1. Create a Springboot Jax-RS project
2. Configure the smart-doc-plugin
3. Generate documentation

1. 创建一个Springboot Jax-RS 项目
2. 配置好smart-doc-plugin
3. 生成文档

## Context(Bug影响描述)

The current situation is that we are completely unable to generate API documentation.
It is suggested to make enhancements so that an error in one method does not affect the generation of API for other methods.
现在的情况是完全无法生成API文档。
建议做一下增强，及时某个方法错误不影响其它方法的API生成。

**Comment by shalousun** [comment]
Pull requests are welcome to participate in the co-construction.
欢迎提pr参与共建

**Comment by shalousun** [comment]
@pky920216344 We used the following example for testing, but we were unable to reproduce the results.
我们写用例做测试，无法复现
```
   /**
     * Test
     * @param list
     */
    @POST
    @Path("/foo")
    @Consumes({MediaType.APPLICATION_JSON})
    @Produces({MediaType.APPLICATION_JSON})
    public void create(List<Person> list) {
        System.out.println(list);
    }
```
<img width="1030" alt="image" src="https://github.com/TongchengOpenSource/smart-doc/assets/9592228/867740bc-e24f-4145-9735-e70003fe7629">
