### ISSUE TITLE
Incomplete field validation information retrieval in the Solr framework

### ISSUE THREAD

**Issue by hanxiang-li** [TongchengOpenSource/smart-doc#676]
## Your Environment(您的使用环境)

* smart-doc version: 3.0.0
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin): smart-doc-maven-plugin
* build tool version(maven or gradle): 3.8.1
* jdk version: 11 

In the Solr framework, the entity class is as follows:
在solon框架中，实体类如下：
```
    @NotBlank(message = "请输入账号")
    @Length(min = 5, max = 16, message = "账号最少5位 最多16位")
    private String username;

    @NotBlank(message = "请输入密码")
    @Length(min = 6, max = 18, message = "密码最少六位 最多18位")
    private String password;

    @NotNull(message = "请同意站点协议和隐私政策")
    private Boolean policy;
```
生成的结果如下：
<img width="1246" alt="image" src="https://github.com/TongchengOpenSource/smart-doc/assets/45918130/31a3b0c4-295b-4f9e-9661-04a896130b7c">

Only 'max' with a value of 16 was recognized, without identifying 'min' and 'message'.
只识别了 max 16,没有识别到 min 和 message

**Comment by hanxiang-li** [comment]
Is it possible to add a 'min' minimum value and place the 'message' into the 'description'?
是否可以添加 min最小值，将message放到description 中？

**Comment by shalousun** [comment]
> 是否可以添加 min最小值，将message放到description 中？

新加一栏实际上没有必要，验证属性非常多都拉出来，栏位多看起来很乱
