### ISSUE TITLE
Can you provide a Javadoc parsing for service classes? Some shared development JAR packages are also expected to generate development documentation through Smart-Doc.

### ISSUE THREAD

**Issue by musarona** [TongchengOpenSource/smart-doc#683]
## Summary(关于这个pr的描述)
For example, when developing a toolkit, we hope to automatically generate the toolkit development documentation through a doc tool. The complete documentation is generated by parsing the comments on the implementation classes. The difference from the current controller parsing is that it does not involve URLs.
比如开发个工具包，希望通过doc工具自动形成工具包开发文档。通过对实现类的注释解析完整的文档。和目前controller解析的区别只在于有无url。

**Comment by jingxiang** [comment]
@musarona 你可以参考使用这个：https://github.com/apideploy-team/apideploy-jakarta-client

**Comment by tuichenchuxin** [comment]
I have the same hope. develop a new template like dubbo seems difficult.
我也希望有相同的功能。开发一个类似 dubbo 的 template 似乎不是很容易。

**Comment by shalousun** [comment]
@tuichenchuxin Support can be added in the future. If you are interested, you are also welcome to participate in the community co-building. The implementation idea can refer to #795.

**Comment by jingxiang** [comment]
@tuichenchuxin 也没有那么复杂，有兴趣可以一起探讨下

**Comment by tuichenchuxin** [comment]
@shalousun @jingxiang Thank you very much for your reply. I am very happy to participate in the co-construction of this idea.
