### ISSUE TITLE
Pushing torna results in an empty folder.

### ISSUE THREAD

**Issue by tubtelly** [TongchengOpenSource/smart-doc#684]
# Version

Torna version: 1.23.2
Java version: 1.8
MySQL version: 8.0
Browser: Edge
Smart-doc version (if used): 2.7.7

# Configuration

```json
{
  "isStrict": false,
  "projectName": "myproject",
  "appToken": "xxxxxxxx",
  "openUrl": "http://ip:port/api",
  "replace": true,
  "packageFilters": "com.xxx.*.controller.*",
  "packageExcludeFilters": "com.xxx.*.controller.feign.*",
  "dataDictionaries": [
    {
      "enumClassName": "com.baomidou.mybatisplus.annotation.IEnum",
      "codeField": "value",
      "descField": "desc"
    }
  ],
  "errorCodeDictionaries": [
    {
      "title": "响应码",
      "enumClassName": "com.xxx.common.enums.BizResponseEnum",
      "codeField": "status",
      "descField": "message"
    }
  ]
}
```

# Actual Results

Pushed packageFilters content.
Did not push packageExcludeFilters content, and an empty folder was created.

# Expected Results

Push packageFilters content.
Do not push packageExcludeFilters content, and do not create an empty folder (this is the key point).

**Comment by chenqi146** [comment]
Are you saying that an empty folder was created on torna? Is there a screenshot from torna for reference?

**Comment by tubtelly** [comment]
# Configuration

```json
{
  "isStrict": false,
  "projectName": "myproject",
  "appToken": "xxxxxxxx",
  "openUrl": "http://ip:port/api",
  "replace": true,
  "packageFilters": "com.xxx.*.controller.*",
  "packageExcludeFilters": "com.xxx.*.controller.feign.*",
  "dataDictionaries": [
    {
      "enumClassName": "com.baomidou.mybatisplus.annotation.IEnum",
      "codeField": "value",
      "descField": "desc"
    }
  ],
  "errorCodeDictionaries": [
    {
      "title": "响应码",
      "enumClassName": "com.xxx.common.enums.BizResponseEnum",
      "codeField": "status",
      "descField": "message"
    }
  ]
}
```

![微信图片_20231215182717](https://github.com/TongchengOpenSource/smart-doc/assets/66456003/64726d06-a028-49a5-96db-57389fdcf7ce)

![微信图片_20231215182939](https://github.com/TongchengOpenSource/smart-doc/assets/66456003/ff8b6007-5065-436c-9498-cc9cd533460f)
