### ISSUE TITLE
Can the data type of parameters be customized?

### ISSUE THREAD

**Issue by wuguowei19880907** [TongchengOpenSource/smart-doc#687]
## Summary(关于这个pr的描述)
Can annotations be used to add explanations for parameter types?
可以通过注解增加参数类型的说明吗？

### Basic example(pr的用例)

For example, in the VO object returned by my interface, the id field is as follows:

![image](https://github.com/TongchengOpenSource/smart-doc/assets/19338820/906a165e-7a33-4504-85f2-8a5f9b4fa927)
![image](https://github.com/TongchengOpenSource/smart-doc/assets/19338820/cb733c67-f9bb-473f-b077-129aea893033)

As shown in the image above, I expect the data type of id in the document to be String, which is converted through @JsonFormat(shape = JsonFormat.Shape.STRING), but it displays as int64 in the document.
如上图，我期望id再文档中的数据类型是string，是通过@JsonFormat(shape = JsonFormat.Shape.STRING)转换后的，但文档中显示的是int64。

### Motivation(提出这个pr目的)
I hope to be able to customize the data type through annotations like @Param or other methods.

希望能够通过比如@param注解等方式，能够自定义数据的类型

**Comment by wuguowei19880907** [comment]
@shalousun

**Comment by shalousun** [comment]
> @shalousun
 The @JsonFormat annotation can be supported，If you are interested, you can participate in open source development

**Comment by wuguowei19880907** [comment]
> > @shalousun
> > The @JsonFormat annotation can be supported，If you are interested, you can participate in open source development

并不是需要支持@JsonFormat，而是能不能支持文档自定义参数类型

**Comment by shalousun** [comment]
> > > @shalousun
> > > The @JsonFormat annotation can be supported，If you are interested, you can participate in open source development
> 
> 并不是需要支持@JsonFormat，而是能不能支持文档自定义参数类型


The community is unlikely to consider this approach. Framework standard annotation conversions can be supported, but such non-standard customizations are not good for standardized implementation. Smart-Doc's philosophy is not only as a tool but also as an embracer of industry standards.
社区不太会考虑这种方案，框架标准的注解转换可以支持，这种非标准自定义对规范化实施非常不好，smart-doc的理念不仅是一个工具，通知也是行业规范化的拥抱者。

**Comment by shalousun** [comment]
same as https://github.com/TongchengOpenSource/smart-doc/issues/714
