### ISSUE TITLE
The generation of the smart-doc-dependency.json file requires a switch to be turned on.

### ISSUE THREAD

**Issue by modefang** [TongchengOpenSource/smart-doc#695]
## Summary(关于这个pr的描述)
In version 3.0.1, when pushing documents to Torna, a .smart-doc-dependency.json file will be generated within the project. We hope to implement this as an optional switch instead of generating it by default.
3.0.1 版本推送文档到 torna 会固定在项目里面生成 .smart-doc-dependency.json 文件，希望做成开关的形式不强制生成。

**Comment by Fioooooooo** [comment]
由于 smart-doc 是静态工具，在构建接口文档的同时会生成一份 `.smart-doc-dependency.json` 文件来记录接口的出入参。增量构建文档时，会基于此扫描有变更的接口类，从而避免全量构建文档。

建议可以把此文件一并提交到 git 仓库，团队之间可以共享文档构建进度。

目前如果使用 smart-doc 的项目非基于 git 管理，会忽略此文件的生成。
