### ISSUE TITLE
When the content of package-info.java is empty, it is not possible to generate interface documentation.

### ISSUE THREAD

**Issue by muker-cmd** [TongchengOpenSource/smart-doc#698]
## Your Environment(您的使用环境)
* smart-doc version:2.7.0
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin):smart-doc-maven-plugin
* build tool version(maven or gradle):maven
* jdk version:1.8

## Expected Behavior(您期望的结果)
Normally generate interface documentation.
正常生成接口文档

## Current Behavior(当前结果)
When there is a package-info.java in the directory and its content is empty, it is not possible to generate an interface.

当目录下有package-info.java，且内容为空时，无法生成接口

## Steps to Reproduce (Bug产生步骤，请尽量提供用例代码)
1.目录结构
![image](https://github.com/TongchengOpenSource/smart-doc/assets/66513199/4ace0ad0-1442-443a-8cf1-c76ead64e06b)

2.package-info.java内容全部注释掉
![image](https://github.com/TongchengOpenSource/smart-doc/assets/66513199/81d295f7-b7ee-4b68-8562-e8c331461d45)
结果
![image](https://github.com/TongchengOpenSource/smart-doc/assets/66513199/ab99ac83-57db-43a8-864c-ec12ae60c371)

3.package-info.java内容存在（或者删除package-info.java文件）
![image](https://github.com/TongchengOpenSource/smart-doc/assets/66513199/6be66dd5-95c7-4fb5-8659-d822e6edd45b)
结果
![image](https://github.com/TongchengOpenSource/smart-doc/assets/66513199/23a3d5a6-825b-49b6-9ff2-df78a29fffdd)

## Context(Bug影响描述)

当需要用到package-info.java生成东西时，与smart-doc冲突，导致两者有一个无法使用

**Comment by shalousun** [comment]
<img width="713" alt="image" src="https://github.com/TongchengOpenSource/smart-doc/assets/9592228/1e901063-577c-428c-9c66-d4a9114cda78">
从qdox的这个方法进去，优化下qdox的代码忽略掉package-info.java

**Comment by shalousun** [comment]
@muker-cmd The package-info.java file must contain a valid package name.
java的package-info.java必须要有一个有效的package设置
