### ISSUE TITLE
Spring MVC can't support binding Collection

### ISSUE THREAD

**Issue by hujian19** [TongchengOpenSource/smart-doc#699]
## Your Environment(您的使用环境)

* smart-doc version: 3.0.1
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin): 3.0.1
* build tool version(maven or gradle): Maven
* jdk version: 1.8

## Current Behavior(当前结果)
报错信息：
java.lang.RuntimeException: can't support binding Collection on method confirmOcrResult.
不支持RequestPart注解下的list参数？？？
<img width="1860" alt="image" src="https://github.com/TongchengOpenSource/smart-doc/assets/13942095/d85d682a-43be-4360-b25c-883b3e240e85">

**Comment by shalousun** [comment]
@hujian19 upgrade to latest

**Comment by hujian19** [comment]
@shalousun The previous description was incorrect and has been corrected; the version being used is 3.0.1.

**Comment by git-yqk** [comment]
> 升级到最新版本

![image](https://github.com/TongchengOpenSource/smart-doc/assets/58689093/60a1a90d-0290-4fbc-9c7a-9a3aca6d4a8b)

版本3.0.2似乎遇到了相似的问题，请问有什么解决方案吗？
