### ISSUE TITLE
Parameters like List<@NotBlank String> list; will cause an error.

### ISSUE THREAD

**Issue by YeungCheungTin** [TongchengOpenSource/smart-doc#7]

**Comment by netdied** [comment]
@RequestMapping("/test")
    public R test(List<@NotBlank String> data1){}
这样的写法 在请求时就会
![image](https://user-images.githubusercontent.com/20217389/69897467-7274ee80-1387-11ea-8a52-c69d54e351ab.png)
spring暂时并不会 支持对请求参数验证 @NotBlank 并不会起作用 看
https://github.com/spring-projects/spring-framework/issues/11041

**Comment by netdied** [comment]
The code like
 ```
@RequestMapping("/test") 
public R test(List<@notblank String> data1){}
```
 will throw an exception during the request because Spring does not directly validate request parameters, and @notblank will not take effect.
spring-projects/spring-framework#11041

**Comment by netdied** [comment]
If there are any other issues, please raise another issue. I will close this one.
