### ISSUE TITLE
Some basic encapsulation classes are in the jar package. How can we display annotations within a jar package?

### ISSUE THREAD

**Issue by lulg** [TongchengOpenSource/smart-doc#70]
We have standardized the return results and encapsulated information such as status, message, etc., into the BaseResponse class. This type of information is contained in other jar files. How can we read their annotations?

**Comment by shalousun** [comment]
@lulg Please refer to the wiki on Gitee based on the Chinese documentation, as there are solutions available. Make sure to thoroughly review the documentation.
