### ISSUE TITLE
When the path of PostMapping or GetMapping is empty, the document cannot be output normally.

### ISSUE THREAD

**Issue by shalousun** [TongchengOpenSource/smart-doc#704]
## Your Environment(您的使用环境)

* smart-doc version: 2.6.3 +
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin):
* build tool version(maven or gradle):
* jdk version:

## Current Behavior(当前结果)
When the path of PostMapping or GetMapping is empty, the document cannot be output normally.
当PostMapping和或者GetMapping的path为空时不能正常输出文档

## Steps to Reproduce (Bug产生步骤，请尽量提供用例代码)

1.
2.
3.
4.

**Comment by snappyyouth** [comment]
What is the expected state cover？
