### ISSUE TITLE
It is hoped that Torna's exported can support the export of Postman.

### ISSUE THREAD

**Issue by yangyf520** [TongchengOpenSource/smart-doc#712]
## Summary(关于这个pr的描述)
Currently, Torna cannot export the Postman format, and I have to send it from my local to Postman for testing every time.
目前torna不能导出postman格式，每次还要本地到postman发给测试。

### Motivation(提出这个pr目的)
Testers can export the  Postman for writing automated test scripts.
测试导出最新postman好编写自动测试脚本

**Comment by shalousun** [comment]
@yangyf520 It is advisable to raise an issue with torna
