### ISSUE TITLE
Fields annotated with the @ToStringSerializer annotation are expected to be correctly identified as String types.

### ISSUE THREAD

**Issue by WingGao** [TongchengOpenSource/smart-doc#714]
## Summary(关于这个pr的描述)

Some objects need to be converted to String for transmission.
有些对象需要转为String进行传输

### Basic example(pr的用例)

```java
public class UserLogin {
	@JsonSerialize(using = ToStringSerializer.class)
	private Long id;
}
```
The 'id' here will be identified as `Long`, but the target should be `String`.
这里的id将会被识别为`Long`,目标应该是`String`

**Comment by shalousun** [comment]
Pull requests are welcome for collaboration.
