### ISSUE TITLE
Cannot properly parse an ImmutableMap nested within an enumeration.

### ISSUE THREAD

**Issue by zwll2013** [TongchengOpenSource/smart-doc#72]
After the environment is set up, running the test class generation results in an error:
com.thoughtworks.qdox.parser.ParseException: syntax error @[20,63] in file:/E:/Workspaces/intellij%20idea/oldTg/ITSS/src/main/java/com/easylinkin/bm/constant/DeviceDataExpressionEnum.java
My enum class is as follows:
```
public enum DeviceDataExpressionEnum {
    /**
     * Temperature and Humidity
     */
    SENSIRION("2101", new ImmutableMap.Builder<String, String>() // This line is the so-called 20th line
            .put("temperature", "#temperature#")
            .put("humidity", "#humidity#")
            .build()),

    /**
     * PM2.5
     */
    PM25("2102", new ImmutableMap.Builder<String, String>()
            .put("pm25", "#granularity#")
            .build());
```

**Comment by shalousun** [comment]
@zwll2013 Based on the issue you've reported, it appears to be a problem with qdox, an underlying parsing library used by smart-doc. Qdox occasionally encounters issues when parsing certain code segments during loading. I will report this issue to the qdox developers to see how they address it. However, you can still use smart-doc in plugin mode, which currently does not affect usage and will not disrupt the build process. At present, we do not recommend using unit tests.

**Comment by zwll2013** [comment]
Hello,
I've tried using the plugin method as well, but the error is the same.

Sent from Windows 10 Mail app

**Comment by shalousun** [comment]
@zwll2013 I have run your example under Maven 3.6.3, and the plugin can proceed with execution, whether triggered via command line or within IntelliJ IDEA.
However, it's uncertain if it will execute in the exact same version of the environment you are using. Currently, qdox has encountered several issues with complex enumerations. The foreign author may not necessarily resolve this issue, and if it remains unsolvable, we might have to resort to design patterns to address this usage of enumerations.

The problematic enumerations currently have two drawbacks:

1. The underlying qdox cannot handle them properly, resulting in errors during source code loading and analysis.

2. Moreover, if enumeration data analysis is required, it is also challenging for smart-doc to implement.
