### ISSUE TITLE
Requirement: Import the API documentation directly into YAPI.

### ISSUE THREAD

**Issue by mostcool** [TongchengOpenSource/smart-doc#73]
Requirement
Import the API documentation directly into YAPI.

**Comment by shalousun** [comment]
@mostcool This requirement can only be implemented within the company itself; smart-doc has no plans to directly integrate with other documentation management systems, nor does it have the resources to do so.
Of course, there is also a lack of leadership in the industry to provide a universal standard like OpenAPI, which would allow for integration with smart-doc.
