### ISSUE TITLE
Add a new tag to support openapi extensions

### ISSUE THREAD

**Issue by baboy** [TongchengOpenSource/smart-doc#749]
## Summary(关于这个pr的描述)

Sometimes, user want to export openapi.json by this plugin, and customize some content or do some extra works. the openapi specification support the extention feature. but the smart-doc tags didn't support configure extensions actually.

### Basic example(pr的用例)

If the proposal involves a new or changed API, include a basic code example. Omit this section if it's not applicable.
There is an example for the java comment.

```
/**
     * 注册接口
     * @extension group "ECS"
     * @extension supportRoles ["role1", "role2"]
     * @extension supportMaps {"x":"v1","y":"v2"}
     * @param apiAddArg xxx
     * @apiNote xxx
     * @return
     */
    @PostMapping("/xxx")
    @ResponseBody
    public HttpResponse<IdResult> add(@Validated @RequestBody ApiAddArg apiAddArg, BindingResult br) {
```
and output the content in openapi.json:
```
{
  "paths":"/xxx/interface-delete": {
      "post": {
        "summary": "删除网卡",
        "deprecated": false,
        "tags": [
          "云服务器"
        ],
        "requestBody": {
          ...
        },
        "responses": {
        ...
        },
        "operationId": "xxx-POST",
        "x-group": "ECS",
        "x-supportArray":  ["role1", "role2"],
        "x-supportMaps":  {"x":"v1","y":"v2"}",
        "parameters": [
             ...
        ]
      }
    }
}
```
**it include a "x-group" attribution with prefix **"x-"**.**
It is compatible with openapi specification.

### Motivation(提出这个pr目的)

we can customize a Api Website with openapi.json, and show some special feature with this extension, such as show a new tag, or grouping some interfaces by a extension.

**Comment by shalousun** [comment]
good
