### ISSUE TITLE
Return value field serialization detection

### ISSUE THREAD

**Issue by Fioooooooo** [TongchengOpenSource/smart-doc#75]
## Summary (Description of this PR)
The project uses MybatisPlus for pagination, which has an IPage object. After serialization, it contains many fields that are not used by the business. Therefore, a custom implementation class was written, and the unnecessary fields were marked with @JsonIgnore. The @ignore annotation was also tried, but smart-doc seems not to detect the ignored fields during serialization, resulting in many redundant fields still being displayed in the documentation.
### Basic Example (Example of the PR)
Sample project: https://github.com/fuyitaoqqq/smart-doc-issue-return-type
Sample images:
![Response Param](https://oss.animalcity.cn/image/20201224164841.png)
![Response Param](https://oss.animalcity.cn/image/20201224164917.png)
### Motivation (Purpose of this PR)
It is unclear whether there is a good solution to handle the ignored fields during serialization, and it is hoped that such adaptation can be made.

**Comment by shalousun** [comment]
@fuyitaoqqq support in 2.0.7
