### ISSUE TITLE
The generic type could not be parsed correctly.

### ISSUE THREAD

**Issue by villllllla** [TongchengOpenSource/smart-doc#751]
## Your Environment(您的使用环境)

2.6.5

## Expected Behavior(您期望的结果)
Return generic value.
返回泛型值

## Current Behavior(当前结果)
The generic type could not be parsed correctly
无法正确解析泛型

**Comment by linwumingshi** [comment]
Please update to the latest version (3.0.2) before generating the document.

请先更新到最新版本(3.0.2)后，再生成文档。

**Comment by shalousun** [comment]
@villllllla Since version 2.7.2, the community has fixed this bug. We currently recommend upgrading directly to the latest version 3.0.2.
自2.7.2版本开始社区已经修改了该项bug，当前建议直接升级到最新的3.0.2版本
