### ISSUE TITLE
Errors in handling generic substitution.

### ISSUE THREAD

**Issue by evan0608** [TongchengOpenSource/smart-doc#756]
## Your Environment(您的使用环境)

* smart-doc version: 3.0.2
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin): 3.0.2
* build tool version(maven or gradle): 3.9.2
* jdk version: 17

## Expected Behavior(您期望的结果)
Generic substitution is normal.
泛型替换正常

## Current Behavior(当前结果)
Errors in handling generic substitution
泛型替换异常

## Possible Solution(bug解决建议)
优化替换方法，例如：
![image](https://github.com/TongchengOpenSource/smart-doc/assets/131756046/3f3d7fce-3131-47d7-b682-8548adfdb4d2)

## Steps to Reproduce (Bug产生步骤，请尽量提供用例代码)
代码路径：com/ly/smart-doc/smart-doc/3.0.2/smart-doc-3.0.2-sources.jar!/com/ly/doc/helper/JsonBuildHelper.java:97

泛型替换前，returnType的值为com.alibaba.cola.dto.SingleResponse\<com.xtc.order.framework.WorkflowInstanceDTO\<T\>\>
![image](https://github.com/TongchengOpenSource/smart-doc/assets/131756046/9cc6794f-f09b-413a-b075-b90ad6430b22)
泛型替换后，returnType的值为com.alibaba.cola.dto.SingleResponse\<com.xtc.order.framework.WorkflowInstanceDcom.xtc.order.demo.model.DemoOrderFormO\<com.xtc.order.demo.model.DemoOrderForm\>\>
![image](https://github.com/TongchengOpenSource/smart-doc/assets/131756046/16eaad97-6d95-4b4c-9c55-fc6f9884574a)

3.以下是一个简化的代码测试用例：
```
/**
 * 流程基础controller类
 *
 * @param <T> 表单数据类型
 */
public abstract class WorkflowController<T> {

    /**
     * 流程详情
     *
     * @param instanceId the instanceId
     * @return the single response
     */
    @GetMapping("/{instanceId}")
    public WorkflowInstanceDTO<T> xtcInfo(@PathVariable("instanceId") String instanceId) {
        T data = info(instanceId);
        WorkflowInstanceDTO<T> workflowInstanceDTO = new WorkflowInstanceDTO<>();
        workflowInstanceDTO.setData(data);
        return workflowInstanceDTO;
    }

    public abstract T info(String instanceId);
}
```

```
/**
 * 示例订单审批接口实现
 */
@RestController
@RequestMapping("/api/order/demo/workflow")
public class DemoOrderWorkflowApiController extends WorkflowController<DemoOrderForm> {

    @Override
    public DemoOrderForm info(String instanceId) {
        return new DemoOrderForm();
    }
}
```

```
/**
 * 示例订单表单数据
 */
@Data
public class DemoOrderForm {
    /**
     * 订单id
     */
    private String id;

    /**
     * 订单编号
     */
    private String orderNo;
}
```

```
/**
 * 工作流实例
 * @param <T> 表单数据
 */
@Getter
@Setter
public class WorkflowInstanceDTO<T> {
    /**
     * 实例ID
     */
    private String id;

    /**
     * 表单数据
     */
    private T data;
}
```

## Context(Bug影响描述)
响应参数无法正确生成接口文档

**Comment by shalousun** [comment]
@evan0608 
Please provide more comprehensive test cases to facilitate the community to reproduce and fix.
请提供更加完善的用例方便社区好复现和修复

**Comment by evan0608** [comment]
邮件已收到

**Comment by evan0608** [comment]
> @evan0608 Please provide more comprehensive test cases to facilitate the community to reproduce and fix. 请提供更加完善的用例方便社区好复现和修复

你好，我在最后补充了测试代码可复现该问题

**Comment by evan0608** [comment]
邮件已收到
