### ISSUE TITLE
Response entity type ignores fields (fields inherit from non modifiable parent class, from mybaits flex)

### ISSUE THREAD

**Issue by Hans-Wu-cn** [TongchengOpenSource/smart-doc#763]
## Summary

When the response entity type inherits Model<T>from mybatis flex, the generated document will have many extra fields. If it is possible to ignore certain classes by configuring them to not generate related documents, it would be better
![image](https://github.com/TongchengOpenSource/smart-doc/assets/50405154/0f6b4058-4834-44f5-b26a-8c7ff870f405)
![image](https://github.com/TongchengOpenSource/smart-doc/assets/50405154/bbe07e44-d3cf-41b2-ae34-5ab5a7693f92)

## development environment
java:21
smart-doc:3.0.2
mybatis-flex:1.7.9

**Comment by shalousun** [comment]
@Hans-Wu-cn There are two ways to ignore response fields, one is using JSONType, for example:
```
@JSONType(ignores ={"current", "size", "orders", "hitCount", "searchCount", "pages","optimizeCountSql"})
@JsonIgnoreProperties({"current", "size", "orders", "hitCount", "searchCount", "pages","optimizeCountSql"})
public class MybatisPlusPage<T> extends Page<T> {
    // ...
}
```
Another way to configure is through customResponseFields, for example:
````
{
    "customResponseFields": [
        {
            "name": "code",
            "desc": "response code",
            "ownerClassName": "org.springframework.data.domain.Pageable",
            "ignore": true,
            "value": "00000"
        }
    ]
}
```

**Comment by Hans-Wu-cn** [comment]
> 有两种方法可以忽略响应字段，一种是使用 JSONType，例如：
> 
> ```
> @JSONType(ignores ={"current", "size", "orders", "hitCount", "searchCount", "pages","optimizeCountSql"})
> @JsonIgnoreProperties({"current", "size", "orders", "hitCount", "searchCount", "pages","optimizeCountSql"})
> public class MybatisPlusPage<T> extends Page<T> {
>     // ...
> }
> ```
> 
> 另一种配置方法是通过 customResponseFields，例如：
> 
> ```
> {
>     "customResponseFields": [
>         {
>             "name": "code",
>             "desc": "response code",
>             "ownerClassName": "org.springframework.data.domain.Pageable",
>             "ignore": true,
>             "value": "00000"
>         }
>     ]
> }
> ```
> ```



> 有两种方法可以忽略响应字段，一种是使用 JSONType，例如：
> 
> ```
> @JSONType(ignores ={"current", "size", "orders", "hitCount", "searchCount", "pages","optimizeCountSql"})
> @JsonIgnoreProperties({"current", "size", "orders", "hitCount", "searchCount", "pages","optimizeCountSql"})
> public class MybatisPlusPage<T> extends Page<T> {
>     // ...
> }
> ```
> 
> 另一种配置方法是通过 customResponseFields，例如：
> 
> ```
> {
>     "customResponseFields": [
>         {
>             "name": "code",
>             "desc": "response code",
>             "ownerClassName": "org.springframework.data.domain.Pageable",
>             "ignore": true,
>             "value": "00000"
>         }
>     ]
> }
> ```
> ```

After modifying according to the second method, it still exists in the document. I'm not sure if it's because I'm using a solo framework?
```
{
  "framework": "solon",
  "allInOne": true,
  "createDebugPage": true,
  "inlineEnum": true,
  "recursionLimit": 2,
  "allInOneDocFileName": "murky-admin-doc.html",
  "increment": true,
  "showValidation": true,
  "requestBodyAdvice": {
    "className": "cn.murky.core.web.ApiResult"
  },
  "ignoreRequestParams": [
    "com.mybatisflex.core.activerecord.Model"
  ],
  "customResponseFields": [
    {
      "ownerClassName": "com.mybatisflex.core.activerecord.Model",
      "ignore": true
    },{
      "ownerClassName": "com.mybatisflex.core.activerecord.query.QueryModel",
      "ignore": true
    },{
      "ownerClassName": "com.mybatisflex.core.query.QueryWrapper",
      "ignore": true
    },{
      "ownerClassName": "com.mybatisflex.core.query.BaseQueryWrapper",
      "ignore": true
    }
  ],
  "groups": [
    {
      "name": "授权模块",
      "apis": "cn.murky.admin.auth.controller.*"
    },
    {
      "name": "系统管理模块",
      "apis": "cn.murky.admin.system.biz.controller.*"
    },
    {
      "name": "租户管理模块",
      "apis": "cn.murky.admin.tenant.biz.controller.*"
    },
    {
      "name": "定时任务管理",
      "apis": "cn.murky.admin.quartz.controller.*"
    }
  ],
  "outPath": "./src/main/resources/static/doc"
}
```
![image](https://github.com/TongchengOpenSource/smart-doc/assets/50405154/a23ab1e7-f99d-4f64-81ff-c18a757c9b57)
![image](https://github.com/TongchengOpenSource/smart-doc/assets/50405154/90642733-4c4a-4699-bdf2-8ddd7d312fe8)
![image](https://github.com/TongchengOpenSource/smart-doc/assets/50405154/9a710e68-5b71-4834-942d-9a5826650623)

Fields from the QueryModel in the graph
