### ISSUE TITLE
When using with Solon, non controller comments are also loaded into the document

### ISSUE THREAD

**Issue by Hans-Wu-cn** [TongchengOpenSource/smart-doc#766]
## Your Environment(您的使用环境，您期望的结果，社区已开启国际化推广，请文心一言、讯飞星火等辅助翻译成英文，减少社区开发者的工作)

* smart-doc version: 3.0.2
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin): 3.0.2
* build tool version(maven or gradle): maven
* jdk version: 21

## Expected Behavior(您期望的结果，社区已开启国际化推广，请用文心一言、讯飞星火等辅助翻译成英文，减少社区开发者的工作)
Non controller comments are not loaded into gold documents

## Context(Bug影响描述，社区已开启国际化推广，请用文心一言、讯飞星火等辅助翻译成英文，减少社区开发者的工作)
Non controller comments are loaded into the document, such as comments in interceptors and comments in services
![image](https://github.com/TongchengOpenSource/smart-doc/assets/50405154/2d25086e-859d-44ea-b0dc-c69f3197c81b)
![image](https://github.com/TongchengOpenSource/smart-doc/assets/50405154/428fcbb7-935d-4096-af0d-02d2a002a08b)

**Comment by Hans-Wu-cn** [comment]
I have found the cause of the problem, as the Solon was configured to register the Component annotation together with the registration annotation. However, the interceptor and various services also use the Component, which caused this problem. May I ask if this Component has any other functions and if it can be removed
![image](https://github.com/TongchengOpenSource/smart-doc/assets/50405154/63f41f65-17b4-4a8f-9d94-08e811ff6309)

But if you don't register him, in some cases, the documents may not be obtained correctly
![image](https://github.com/TongchengOpenSource/smart-doc/assets/50405154/ed3a3bef-7cd8-4bc4-9a54-6cc937e2024b)

I wonder if it's possible to give up assembling a JavaClass without apiMethodDocs. If this meets your requirements, I will submit a PR

**Comment by noear** [comment]
Solon when developed using the gateway pattern. The '@Component' and '@Mapping' annotations are used. These components do not automatically enter the routing system and can be optionally added to the gateway.

It looks like this (notice the last line)：

```java
@Mapping("/api/v3/app/**")
@Component
public class ApiGateway3x extends UapiGateway {
    @Override
    protected void register() {
        filter(new BreakerFilter()); //融断

        before(new StartHandler()); //开始计时
        before(new ParamsParseHandler()); //参数解析
        before(new ParamsSignCheckHandler(new Md5Encoder())); //参数签名较验
        before(new ParamsRebuildHandler(new AesDecoder())); //参数重构

        after(new OutputBuildHandler(new AesEncoder())); //输出构建
        after(new OutputSignHandler(new Md5Encoder())); //输出签名
        after(new OutputHandler()); //输出
        after(new EndBeforeLogHandler()); //日志
        after(new EndHandler("v3.api.app")); //结束计时

        //添加一批具体的接口处理Bean
        addBeans(bw -> "api".equals(bw.tag()));
    }
}
```

**Comment by noear** [comment]
It's okay to remember the early days. If not, delete it first

**Comment by shalousun** [comment]
@Hans-Wu-cn Classes annotated with @component can be discarded in the absence of a router.

**Comment by Hans-Wu-cn** [comment]
#771 
Which version will it be released in
