### ISSUE TITLE
If code similar to @Validated(GenerateDataByPlanDateGroup.class) is detected, then only the fields marked with GenerateDataByPlanDateGroup should be included in the generated documentation.

### ISSUE THREAD

**Issue by baichoulishang** [TongchengOpenSource/smart-doc#791]
如果检测到类似 @Validated(GenerateDataByPlanDateGroup.class) 的代码，那么生成文档的时候，只生成GenerateDataByPlanDateGroup标记的那些字段

**Comment by shalousun** [comment]
@baichoulishang Please create an issue according to the official template and also provide the translation in English. 
The community has launched international promotion, and in the future, we will no longer process issues and pull requests submitted in Chinese. Submissions in Chinese have added a lot of workload to the community.

**Comment by baichoulishang** [comment]
If code similar to @Validated(GenerateDataByPlanDateGroup.class) is detected, then only the fields marked with GenerateDataByPlanDateGroup should be included in the generated documentation.

**Comment by shalousun** [comment]
Smart-doc supports group validation,the test case here: https://github.com/smart-doc-group/smart-doc-example-cn/blob/master/src/main/java/com/power/doc/controller/jsr/ValidatorTestController.java. We're not familiar with your group validation use case based on the situation you described, so please provide a reproducible example.

**Comment by q454578219** [comment]
@shalousun I have also encountered this problem too.
+ Controller
```java
public Response update(@RequestBody @Validated({UpdateGroup.class}) IllegalBuildReportParam szjfIllegalBuildReport)
```

+ Param
```java
public class IllegalBuildReportParam implements Serializable {
	private static final long serialVersionUID = 1L;

	/**
     * 违建举报id（主键）2
     */
	@NotBlank(message="id不得为空",groups = {UpdateGroup.class})
	@Null(message = "新增不能指定id",groups = {AddGroup.class})
	private String id;
	/**
     * 违建位置
     */
	@NotBlank(message="位置不得为空")
	private String buildLocation;
}
```
+ torna
![1726280244941](https://github.com/user-attachments/assets/f65f895e-76d6-4aa8-95b7-c4070e1bda9e)

the field "buildLocation" is a always required field,but it is show not required

**Comment by linwumingshi** [comment]
> @shalousun I have also encountered this problem too. Controller public Response update(@RequestBody @validated({UpdateGroup.class}) IllegalBuildReportParam szjfIllegalBuildReport) Param public class IllegalBuildReportParam implements Serializable { private static final long serialVersionUID = 1L;
> 
> ```
> /**
>  * 违建举报id（主键）2
>  */
> @NotBlank(message="id不得为空",groups = {UpdateGroup.class})
> @Null(message = "新增不能指定id",groups = {AddGroup.class})
> private String id;
> /**
>  * 违建位置
>  */
> @NotBlank(message="位置不得为空")
> private String buildLocation;
> ```
> 
> } torna ![1726280244941](https://private-user-images.githubusercontent.com/38492901/367480649-f65f895e-76d6-4aa8-95b7-c4070e1bda9e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyODMwMjIsIm5iZiI6MTcyNjI4MjcyMiwicGF0aCI6Ii8zODQ5MjkwMS8zNjc0ODA2NDktZjY1Zjg5NWUtNzZkNi00YWE4LTk1YjctYzQwNzBlMWJkYTllLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE0VDAyNTg0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzMDNhYTBkMjAwOWYyNjMzM2M5ZmQ5MTQ1ZTE5ZjVmY2I1ZTg5YTQ0MGU5ZjA2MzZhYzM1YmQ2ZGNlNjg2MWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Cr2iDXDcDIUKI-eG75SsikBpK8oZ-w12rd1LVhkkF7A)
> 
> the field "buildLocation" is a always required field,but it is show not required





It seems that the behavior you're encountering is related to how JSR 303 handles validation groups. When you specify a validation group, JSR 303 does not automatically include the `Default` group. If you want the `buildLocation` field to be always required, even in specific validation groups, there are two possible solutions:

1. Make `UpdateGroup` extend the `Default` group so that the default validation is included.
2. Add the `Default` group explicitly in the `@Validated` annotation alongside the `UpdateGroup`.

The result you're seeing from smart-doc is correct based on this behavior.

---

**Comment by linwumingshi** [comment]
@q454578219 

It seems that the behavior you're encountering is related to how JSR 303 handles validation groups. When you specify a validation group, JSR 303 does not automatically include the `Default` group. If you want the `buildLocation` field to be always required, even in specific validation groups, there are two possible solutions:

1. Make `UpdateGroup` extend the `Default` group so that the default validation is included.
2. Add the `Default` group explicitly in the `@Validated` annotation alongside the `UpdateGroup`.

The result you're seeing from smart-doc is correct based on this behavior.

---

**Comment by q454578219** [comment]
> > @shalousun I have also encountered this problem too. Controller public Response update(@RequestBody @validated({UpdateGroup.class}) IllegalBuildReportParam szjfIllegalBuildReport) Param public class IllegalBuildReportParam implements Serializable { private static final long serialVersionUID = 1L;
> > ```
> > /**
> >  * 违建举报id（主键）2
> >  */
> > @NotBlank(message="id不得为空",groups = {UpdateGroup.class})
> > @Null(message = "新增不能指定id",groups = {AddGroup.class})
> > private String id;
> > /**
> >  * 违建位置
> >  */
> > @NotBlank(message="位置不得为空")
> > private String buildLocation;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > } torna ![1726280244941](https://private-user-images.githubusercontent.com/38492901/367480649-f65f895e-76d6-4aa8-95b7-c4070e1bda9e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyODMwMjIsIm5iZiI6MTcyNjI4MjcyMiwicGF0aCI6Ii8zODQ5MjkwMS8zNjc0ODA2NDktZjY1Zjg5NWUtNzZkNi00YWE4LTk1YjctYzQwNzBlMWJkYTllLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE0VDAyNTg0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzMDNhYTBkMjAwOWYyNjMzM2M5ZmQ5MTQ1ZTE5ZjVmY2I1ZTg5YTQ0MGU5ZjA2MzZhYzM1YmQ2ZGNlNjg2MWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Cr2iDXDcDIUKI-eG75SsikBpK8oZ-w12rd1LVhkkF7A)
> > the field "buildLocation" is a always required field,but it is show not required
> 
> It seems that the behavior you're encountering is related to how JSR 303 handles validation groups. When you specify a validation group, JSR 303 does not automatically include the group. If you want the field to be always required, even in specific validation groups, there are two possible solutions:`Default``buildLocation`
> 
> 1. Make  extend the  group so that the default validation is included.`UpdateGroup``Default`
> 2. Add the  group explicitly in the  annotation alongside the .`Default``@Validated``UpdateGroup`
> 
> The result you're seeing from smart-doc is correct based on this behavior.

no I done, it is my UpdateGroup 
![image](https://github.com/user-attachments/assets/921f9c3c-0ee7-4f9f-bb51-6c1a4c918da8)

**Comment by linwumingshi** [comment]
@q454578219 
Could you let me know which version of smart-doc you are using? I wasn't able to reproduce your issue in the latest version (`3.0.7`). If you're not using the most recent version, please consider upgrading to `3.0.7`.

**Comment by q454578219** [comment]
@linwumingshi Mainly because my other project ran very successfully, which is quite strange. However, the difference between the current project and that project is that this project runs on multiple modules, and the JDK version of the project is 1.8 and this is 17, so the validation package for that project is import javax.validation.craints NotBlank;  And this is import jakarta.validation.cnstricts NotBlank;
The original version was 2.4.9, but the new project was updated to 2.7.7 upon seeing it
![image](https://github.com/user-attachments/assets/45d42f1d-fcfd-411c-975d-e1701652b5ec)

There is 3. X here, but I don't know if the version span is large, so I didn't use it. i will try it, thank you

**Comment by linwumingshi** [comment]
[Quick-Start](https://smart-doc-group.github.io/guide/getting-started#quick-start)

 
@q454578219 

Also, note that the `groupId` has changed to `com.ly.smart-doc`. Here's the updated configuration:

```xml
<plugin>
    <groupId>com.ly.smart-doc</groupId>
    <artifactId>smart-doc-maven-plugin</artifactId>
    <version>[latest version]</version>
    <configuration>
        <configFile>./src/main/resources/smart-doc.json</configFile>
        <projectName>${project.description}</projectName>
        <includes>
            <!-- Page paging using mybatis-plus requires the source code package used by include -->
            <include>com.baomidou:mybatis-plus-extension</include>
            <!-- IPage paging using mybatis-plus needs to include mybatis-plus-core -->
            <include>com.baomidou:mybatis-plus-core</include>
            <!-- Paging using jpa requires the source code package used by include -->
            <include>org.springframework.data:spring-data-commons</include>
        </includes>
    </configuration>
    <executions>
        <execution>
            <!-- If you do not need to start smart-doc when compiling, comment out phase -->
            <phase>compile</phase>
            <goals>
                <!-- smart-doc provides html, openapi, markdown and other goals, which can be configured as needed -->
                <goal>html</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```

**Comment by q454578219** [comment]
@linwumingshi it worked,thanks  ^_^
![image](https://github.com/user-attachments/assets/88ab15a4-050f-4c23-9f0d-8aa904e00148)
