### ISSUE TITLE
Unable to extract the comments of entity class fields.

### ISSUE THREAD

**Issue by jqncc** [TongchengOpenSource/smart-doc#793]
## Your Environment(您的使用环境，您期望的结果，社区已开启国际化推广，请文心一言、讯飞星火等辅助翻译成英文，减少社区开发者的工作)
* smart-doc version:3.0.4
* plugin version :smart-doc-maven-plugin 3.0.4
* build tool version(maven or gradle): maven
* jdk version: 1.8

Problem: When generating OpenAPI documentation, the documentationProblem: When generating OpenAPI documentation, the documentation the annotations of all entity but the annotations of all entity class fields are not extracted, even though most fields actually have annotations.
Project structure (Spring MVC):
问题: 生成openapi文档, 能生成文档 , 但所有实体类的字段都没有提取到注释, 而事实上是大多数字段都有注释
项目大概结构(springmvc): 
```
-xxx-app
   -controler
-xxx-core
  -entity
```

The controller returns a unified encapsulation object, and the annotation of one of the entity classes is as follows:
controller返回结果为统一封装对象,其中一个实体类注释如下
![8](https://github.com/TongchengOpenSource/smart-doc/assets/5461345/89f5d4f7-3ea4-4f2e-a34b-3368da1ee58c)

**Comment by shalousun** [comment]
@jqncc Please submit issues in English. Smart-doc is an international open-source tool, and submitting issues in Chinese increases the workload of the community（国内目前很多免费的大模型工具可以翻译， 希望理解下社区开发者）.
请使用英文来提issue，smart-doc已经是国际化的开源工具，中文提交issue增加了社区的工作量。

To address your issue, please carefully read the official documentation here: https://smart-doc-group.github.io/#/zh-cn/faq/faq?id=%e6%b3%a8%e9%87%8a%e6%80%8e%e4%b9%88%e6%8f%90%e5%8f%96%e4%b8%8d%e5%88%b0%e5%95%8a%ef%bc%9f

针对你的问题，请仔细阅读官方这个说明文档
https://smart-doc-group.github.io/#/zh-cn/faq/faq?id=%e6%b3%a8%e9%87%8a%e6%80%8e%e4%b9%88%e6%8f%90%e5%8f%96%e4%b8%8d%e5%88%b0%e5%95%8a%ef%bc%9f

https://smart-doc-group.github.io/#/zh-cn/faq/faq?id=%e5%a4%9a%e6%a8%a1%e5%9d%97

**Comment by linwumingshi** [comment]
https://smart-doc-group.github.io/zh/guide/faq/faq#%E6%B3%A8%E9%87%8A%E6%80%8E%E4%B9%88%E6%8F%90%E5%8F%96%E4%B8%8D%E5%88%B0%E5%95%8A
