### ISSUE TITLE
Failed to set sequence number using @order

### ISSUE THREAD

**Issue by q651742112** [TongchengOpenSource/smart-doc#796]
## Your Environment
* smart-doc version:
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin):
* build tool version(maven or gradle):
* jdk version:17

I use the @order annotation to sort but it does not actually work, the sequence number does not show the specified sequence number (set 1, 2, 3...). Instead, start with something else

## Expected Behavior
Serial numbers are 1, 2, 3, 4

<img width="851" alt="image" src="https://github.com/TongchengOpenSource/smart-doc/assets/32741777/658fc536-bbd9-47d9-91e1-1b306c23e56b">

## Current Behavior
Currently from 22, 23, 24,...
<img width="970" alt="image" src="https://github.com/TongchengOpenSource/smart-doc/assets/32741777/e9b7189c-3247-48e0-81ef-f9a4c8cdb440">

## Possible Solution
don't know why

**Comment by shalousun** [comment]
@q651742112 Please submit issues in English

**Comment by q651742112** [comment]
> @q651742112 Please submit issues in English
I have changed to English

**Comment by shalousun** [comment]
Fixed, it can be used normally after the release of 3.0.6.
