### ISSUE TITLE
Is smart-doc maven plugin support skip without modify pom?

### ISSUE THREAD

**Issue by tuichenchuxin** [TongchengOpenSource/smart-doc#798]
## Summary
Is smart-doc maven plugin support skip without modify pom?

### Basic example
```
mvn clean install -Dsmart-doc:skip=true
```

### Motivation

Make it more convenient to use.

**Comment by shalousun** [comment]
@tuichenchuxin We can provide support,  The user guides should also be added to the official documentation at https://github.com/smart-doc-group/smart-doc-group.github.io.

**Comment by tuichenchuxin** [comment]
> @tuichenchuxin We can provide support, The user guides should also be added to the official documentation at https://github.com/smart-doc-group/smart-doc-group.github.io.

Thank you very much. you say that this guide adds content, do you mean @javadoc feature?

**Comment by shalousun** [comment]
> > @tuichenchuxin We can provide support, The user guides should also be added to the official documentation at https://github.com/smart-doc-group/smart-doc-group.github.io.
> 
> Thank you very much. you say that this guide adds content, do you mean @JavaDoc feature?

1. There is a descriptive document for smart-doc custom tag. Add the usage description of the `javadoc` tag.
2. Update the newly added Mojo of the Maven plugin in the documentation.
3. Include the usage of skipping Maven plugin support in the documentation as well.

**Comment by tuichenchuxin** [comment]
> > > @tuichenchuxin We can provide support, The user guides should also be added to the official documentation at https://github.com/smart-doc-group/smart-doc-group.github.io.
> > 
> > 
> > Thank you very much. you say that this guide adds content, do you mean @JavaDoc feature?
> 
> 1. There is a descriptive document for smart-doc custom tag. Add the usage description of the `javadoc` tag.
> 2. Update the newly added Mojo of the Maven plugin in the documentation.
> 3. Include the usage of skipping Maven plugin support in the documentation as well.

OK, I'll add document of `javadoc`

**Comment by tuichenchuxin** [comment]
@shalousun about support skip, if you have some idea, I can also make some contribution.

**Comment by shalousun** [comment]
> @shalousun about support skip, if you have some idea, I can also make some contribution.

The current `smart-doc-maven` has a skip configuration, but the naming is not very distinctive. It can be modified to `@Parameter(property = "smartdoc.skip") private String skip;` so that when using the command, it can become `mvn clean install -Dsmartdoc.skip=true`.

**Comment by tuichenchuxin** [comment]
> > @shalousun about support skip, if you have some idea, I can also make some contribution.
> 
> The current `smart-doc-maven` has a skip configuration, but the naming is not very distinctive. It can be modified to `@Parameter(property = "smartdoc.skip") private String skip;` so that when using the command, it can become `mvn clean install -Dsmartdoc.skip=true`.

Great, I'll support this.
