### ISSUE TITLE
Cannot generate documentation for requests whose content-type is form-data and urlencoded

### ISSUE THREAD

**Issue by shaunhurryup** [TongchengOpenSource/smart-doc#799]
I did read the documentation and QA, but didn't find the answers :-(

## Your Environment

- MBP Apple silicon
- maven-plugin
```xml
            <plugin>
                <groupId>com.ly.smart-doc</groupId>
                <artifactId>smart-doc-maven-plugin</artifactId>
                <version>3.0.4</version>
                <configuration>
                    <configFile>./src/main/resources/smart-doc.json</configFile>
                    <projectName>${project.description}</projectName>
                </configuration>
                <executions>
                    <execution>
                        <!--如果不需要在执行编译时启动smart-doc，则将phase注释掉-->
                        <phase>compile</phase>
                        <goals>
                            <!--smart-doc提供了html、openapi、markdown等goal，可按需配置-->
                            <goal>openapi</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

- smart-doc.json

```json
{
  "outPath": "./src/main/resources/static/doc",
  "pathPrefix": "/api",
  "allInOne": true
}
```

* build tool version(maven or gradle): maven
* jdk version: 8

## Expected Behavior

The type, example, and description of the request parameters should be in the `/api/example/goods-form-urlencoded.post.requestBody.content.application/x-www-form-urlencoded`

```json
"/api/example/goods-form-urlencoded": {
      "post": {
        "summary": "指定 content-type=application/x-www-form-urlencoded 请求头以添加商品",
        "deprecated": false,
        "tags": [
          "管理 商品信息"
        ],
        "requestBody": {
          "content": {
            "application/x-www-form-urlencoded": {
              "schema": {
                    + There should be the content of the request parameters
                    + There should be the content of the request parameters
                    + There should be the content of the request parameters
               },
              "examples": {
                "json": {
                  "summary": "test data",
                  "value": "curl -X POST -H 'Content-Type: application/x-www-form-urlencoded' -i '/api/example/goods-form-urlencoded' --data 'type=electronics&name=iPhone 15 Pro Max&price=9999&secondHand=false&description=这是一款新款 iPhone，性能强劲，拍照效果好，电池续航长&tags=[\"新款\", \"性能强劲\", \"拍照效果好\", \"电池续航长\"]'"
                }
              }
            }
          }
        },
```

## Current Behavior

The type, example, and description of the request parameters are set in `/api/example/goods-form-urlencoded.post.parameters` incorrectly

```json
"/api/example/goods-form-urlencoded": {
      "post": {
        "summary": "指定 content-type=application/x-www-form-urlencoded 请求头以添加商品",
        "deprecated": false,
        "tags": [
          "管理 商品信息"
        ],
        "requestBody": {
          "content": {
            "application/x-www-form-urlencoded": {
              "schema": {
                    + There should be the content of the request parameters
                    + There should be the content of the request parameters
                    + There should be the content of the request parameters
               },
              "examples": {
                "json": {
                  "summary": "test data",
                  "value": "curl -X POST -H 'Content-Type: application/x-www-form-urlencoded' -i '/api/example/goods-form-urlencoded' --data 'type=electronics&name=iPhone 15 Pro Max&price=9999&secondHand=false&description=这是一款新款 iPhone，性能强劲，拍照效果好，电池续航长&tags=[\"新款\", \"性能强劲\", \"拍照效果好\", \"电池续航长\"]'"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {},
                "examples": {
                  "json": {
                    "summary": "test data",
                    "value": "Return void."
                  }
                }
              }
            }
          }
        },
        "operationId": "api-example-goods-form-urlencoded-POST",
        + But it's incorrectly set here
        "parameters": [
          {
            "schema": {
              "format": "enum",
              "type": "string",
              "enum": [
                "FRUIT",
                "ELECTRONICS",
                "FOOD",
                "DRINK",
                "OTHER"
              ]
            },
            "in": "query",
            "description": "商品类型",
            "required": true,
            "example": "electronics",
            "name": "type"
          },
          {
            "schema": {
              "format": "string",
              "type": "string"
            },
            "in": "query",
            "description": "商品名称",
            "required": true,
            "example": "iPhone 15 Pro Max",
            "name": "name"
          },
          {
            "schema": {
              "format": "int32",
              "type": "integer"
            },
            "in": "query",
            "description": "商品价格",
            "required": true,
            "example": "9999",
            "name": "price"
          },
          {
            "schema": {
              "format": "boolean",
              "type": "boolean"
            },
            "in": "query",
            "description": "是否二手",
            "required": true,
            "example": "false",
            "name": "secondHand"
          },
          {
            "schema": {
              "format": "string",
              "type": "string"
            },
            "in": "query",
            "description": "商品描述",
            "required": false,
            "example": "这是一款新款 iPhone，性能强劲，拍照效果好，电池续航长",
            "name": "description"
          },
          {
            "schema": {
              "type": "object"
            },
            "in": "query",
            "description": "商品标签",
            "required": false,
            "example": "[新款, 性能强劲, 拍照效果好, 电池续航长]",
            "name": "tags"
          }
        ]
      }
    },
```

# Context

```kotlin
/**
 * 指定 content-type=application/x-www-form-urlencoded 请求头以添加商品
 */
@PostMapping(value = "/goods-form-urlencoded", consumes = MediaType.APPLICATION_FORM_URLENCODED_VALUE)
public void addGoodByFormUrlencoded(AddGoodRequestJson json) {
    // 实现逻辑
}

@Data
public class AddGoodRequestJson {
    /**
     * 商品类型
     *
     * @mock electronics
     */
    @NotNull
    private GoodType type;

    /**
     * 商品名称
     *
     * @mock iPhone 15 Pro Max
     */
    @NotNull
    private String name;

    /**
     * 商品价格
     *
     * @mock 9999
     */
    @NotNull
    private int price;

    /**
     * 是否二手
     *
     * @mock false
     */
    @NotNull
    private boolean secondHand;

    /**
     * 商品描述
     *
     * @mock 这是一款新款 iPhone，性能强劲，拍照效果好，电池续航长
     */
    private String description;

    /**
     * 商品标签
     *
     * @mock ["新款", "性能强劲", "拍照效果好", "电池续航长"]
     */
    private String[] tags;
}
```

**Comment by shalousun** [comment]
@shaunhurryup According to the code you provided, the OpenAPI generated by smart-doc can be normally displayed by the latest version of `springdoc-openapi-starter-webmvc-ui`, and requests can also be processed normally. The OpenAPI generated by smart-doc is based on the 3.0.3 protocol, not Swagger 2. Of course, due to data acquisition reasons, smart-doc will make some sacrifices in the implementation of the components section, which will affect certain code generation.

<img width="969" alt="image" src="https://github.com/TongchengOpenSource/smart-doc/assets/9592228/814919c8-d43a-42d6-8e34-9b76714b5ad0">

**Comment by shalousun** [comment]
@shaunhurryup Currently, smart-doc is optimal for scenarios that use JSON requests, but its handling of schemas and components is not very complete. This can affect scenarios where OpenAPI is used to generate code. The documentation display can be used normally. If you are familiar with OpenAPI, you are welcome to participate in the joint improvement.

**Comment by shaunhurryup** [comment]
> @shaunhurryup According to the code you provided, the OpenAPI generated by smart-doc can be normally displayed by the latest version of `springdoc-openapi-starter-webmvc-ui`, and requests can also be processed normally. The OpenAPI generated by smart-doc is based on the 3.0.3 protocol, not Swagger 2. Of course, due to data acquisition reasons, smart-doc will make some sacrifices in the implementation of the components section, which will affect certain code generation. 
> 
> <img alt="image" width="969" src="https://private-user-images.githubusercontent.com/9592228/335168809-814919c8-d43a-42d6-8e34-9b76714b5ad0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNzE3NTYsIm5iZiI6MTcxNzA3MTQ1NiwicGF0aCI6Ii85NTkyMjI4LzMzNTE2ODgwOS04MTQ5MTljOC1kNDNhLTQyZDYtOGUzNC05Yjc2NzE0YjVhZDAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MzBUMTIxNzM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGRjNjY0MTI4MDk2NjdmMGNkYWZlYjI4NjljMGIxYTA4ZjU4YjRmMmM5MjBlZjkwYWI2MTU2MWM3MDQxOTkwMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.K334WoGmWDc4oRGvpFsThkUuiuEEXUFxk92xk5mb4TY">

1. can be normally displayed

Yeah, the JSON output can be rendered by any UI tools that support the OpenAPI specification. However, it is displayed using query parameters instead of x-www-form-urlencoded.

> By Apifox

![CleanShot 2024-05-30 at 20 34 42@2x](https://github.com/TongchengOpenSource/smart-doc/assets/45918719/f37f9121-61ad-4ec2-9d5c-51e49f910db7)

![CleanShot 2024-05-30 at 20 35 41@2x](https://github.com/TongchengOpenSource/smart-doc/assets/45918719/6c9c6afc-1481-4a2e-890b-5767b6cf94b1)

I import json output to Postman, it display query parameters too

![CleanShot 2024-05-30 at 20 38 13@2x](https://github.com/TongchengOpenSource/smart-doc/assets/45918719/0f069f29-f7f7-4c00-8656-1181b40cc5ba)


2. request can be processed

A request of type `query parameters` cannot be answered correctly by a server that defines type `application/x-www-form-urlencoded`

You can see my json output if you want~

[openapi.json](https://github.com/TongchengOpenSource/smart-doc/files/15500073/openapi.json)

**Comment by shalousun** [comment]
@shaunhurryup We have tested it, and the parameters generated by openapi ui are also placed in the parameters. Our processing method is to directly split the parameter fields, not using ref. There may be no mandatory requirements for the presentation of application/x-www-form-urlencoded. It does indeed treat x-www-form-urlencoded types as key=value from the browser's perspective. Whether the community will optimize it to the way you want remains to be seen, as I don't have time to deal with it recently. Smart-doc initially leaned towards the more mainstream JSON request method at present, so its support for form requests will be somewhat weaker.

<img width="675" alt="image" src="https://github.com/TongchengOpenSource/smart-doc/assets/9592228/a49713b2-51d9-4fbb-a5b4-a5d360e4f843">
