### ISSUE TITLE
How to get the annotations of fields in the common package when using single tests in multi-module?

### ISSUE THREAD

**Issue by zzmdiao** [TongchengOpenSource/smart-doc#800]
smart-doc version:3.0.4
build tool version(maven or gradle): maven
jdk version: 1.8
问题: 生成torna文档, 能生成文档 , 但所有实体类的字段都没有提取到注释, 而事实上是大多数字段都有注释
看了官方文档https://smart-doc-group.github.io/#/zh-cn/faq/faq?id=%e5%a4%9a%e6%a8%a1%e5%9d%97
![image](https://github.com/TongchengOpenSource/smart-doc/assets/18062941/02c9b13d-15fc-49ea-8b65-27a5e358b4a5)
这个有其他方法可以解决吗
`-xxx-web
   -controller

-xxx-core
  -entity`
web依赖core，单测是放到web中的

**Comment by shalousun** [comment]
@zzmdiao Please submit issues in English， Or submit the issue in a combination of Chinese and English，In China, there are many AI tools that can quickly translate. Smart-doc has already done a lot of international promotion. After submitting issues in Chinese, the community needs to translate them, which increases the workload of the community developers. Currently, all developers in the community are part-time, and everyone is quite busy. Over the past few weeks, I have spent a lot of time translating community issues and documentation, hoping for your understanding.

在中国内国有很多AI工具都能快速翻译，smart-doc已经做了很多面向国际化的推广宣传，用中文提交issue后社区需要进行翻译，增加社区开发者的工作量，社区目前开发者都是兼职性开发，大家比较辛苦，过去的几个周我就花很多的时间去做社区issue的翻译和文档翻译，希望能理解下。

**Comment by shalousun** [comment]
@zzmdiao The community does not recommend using smart-doc in unit testing. After Java code is compiled, comments are erased, and what is obtained in the unit testing scenario are the compiled classes; field information is also obtained through reflection. The community will not provide documentation for this use case. To use unit testing, you need to specify the path of the source code yourself in ApiConfig, which is very problematic for team collaboration.

**Comment by zzmdiao** [comment]
> @zzmdiao The community does not recommend using smart-doc in unit testing. After Java code is compiled, comments are erased, and what is obtained in the unit testing scenario are the compiled classes; field information is also obtained through reflection. The community will not provide documentation for this use case. To use unit testing, you need to specify the path of the source code yourself in ApiConfig, which is very problematic for team collaboration.@zzmdiao 社区不建议在单元测试中使用 smart-doc。 Java代码编译后，注释被删除，单元测试场景中得到的是编译后的类；场信息也是通过反射获得的。社区不会提供此用例的文档。使用单元测试需要自己在ApiConfig中指定源代码的路径，这对于团队协作来说是非常糟糕的。

So, this means that you can specify sourceCodePaths to solve the issue. Why is this approach very problematic for team collaboration? For example, I set the source code as "Paths.get(System.getProperty("user.dir")).getParent().toString()".

**Comment by shalousun** [comment]
@zzmdiao The setting of `sourceCodePaths` depends on the local code directory of each developer in the team, and everyone's code path may not be consistent. In team collaboration development, conflicting paths need to be continuously modified.

**Comment by zzmdiao** [comment]
> @zzmdiao The setting of `sourceCodePaths` depends on the local code directory of each developer in the team, and everyone's code path may not be consistent. In team collaboration development, conflicting paths need to be continuously modified.

I want to trigger the integration through unit testing in the pipeline, but it can also be executed locally through unit testing. If the sourceCodePaths is set to Paths.get(System.getProperty("user.dir")).getParent().toString(), can it avoid collaboration issues among multiple people?

**Comment by shalousun** [comment]
> > @zzmdiao The setting of `sourceCodePaths` depends on the local code directory of each developer in the team, and everyone's code path may not be consistent. In team collaboration development, conflicting paths need to be continuously modified.
> 
> I want to trigger the integration through unit testing in the pipeline, but it can also be executed locally through unit testing. If the sourceCodePaths is set to Paths.get(System.getProperty("user.dir")).getParent().toString(), can it avoid collaboration issues among multiple people?

The only solution is to prohibit developers from modifying the unit tests that launch smart-doc. Then, use plugins to generate documentation during local development. In the pipeline process, use unit tests and dynamically specify the code path. Otherwise, multi-person development will still cause conflicts in code modifications. The best way is to optimize your pipeline process to avoid file modification conflicts under multi-person collaborative development.

**Comment by zzmdiao** [comment]
> > > @zzmdiao The setting of `sourceCodePaths` depends on the local code directory of each developer in the team, and everyone's code path may not be consistent. In team collaboration development, conflicting paths need to be continuously modified.
> > 
> > 
> > I want to trigger the integration through unit testing in the pipeline, but it can also be executed locally through unit testing. If the sourceCodePaths is set to Paths.get(System.getProperty("user.dir")).getParent().toString(), can it avoid collaboration issues among multiple people?
> 
> The only solution is to prohibit developers from modifying the unit tests that launch smart-doc. Then, use plugins to generate documentation during local development. In the pipeline process, use unit tests and dynamically specify the code path. Otherwise, multi-person development will still cause conflicts in code modifications. The best way is to optimize your pipeline process to avoid file modification conflicts under multi-person collaborative development.唯一的解决方案是禁止开发人员修改启动 smart-doc 的单元测试。然后，在本地开发时使用插件生成文档。在管道流程中，使用单元测试并动态指定代码路径。否则多人开发还是会造成代码修改冲突。最好的办法就是优化你的pipeline流程，避免多人协作开发下的文件修改冲突。



> > > @zzmdiao The setting of `sourceCodePaths` depends on the local code directory of each developer in the team, and everyone's code path may not be consistent. In team collaboration development, conflicting paths need to be continuously modified.
> > 
> > 
> > I want to trigger the integration through unit testing in the pipeline, but it can also be executed locally through unit testing. If the sourceCodePaths is set to Paths.get(System.getProperty("user.dir")).getParent().toString(), can it avoid collaboration issues among multiple people?
> 
> The only solution is to prohibit developers from modifying the unit tests that launch smart-doc. Then, use plugins to generate documentation during local development. In the pipeline process, use unit tests and dynamically specify the code path. Otherwise, multi-person development will still cause conflicts in code modifications. The best way is to optimize your pipeline process to avoid file modification conflicts under multi-person collaborative development.

get,thanks
