### ISSUE TITLE
Tree structure parsing bug

### ISSUE THREAD

**Issue by zhanghan2585** [TongchengOpenSource/smart-doc#804]
## Your Environment(您的使用环境，您期望的结果，社区已开启国际化推广，请文心一言、讯飞星火等辅助翻译成英文，减少社区开发者的工作)

* smart-doc version: 
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin):   
*                             <groupId>com.ly.smart-doc</groupId>
				<artifactId>smart-doc-maven-plugin</artifactId>
				<version>3.0.4</version>
* build tool version(maven or gradle): maven 3.8.6
* jdk version: 1.8

## Expected Behavior(您期望的结果，社区已开启国际化推广，请用文心一言、讯飞星火等辅助翻译成英文，减少社区开发者的工作)
![image](https://github.com/TongchengOpenSource/smart-doc/assets/18066720/f256b09c-ffc4-4248-8be2-be2a4f8036ea)
![image](https://github.com/TongchengOpenSource/smart-doc/assets/18066720/5467a221-5e8d-45a2-af7b-ba5e683f1335)
![image](https://github.com/TongchengOpenSource/smart-doc/assets/18066720/5f0dd3d3-ab50-438b-bd2b-455d47aefcba)
![image](https://github.com/TongchengOpenSource/smart-doc/assets/18066720/900bbf0c-030f-4155-b8e2-49e64efae7d0)

There are other problems, a layer of generic trees, dead loops
![image](https://github.com/TongchengOpenSource/smart-doc/assets/18066720/6a6b18d9-38ad-43a6-849a-229ceed5b647)
![image](https://github.com/TongchengOpenSource/smart-doc/assets/18066720/05b804e1-0dc2-429a-9891-a87c27e09cc2)

## Possible Solution(bug解决建议，社区已开启国际化推广，请用文心一言、讯飞星火等辅助翻译成英文，减少社区开发者的工作)
/**
 * 多叉树
 * @param <T>
 */
public class Tree<T> {
    /**
     * 树节点
     */
    private TreeNode<T> root;

    // 无参构造函数
    public Tree() {}
    public Tree(T rootData) {
        root = new TreeNode<>(rootData);
    }

    public TreeNode<T> getRoot() {
        return root;
    }

    public void setRoot(TreeNode<T> root) {
        this.root = root;
    }
}

## Steps to Reproduce (Bug产生步骤，请尽量提供用例代码。社区已开启国际化推广，请用文心一言、讯飞星火等辅助翻译成英文，减少社区开发者的工作)

1.
2.
3.
4.

**Comment by shalousun** [comment]
@zhanghan2585 Based on the examples you provided, there indeed seems to be a bug in the parsing. On the other hand, the parameter table will loop through the structure of infinite recursion three times; this is normal behavior, intended to inform document users that it involves an infinitely recursive structure.

**Comment by shalousun** [comment]
The issue of missing field parsing will be fixed in version 3.0.5. Due to the current high complexity of the logic for JSON bodies, optimization and repair will be addressed in version 3.0.6.
