### ISSUE TITLE
buildReqJson reported java.lang.StringIndexOutOfBoundsException: String index out of range: -1

### ISSUE THREAD

**Issue by dannyhnu** [TongchengOpenSource/smart-doc#82]
* smart-doc version: 2.0.6
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin): smart-doc-maven-plugin
* build tool version(maven or gradle): maven

java.lang.StringIndexOutOfBoundsException: String index out of range: -1
    at java.lang.String.substring (String.java:1967)
    at com.power.doc.utils.DocUtil.formatAndRemove (DocUtil.java:258)
    at com.power.doc.template.SpringBootDocBuildTemplate.buildReqJson (SpringBootDocBuildTemplate.java:467)
    at com.power.doc.template.SpringBootDocBuildTemplate.buildControllerMethod (SpringBootDocBuildTemplate.java:233)
    at com.power.doc.template.SpringBootDocBuildTemplate.getApiData (SpringBootDocBuildTemplate.java:89)
    at com.power.doc.builder.ApiDocBuilder.buildApiDoc (ApiDocBuilder.java:68)

**Comment by shalousun** [comment]
@dannyhnu It's difficult for us to troubleshoot such errors without a specific test case. Could you please provide a test case while debugging? The general issue seems to be the use of regular expressions in your controller paths, similar to this pattern: `detail/{id:[a-zA-Z0-9]{3}}/{name:[a-zA-Z0-9]{3}}`. If the debugger cannot find the erroneous test case, directly search within your project for paths with regular expression validation like this one and provide them to us for testing. The reason the issue template asks for test cases is that everyone has different coding habits, making it hard to cover all possible cases.

**Comment by wz2326** [comment]
When using regular expressions in URLs, try to use '/' as the delimiter, such as: `/detail/{id:[a-zA-Z0-9]{3}}/{name:[a-zA-Z0-9]{3}}`
For patterns like this one: `/{prefix:[A-Z]{3}_[a-z]+_[0-9]{2}}_{path:\w+}{ext:\.[a-z]+}`, or more complex ones, support is currently not available.

**Comment by shalousun** [comment]
fixed in 2.0.7

**Comment by dannyhnu** [comment]
> @dannyhnu  It's difficult for us to troubleshoot such errors without a specific test case. Could you please provide a test case while debugging? The general issue seems to be the use of regular expressions in your controller paths, similar to this pattern: `detail/{id:[a-zA-Z0-9]{3}}/{name:[a-zA-Z0-9]{3}}`. If the debugger cannot find the erroneous test case, directly search within your project for paths with regular expression validation like this one and provide them to us for testing. The reason the issue template asks for test cases is that everyone has different coding habits, making it hard to cover all possible cases.

Understood. I suggest adding the class or URL where the error occurred in the error report, as I am unable to individually check which controller is causing the error.

**Comment by dannyhnu** [comment]
> 2.0.7

When will it be submitted to the repository? Thank you!
