### ISSUE TITLE
Can support EnumSet and JSR310 DateTime?

### ISSUE THREAD

**Issue by Ikki-Dai** [TongchengOpenSource/smart-doc#828]
## Summary(

i use EnumSet and JSR310 dateTime type such as `Instant`, `LocalDateTime` and with annotation `JsonFormat(pattern="yyyy-MM-dd HH:mm:ss", timezone="GMT+8")`. but it was recognized as an object

### Basic example

```java

@JsonFormat(pattern="yyyy-MM-dd HH:mm:ss'T'Z", timezone="GMT+8")
private Instant expiration;

private LocalDateTime issuedAt;

private EnumSet<Access> access;

public enum Access{READ, WRITE}
```

### Motivation

i wana this plugin can support api generator better

**Comment by shalousun** [comment]
If you are interested, submit a PR to support it.
