### ISSUE TITLE
In the @PostMapping, consumes = MediaType.APPLICATION_JSON_VALUE is not being correctly parsed.

### ISSUE THREAD

**Issue by GTaurus** [TongchengOpenSource/smart-doc#83]
## Your Environment (Your Usage Environment)

* smart-doc version:
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin): 2.0.5
* build tool version(maven or gradle): maven

## Expected Behavior (Expected Outcome)
Content-Type: application/json

## Current Behavior (Current Outcome)
Content-Type: application/x-www-form-urlencoded;charset=utf-8

## Possible Solution (Suggested Fix for the Bug)
It is hoped that the Content-Type can be determined not only by `@RequestBody` but also through the consumes parameter.

## Steps to Reproduce (Steps to Trigger the Bug, please provide sample code if possible)
```java
  @PostMapping(
      value = "draw-apply",
      consumes = MediaType.APPLICATION_JSON_VALUE,
      produces = MediaType.APPLICATION_JSON_VALUE)
```
***Because additional processing of parameters is required, `@RequestBody` was not used***

## Context (Impact of the Bug)

Since only JSON has a Request-Example, this situation is very troublesome.

**Comment by shalousun** [comment]
@GTaurus This is meaningless.
```
/**
     * Update
     *
     * @param id   The ID
     * @param ball
     * @return
     */
    @PutMapping(value = "/update", consumes = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
    public Ball updateBall(Ball ball) {
        LOGGER.info("ball:{}", JSON.toJSONString(ball));
        return ball;
    }
```
In this example, without using `@RequestBody`, the backend also cannot receive the Ball object, and the 'consumes' parameter is ineffective. As an open-source project, we should first deal with the actual situation. It's meaningless to have open-source projects adapt to some issues of historical projects.
