### ISSUE TITLE
@RequestPart annotation parameter support issue

### ISSUE THREAD

**Issue by zooltech** [TongchengOpenSource/smart-doc#847]
* smart-doc-maven-plugin version: 3.0.5
* build tool version(maven or gradle): maven 3.9.8
* jdk version: 1.8

Controller method:
```
@PostMapping(value = "/picture/add", consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
public Result<MainContentPicDTO> addMainContentPic(@RequestPart("param") @NotNull final MainContentPicParam param,
                                                   @RequestPart("file") @NotNull final MultipartFile file) {
 ....
}
```

Description of API document parameters generated：
![image](https://github.com/TongchengOpenSource/smart-doc/assets/1016136/568b0f07-f833-41df-b670-9415626b15eb)

There is no "param" parameter. Just directly listing the properties of the parameter object.

**Comment by shalousun** [comment]
@zooltech If you can fix it yourself, we would greatly appreciate a pull request from you. The official documentation also provides instructions on how to submit a pull request.
