### ISSUE TITLE
It is recommended to add a custom tag that allows the output of Request-Example without using @RequestBody.

### ISSUE THREAD

**Issue by GTaurus** [TongchengOpenSource/smart-doc#85]
## Summary (Description of this PR)
Suggest adding a custom tag that can output Request-Example without using `@RequestBody`,
For example: `@jsonExample`.

The reason is issue #83.

**Comment by netdied** [comment]
![image](https://user-images.githubusercontent.com/20217389/113385016-d4999580-93b9-11eb-8119-5d44f4de5dbc.png)
![image](https://user-images.githubusercontent.com/20217389/113385032-de22fd80-93b9-11eb-9330-da8d4d5a5551.png)
I checked the code for issue #83 and found that there is already a request-example available. Could you please provide some test samples, or download the latest version for testing?

**Comment by GTaurus** [comment]
The hope is to be able to output a JSON format Request-Example even without using `@RequestBody`.
After using `@RequestBody`, it will be intercepted by Spring's RequestBody interceptor by default, and some of our project codes use our own interceptor. We cannot globally disable the RequestBody interceptor, so we hope there is a way to forcefully specify its usage.
