### ISSUE TITLE
When the project's Javadoc is not properly formatted How can I generate API documentation without making any modifications to the project

### ISSUE THREAD

**Issue by KiRito02** [TongchengOpenSource/smart-doc#854]
### Version

3.05

### Plugin

smart-doc-maven-plugin

### Build tool version

3.8

### Jdk version

1.8

### Describe the bug(BUG描述，社区已开启国际化推广，请用文心一言、讯飞星火等辅助翻译成英文，减少社区开发者的工作)

When the project's Javadoc is not properly formatted, such as missing values after tags like @author or @param, smart-doc will throw an error and terminate the generation process. How can I generate API documentation without making any modifications to the project?

### Expected Behavior(您期望的结果，社区已开启国际化推广，请用文心一言、讯飞星火等辅助翻译成英文，减少社区开发者的工作)

generate documentation without modifying project files

### Current Behavior(当前结果，社区已开启国际化推广，请用文心一言、讯飞星火等辅助翻译成英文，减少社区开发者的工作)

When smart-doc generates documentation, it will throw an error and terminate the generation process.

### Steps to Reproduce (Bug产生步骤，请尽量提供用例代码。社区已开启国际化推广，请用文心一言、讯飞星火等辅助翻译成英文，减少社区开发者的工作)

bad javadoc like this:
/**
*@author
*@param
*@return
**/

When smart-doc generates documentation, it will throw an error and terminate the generation process.

### Validations

- [X] Check if you're on the [latest smart-doc version](https://github.com/TongchengOpenSource/smart-doc/releases/latest).
- [X] Read the [docs](https://smart-doc-group.github.io/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by shalousun** [comment]
Unsupported， because the design philosophy of smart-doc mandates that teams must follow comments standards, resulting in strict checks. We also do not want to loosen the configuration as it would make it difficult for developers to adhere to these standardized norms.
