### ISSUE TITLE
Encountered a ClassCastException during the build of Dubbo

### ISSUE THREAD

**Issue by xiangganLuo** [TongchengOpenSource/smart-doc#889]
### Contact Details

cvprog@163.com

### Version

3.0.6

### Plugin

smart-doc-maven-plugin

### Build tool version

maven 3.8.2

### Jdk version

17

### Describe the bug (Bug描述，社区已开启国际化推广，请用文心一言、讯飞星火等辅助翻译成英文，减少社区开发者的工作)

During the generation of Dubbo API documentation using torna-rpc, an object conversion problem occurred: ClassCastException: class com.ly.doc.model.JavadocJavaMethod cannot be cast to class com.ly.doc.model.RpcJavaMethod.

Specific reasons were found through debugging in the following code:
In the RpcDocBuildTemplate class, there's an issue with the object conversion in the collection for the method (List<RpcJavaMethod>) buildServiceMethod(cls, apiConfig, projectBuilder).

Then, in the RpcTornaBuilder class, a ClassCastException occurs when executing the TornaUtil.buildDubboApis method at line 80, during the for loop.

1. Type conversion:
![1](https://github.com/user-attachments/assets/5d4d6104-6585-452e-ab67-d1c516883d71)
2. Where the list is used:
![2](https://github.com/user-attachments/assets/d3aded84-2864-40e4-9798-726671f9bfa7)
3. Exception information:
![3](https://github.com/user-attachments/assets/10046ae7-2f60-4d14-8b50-b3ab41667ded)

### Expected Behavior (您期望的结果，社区已开启国际化推广，请用文心一言、讯飞星火等辅助翻译成英文，减少社区开发者的工作)

The ability to construct Dubbo interface documentation

### Current Behavior (当前结果，社区已开启国际化推广，请用文心一言、讯飞星火等辅助翻译成英文，减少社区开发者的工作)

ClassCastException

### Steps to Reproduce (Bug产生步骤，请尽量提供用例代码。社区已开启国际化推广，请用文心一言、讯飞星火等辅助翻译成英文，减少社区开发者的工作)

1. JavaDoc annotations for the Dubbo interface：
/**
 * @dubbo
 * @service test1
 * @protocol dubbo
 * @apiname test
 * @tag 1.1.1
 */

2. Plug-in configuration:
![4](https://github.com/user-attachments/assets/ddc71858-187f-4559-96ff-c6cb41a4b255)

### Possible Solution (Bug解决建议，社区已开启国际化推广，请用文心一言、讯飞星火等辅助翻译成英文，减少社区开发者的工作)

Method one:
Implement the buildServiceMethod method in IRpcDocTemplate, facilitating future extensions of the RpcJavaMethod field.

Method two:
Change the RpcJavaMethod used in the for loop to JavadocJavaMethod. Currently, there are no special fields in RpcJavaMethod.

### Validations

- [X] Check if you're on the [latest smart-doc version](https://github.com/TongchengOpenSource/smart-doc/releases/latest). (请检查是否为最新版本)
- [X] Read the [docs](https://smart-doc-group.github.io/). (请先阅读官方文档)
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate. (检查是否存在报告相同错误的问题，以避免产生重复)

**Comment by linwumingshi** [comment]
@xiangganLuo Pull requests are warmly welcomed for collaborative development.

**Comment by xiangganLuo** [comment]
Alright, I'll handle it this afternoon and submit the PR.
