### ISSUE TITLE
How to customize the data type of certain parameters/or return value types?

### ISSUE THREAD

**Issue by ldwqh0** [TongchengOpenSource/smart-doc#89]
In some cases, special type conversion strategies may be required.
For example, types like java.util.UUID, java.time.ZonedDateTime, JodaTime, etc.
Under the default configuration of Spring Boot, these types of parameters are outputted as Strings.
However, Smart-doc parses the entire class and then outputs each property separately. Here's an example:
```java
   /**
     * Test it out
     *
     * @param tt
     * @return
     */
    @GetMapping
    @ResponseBody
    public ZonedDateTime ts(@RequestParam("bood") ZonedDateTime tt) {
        return ZonedDateTime.now();
    }
```
The document it parses is as follows:
Field | Type|Description|Since
---|---|---|---
offset|object|No comments found.|-
└─totalSeconds|int32|No comments found.|-
zone|object|No comments found.|-
chronology|object|No comments found.|-
└─id|string|No comments found.|-
└─calendarType|string|No comments found.|-
└─availableChronologies|array|No comments found.|-
dateTime|string|No comments found.|-

But this is not the actual result; the actual result is simply returning a string.

Is there a way to customize the mapping relationship between certain types?
I have tried configuring the configuration file:
```json
{
  "allInOne": true,
  "isStrict": false,
  "outPath": "src/main/resources/static/doc",
  "apiObjectReplacements": [
    {
      "className": "java.time.ZonedDateTime",
      "replacementClassName": "java.lang.String"
    },
    {
      "className": "java.util.UUID",
      "replacementClassName": "java.lang.String"
    }
  ]
}
```
But it seems not to take effect.
I traced it to the DocClassUtil class and found that it contains some fixed value switch statements.
Therefore, is there a good solution to solve similar problems?

**Comment by shalousun** [comment]
@ldwqh0 ZonedDateTime, what format will it be in when passed from the front end?

**Comment by ldwqh0** [comment]
> @ldwqh0 ZonedDateTime，ZonedDateTime, what format will it be in when passed from the front end?

Strings for date and time specified by ISO 8601 are typically generated using `Date.toISOString()`, with values similar to "2021-03-07T06:39:07.975Z".
