### ISSUE TITLE
When using encoders to specify only one class, the write encoders = MessageResponseEncoder.class does not resolve the response parameters.

### ISSUE THREAD

**Issue by shalousun** [TongchengOpenSource/smart-doc#901]
### Version

3.0.7

### Plugin

smart-doc-maven-plugin

### Build tool version

3.8.6

### Jdk version

17

### Describe the bug (Bug描述，社区已开启国际化推广，请用文心一言、讯飞星火等辅助翻译成英文，减少社区开发者的工作)

When using encoders to specify only one class, the write `encoders = MessageResponseEncoder.class` does not resolve the response parameters.

### Expected Behavior (您期望的结果，社区已开启国际化推广，请用文心一言、讯飞星火等辅助翻译成英文，减少社区开发者的工作)

Can Resolve Normally

### Current Behavior (当前结果，社区已开启国际化推广，请用文心一言、讯飞星火等辅助翻译成英文，减少社区开发者的工作)

When using encoders to specify only one class, the write `encoders = MessageResponseEncoder.class` does not resolve the response parameters.

### Steps to Reproduce (Bug产生步骤，请尽量提供用例代码。社区已开启国际化推广，请用文心一言、讯飞星火等辅助翻译成英文，减少社区开发者的工作)

Test Code Example
```
@ServerEndpoint(value = "/ws/chat/{userId}",
        decoders = MessageDecoder.class,
        encoders = MessageResponseEncoder.class)
public class ChatEndpoint {

}
```

### Validations

- [X] Check if you're on the [latest smart-doc version](https://github.com/TongchengOpenSource/smart-doc/releases/latest). (请检查是否为最新版本)
- [X] Read the [docs](https://smart-doc-group.github.io/). (请先阅读官方文档)
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate. (检查是否存在报告相同错误的问题，以避免产生重复)

**Comment by linwumingshi** [comment]
In the case where only the `decoders` configuration is set up, and there's no `@OnMessage` method defined, this configuration won't have any effect. The `@OnMessage` annotation is necessary to specify a method that handles incoming messages according to the decoder setup.
