### ISSUE TITLE
It is recommended to adjust the version information and document generation time to the upper left or right corner of the page, and to add a "Back to Top" button in the lower right corner.

### ISSUE THREAD

**Issue by wangran99** [TongchengOpenSource/smart-doc#91]
## Summary (Description of this PR)
Brief explanation of the feature.
1. It is recommended to adjust the position of the version information and document generation time to the upper left or right corner of the page.
2. It is suggested to add a "Back to Top" button in the lower right corner.
### Basic Example (Use Cases for the PR)
If the proposal involves a new or changed API, include a basic code example. Omit this section if it's not applicable.
### Motivation (Purpose of this PR)
Why are we doing this? What use cases does it support? What is the expected outcome?
1. To facilitate seeing the document version information and generation time as soon as the page is opened, without needing to scroll to the bottom.
2. To make it convenient to return to the top.

**Comment by shalousun** [comment]
@wangran99 If you can handle it yourself, feel free to implement it and submit a PR. I won't have time to work on it for the next month or so.
