### ISSUE TITLE
How to ignore specific request parameters

### ISSUE THREAD

**Issue by ldwqh0** [TongchengOpenSource/smart-doc#92]
This is a code snippet:
```java
@PutMapping
public UserDto update(@AuthenticationPrincipal(expression = "id") Long userId, @RequestBody UserDto user) {
    return userService.saveOwnerInfo(userId, user);
}
```
I now want to ignore the parameter specified by `@AuthenticationPrincipal(expression = "id") Long userId`, but keep the parameter specified by `@RequestBody`. How should I handle this?

**Comment by shalousun** [comment]
@ldwqh0 Your system is generally internal. In fact, you can handle it flexibly, just add a comment to explain. Theoretically, tools like smart-doc that rely entirely on comments cannot handle your scenario. The most practical use case for smart-doc is for RESTful APIs, which are stateless deliveries.

**Comment by ldwqh0** [comment]
Documents like this are used 99% of the time for internal systems.
That being said, as long as you don't lose motivation, there are always more solutions than problems. If there is a need, it can be addressed in certain ways.
For instance, adding a custom tag `@ignoreRequestParams` param1 param2 in the doc could also be a solution.

**Comment by shalousun** [comment]
@ldwqh0 Later on, we will add a tag to support this.
