### ISSUE TITLE
The enum type field in the request body is parsed as an object.

### ISSUE THREAD

**Issue by austconthing** [TongchengOpenSource/smart-doc#93]
## Your Environment(您的使用环境)

* smart-doc version:
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin):
* build tool version(maven or gradle):

## Steps to Reproduce (Bug产生步骤，请尽量提供用例代码)

1.
2.
3.
4.

**Comment by shalousun** [comment]
@austconthing Please fill in the form according to the issue template, and try to provide concrete examples.
