### ISSUE TITLE
Is it possible to provide a public parameter packaging feature?

### ISSUE THREAD

**Issue by gardenerHan** [TongchengOpenSource/smart-doc#94]
## Our service has implemented unified packaging for both output and input parameters at the gateway level, resulting in one less layer of packaging objects in the interface declarations.
I see that there is a provision for unified output parameter packaging in the configuration; can unified input parameter configuration also be provided? Or could you guide me on where to extend this functionality?
Thank you very much!

**Comment by shalousun** [comment]
@gardenerHan This configuration is similar to responseBodyAdvice, which adds a wrapper class to the document output.

**Comment by gardenerHan** [comment]
> @gardenerHan This configuration is similar to responseBodyAdvice, which adds a wrapper class to the output of the documentation.

Yes, I see that there is a configuration for wrapping the output parameters, but there doesn't seem to be a place to configure the input parameters. Is there a way to resolve this?

**Comment by dylan-tao** [comment]
> > @gardenerHan This configuration is similar to responseBodyAdvice, which adds a wrapper class to the output of the documentation.
> 
> Yes, I see that there is a configuration for wrapping the output parameters, but there doesn't seem to be a place to configure the input parameters. Is there a way to resolve this?

Version 2.1.3 now supports this feature and can be used accordingly.

**Comment by gardenerHan** [comment]
@dylan-tao What I hope for is a configuration that can wrap the request parameters, rather than one that overrides the attributes of the request parameters.

**Comment by gardenerHan** [comment]
@dylan-tao What I'm hoping for is a configuration that can wrap the request parameters, not one that overrides the attributes of the request parameters.

> > > @gardenerHan This configuration is similar to responseBodyAdvice, which adds a wrapper class to the output of the documentation.
> > 
> > 
> > Yes, I see that there is a configuration for wrapping the output parameters, but there doesn't seem to be a place to configure the input parameters. Is there a way to resolve this?
> 
> 2.1.3 version already supports this and can be used now.

I still don't see any configuration parameters in the source code and settings of version 2.1.3 that can wrap the input parameters; I only see a new configuration that overrides the input parameter attributes.

I hope my interface definition is like this:
```java
@PostMapping("getTable")
public ListData getTable(@RequestBody DataTableReqDto req){} ;

public class DataTableReqDto implements Serializable {

    /**
     * Database code
     *
     * @mock default
     */
    private String dbCode;

    /**
     * Database name
     *
     * @mock low_code
     */
    private String tableSchema;

    /**
     * Table name
     *
     * @mock data_source
     */
    private String tableName;

}
```

I want the frontend to see the document as:
```json
{
	"pubRequest":{
		"method":"user/login",
		"sign":"3dnx7p",
		"signType":"md5",
		"token":"t8mcr9",
		"version":"1.0"
	},
	"body":{
		"dbCode":"default",
		"tableSchema":"low_code",
		"tableName":"data_source"
	}
}
```

All our parameter wrapping and unwrapping are done by the gateway, which results in one less layer of wrapping objects between the frontend and the interface.
