### ISSUE TITLE
If the request parameter contains type "date" and the parameter name is endTime or beginTime, the resulting example value may be different from what you expect. 

### ISSUE THREAD

**Issue by jasonkung22** [TongchengOpenSource/smart-doc#947]
### Version

3.0.8

### Plugin

smart-doc-maven-plugin

### Build tool version

3.6.3

### Jdk version

1.8

### Describe the bug (Bug描述，社区已开启国际化推广，请用文心一言、讯飞星火等辅助翻译成英文，减少社区开发者的工作)

1. If the request parameter contains type "date" and the parameter name is endTime or beginTime, the result example value may be different from what you expect
2. In the sample generation method of the response result, the parameter should be passed with "simpleType"

### Expected Behavior (您期望的结果，社区已开启国际化推广，请用文心一言、讯飞星火等辅助翻译成英文，减少社区开发者的工作)

If the request parameter contains the date type and the parameter name is endTime or beginTime, the generated example value is in the format yyyy-MM-dd HH:mm:ss. And the sample response is consistent with the request

### Current Behavior (当前结果，社区已开启国际化推广，请用文心一言、讯飞星火等辅助翻译成英文，减少社区开发者的工作)

![image](https://github.com/user-attachments/assets/64bead9c-a38d-4e40-b393-3c7189c477e9)
![image](https://github.com/user-attachments/assets/9c0eef06-ee20-4da5-9835-5b0c9176c8e5)

### Steps to Reproduce (Bug产生步骤，请尽量提供用例代码。社区已开启国际化推广，请用文心一言、讯飞星火等辅助翻译成英文，减少社区开发者的工作)

![image](https://github.com/user-attachments/assets/371cb5e3-7f8d-4435-98be-079573d807fe)

### Possible Solution (Bug解决建议，社区已开启国际化推广，请用文心一言、讯飞星火等辅助翻译成英文，减少社区开发者的工作)

1. begintime-date and endtime-date are changed to yyyy-MM-dd HH:mm:ss.
![image](https://github.com/user-attachments/assets/fea9c33a-b963-4d66-b61b-4b0a7692a142)
2, 352 lines in ParamsBuildHelper, DocUtil. GetValByTypeAndFieldName parameters from subTypeName typeSimpleName instead
![image](https://github.com/user-attachments/assets/d593582b-1f7f-4894-b121-c95136df5162)

### Validations

- [X] Check if you're on the [latest smart-doc version](https://github.com/TongchengOpenSource/smart-doc/releases/latest). (请检查是否为最新版本)
- [X] Read the [docs](https://smart-doc-group.github.io/). (请先阅读官方文档)
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate. (检查是否存在报告相同错误的问题，以避免产生重复)

**Comment by jasonkung22** [comment]
The generated result after modification:
![image](https://github.com/user-attachments/assets/bf40e32e-40d6-4a82-8eb3-1fa26d95aa54)
![image](https://github.com/user-attachments/assets/d8976488-b930-49c4-986b-e8452e31ab51)

**Comment by linwumingshi** [comment]
@jasonkung22   Thanks for your issue! Please provide a minimal sample application that reproduces the problem for faster issue triage.

**Comment by jasonkung22** [comment]
```java
@RestController
@RequestMapping("test")
public class TestController {

    /**
     * 测试date
     * @param beginTime  header开始时间
     * @param finishTime header完成时间
     * @param startTime  开始时间
     * @param endTime    结束时间
     * @return 测试响应
     */
    @GetMapping("date")
    public TestResponse getPublicInfo(
            @RequestHeader Date beginTime,
            @RequestHeader Date finishTime,
            @RequestParam Date startTime,
            @RequestParam Date endTime) {
        return null;
    }

    public static class TestResponse {

        /**
         * 开始时间
         */
        private Date beginTime;
        /**
         * 完成时间
         */
        private Date finishTime;
        /**
         * 开始时间
         */
        private Date startTime;
        /**
         * 结束时间
         */
        private Date endTime;
    }
}
```
生成结果如下：
![image](https://github.com/user-attachments/assets/9e53b726-6a7d-4971-b36b-089dba946788)

**Comment by linwumingshi** [comment]
The bug occurs only when the configuration file [Config](https://smart-doc-group.github.io/guide/advanced/config#complete-configuration) has 'randomMock' set to true.

```json
 "randomMock": true,
```
