### ISSUE TITLE
Can support for Map parameters be added?

### ISSUE THREAD

**Issue by Gmakter** [TongchengOpenSource/smart-doc#95]
## Your Environment(您的使用环境)

* smart-doc version: 2.1.0
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin): 2.1.0
* build tool version(maven or gradle): maven 

## Expected Behavior(您期望的结果)

When using a Map as a parameter, the API supports an arbitrary number of key/value pairs.
```shell
curl -X GET -H 'token:kk' -i http://{{server}}:8080/app/test3.do?key1=value1&key2=value2&key3=value3
```
```java
    @GetMapping(value = "/test3")
    public Map test3(@RequestParam Map map){
        return map;
    }
```

## Current Behavior(当前结果)

![bug](https://user-images.githubusercontent.com/13639642/113126666-77330680-924a-11eb-83f5-d68e0f061d6c.png)

**Comment by netdied** [comment]
The content of the curl-example is editable.

**Comment by Gmakter** [comment]
I am wondering if it would be more convenient to add parameters by setting up a button similar to the "add query parameter" button in the talend api tester plugin next to the "send request" button?
![bug](https://user-images.githubusercontent.com/13639642/113143665-fdf1de80-925e-11eb-9547-25b66e76ca0b.png)

**Comment by netdied** [comment]
If you need a more user-friendly testing page, you might want to try using the Torna+Smart-Doc combination mode.
