### ISSUE TITLE
The doc api param type is wrong when the POST request use RequestParam

### ISSUE THREAD

**Issue by skydream-xu** [TongchengOpenSource/smart-doc#953]
### Version

3.0.7

### Plugin

smart-doc-maven-plugin

### Build tool version

3.0.7

### Jdk version

17

### Describe the bug (Bug描述，社区已开启国际化推广，请用文心一言、讯飞星火等辅助翻译成英文，减少社区开发者的工作)

The doc api param type is wrong when the POST request use RequestParam
  ```java
@PostMapping("/copy")
    public int copy(@RequestParam("id") Integer id)
```
![image](https://github.com/user-attachments/assets/2a751949-e45e-4fc4-b786-d24e625489ef)

### Expected Behavior (您期望的结果，社区已开启国际化推广，请用文心一言、讯飞星火等辅助翻译成英文，减少社区开发者的工作)

query-parameters

### Current Behavior (当前结果，社区已开启国际化推广，请用文心一言、讯飞星火等辅助翻译成英文，减少社区开发者的工作)

![Uploading image.png…]()

### Steps to Reproduce (Bug产生步骤，请尽量提供用例代码。社区已开启国际化推广，请用文心一言、讯飞星火等辅助翻译成英文，减少社区开发者的工作)

see the description

### Validations

- [ ] Check if you're on the [latest smart-doc version](https://github.com/TongchengOpenSource/smart-doc/releases/latest). (请检查是否为最新版本)
- [X] Read the [docs](https://smart-doc-group.github.io/). (请先阅读官方文档)
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate. (检查是否存在报告相同错误的问题，以避免产生重复)

**Comment by linwumingshi** [comment]
In smart-doc, the `@RequestParam `annotation in a POST request is correctly handled as POST `application/x-www-form-urlencoded` or `multipart/form-data` content types.

**Comment by skydream-xu** [comment]
> In smart-doc, the `@RequestParam `annotation in a POST request is correctly handled as POST `application/x-www-form-urlencoded` or `multipart/form-data` content types.

I only found the `@RequestParam` which use in a Get request  in the smart-doc 。 I try to modify the request code ContentType to
```JAVA
    @PostMapping(value = "/copy", produces = MediaType.APPLICATION_FORM_URLENCODED_VALUE)
    public int copy(@RequestParam("id") Integer id) {
```
but the apidoc still the same
![image](https://github.com/user-attachments/assets/4bb5a264-0cda-4805-bfe4-470f892f5a9d)

**Comment by linwumingshi** [comment]
> > In smart-doc, the `@RequestParam `annotation in a POST request is correctly handled as POST `application/x-www-form-urlencoded` or `multipart/form-data` content types.在 smart-doc 中，POST 请求中的`@RequestParam`注释被正确处理为 POST `application/x-www-form-urlencoded` `multipart/form-data`内容类型。
> 
> I only found the @RequestParam which use in a Get request in the smart-doc 。 I try to modify the request code ContentType to我在smart-doc中只找到了在Get请求中使用的which。我尝试将请求代码ContentType修改为 @PostMapping(value = "/copy", produces = MediaType.APPLICATION_FORM_URLENCODED_VALUE)@PostMapping(value = "/copy", 产生 = MediaType.APPLICATION_FORM_URLENCODED_VALUE) public int copy(@RequestParam("id") Integer id) {公共 int copy(("id") 整数 id) {
> 
> but the apidoc still the same但 apidoc 仍然是一样的 ![image](https://private-user-images.githubusercontent.com/4115799/387078961-4bb5a264-0cda-4805-bfe4-470f892f5a9d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5MTE1MjQsIm5iZiI6MTczMTkxMTIyNCwicGF0aCI6Ii80MTE1Nzk5LzM4NzA3ODk2MS00YmI1YTI2NC0wY2RhLTQ4MDUtYmZlNC00NzBmODkyZjVhOWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMThUMDYyNzA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTViNmU3MGVhNzAxNDhlNGI1NWJmODliODAwOTkyMDZiMzlhZGJhMGZjZDAzMzVkZjFmZWFkMDgwZDIyYmQwNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.MGGizYjzjCXQ_YmK2DDw0DoaiPDuuO7Y5hVh6Fs8RVo)


The API info like:
**URL:** http://127.0.0.1:8080/enum/testQueryEnum

**Type:** POST

**Author:** cqmike

**Content-Type:** application/x-www-form-urlencoded

**Description:** 测试query参数枚举

**Request-headers:**

| Header | Type | Required | Description | Since |
|--------|------|----------|-------------|-------|
|token|string|false|desc<br>ssssss<br>wwwqqwq|-|

**Body-parameters:**

| Parameter | Type | Required | Description | Since |
|-----------|------|----------|-------------|-------|
|genderEnum|int32|false|No comments found.<br/>(See: 性别数据字典)|-|

**Request-example:**
```bash
curl -X POST -H "token:kk" -i 'http://127.0.0.1:8080/enum/testQueryEnum' --data 'genderEnum=WOMAN'
```

**Response-example:**
```json
string
```



[@RequestParam](https://docs.spring.io/spring-framework/reference/web/webmvc/mvc-controller/ann-methods/requestparam.html)


You can use the `@RequestParam` annotation to bind Servlet request parameters (**that is, query parameters or form data**) to a method argument in a controller.

**Comment by linwumingshi** [comment]
> > In smart-doc, the `@RequestParam `annotation in a POST request is correctly handled as POST `application/x-www-form-urlencoded` or `multipart/form-data` content types.
> 
> I only found the `@RequestParam` which use in a Get request in the smart-doc 。 I try to modify the request code ContentType to
> 
> ```java
>     @PostMapping(value = "/copy", produces = MediaType.APPLICATION_FORM_URLENCODED_VALUE)
>     public int copy(@RequestParam("id") Integer id) {
> ```
> 
> but the apidoc still the same ![image](https://private-user-images.githubusercontent.com/4115799/387078961-4bb5a264-0cda-4805-bfe4-470f892f5a9d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5MTI3MDUsIm5iZiI6MTczMTkxMjQwNSwicGF0aCI6Ii80MTE1Nzk5LzM4NzA3ODk2MS00YmI1YTI2NC0wY2RhLTQ4MDUtYmZlNC00NzBmODkyZjVhOWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMThUMDY0NjQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmJhOTk5Yjg5NDgzOGU4NjI0ZWVhYTI5ZGRjNWVlYzI5MjJlNTg1YzRhODU0NDc3YTU4NTQwMGY0OTkwNTlkYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.3H4A64oWhZOYTaHVwPzh2ncOk1gtahhoyn0aOvkGC7k)



The API info like:
**URL:** http://127.0.0.1:8080/enum/testQueryEnum

**Type:** POST

**Author:** cqmike

**Content-Type:** application/x-www-form-urlencoded

**Body-parameters:**

| Parameter | Type | Required | Description | Since |
|-----------|------|----------|-------------|-------|
|genderEnum|int32|false|No comments found.|-|


You can check the documentation for Spring MVC's `@RequestParam` annotation, or you can test it yourself; `@RequestParam` supports binding form data to method parameters in the controller.

[SpringMVC @RequestParam](https://docs.spring.io/spring-framework/reference/web/webmvc/mvc-controller/ann-methods/requestparam.html)

The first line of the documentation is:
You can use the `@RequestParam` annotation to bind Servlet request parameters (**that is, query parameters or form data**) to a method argument in a controller.

**Comment by skydream-xu** [comment]
> > > In smart-doc, the `@RequestParam `annotation in a POST request is correctly handled as POST `application/x-www-form-urlencoded` or `multipart/form-data` content types.
> > 
> > 
> > I only found the `@RequestParam` which use in a Get request in the smart-doc 。 I try to modify the request code ContentType to
> > ```java
> >     @PostMapping(value = "/copy", produces = MediaType.APPLICATION_FORM_URLENCODED_VALUE)
> >     public int copy(@RequestParam("id") Integer id) {
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > but the apidoc still the same ![image](https://private-user-images.githubusercontent.com/4115799/387078961-4bb5a264-0cda-4805-bfe4-470f892f5a9d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5MTI3MDUsIm5iZiI6MTczMTkxMjQwNSwicGF0aCI6Ii80MTE1Nzk5LzM4NzA3ODk2MS00YmI1YTI2NC0wY2RhLTQ4MDUtYmZlNC00NzBmODkyZjVhOWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMThUMDY0NjQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmJhOTk5Yjg5NDgzOGU4NjI0ZWVhYTI5ZGRjNWVlYzI5MjJlNTg1YzRhODU0NDc3YTU4NTQwMGY0OTkwNTlkYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.3H4A64oWhZOYTaHVwPzh2ncOk1gtahhoyn0aOvkGC7k)
> 
> The API info like: **URL:** http://127.0.0.1:8080/enum/testQueryEnum
> 
> **Type:** POST
> 
> **Author:** cqmike
> 
> **Content-Type:** application/x-www-form-urlencoded
> 

> > **Body-parameters:**

> 
> Parameter	Type	Required	Description	Since
> genderEnum	int32	false	No comments found.	-
> You can check the documentation for Spring MVC's `@RequestParam` annotation, or you can test it yourself; `@RequestParam` supports binding form data to method parameters in the controller.
> 
> [SpringMVC @RequestParam](https://docs.spring.io/spring-framework/reference/web/webmvc/mvc-controller/ann-methods/requestparam.html)
> 
> The first line of the documentation is: You can use the `@RequestParam` annotation to bind Servlet request parameters (**that is, query parameters or form data**) to a method argument in a controller.

Maybe I don't describe clear , I mean the `@RequestParam` doc is wrong ， the param type is query not body  in doc , but the smart gen api doc is Body-parameters not Query-parameters

**Comment by linwumingshi** [comment]
> > > > In smart-doc, the `@RequestParam `annotation in a POST request is correctly handled as POST `application/x-www-form-urlencoded` or `multipart/form-data` content types.
> > > 
> > > 
> > > I only found the `@RequestParam` which use in a Get request in the smart-doc 。 I try to modify the request code ContentType to
> > > ```java
> > >     @PostMapping(value = "/copy", produces = MediaType.APPLICATION_FORM_URLENCODED_VALUE)
> > >     public int copy(@RequestParam("id") Integer id) {
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > but the apidoc still the same ![image](https://private-user-images.githubusercontent.com/4115799/387078961-4bb5a264-0cda-4805-bfe4-470f892f5a9d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5MTI3MDUsIm5iZiI6MTczMTkxMjQwNSwicGF0aCI6Ii80MTE1Nzk5LzM4NzA3ODk2MS00YmI1YTI2NC0wY2RhLTQ4MDUtYmZlNC00NzBmODkyZjVhOWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMThUMDY0NjQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmJhOTk5Yjg5NDgzOGU4NjI0ZWVhYTI5ZGRjNWVlYzI5MjJlNTg1YzRhODU0NDc3YTU4NTQwMGY0OTkwNTlkYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.3H4A64oWhZOYTaHVwPzh2ncOk1gtahhoyn0aOvkGC7k)
> > 
> > 
> > The API info like: **URL:** http://127.0.0.1:8080/enum/testQueryEnum
> > **Type:** POST
> > **Author:** cqmike
> > **Content-Type:** application/x-www-form-urlencoded
> 
> > > **Body-parameters:**
> 
> > Parameter	Type	Required	Description	Since
> > genderEnum	int32	false	No comments found.	-
> > You can check the documentation for Spring MVC's `@RequestParam` annotation, or you can test it yourself; `@RequestParam` supports binding form data to method parameters in the controller.
> > [SpringMVC @RequestParam](https://docs.spring.io/spring-framework/reference/web/webmvc/mvc-controller/ann-methods/requestparam.html)
> > The first line of the documentation is: You can use the `@RequestParam` annotation to bind Servlet request parameters (**that is, query parameters or form data**) to a method argument in a controller.
> 
> Maybe I don't describe clear , I mean the `@RequestParam` doc is wrong ， the param type is query not body in doc , but the smart gen api doc is Body-parameters not Query-parameters



---

I don't believe this is an error. In Spring MVC, the `@RequestParam` annotation is described as binding "Servlet request parameters"—including both query parameters and form data. Therefore, it is correct for smart-doc to generate parameters annotated with `@RequestParam` as body parameters in a POST request, especially when the `Content-Type` is set to `application/x-www-form-urlencoded`.

## Example
```java
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

/**
 * TestRequestParam Controller
 *
 * This controller demonstrates the usage of the `@RequestParam` annotation in a POST request.
 * It binds a request parameter (from either the query string or form data) to a method parameter.
 *
 * @author test
 * @version 1.0.0
 * @since 2024-11-18 15:21:47
 */
@RequestMapping
@RestController
public class TestRequestParam {

    /**
     * Example method for handling POST requests with `@RequestParam`.
     * <p>
     * Accepts a single integer parameter `id` from the request, which can be passed as a
     * query parameter or form data.
     * <p>
     * Example usage:
     * - As a query parameter:
     *   {@code curl --location --request POST 'http://127.0.0.1:28080/testRequestParamInPost?id=1'}
     * - As form data:
     *   {@code curl --location 'http://127.0.0.1:28080/testRequestParamInPost' --data 'id=1'}
     *
     * @param id The ID parameter to bind from the request.
     * @return The ID value provided in the request.
     */
    @PostMapping("/testRequestParamInPost")
    public Integer testRequestParamInPost(@RequestParam("id") Integer id) {
        return id;
    }
}
```

### Example of Using `@RequestParam` Annotation

#### Sample Method
```java
@PostMapping("/testRequestParamInPost")
public Integer testRequestParamInPost(@RequestParam("id") Integer id) {
    return id;
}
```

#### Request Examples

1. **Using Query Parameter**:
    ```bash
    curl --location --request POST 'http://127.0.0.1:28080/testRequestParamInPost?id=1'
    ```

2. **Using Form Data**:
    ```bash
    curl --location 'http://127.0.0.1:28080/testRequestParamInPost' --data 'id=1'
    ```

#### Explanation
- Both requests successfully bind and return the `id` value as `1`.
- The `@RequestParam` annotation can bind request parameters—whether from the query string or form data—to controller method parameters.

---

**Comment by jasonkung22** [comment]
The problem can also cause the object's nested parameter structure to be incorrect.
### Example：

```java
@RestController
@RequestMapping
public class QueryPostController {


    /**
     * 测试query+body参数
     * @param gender        性别数据
     * @param testBodyParam 测试参数
     * @return 性别数据字典
     *
     * @author cqmike
     * @since 1.0.0
     */
    @PostMapping("/post/testQueryAndBody")
    public Integer testJsonValueQueryEnum(@RequestParam("gender") Integer gender,
            @RequestBody TestBodyParam testBodyParam) {
        return null;
    }

    @Data
    public static class TestBodyParam {

        /**
         * 测试参数1
         */
        private TestBodyObjectParam test1;
        /**
         * 测试参数2
         */
        private TestBodyObjectParam test2;
        /**
         * 测试参数3
         */
        private TestBodyObjectParam test3;
    }

    @Data
    public static class TestBodyObjectParam {

        /**
         * 测试参数1
         */
        private String test1;
        /**
         * 测试参数2
         */
        private String test2;
        /**
         * 测试参数3
         */
        private String test3;
    }
}
```
### Expected Behavior：
![image](https://github.com/user-attachments/assets/1844dcb1-045e-4362-9643-bd9abc58784d)


### Current Behavior：

![image](https://github.com/user-attachments/assets/f1af17d3-7940-4617-92e6-1b51430b0fe2)
