### ISSUE TITLE
When a method in the Controller has a void return type, the API documentation indicates "Doesn't return a value."

### ISSUE THREAD

**Issue by dylan-tao** [TongchengOpenSource/smart-doc#96]
## Your Environment (Your Usage Environment)
* smart-doc version: 2.1.1
* plugin version (e.g., smart-doc-maven-plugin or smart-doc-gradle-plugin): 2.1.1
* build tool version (maven or gradle): maven

## Expected Behavior (Expected Outcome)
When a method in the controller has a return type of void, and responseBodyAdvice is set to a Result object: {"code":"200", "msg":"Success", "result": Object}, it is expected to return code and msg, ignoring result (which is void).

## Current Behavior (Current Outcome)
The API documentation output indicates "Response-example: Doesn't return a value."

## Possible Solution (Bug Fix Suggestion)
It is suggested that if responseBodyAdvice wrapping is not set, the current result should be returned; if responseBodyAdvice wrapping is set, then return code and msg, ignoring the result generic attribute.

## Steps to Reproduce (Steps to Generate the Bug)
1. Configure responseBodyAdvice as a Result object with content: {"code":"200", "msg":"Success", "result": Object}
2. Spring Boot automatically wraps the return of methods in the controller;
3. If the method's return is non-void, it returns normally; if it is void, it ignores the wrapped object.

## Context (Impact of the Bug)
This causes certain void-returning types in the controller to lack return attribute descriptions in the API documentation.

**Comment by netdied** [comment]
Fixed, wait for the new version to be released or pull from the dev branch and build.
