### ISSUE TITLE
The resulting markdown file does not contain the 'Example' field

### ISSUE THREAD

**Issue by jasonkung22** [TongchengOpenSource/smart-doc#971]
### Expected Behavior：
![1732698115864](https://github.com/user-attachments/assets/53f6e398-c580-46db-b833-e4e581ca1aa2)

### Current Behavior：
![image](https://github.com/user-attachments/assets/a75439ec-e949-4c61-bf33-3ad517c03fd5)

### Basic example (PR的用例，社区已开启国际化推广，请文心一言、讯飞星火等辅助翻译成英文，减少社区开发者的工作)

nothing

### Describe the solution you'd like (描述您想要的解决方案，社区已开启国际化推广，请文心一言、讯飞星火等辅助翻译成英文，减少社区开发者的工作)

nothing

### Validations

- [X] Read the [docs](https://smart-doc-group.github.io/). (请先阅读官方文档)
- [X] Read the [Contributing Guidelines](https://smart-doc-group.github.io/guide/community/contributing). (请先阅读官方文档·贡献指南)
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate. (检查是否存在报告相同错误的问题，以避免产生重复)

**Comment by shalousun** [comment]
This doesn't seem to be particularly necessary. In smart-doc, the parameter values are actually placed in the request or response examples. Too many table columns may not be ideal.

**Comment by jasonkung22** [comment]
For enum type parameters, Example is necessary, it is convenient to know that you should pass 'enumName' or 'enumValue', if you need to look inside the request or response example, it may not be too convenient. In addition, 'Torna' can also see the example value of the parameter, which is really more convenient
![image](https://github.com/user-attachments/assets/69591c7f-d69c-469e-bf3d-0aa35e1c39b1)
