### ISSUE TITLE
Enhance the customResponseFields extension to support the ignore configuration option.

### ISSUE THREAD

**Issue by dylan-tao** [TongchengOpenSource/smart-doc#98]
## Summary (Description of this PR)
It is hoped that the customResponseFields extension will be enhanced with an ignore configuration option to omit certain attributes of custom global responses from being output in the API documentation.
### Basic Example (Use Case for the PR)
```json
"customResponseFields":[
    {
      "name":"code",
      "desc":"Status code",
      "ownerClassName":"com.javaosc.constant.entity.Result",
      "value":"200",
       "ignore":true // Whether to ignore a certain attribute globally or locally
    }
]
```
### Motivation (Purpose of this PR)
To block custom attributes in special scenarios using third-party pagination plugins or gateway extensions, reducing the maintenance effort for developers and making the output API documentation more concise and clear.

**Comment by netdied** [comment]
Fixed, wait for the new version to be released or download the dev branch and build it.
