### ISSUE TITLE
By default, the type of the enumeration attribute field should be `enum`

### ISSUE THREAD

**Issue by linwumingshi** [TongchengOpenSource/smart-doc#986]
### Version

3.0.9

### Plugin

smart-doc-maven-plugin

### Build tool version

3.9.6

### Jdk version

1.8

### Describe the bug (Bug描述，社区已开启国际化推广，请用文心一言、讯飞星火等辅助翻译成英文，减少社区开发者的工作)

#973     

#977

https://github.com/TongchengOpenSource/smart-doc/blob/66016e36bffac9efacd0b828b5a99afc6d5478db/src/main/resources/default.json#L14

### Expected Behavior (您期望的结果，社区已开启国际化推广，请用文心一言、讯飞星火等辅助翻译成英文，减少社区开发者的工作)

 "enumNameExample": true, 

### Current Behavior (当前结果，社区已开启国际化推广，请用文心一言、讯飞星火等辅助翻译成英文，减少社区开发者的工作)

 "enumNameExample": false, 

### Steps to Reproduce (Bug产生步骤，请尽量提供用例代码。社区已开启国际化推广，请用文心一言、讯飞星火等辅助翻译成英文，减少社区开发者的工作)

The default value is false, which destroys the original enumeration logic

@jasonkung22

### Context (Bug影响描述，社区已开启国际化推广，请用文心一言、讯飞星火等辅助翻译成英文，减少社区开发者的工作)

This upgrade may affect the changes made by existing users. Please make adjustments as needed and refer to the relevant documentation.

https://github.com/smart-doc-group/smart-doc-group.github.io/pull/144

### Validations

- [X] Check if you're on the [latest smart-doc version](https://github.com/TongchengOpenSource/smart-doc/releases/latest). (请检查是否为最新版本)
- [X] Read the [docs](https://smart-doc-group.github.io/). (请先阅读官方文档)
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate. (检查是否存在报告相同错误的问题，以避免产生重复)

**Comment by jasonkung22** [comment]
ok,  I will change, the modification rules are as follows.

```text
1. Added the 'enumConvertor' configuration
2. non-JSON parameters (header/get/path request, post/put request formdata mode)
	1.1. if the 'enumConvertor' configuration is true
		a. If there is '@JsonValue' annotation, take enumeration value according to '@JsonValue' annotation, the parameter type is the actual type of the enumeration value
		b. If there is no '@JsonValue' annotation, take the enumeration name, the parameter type is enum
	1.2. If 'enumConvertor' configuration is false
		Take enumeration name, the parameter type is enum

3. json parameters or json response (post/put request body mode)
	2.1. if there is '@JsonValue' annotation, take the enumeration value according to '@JsonValue' annotation, the parameter type is the actual type of the enumeration value
	2.2. if there is no '@JsonValue' annotation, take the enumeration name, the parameter type is enum
```

![enum converotr](https://github.com/user-attachments/assets/21cfee67-58b8-46cf-bf08-35b5a07a26d4)
